module

public import LeanSpherical.Auto.ConvexDuality
public import LeanSpherical.Auto.RadialFourierTransform
public import LeanSpherical.Auto.Spherical.SphericalMaximal
public import LeanSpherical.Auto.Spherical.FractalDilations.AHRSUpperBounds
public import LeanSpherical.Auto.Spherical.FractalDilations.RSTypeSetCharacterization
public import LeanSpherical.Auto.Spherical.LegendreAssouad
public import LeanSpherical.Auto.Spherical.FractalDilations.BRRS
public import LeanSpherical.Auto.Spherical.FractalDilations.BRSRadial

@[expose] public section

#check Auto.Spherical.FractalDilations.AHRSUpperBounds.closure_typeSet_eq
#print axioms Auto.Spherical.FractalDilations.AHRSUpperBounds.closure_typeSet_eq

#check Auto.Spherical.FractalDilations.AHRSUpperBounds.eLpNorm_restrictedSphericalMaximal_le
#print axioms Auto.Spherical.FractalDilations.AHRSUpperBounds.eLpNorm_restrictedSphericalMaximal_le

#check Auto.Spherical.FractalDilations.AHRSUpperBounds.eLpNorm_sphericalMaximal_le
#print axioms Auto.Spherical.FractalDilations.AHRSUpperBounds.eLpNorm_sphericalMaximal_le

#check Auto.Spherical.FractalDilations.AHRSUpperBounds.eLpNorm_lacunarySphericalMaximal_le
#print axioms Auto.Spherical.FractalDilations.AHRSUpperBounds.eLpNorm_lacunarySphericalMaximal_le

#check Auto.Spherical.FractalDilations.AHRSUpperBounds.theorem_one
#print axioms Auto.Spherical.FractalDilations.AHRSUpperBounds.theorem_one

#check Auto.Spherical.FractalDilations.AHRSUpperBounds.theorem_one_Lp
#print axioms Auto.Spherical.FractalDilations.AHRSUpperBounds.theorem_one_Lp

#check Auto.Spherical.SphericalMaximal.stein_spherical_maximal
#print axioms Auto.Spherical.SphericalMaximal.stein_spherical_maximal
