import LeanSpherical.Codex.Spherical.SphericalMaximal
import LeanSpherical.Codex.Spherical.FractalDilations.MinkowskiDiagonal
import LeanSpherical.Codex.Spherical.PowerWeights.Public
import LeanSpherical.Codex.Spherical.HardyLittlewoodMaximal

#check LeanSpherical.HarmonicAnalysis.dyadic_hardy_littlewood_weak_one
#print axioms LeanSpherical.HarmonicAnalysis.dyadic_hardy_littlewood_weak_one

#check LeanSpherical.HarmonicAnalysis.dyadic_hardy_littlewood_maximal_Lp
#print axioms LeanSpherical.HarmonicAnalysis.dyadic_hardy_littlewood_maximal_Lp

#check LeanSpherical.HarmonicAnalysis.stein_spherical_maximal_Lp
#print axioms LeanSpherical.HarmonicAnalysis.stein_spherical_maximal_Lp

#check LeanSpherical.HarmonicAnalysis.FractalDilations.minkowski_segment_strong_type_d_ge_three
#print axioms LeanSpherical.HarmonicAnalysis.FractalDilations.minkowski_segment_strong_type_d_ge_three

#check LeanSpherical.HarmonicAnalysis.PowerWeightPublic.power_weight_spherical_maximal
#print axioms LeanSpherical.HarmonicAnalysis.PowerWeightPublic.power_weight_spherical_maximal
