
/- This file was machine-generated by Codex -/

import LeanSpherical.Auto.Spherical.FractalDilations.SharpnessTests
open Auto.Spherical.FourierRadius
open Auto.Spherical.FractalDilations.ExponentRegions
open Auto.Spherical.SurfaceCore







/-!
# Mass preservation for normalized spherical averages

The annulus sharpness example is most efficiently handled by total mass: a
small nonnegative ball has mass of order `δ^d`, and every fixed normalized
spherical average preserves that mass.  This file exposes that Fubini fact
for the literal spherical averages used by the existing Stein development.
-/

namespace Auto.Spherical.FractalDilations.AnnulusCore

open MeasureTheory Metric Set

noncomputable section

private theorem integrable_sphere_translate_product
    {d : ℕ} (f : Euclidean d → ℂ) (hfcont : Continuous f)
    (hf : Integrable f volume) (r : ℝ) :
    Integrable
      (fun p : Euclidean d × sphere (0 : Euclidean d) 1 =>
        f (p.1 + r • (p.2 : Euclidean d)))
      (volume.prod (unitSurfaceMeasure d)) := by
  have hmeas : AEStronglyMeasurable
      (fun p : Euclidean d × sphere (0 : Euclidean d) 1 =>
        f (p.1 + r • (p.2 : Euclidean d)))
      (volume.prod (unitSurfaceMeasure d)) := by
    apply (hfcont.comp (continuous_fst.add
      ((continuous_const : Continuous fun _ : Euclidean d × sphere (0 : Euclidean d) 1 => r).smul
        (continuous_subtype_val.comp continuous_snd)))).aestronglyMeasurable
  refine (integrable_prod_iff' hmeas).2 ?_
  constructor
  · filter_upwards with ω
    exact hf.comp_add_right (r • (ω : Euclidean d))
  · have h_eq : (fun ω : sphere (0 : Euclidean d) 1 =>
        ∫ x : Euclidean d, ‖f (x + r • (ω : Euclidean d))‖) =
        fun _ => ∫ x : Euclidean d, ‖f x‖ := by
      funext ω
      exact integral_add_right_eq_self (fun x : Euclidean d => ‖f x‖)
        (r • (ω : Euclidean d))
    rw [h_eq]
    exact integrable_const _

/-- A normalized spherical average preserves the integral of a continuous
integrable function. -/
theorem integral_normalizedSphericalAverage_eq_integral
    {d : ℕ} (hd : 0 < d) (f : Euclidean d → ℂ)
    (hfcont : Continuous f) (hf : Integrable f volume) (r : ℝ) :
    (∫ x : Euclidean d, normalizedSphericalAverage d f r x) =
      ∫ x : Euclidean d, f x := by
  have hprod := integrable_sphere_translate_product f hfcont hf r
  have havg :
      (∫ x : Euclidean d, sphericalAverage d f r x) =
        (surfaceMass d : ℂ) * ∫ x : Euclidean d, f x := by
    calc
      (∫ x : Euclidean d, sphericalAverage d f r x) =
          ∫ x : Euclidean d, ∫ ω : sphere (0 : Euclidean d) 1,
            f (x + r • (ω : Euclidean d)) ∂unitSurfaceMeasure d := rfl
      _ = ∫ ω : sphere (0 : Euclidean d) 1, ∫ x : Euclidean d,
          f (x + r • (ω : Euclidean d)) ∂volume ∂unitSurfaceMeasure d :=
        integral_integral_swap hprod
      _ = ∫ _ : sphere (0 : Euclidean d) 1,
          (∫ x : Euclidean d, f x ∂volume) ∂unitSurfaceMeasure d := by
        apply integral_congr_ae
        filter_upwards with ω
        exact integral_add_right_eq_self f (r • (ω : Euclidean d))
      _ = (surfaceMass d : ℂ) * ∫ x : Euclidean d, f x := by
        simp [surfaceMass]
  calc
    (∫ x : Euclidean d, normalizedSphericalAverage d f r x) =
        ((surfaceMass d)⁻¹ : ℂ) * ∫ x : Euclidean d, sphericalAverage d f r x := by
      unfold normalizedSphericalAverage
      rw [integral_const_mul]
    _ = ((surfaceMass d)⁻¹ : ℂ) *
        ((surfaceMass d : ℂ) * ∫ x : Euclidean d, f x) := by rw [havg]
    _ = ∫ x : Euclidean d, f x := by
      have hmass : (surfaceMass d : ℂ) ≠ 0 := by
        exact_mod_cast surfaceMass_ne_zero hd
      field_simp

/-- On real-valued data, the normalized spherical average is real-valued and
has the literal scalar integral formula. -/
theorem normalizedSphericalAverage_ofReal_eq
    {d : ℕ} (g : Euclidean d → ℝ) (r : ℝ) (x : Euclidean d) :
    normalizedSphericalAverage d (fun y => (g y : ℂ)) r x =
      ((surfaceMass d)⁻¹ * ∫ ω : sphere (0 : Euclidean d) 1,
        g (x + r • (ω : Euclidean d)) ∂unitSurfaceMeasure d : ℝ) := by
  unfold normalizedSphericalAverage sphericalAverage
  have hInt :
      (∫ ω : sphere (0 : Euclidean d) 1,
        (g (x + r • (ω : Euclidean d)) : ℂ) ∂unitSurfaceMeasure d) =
        ((∫ ω : sphere (0 : Euclidean d) 1,
          g (x + r • (ω : Euclidean d)) ∂unitSurfaceMeasure d : ℝ) : ℂ) := by
    exact integral_ofReal
  rw [hInt]
  push_cast
  rfl

/-- Nonnegative real data have nonnegative normalized spherical averages in
the literal real coordinate. -/
theorem normalizedSphericalAverage_re_nonneg_of_nonneg
    {d : ℕ} (hd : 0 < d) (g : Euclidean d → ℝ) (hg : ∀ y, 0 ≤ g y)
    (r : ℝ) (x : Euclidean d) :
    0 ≤ (normalizedSphericalAverage d (fun y => (g y : ℂ)) r x).re := by
  rw [normalizedSphericalAverage_ofReal_eq]
  apply mul_nonneg
  · exact inv_nonneg.mpr (surfaceMass_pos hd).le
  · apply integral_nonneg
    intro ω
    exact hg _

/-- The standard smooth ball cutoff can be chosen real-valued and
nonnegative, in addition to being one on the inner ball, supported in the
doubled ball, and bounded by one. -/
theorem exists_schwartz_ball_test_real_nonnegative_bounded
    (d : ℕ) {R : ℝ} (hR : 0 < R) :
    ∃ f : SchwartzMap (Euclidean d) ℂ,
      (∀ y : Euclidean d, f y = ((f y).re : ℂ)) ∧
      (∀ y : Euclidean d, 0 ≤ (f y).re) ∧
      (∀ y : Euclidean d, ‖y‖ ≤ R → f y = 1) ∧
      (∀ y : Euclidean d, 2 * R ≤ ‖y‖ → f y = 0) ∧
      (∀ y : Euclidean d, ‖f y‖ ≤ 1) := by
  let b : ContDiffBump (0 : Euclidean d) :=
    ⟨R, 2 * R, hR, by linarith⟩
  let g : Euclidean d → ℂ := Complex.ofRealCLM ∘ b
  have hcompact : HasCompactSupport g := by
    exact b.hasCompactSupport.comp_left (by rfl)
  have hsmooth : ContDiff ℝ (⊤ : ℕ∞) g := by
    exact Complex.ofRealCLM.contDiff.comp b.contDiff
  refine ⟨hcompact.toSchwartzMap hsmooth, ?_, ?_, ?_, ?_, ?_⟩
  · intro y
    change (b y : ℂ) = (((b y : ℂ).re : ℝ) : ℂ)
    simp
  · intro y
    change 0 ≤ (b y : ℂ).re
    simpa using ContDiffBump.nonneg' b y
  · intro y hy
    change (b y : ℂ) = 1
    have hmem : y ∈ closedBall (0 : Euclidean d) b.rIn := by
      simpa only [mem_closedBall, dist_zero_right] using hy
    rw [b.one_of_mem_closedBall hmem]
    norm_num
  · intro y hy
    change (b y : ℂ) = 0
    have hdist : b.rOut ≤ dist y (0 : Euclidean d) := by
      simpa only [dist_zero_right] using hy
    rw [b.zero_of_le_dist hdist]
    norm_num
  · intro y
    change ‖(b y : ℂ)‖ ≤ 1
    rw [Complex.norm_real, Real.norm_of_nonneg (ContDiffBump.nonneg' b y)]
    exact ContDiffBump.le_one b

end

end Auto.Spherical.FractalDilations.AnnulusCore