
/- This file was machine-generated by Codex -/

import LeanSpherical.Auto.Spherical.FractalDilations.CoordinateMiddleNonstationary
open Auto.Spherical.FractalDilations.CoordinateMeridianWaves
open Auto.Spherical.FractalDilations.CoordinateMiddleNonstationary
open Auto.Spherical.FractalDilations.QuadraticStationaryPhase







/-!
# Arbitrary-order decay of the literal coordinate middle wave

The coordinate middle meridian is supported away from the two stationary
poles.  The one-step identity in `CoordinateMiddleNonstationary` records this
fact once.  For the conic kernel calculation one needs the stronger, standard
statement that the middle factor is rapidly decreasing, uniformly in its
frequency.  This file proves that statement by iterating the *actual*
variable-phase integration by parts.

At every stage the derivative is divided by a guarded cosine.  A compact
extra cutoff is included at the first stage.  Thus every iterated amplitude is
globally smooth and remains supported in the central part of the meridian;
there is no symbol-class hypothesis or formal error term in the result.
-/

namespace Auto.Spherical.FractalDilations.CoordinateMiddleRapidDecay

open Filter MeasureTheory Metric Set
open scoped ContDiff Topology

noncomputable section

/-- The successive guarded amplitudes in the variable-phase integration by
parts for the literal coordinate middle meridian.  The zeroth amplitude has
an additional compact guard, which is identically one wherever the middle
cutoff can be nonzero on the meridian. -/
noncomputable def coordinateMiddleIBPCompactAmplitude (m : Nat) : Nat → Real → Complex
  | 0 => fun theta => (coordinateMiddleGuardCutoff theta : Complex) *
      coordinateMiddleIBPAmplitude m theta
  | Nat.succ k => fun theta =>
      deriv (coordinateMiddleIBPCompactAmplitude m k) theta /
        (coordinateMiddleCosineGuard theta : Complex)

/-- The corresponding compact variable-phase integral.  Its zeroth member is
the literal coordinate middle integral. -/
noncomputable def coordinateMiddleIBPCompactIntegral
    (m k : Nat) (l : Real) : Complex :=
  ∫ theta in (-(Real.pi / 2) : Real)..(Real.pi / 2),
    coordinateMiddleIBPCompactAmplitude m k theta *
      ((Real.cos theta : Real) : Complex) *
        Complex.exp (((-l * Real.sin theta : Real) : Complex) * Complex.I)

private theorem coordinateMiddleGuardCutoff_eq_zero_of_rOut_le_abs
    {theta : Real} (hlarge : 31 * Real.pi / 64 ≤ |theta|) :
    coordinateMiddleGuardCutoff theta = 0 := by
  unfold coordinateMiddleGuardCutoff
  apply coordinateMiddleGuardBump.zero_of_le_dist
  change 31 * Real.pi / 64 ≤ dist theta 0
  rw [Real.dist_eq]
  simpa using hlarge

/-- The compact zeroth guarded amplitude vanishes outside the central part of
the meridian.  The statement is global, which lets us differentiate the
vanishing identity without any endpoint bookkeeping. -/
private theorem coordinateMiddleIBPCompactAmplitude_zero_eq_zero_of_large_abs
    (m : Nat) {theta : Real} (hlarge : 15 * Real.pi / 32 < |theta|) :
    coordinateMiddleIBPCompactAmplitude m 0 theta = 0 := by
  by_cases hout : 31 * Real.pi / 64 ≤ |theta|
  · have hguard : coordinateMiddleGuardCutoff theta = 0 :=
      coordinateMiddleGuardCutoff_eq_zero_of_rOut_le_abs hout
    simp [coordinateMiddleIBPCompactAmplitude, hguard]
  · have hsmall : |theta| < 31 * Real.pi / 64 := lt_of_not_ge hout
    have htheta : theta ∈ Icc (-(Real.pi / 2)) (Real.pi / 2) := by
      rw [abs_lt] at hsmall
      constructor <;> nlinarith [Real.pi_pos]
    have hmiddle : coordinateMiddleMeridianCutoff theta = 0 :=
      coordinateMiddleMeridianCutoff_eq_zero_of_large_abs htheta (le_of_lt hlarge)
    simp [coordinateMiddleIBPCompactAmplitude, coordinateMiddleIBPAmplitude,
      coordinateMiddleIBPAmplitudeReal, hmiddle]

/-- A smooth function which vanishes outside the central coordinate interval
has zero derivative there as well. -/
private theorem deriv_eq_zero_of_coordinateMiddle_large_abs
    {F : Real → Complex}
    (hF : ∀ theta : Real, 15 * Real.pi / 32 < |theta| → F theta = 0)
    {theta : Real} (htheta : 15 * Real.pi / 32 < |theta|) :
    deriv F theta = 0 := by
  have habs_cont : ContinuousAt (fun x : Real => |x|) theta := by fun_prop
  have hlocal : F =ᶠ[𝓝 theta] (fun _ : Real => (0 : Complex)) := by
    filter_upwards [habs_cont.tendsto.eventually (eventually_gt_nhds htheta)]
      with y hy
    exact hF y hy
  simpa using hlocal.deriv_eq

/-- Every guarded amplitude remains supported in the same fixed central
interval after arbitrarily many variable-phase integrations by parts. -/
theorem coordinateMiddleIBPCompactAmplitude_eq_zero_of_large_abs
    (m k : Nat) {theta : Real} (hlarge : 15 * Real.pi / 32 < |theta|) :
    coordinateMiddleIBPCompactAmplitude m k theta = 0 := by
  induction k generalizing theta with
  | zero =>
      exact coordinateMiddleIBPCompactAmplitude_zero_eq_zero_of_large_abs m hlarge
  | succ k ih =>
      have hderiv : deriv (coordinateMiddleIBPCompactAmplitude m k) theta = 0 :=
        deriv_eq_zero_of_coordinateMiddle_large_abs
          (fun y hy => ih hy) hlarge
      simp [coordinateMiddleIBPCompactAmplitude, hderiv]

/-- All amplitudes used in the repeated middle-meridian integration by parts
are genuinely smooth on the whole real line. -/
theorem contDiff_coordinateMiddleIBPCompactAmplitude (m k : Nat) :
    ContDiff Real (⊤ : ℕ∞) (coordinateMiddleIBPCompactAmplitude m k) := by
  induction k with
  | zero =>
      have hcutReal : ContDiff Real (⊤ : ℕ∞) coordinateMiddleGuardCutoff := by
        unfold coordinateMiddleGuardCutoff
        exact coordinateMiddleGuardBump.contDiff
      have hcut : ContDiff Real (⊤ : ℕ∞)
          (fun theta : Real => (coordinateMiddleGuardCutoff theta : Complex)) := by
        change ContDiff Real (⊤ : ℕ∞)
          (Complex.ofRealCLM ∘ coordinateMiddleGuardCutoff)
        exact Complex.ofRealCLM.contDiff.comp hcutReal
      simpa only [coordinateMiddleIBPCompactAmplitude] using
        hcut.mul (contDiff_coordinateMiddleIBPAmplitude m)
  | succ k ih =>
      have hguard : ContDiff Real (⊤ : ℕ∞) coordinateMiddleCosineGuard :=
        contDiff_coordinateMiddleCosineGuard
      have hderiv : ContDiff Real (⊤ : ℕ∞)
          (deriv (coordinateMiddleIBPCompactAmplitude m k)) :=
        (contDiff_infty_iff_deriv.mp ih).2
      have hinv : ContDiff Real (⊤ : ℕ∞)
          (fun theta : Real => (coordinateMiddleCosineGuard theta)⁻¹) :=
        hguard.inv (fun theta =>
          ne_of_gt (coordinateMiddleCosineGuard_pos theta))
      have hsmul := hinv.smul hderiv
      change ContDiff Real (⊤ : ℕ∞) (fun theta : Real =>
        (coordinateMiddleCosineGuard theta)⁻¹ •
          deriv (coordinateMiddleIBPCompactAmplitude m k) theta) at hsmul
      convert hsmul using 1
      ext theta
      simp only [coordinateMiddleIBPCompactAmplitude, Algebra.smul_def,
        div_eq_mul_inv]
      rw [map_inv₀]
      change deriv (coordinateMiddleIBPCompactAmplitude m k) theta *
          (↑(coordinateMiddleCosineGuard theta) : Complex)⁻¹ =
        (↑(coordinateMiddleCosineGuard theta) : Complex)⁻¹ *
          deriv (coordinateMiddleIBPCompactAmplitude m k) theta
      exact mul_comm _ _

/-- At the zeroth stage the compact guarded amplitude recovers exactly the
literal middle density on the meridian. -/
theorem coordinateMiddleIBPCompactAmplitude_zero_mul_cos_eq_middle
    (m : Nat) {theta : Real}
    (htheta : theta ∈ Icc (-(Real.pi / 2)) (Real.pi / 2)) :
    coordinateMiddleIBPCompactAmplitude m 0 theta *
        ((Real.cos theta : Real) : Complex) =
      (coordinateMiddleMeridianCutoff theta : Complex) *
        ((Real.cos theta ^ m : Real) : Complex) := by
  by_cases hmiddle : coordinateMiddleMeridianCutoff theta = 0
  · simp [coordinateMiddleIBPCompactAmplitude, coordinateMiddleIBPAmplitude,
      coordinateMiddleIBPAmplitudeReal, hmiddle]
  · have habs : |theta| ≤ 15 * Real.pi / 32 := by
      by_contra hnot
      exact hmiddle (coordinateMiddleMeridianCutoff_eq_zero_of_large_abs htheta
        (lt_of_not_ge hnot).le)
    have hguard : coordinateMiddleGuardCutoff theta = 1 :=
      coordinateMiddleGuardCutoff_eq_one_of_abs_le habs
    rw [show coordinateMiddleIBPCompactAmplitude m 0 theta =
        (coordinateMiddleGuardCutoff theta : Complex) *
          coordinateMiddleIBPAmplitude m theta by rfl, hguard]
    simp only [Complex.ofReal_one, one_mul]
    exact coordinateMiddleIBPAmplitude_mul_cos_eq_middle m htheta

/-- One recursive guarded amplitude recovers the derivative of the preceding
one after multiplication by the variable phase derivative. -/
theorem coordinateMiddleIBPCompactAmplitude_succ_mul_cos_eq_deriv
    (m k : Nat) (theta : Real) :
    coordinateMiddleIBPCompactAmplitude m (k + 1) theta *
        ((Real.cos theta : Real) : Complex) =
      deriv (coordinateMiddleIBPCompactAmplitude m k) theta := by
  by_cases hcentral : |theta| ≤ 15 * Real.pi / 32
  · have hguard : coordinateMiddleCosineGuard theta = Real.cos theta := by
      unfold coordinateMiddleCosineGuard
      rw [coordinateMiddleGuardCutoff_eq_one_of_abs_le hcentral]
      ring
    have hguardne : (coordinateMiddleCosineGuard theta : Complex) ≠ 0 :=
      Complex.ofReal_ne_zero.mpr
        (ne_of_gt (coordinateMiddleCosineGuard_pos theta))
    have hcosne : (Real.cos theta : Complex) ≠ 0 := by
      rw [← hguard]
      exact hguardne
    rw [show coordinateMiddleIBPCompactAmplitude m (k + 1) theta =
        deriv (coordinateMiddleIBPCompactAmplitude m k) theta /
          (coordinateMiddleCosineGuard theta : Complex) by rfl]
    rw [hguard]
    field_simp [hcosne]
  · have hlarge : 15 * Real.pi / 32 < |theta| := lt_of_not_ge hcentral
    have hderiv : deriv (coordinateMiddleIBPCompactAmplitude m k) theta = 0 :=
      deriv_eq_zero_of_coordinateMiddle_large_abs
        (fun y hy => coordinateMiddleIBPCompactAmplitude_eq_zero_of_large_abs m k hy)
        hlarge
    rw [show coordinateMiddleIBPCompactAmplitude m (k + 1) theta =
        deriv (coordinateMiddleIBPCompactAmplitude m k) theta /
          (coordinateMiddleCosineGuard theta : Complex) by rfl, hderiv]
    simp

/-- The literal coordinate middle integral is the zeroth compact
variable-phase integral. -/
theorem coordinateMiddleMeridianLocalizedIntegral_eq_coordinateMiddleIBPCompactIntegral_zero
    (m : Nat) (l : Real) :
    coordinateMiddleMeridianLocalizedIntegral m l =
      coordinateMiddleIBPCompactIntegral m 0 l := by
  rw [coordinateMiddleMeridianLocalizedIntegral_eq_middle_cutoff]
  unfold coordinateMiddleIBPCompactIntegral
  apply intervalIntegral.integral_congr
  intro theta htheta
  have htheta' : theta ∈ Icc (-(Real.pi / 2) : Real) (Real.pi / 2) := by
    rw [uIcc_of_le (by linarith [Real.pi_pos])] at htheta
    exact ⟨htheta.1, htheta.2⟩
  change (coordinateMiddleMeridianCutoff theta : Complex) *
      ((Real.cos theta ^ m : Real) : Complex) *
      Complex.exp (((-l * Real.sin theta : Real) : Complex) * Complex.I) =
    coordinateMiddleIBPCompactAmplitude m 0 theta *
      ((Real.cos theta : Real) : Complex) *
      Complex.exp (((-l * Real.sin theta : Real) : Complex) * Complex.I)
  rw [coordinateMiddleIBPCompactAmplitude_zero_mul_cos_eq_middle m htheta']

/-- One literal variable-phase integration by parts in the recursive compact
middle-meridian family. -/
theorem coordinateMiddleIBPCompactIntegral_eq_neg_inv_mul_succ
    (m k : Nat) {l : Real} (hl : l ≠ 0) :
    coordinateMiddleIBPCompactIntegral m k l =
      -((((-l : Real) : Complex) * Complex.I)⁻¹) *
        coordinateMiddleIBPCompactIntegral m (k + 1) l := by
  let a : Real := -(Real.pi / 2)
  let b : Real := Real.pi / 2
  let E : Real → Complex := fun theta =>
    Complex.exp (((-l * Real.sin theta : Real) : Complex) * Complex.I)
  let q : Complex := ((-l : Real) : Complex) * Complex.I
  let s : Complex := q⁻¹
  let A : Real → Complex := coordinateMiddleIBPCompactAmplitude m k
  let A' : Real → Complex := fun theta => deriv A theta
  have hq : q ≠ 0 := by
    dsimp [q]
    exact mul_ne_zero (Complex.ofReal_ne_zero.mpr (neg_ne_zero.mpr hl))
      Complex.I_ne_zero
  have hsq : s * q = 1 := by
    dsimp [s]
    exact inv_mul_cancel₀ hq
  have hA : ∀ theta ∈ uIcc a b, HasDerivAt A (A' theta) theta := by
    intro theta _
    exact ((contDiff_coordinateMiddleIBPCompactAmplitude m k).differentiable (by simp)
      theta).hasDerivAt
  have hE : ∀ theta ∈ uIcc a b,
      HasDerivAt E (E theta * (q * (Real.cos theta : Complex))) theta := by
    intro theta _
    dsimp [E, q]
    have hreal : HasDerivAt (fun x : Real => -l * Real.sin x)
        (-l * Real.cos theta) theta := by
      simpa [mul_comm] using (Real.hasDerivAt_sin theta).const_mul (-l)
    have harg : HasDerivAt
        (fun x : Real => ((-l * Real.sin x : Real) : Complex) * Complex.I)
        (((-l * Real.cos theta : Real) : Complex) * Complex.I) theta := by
      simpa only [Complex.real_smul] using hreal.smul_const Complex.I
    simpa [mul_assoc, mul_left_comm, mul_comm] using harg.cexp
  have hV : ∀ theta ∈ uIcc a b,
      HasDerivAt (fun x : Real => s * E x)
        (E theta * (Real.cos theta : Complex)) theta := by
    intro theta htheta
    have h := (hE theta htheta).const_mul s
    have hcancel : s * (E theta * (q * (Real.cos theta : Complex))) =
        E theta * (Real.cos theta : Complex) := by
      calc
        s * (E theta * (q * (Real.cos theta : Complex))) =
            (s * q) * (E theta * (Real.cos theta : Complex)) := by ring
        _ = E theta * (Real.cos theta : Complex) := by rw [hsq, one_mul]
    simpa only [hcancel] using h
  have hA'cont : Continuous A' := by
    dsimp [A']
    exact (contDiff_coordinateMiddleIBPCompactAmplitude m k).continuous_deriv (by simp)
  have hV'cont : Continuous (fun theta : Real =>
      E theta * (Real.cos theta : Complex)) := by
    dsimp [E]
    fun_prop
  have hparts := intervalIntegral.integral_mul_deriv_eq_deriv_mul
    (u := A) (u' := A') (v := fun theta : Real => s * E theta)
    (v' := fun theta : Real => E theta * (Real.cos theta : Complex))
    hA hV (hA'cont.intervalIntegrable a b) (hV'cont.intervalIntegrable a b)
  have hleft :
      (∫ theta in a..b, A theta * (E theta * (Real.cos theta : Complex))) =
        coordinateMiddleIBPCompactIntegral m k l := by
    unfold coordinateMiddleIBPCompactIntegral
    apply intervalIntegral.integral_congr
    intro theta _
    dsimp [A, E]
    ring
  have hright :
      (∫ theta in a..b, A' theta * (s * E theta)) =
        s * coordinateMiddleIBPCompactIntegral m (k + 1) l := by
    unfold coordinateMiddleIBPCompactIntegral
    rw [← intervalIntegral.integral_const_mul]
    apply intervalIntegral.integral_congr
    intro theta _
    have hderiv := coordinateMiddleIBPCompactAmplitude_succ_mul_cos_eq_deriv m k theta
    dsimp [A', A, E]
    rw [← hderiv]
    ring
  have hboundary :
      A b * (s * E b) - A a * (s * E a) = 0 := by
    have hleft_abs : 15 * Real.pi / 32 < |a| := by
      dsimp [a]
      rw [abs_of_nonpos] <;> nlinarith [Real.pi_pos]
    have hright_abs : 15 * Real.pi / 32 < |b| := by
      dsimp [b]
      rw [abs_of_nonneg] <;> nlinarith [Real.pi_pos]
    have hAleft : A a = 0 := by
      dsimp [A]
      exact coordinateMiddleIBPCompactAmplitude_eq_zero_of_large_abs m k hleft_abs
    have hAright : A b = 0 := by
      dsimp [A]
      exact coordinateMiddleIBPCompactAmplitude_eq_zero_of_large_abs m k hright_abs
    rw [hAleft, hAright]
    ring
  calc
    coordinateMiddleIBPCompactIntegral m k l =
        ∫ theta in a..b, A theta * (E theta * (Real.cos theta : Complex)) := hleft.symm
    _ = A b * (s * E b) - A a * (s * E a) -
        ∫ theta in a..b, A' theta * (s * E theta) := hparts
    _ = -s * coordinateMiddleIBPCompactIntegral m (k + 1) l := by
      rw [hboundary, hright]
      ring
    _ = -((((-l : Real) : Complex) * Complex.I)⁻¹) *
        coordinateMiddleIBPCompactIntegral m (k + 1) l := by
      rfl

/-- The exact repeated variable-phase identity for the literal coordinate
middle meridian. -/
theorem coordinateMiddleMeridianLocalizedIntegral_eq_iteratedIBPCompactIntegral
    (m N : Nat) {l : Real} (hl : l ≠ 0) :
    coordinateMiddleMeridianLocalizedIntegral m l =
      (- (((-l : Real) : Complex) * Complex.I)⁻¹) ^ N *
        coordinateMiddleIBPCompactIntegral m N l := by
  induction N with
  | zero =>
      rw [coordinateMiddleMeridianLocalizedIntegral_eq_coordinateMiddleIBPCompactIntegral_zero]
      simp
  | succ N ih =>
      rw [ih, coordinateMiddleIBPCompactIntegral_eq_neg_inv_mul_succ m N hl, pow_succ]
      ring

/-- The literal coordinate middle meridian has arbitrary polynomial decay in
the absolute frequency.  This is uniform for every meridian power `m`, so in
particular it covers the planar case `m = 0` and the `m = d - 2` factors in
all higher dimensions. -/
theorem exists_coordinateMiddleMeridianLocalizedIntegral_abs_decay
    (m N : Nat) :
    ∃ C : Real, 0 < C ∧ ∀ l : Real, 1 ≤ |l| →
      ‖coordinateMiddleMeridianLocalizedIntegral m l‖ ≤ C / |l| ^ N := by
  let A : Real → Complex := coordinateMiddleIBPCompactAmplitude m N
  have hAcont : Continuous A :=
    (contDiff_coordinateMiddleIBPCompactAmplitude m N).continuous
  have hAbounded : Bornology.IsBounded (A '' Icc (-(Real.pi / 2) : Real)
      (Real.pi / 2)) :=
    (isCompact_Icc.image_of_continuousOn hAcont.continuousOn).isBounded
  rcases hAbounded.exists_pos_norm_le with ⟨M, hM, hMbound⟩
  refine ⟨Real.pi * M, mul_pos Real.pi_pos hM, ?_⟩
  intro l hl
  have hlne : l ≠ 0 := by
    intro hzero
    rw [hzero, abs_zero] at hl
    norm_num at hl
  have hlength : |(Real.pi / 2 : Real) - -(Real.pi / 2)| = Real.pi := by
    rw [abs_of_nonneg]
    · ring
    · nlinarith [Real.pi_pos]
  have hint :
      ‖coordinateMiddleIBPCompactIntegral m N l‖ ≤ M * Real.pi := by
    unfold coordinateMiddleIBPCompactIntegral
    calc
      ‖∫ theta in (-(Real.pi / 2) : Real)..(Real.pi / 2),
          coordinateMiddleIBPCompactAmplitude m N theta *
            ((Real.cos theta : Real) : Complex) *
              Complex.exp (((-l * Real.sin theta : Real) : Complex) * Complex.I)‖ ≤
          M * |(Real.pi / 2 : Real) - -(Real.pi / 2)| := by
            apply intervalIntegral.norm_integral_le_of_norm_le_const
            intro theta htheta
            have htheta' : theta ∈ Icc (-(Real.pi / 2) : Real) (Real.pi / 2) := by
              rw [uIoc_of_le (by linarith [Real.pi_pos])] at htheta
              exact ⟨htheta.1.le, htheta.2⟩
            have hbound : ‖coordinateMiddleIBPCompactAmplitude m N theta‖ ≤ M :=
              hMbound _ (mem_image_of_mem _ htheta')
            rw [norm_mul, norm_mul, Complex.norm_real, Real.norm_eq_abs,
              Complex.norm_exp_ofReal_mul_I, mul_one]
            calc
              ‖coordinateMiddleIBPCompactAmplitude m N theta‖ * |Real.cos theta| ≤
                  M * 1 :=
                mul_le_mul hbound (Real.abs_cos_le_one theta) (abs_nonneg _) hM.le
              _ = M := by ring
      _ = M * Real.pi := by rw [hlength]
  have hinv : ‖-((((-l : Real) : Complex) * Complex.I)⁻¹)‖ = 1 / |l| := by
    rw [norm_neg, norm_inv, norm_mul, Complex.norm_real, Complex.norm_I,
      mul_one, Real.norm_eq_abs, abs_neg]
    exact inv_eq_one_div _
  rw [coordinateMiddleMeridianLocalizedIntegral_eq_iteratedIBPCompactIntegral m N hlne,
    norm_mul, norm_pow, hinv]
  calc
    (1 / |l|) ^ N * ‖coordinateMiddleIBPCompactIntegral m N l‖ ≤
        (1 / |l|) ^ N * (M * Real.pi) :=
      mul_le_mul_of_nonneg_left hint (pow_nonneg (by positivity) _)
    _ = (Real.pi * M) / |l| ^ N := by
      rw [one_div_pow]
      ring

end

end Auto.Spherical.FractalDilations.CoordinateMiddleRapidDecay
