
/- This file was machine-generated by Codex -/

import LeanSpherical.Auto.Spherical.FractalDilations.Maximal
import LeanSpherical.Auto.Spherical.SphericalMaximalL2
open Auto.Spherical.FourierRadius
open Auto.Spherical.FractalDilations.Maximal
open Auto.Spherical.SphericalAverages
open Auto.Spherical.SphericalMaximalL2
open Auto.Spherical.SurfaceCore







/-!
# Finite-radius `L²` estimates

This file records the elementary input for a finite radius set.  It is kept
separate from the covering and dimension arguments: a maximum over finitely
many normalized spherical averages is controlled by the number of radii and
the fixed-radius `L²` contraction.
-/

namespace Auto.Spherical.FractalDilations.FiniteRadiusL2

open Filter MeasureTheory Set

noncomputable section

/-- The square of a normalized spherical average of a continuous `L¹ ∩ L²`
input is integrable.  The estimate itself is the fixed-radius contraction
from `FourierRadius`; this lemma only supplies the integrability needed for a
finite supremum. -/
theorem integrable_norm_sq_normalizedSphericalAverage
    {d : ℕ} (f : Euclidean d → ℂ) (hfcont : Continuous f)
    (hf : Integrable f volume) (hf2 : MemLp f 2 volume) (r : ℝ) :
    Integrable (fun x : Euclidean d =>
      ‖normalizedSphericalAverage d f r x‖ ^ (2 : ℕ)) volume := by
  have hbase : Integrable (fun x : Euclidean d =>
      ‖sphericalAverage d f r x‖ ^ (2 : ℕ)) volume :=
    integrable_norm_sq_sphericalAverage f hfcont hf hf2 r
  have hrewrite :
      (fun x : Euclidean d => ‖normalizedSphericalAverage d f r x‖ ^ (2 : ℕ)) =
        fun x => ‖((surfaceMass d)⁻¹ : ℂ)‖ ^ (2 : ℕ) *
          ‖sphericalAverage d f r x‖ ^ (2 : ℕ) := by
    funext x
    rw [normalizedSphericalAverage, norm_mul]
    ring
  rw [hrewrite]
  exact hbase.const_mul _

/-- The pointwise finite-radius maximal function.  The value on an empty
finite set is defined to be zero; on a nonempty set it is the literal finite
supremum of the normalized spherical averages. -/
def finiteRadiusSphericalMaximalReal (d : ℕ) (s : Finset ℝ)
    (f : SchwartzMap (Euclidean d) ℂ) : Euclidean d → ℝ :=
  fun x => if hs : s.Nonempty then
    s.sup' hs (fun r => ‖normalizedSphericalAverage d (f : Euclidean d → ℂ) r x‖)
  else 0

/-- On a nonempty finite radius set, the definition is the expected finite
supremum. -/
theorem finiteRadiusSphericalMaximalReal_eq_sup'
    {d : ℕ} (s : Finset ℝ) (hs : s.Nonempty)
    (f : SchwartzMap (Euclidean d) ℂ) (x : Euclidean d) :
    finiteRadiusSphericalMaximalReal d s f x =
      s.sup' hs (fun r => ‖normalizedSphericalAverage d (f : Euclidean d → ℂ) r x‖) := by
  simp [finiteRadiusSphericalMaximalReal, hs]

/-- The finite supremum of normalized spherical averages has its elementary
square-integral estimate.  No separation of the radii is needed. -/
theorem finiteRadiusSphericalMaximalReal_sq_bound
    {d : ℕ} (hd : 0 < d) (s : Finset ℝ) (hs : s.Nonempty)
    (f : SchwartzMap (Euclidean d) ℂ) :
    Integrable (fun x : Euclidean d =>
      (finiteRadiusSphericalMaximalReal d s f x) ^ (2 : ℕ)) volume ∧
      (∫ x : Euclidean d,
        (finiteRadiusSphericalMaximalReal d s f x) ^ (2 : ℕ)) ≤
        s.card * ∫ x : Euclidean d, ‖(f : Euclidean d → ℂ) x‖ ^ (2 : ℕ) := by
  let u : ℝ → Euclidean d → ℝ := fun r x =>
    ‖normalizedSphericalAverage d (f : Euclidean d → ℂ) r x‖
  have hu_meas (r : ℝ) : Measurable (u r) := by
    have hcont : Continuous (fun x : Euclidean d =>
        normalizedSphericalAverage d (f : Euclidean d → ℂ) r x) := by
      unfold normalizedSphericalAverage
      exact continuous_const.mul
        ((continuous_sphericalAverage (f : Euclidean d → ℂ) f.continuous).comp
          ((continuous_const : Continuous fun _ : Euclidean d => r).prodMk continuous_id))
    exact hcont.norm.measurable
  have hu_int (r : ℝ) : Integrable (fun x : Euclidean d => (u r x) ^ (2 : ℕ)) volume := by
    simpa only [u] using
      integrable_norm_sq_normalizedSphericalAverage
        (f : Euclidean d → ℂ) f.continuous f.integrable (f.memLp 2 volume) r
  have hfinite := integrable_sq_finset_sup_radius_blocks s hs u
    (fun r _ => hu_meas r) (fun r _ => hu_int r)
  have hsum_bound :
      (∑ r ∈ s, ∫ x : Euclidean d, (u r x) ^ (2 : ℕ)) ≤
        s.card * ∫ x : Euclidean d, ‖(f : Euclidean d → ℂ) x‖ ^ (2 : ℕ) := by
    calc
      (∑ r ∈ s, ∫ x : Euclidean d, (u r x) ^ (2 : ℕ)) ≤
          ∑ r ∈ s, ∫ x : Euclidean d, ‖(f : Euclidean d → ℂ) x‖ ^ (2 : ℕ) := by
        refine Finset.sum_le_sum fun r hr => ?_
        simpa only [u] using
          integral_norm_sq_normalizedSphericalAverage_le hd
            (f : Euclidean d → ℂ) f.continuous f.integrable (f.memLp 2 volume) r
      _ = s.card * ∫ x : Euclidean d, ‖(f : Euclidean d → ℂ) x‖ ^ (2 : ℕ) := by
        simp [nsmul_eq_mul]
  have hrewrite :
      (fun x : Euclidean d =>
        (finiteRadiusSphericalMaximalReal d s f x) ^ (2 : ℕ)) =
          fun x => (s.sup' hs (fun r => u r x)) ^ (2 : ℕ) := by
    funext x
    rw [finiteRadiusSphericalMaximalReal_eq_sup' s hs f x]
  rw [hrewrite]
  exact ⟨hfinite.1, hfinite.2.trans hsum_bound⟩

/-- A finite positive set of radii is pointwise dominated by its literal
finite supremum. -/
theorem fractalSphericalMaximalReal_finset_le
    {d : ℕ} (hd : 0 < d) (s : Finset ℝ) (hs : s.Nonempty)
    (hspos : ∀ r ∈ s, 0 < r) (f : SchwartzMap (Euclidean d) ℂ)
    (x : Euclidean d) :
    fractalSphericalMaximalReal d (↑s : Set ℝ) f x ≤
      finiteRadiusSphericalMaximalReal d s f x := by
  have hEpos : (↑s : Set ℝ) ⊆ Ioi (0 : ℝ) := by
    intro r hr
    exact hspos r (by simpa using hr)
  let U : ℝ := s.sup' hs (fun r =>
    ‖normalizedSphericalAverage d (f : Euclidean d → ℂ) r x‖)
  have hU_nonneg : 0 ≤ U := by
    obtain ⟨r, hr⟩ := hs
    have hle : ‖normalizedSphericalAverage d (f : Euclidean d → ℂ) r x‖ ≤ U := by
      dsimp [U]
      exact Finset.le_sup' (fun t =>
        ‖normalizedSphericalAverage d (f : Euclidean d → ℂ) t x‖) hr
    exact (norm_nonneg _).trans hle
  have hraw : fractalSphericalMaximal d (↑s : Set ℝ)
      (f : Euclidean d → ℂ) x ≤ ENNReal.ofReal U := by
    apply iSup_le
    intro r
    apply ENNReal.ofReal_le_ofReal
    have hr : r.1 ∈ s := r.2
    dsimp [U]
    exact Finset.le_sup' (fun t =>
      ‖normalizedSphericalAverage d (f : Euclidean d → ℂ) t x‖) hr
  have hraw_ne : fractalSphericalMaximal d (↑s : Set ℝ)
      (f : Euclidean d → ℂ) x ≠ ⊤ :=
    fractalSphericalMaximal_ne_top hd (↑s : Set ℝ) hEpos f x
  have hreal : fractalSphericalMaximalReal d (↑s : Set ℝ) f x ≤ U := by
    unfold fractalSphericalMaximalReal
    have hto := (ENNReal.toReal_le_toReal hraw_ne ENNReal.ofReal_ne_top).mpr hraw
    simpa only [ENNReal.toReal_ofReal hU_nonneg] using hto
  simpa only [finiteRadiusSphericalMaximalReal_eq_sup' s hs f x, U] using hreal

/-- The restricted fractal maximal operator on a finite positive radius set
obeys the same cardinality-controlled `L²` estimate as its finite supremum
model. -/
theorem fractalSphericalMaximalReal_finset_sq_bound
    {d : ℕ} (hd : 0 < d) (s : Finset ℝ) (hs : s.Nonempty)
    (hspos : ∀ r ∈ s, 0 < r) (f : SchwartzMap (Euclidean d) ℂ) :
    Integrable (fun x : Euclidean d =>
      (fractalSphericalMaximalReal d (↑s : Set ℝ) f x) ^ (2 : ℕ)) volume ∧
      (∫ x : Euclidean d,
        (fractalSphericalMaximalReal d (↑s : Set ℝ) f x) ^ (2 : ℕ)) ≤
        s.card * ∫ x : Euclidean d, ‖(f : Euclidean d → ℂ) x‖ ^ (2 : ℕ) := by
  have hfinite := finiteRadiusSphericalMaximalReal_sq_bound hd s hs f
  have hpoint (x : Euclidean d) :
      (fractalSphericalMaximalReal d (↑s : Set ℝ) f x) ^ (2 : ℕ) ≤
        (finiteRadiusSphericalMaximalReal d s f x) ^ (2 : ℕ) := by
    have hleft : 0 ≤ fractalSphericalMaximalReal d (↑s : Set ℝ) f x := by
      unfold fractalSphericalMaximalReal
      exact ENNReal.toReal_nonneg
    have hright : 0 ≤ finiteRadiusSphericalMaximalReal d s f x := by
      rw [finiteRadiusSphericalMaximalReal_eq_sup' s hs f x]
      obtain ⟨r, hr⟩ := hs
      exact (norm_nonneg _).trans
        (Finset.le_sup' (fun t =>
          ‖normalizedSphericalAverage d (f : Euclidean d → ℂ) t x‖) hr)
    nlinarith [fractalSphericalMaximalReal_finset_le hd s hs hspos f x]
  have hint : Integrable (fun x : Euclidean d =>
      (fractalSphericalMaximalReal d (↑s : Set ℝ) f x) ^ (2 : ℕ)) volume := by
    refine Integrable.mono' hfinite.1
      ((measurable_fractalSphericalMaximalReal (↑s : Set ℝ) f).pow_const 2).aestronglyMeasurable ?_
    filter_upwards with x
    rw [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg _)]
    exact hpoint x
  refine ⟨hint, ?_⟩
  calc
    (∫ x : Euclidean d,
      (fractalSphericalMaximalReal d (↑s : Set ℝ) f x) ^ (2 : ℕ)) ≤
        ∫ x : Euclidean d,
          (finiteRadiusSphericalMaximalReal d s f x) ^ (2 : ℕ) :=
      integral_mono hint hfinite.1 hpoint
    _ ≤ s.card * ∫ x : Euclidean d, ‖(f : Euclidean d → ℂ) x‖ ^ (2 : ℕ) := hfinite.2

end

end Auto.Spherical.FractalDilations.FiniteRadiusL2