
/- This file was machine-generated by Codex -/

import LeanSpherical.Auto.Spherical.FractalDilations.Q4CrossedMarcinkiewicz
import LeanSpherical.Auto.Spherical.FractalDilations.Q4FactorInterpolation
import LeanSpherical.Auto.Spherical.RationalTails
import LeanSpherical.Auto.Spherical.FractalDilations.MinkowskiQ3StrictRate
open Auto.Spherical.FractalDilations.AbsoluteDyadic
open Auto.Spherical.FractalDilations.AbsoluteReassembly
open Auto.Spherical.FractalDilations.DyadicCovering
open Auto.Spherical.FractalDilations.ExponentRegions
open Auto.Spherical.FractalDilations.Minkowski
open Auto.Spherical.FractalDilations.Q4FactorInterpolation
open Auto.Spherical.FractalDilations.MinkowskiDiscretization
open Auto.Spherical.FractalDilations.MinkowskiQ3StrictRate
open Auto.Spherical.FractalDilations.Q4CrossedMarcinkiewicz
open Auto.Spherical.FractalDilations.RawDyadicSurfaceEndpoint
open Auto.Spherical.FractalDilations.SeparatedPacking
open Auto.Spherical.InterpolationCore
open Auto.Spherical.SchwartzData
open Auto.Spherical.SurfaceCore hiding dyadicScale dyadicScale_pos







/-!
# Rational-Schwartz crossed interpolation at the Minkowski edge

This is the strict `Q₃` interpolation calculation in Lemma 2.3 of
Anderson--Hughes--Roos--Seeger.  Its input is the *literal* physical
`L¹ → L∞` estimate and the literal finite-cover square estimate from
`MinkowskiQ3StrictRate`.

The cutoff is deliberately kept inside the Schwartz class.  At output height
`t`, the rational decomposition is made at
`(K / t)^(1 / (p - 1))`.  The high part is killed by the physical endpoint.
The low part has a hard-cutoff contribution and a residual rational tail;
both are integrated by Tonelli.  This is the direct crossed
`L^(r') → L^r` argument, rather than an endpoint or restricted-weak-type
substitute.
-/

namespace Auto.Spherical.FractalDilations.MinkowskiQ3RationalInterpolation

open Filter MeasureTheory Set ENNReal

noncomputable section

/-- The amplitude scale used in the direct `Q₃` crossed interpolation. -/
def q3RationalAmplitudeScale (p K t : ℝ) : ℝ :=
  (K / t) ^ ((p - 1)⁻¹)

/-- The scale is positive at every positive output height. -/
theorem q3RationalAmplitudeScale_pos
    {p K t : ℝ} (hp1 : 1 < p) (hK : 0 < K) (ht : 0 < t) :
    0 < q3RationalAmplitudeScale p K t := by
  unfold q3RationalAmplitudeScale
  exact Real.rpow_pos_of_pos (div_pos hK ht) _

/-- Its negative `p - 1` power is exactly the output-height factor that
kills the rational high part. -/
theorem q3RationalAmplitudeScale_rpow_one_sub
    {p K t : ℝ} (hp1 : 1 < p) (hK : 0 < K) (ht : 0 < t) :
    (q3RationalAmplitudeScale p K t) ^ (1 - p) = t / K := by
  unfold q3RationalAmplitudeScale
  have hpminus : p - 1 ≠ 0 := by linarith
  have hbase : 0 ≤ K / t := (div_pos hK ht).le
  rw [← Real.rpow_mul hbase]
  have hpower : (p - 1)⁻¹ * (1 - p) = (-1 : ℝ) := by
    field_simp [hpminus]
    ring
  rw [hpower, Real.rpow_neg_one]
  field_simp [hK.ne', ht.ne']

/-- The amplitude-scale map is measurable on the whole real line.  Although
only positive output heights occur in the layer-cake integral, this global
form is needed for the Schwartz profile measurability statement. -/
theorem measurable_q3RationalAmplitudeScale
    {p K : ℝ} (hp1 : 1 < p) :
    Measurable (q3RationalAmplitudeScale p K) := by
  unfold q3RationalAmplitudeScale
  have hexp : 0 ≤ (p - 1)⁻¹ := by
    exact inv_nonneg.mpr (by linarith)
  exact (continuous_id.rpow_const (fun _ => Or.inr hexp)).measurable.comp
    (measurable_const.div measurable_id)

/-- The scalar residual left by the rational low cutoff.  The equality is
the one-dimensional calculation behind the direct crossed interpolation.
It is kept in `ENNReal` because it is subsequently inserted directly into a
Tonelli argument. -/
private theorem q3_rational_residual_tail_scalar
    {u p q K : ℝ} (hu : 0 < u) (hp1 : 1 < p) (hp2 : p < 2)
    (hq : q = p / (p - 1)) (hK : 0 < K) :
    ENNReal.ofReal (K ^ (2 / (p - 1)) / 4) *
        (∫⁻ t in Ioi (K / u ^ (p - 1)),
          (ENNReal.ofReal t) ^ (q - 3 - 2 / (p - 1))) =
      ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2) * u ^ p) := by
  have hpminus : 0 < p - 1 := by linarith
  have hqpos : 0 < q := by
    rw [hq]
    exact div_pos (by linarith) hpminus
  have hupow : 0 < u ^ (p - 1) := Real.rpow_pos_of_pos hu _
  have hthreshold : 0 < K / u ^ (p - 1) := div_pos hK hupow
  have hqshift : q - 2 / (p - 1) = 2 - q := by
    rw [hq]
    field_simp [hpminus.ne']
    ring
  rw [show q - 3 - 2 / (p - 1) =
      (q - 2 / (p - 1)) - 3 by ring]
  rw [lintegral_rpow_Ioi_eq (p := q - 2 / (p - 1)) (by rw [hqshift]; linarith)
    hthreshold]
  rw [hqshift]
  have hdiv :
      (K / u ^ (p - 1)) ^ ((2 - q) - 2) = K ^ (-q) * u ^ p := by
    have hpow : (u ^ (p - 1)) ^ q = u ^ p := by
      rw [← Real.rpow_mul hu.le]
      congr 1
      rw [hq]
      field_simp [hpminus.ne']
    rw [show (2 - q) - 2 = -q by ring]
    rw [Real.div_rpow hK.le hupow.le]
    rw [div_eq_mul_inv, Real.rpow_neg (le_of_lt hupow), inv_inv, hpow]
  have hKpower : K ^ (2 / (p - 1)) * K ^ (-q) = K ^ (q - 2) := by
    rw [← Real.rpow_add hK]
    congr 1
    rw [hq]
    field_simp [hpminus.ne']
    ring
  have hreal :
      (K ^ (2 / (p - 1)) / 4) *
          ((K / u ^ (p - 1)) ^ ((2 - q) - 2) / (2 - (2 - q))) =
        ((1 : ℝ) / 4 / q) * K ^ (q - 2) * u ^ p := by
    rw [hdiv, show 2 - (2 - q) = q by ring]
    calc
      K ^ (2 / (p - 1)) / 4 * (K ^ (-q) * u ^ p / q) =
          (K ^ (2 / (p - 1)) * K ^ (-q)) * u ^ p / (4 * q) := by ring
      _ = K ^ (q - 2) * u ^ p / (4 * q) := by rw [hKpower]
      _ = (1 : ℝ) / 4 / q * K ^ (q - 2) * u ^ p := by ring
  have hleft_nonneg :
      0 ≤ (K ^ (2 / (p - 1)) / 4) := by positivity
  have hright_nonneg :
      0 ≤ ((K / u ^ (p - 1)) ^ ((2 - q) - 2) / (2 - (2 - q))) := by
    rw [show 2 - (2 - q) = q by ring]
    positivity
  rw [← ENNReal.ofReal_mul hleft_nonneg, hreal]

/-- Rewriting the rational residual against the layer-cake weight. -/
private theorem q3_rational_rescaled_weight
    {p q K t : ℝ} (hp1 : 1 < p) (hK : 0 < K) (ht : 0 < t) :
    ENNReal.ofReal
        ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4) *
        (ENNReal.ofReal t) ^ (q - 3) =
      ENNReal.ofReal (K ^ (2 / (p - 1)) / 4) *
        (ENNReal.ofReal t) ^ (q - 3 - 2 / (p - 1)) := by
  have hpminus : p - 1 ≠ 0 := by linarith
  have hbase : 0 < K / t := div_pos hK ht
  have hsquare :
      (((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) =
        (K / t) ^ (2 / (p - 1)) := by
    calc
      (((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) =
          ((K / t) ^ ((p - 1)⁻¹)) ^ ((2 : ℕ) : ℝ) :=
        (Real.rpow_natCast _ 2).symm
      _ = (K / t) ^ ((p - 1)⁻¹ * ((2 : ℕ) : ℝ)) := by
        rw [← Real.rpow_mul hbase.le]
      _ = (K / t) ^ (2 / (p - 1)) := by
        congr 1
        push_cast
        field_simp [hpminus]
  have hreal :
      ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4) * t ^ (q - 3) =
        (K ^ (2 / (p - 1)) / 4) * t ^ (q - 3 - 2 / (p - 1)) := by
    have key : ∀ A T B C : ℝ, A / T / C * B = A / C * (B / T) := by
      intro A T B C
      ring
    rw [hsquare, Real.div_rpow hK.le ht.le]
    conv_rhs => rw [show q - 3 - 2 / (p - 1) = (q - 3) - 2 / (p - 1) from by ring,
      Real.rpow_sub ht]
    exact key _ _ _ _
  rw [ENNReal.ofReal_rpow_of_pos ht, ENNReal.ofReal_rpow_of_pos ht]
  have hleft_nonneg :
      0 ≤ (((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4 := by positivity
  rw [← ENNReal.ofReal_mul hleft_nonneg, hreal,
    ENNReal.ofReal_mul (by positivity : 0 ≤ K ^ (2 / (p - 1)) / 4)]

/-- The non-hard part of the rational low cutoff has an integrable crossed
tail.  This is the additional calculation absent from the hard-cutoff proof:
on `K < t u^(p-1)` the rational low part is at most half its amplitude
scale. -/
private theorem q3_rational_residual_tail
    {α : Type*} [MeasurableSpace α] {μ : Measure α} [SFinite μ]
    (u : α → ℝ) (hu : Measurable u) (hu_nonneg : ∀ x, 0 ≤ u x)
    {p q K : ℝ} (hp1 : 1 < p) (hp2 : p < 2)
    (hq : q = p / (p - 1)) (hK : 0 < K) :
    (∫⁻ t in Ioi (0 : ℝ),
      ((∫⁻ x,
        {x | K < t * (u x) ^ (p - 1)}.indicator
          (fun _ => ENNReal.ofReal
            ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x ∂μ) *
        (ENNReal.ofReal t) ^ (q - 3))) ≤
      ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2)) *
        ∫⁻ x, (ENNReal.ofReal (u x)) ^ p ∂μ := by
  let a : α → ℝ := fun x => K / (u x) ^ (p - 1)
  let v : α → ENNReal := fun x =>
    ({x | 0 < u x}.indicator (fun _ => (1 : ENNReal)) x)
  let w : ℝ → ENNReal := fun t =>
    ENNReal.ofReal (K ^ (2 / (p - 1)) / 4) *
      (ENNReal.ofReal t) ^ (q - 3 - 2 / (p - 1))
  have hpminus : 0 < p - 1 := by linarith
  have hqpos : 0 < q := by
    rw [hq]
    exact div_pos (by linarith) hpminus
  have hpow : Measurable (fun x => (u x) ^ (p - 1)) := by
    exact (continuous_id.rpow_const (fun _ => Or.inr hpminus.le)).measurable.comp hu
  have ha : Measurable a := by
    exact measurable_const.div hpow
  have ha_nonneg : ∀ x, 0 ≤ a x := by
    intro x
    exact div_nonneg hK.le (Real.rpow_nonneg (hu_nonneg x) _)
  have hv : Measurable v := by
    exact measurable_const.indicator (measurableSet_lt measurable_const hu)
  have hw : Measurable w := by
    exact measurable_const.mul
      (ENNReal.continuous_rpow_const.measurable.comp
        ENNReal.continuous_ofReal.measurable)
  have hcut_meas (t : ℝ) : Measurable (fun x =>
      {x | K < t * (u x) ^ (p - 1)}.indicator
        (fun _ => ENNReal.ofReal
          ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x) := by
    exact measurable_const.indicator
      (measurableSet_lt measurable_const (measurable_const.mul hpow))
  have hpoint (t : ℝ) (ht : 0 < t) (x : α) :
      (ENNReal.ofReal t) ^ (q - 3) *
          {x | K < t * (u x) ^ (p - 1)}.indicator
            (fun _ => ENNReal.ofReal
              ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x ≤
        w t * ({x | a x < t}.indicator v x) := by
    by_cases hzero : u x = 0
    · have hpowzero : (u x) ^ (p - 1) = 0 := by
        rw [hzero, Real.zero_rpow hpminus.ne']
      have hnotcut : ¬ K < t * (u x) ^ (p - 1) := by
        rw [hpowzero]
        linarith
      have hind : ({x | K < t * (u x) ^ (p - 1)}.indicator
          (fun _ => ENNReal.ofReal
            ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x) = 0 := by
        apply Set.indicator_of_notMem
        simpa only [Set.mem_setOf_eq] using hnotcut
      rw [hind, mul_zero]
      exact zero_le
    · have hupos : 0 < u x := lt_of_le_of_ne (hu_nonneg x) (Ne.symm hzero)
      have hupow : 0 < (u x) ^ (p - 1) := Real.rpow_pos_of_pos hupos _
      have hcut : K < t * (u x) ^ (p - 1) ↔ a x < t := by
        dsimp only [a]
        exact (div_lt_iff₀ hupow).symm
      by_cases hmem : K < t * (u x) ^ (p - 1)
      · have hva : v x = 1 := by simp [v, hupos]
        have hscale := q3_rational_rescaled_weight hp1 hK ht (q := q)
        rw [show {x | K < t * (u x) ^ (p - 1)}.indicator
              (fun _ => ENNReal.ofReal
                ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x =
              ENNReal.ofReal ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4) from by
              simp [hmem]]
        rw [show ({x | a x < t}.indicator v x) = 1 from by
          simp [hcut.mp hmem, hva]]
        simp only [mul_one, w]
        rw [mul_comm, hscale]
      · have hnot : ¬ a x < t := by simpa only [hcut] using hmem
        simp [hmem, hnot]
  have houter :
      (∫⁻ t in Ioi (0 : ℝ),
        ((∫⁻ x,
          {x | K < t * (u x) ^ (p - 1)}.indicator
            (fun _ => ENNReal.ofReal
              ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x ∂μ) *
          (ENNReal.ofReal t) ^ (q - 3))) ≤
        ∫⁻ t in Ioi (0 : ℝ),
          w t * ∫⁻ x in {x | a x < t}, v x ∂μ := by
    apply lintegral_mono_ae
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    have hleft :
        (∫⁻ x,
          {x | K < t * (u x) ^ (p - 1)}.indicator
            (fun _ => ENNReal.ofReal
              ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x ∂μ) *
            (ENNReal.ofReal t) ^ (q - 3) =
          ∫⁻ x, (ENNReal.ofReal t) ^ (q - 3) *
            ({x | K < t * (u x) ^ (p - 1)}.indicator
              (fun _ => ENNReal.ofReal
                ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x) ∂μ := by
      rw [mul_comm, ← lintegral_const_mul _ (hcut_meas t)]
    have hright :
        (∫⁻ x, w t * ({x | a x < t}.indicator v x) ∂μ) =
          w t * ∫⁻ x in {x | a x < t}, v x ∂μ := by
      calc
        (∫⁻ x, w t * ({x | a x < t}.indicator v x) ∂μ) =
            w t * ∫⁻ x, ({x | a x < t}.indicator v x) ∂μ :=
          lintegral_const_mul _ (hv.indicator (measurableSet_lt ha measurable_const))
        _ = w t * ∫⁻ x in {x | a x < t}, v x ∂μ := by
          rw [lintegral_indicator (measurableSet_lt ha measurable_const)]
    rw [hleft, ← hright]
    apply lintegral_mono
    intro x
    exact hpoint t ht x
  have hswap :
      (∫⁻ t in Ioi (0 : ℝ),
          w t * ∫⁻ x in {x | a x < t}, v x ∂μ) =
        ∫⁻ x, v x * (∫⁻ t in Ioi (a x), w t) ∂μ := by
    exact lintegral_swap_indicator_lt a ha ha_nonneg v hv w hw
  have hpointwise (x : α) :
      v x * (∫⁻ t in Ioi (a x), w t) ≤
        ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2)) *
          (ENNReal.ofReal (u x)) ^ p := by
    by_cases hzero : u x = 0
    · simp [v, hzero]
    · have hupos : 0 < u x := lt_of_le_of_ne (hu_nonneg x) (Ne.symm hzero)
      have hvone : v x = 1 := by simp [v, hupos]
      rw [hvone, one_mul]
      change (∫⁻ t in Ioi (K / (u x) ^ (p - 1)),
        ENNReal.ofReal (K ^ (2 / (p - 1)) / 4) *
          (ENNReal.ofReal t) ^ (q - 3 - 2 / (p - 1))) ≤ _
      rw [lintegral_const_mul _ (show Measurable
        (fun t : ℝ => (ENNReal.ofReal t) ^ (q - 3 - 2 / (p - 1))) from
        ENNReal.continuous_rpow_const.measurable.comp
          ENNReal.continuous_ofReal.measurable)]
      rw [q3_rational_residual_tail_scalar hupos hp1 hp2 hq hK]
      have hconstant : 0 ≤ ((1 : ℝ) / 4 / q) * K ^ (q - 2) := by
        positivity
      rw [ENNReal.ofReal_mul hconstant, ENNReal.ofReal_rpow_of_pos hupos]
  calc
    (∫⁻ t in Ioi (0 : ℝ),
        ((∫⁻ x,
          {x | K < t * (u x) ^ (p - 1)}.indicator
            (fun _ => ENNReal.ofReal
              ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x ∂μ) *
          (ENNReal.ofReal t) ^ (q - 3))) ≤
        ∫⁻ t in Ioi (0 : ℝ),
          w t * ∫⁻ x in {x | a x < t}, v x ∂μ := houter
    _ = ∫⁻ x, v x * (∫⁻ t in Ioi (a x), w t) ∂μ := hswap
    _ ≤ ∫⁻ x, ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2)) *
          (ENNReal.ofReal (u x)) ^ p ∂μ := by
      apply lintegral_mono
      intro x
      exact hpointwise x
    _ = _ := lintegral_const_mul _
      (ENNReal.continuous_rpow_const.measurable.comp hu.ennreal_ofReal)

/-- The rational Schwartz low part, evaluated at the height-dependent
crossed scale, has the required square tail.  The first summand is exactly
the hard power-cutoff tail; the second is `q3_rational_residual_tail`. -/
private theorem q3_rational_schwartz_crossed_low_tail
    {d : Nat} (f : SchwartzMap (Euclidean d) ℂ)
    (low high : ℝ → SchwartzMap (Euclidean d) ℂ)
    (hlow : ∀ t x, low t x =
      ((1 + ‖(t⁻¹ : ℝ) • f x‖ ^ 2) ^ (-1 : ℝ)) • f x)
    (hhigh : ∀ t, high t = f - low t)
    {p q K : ℝ} (hp1 : 1 < p) (hp2 : p < 2)
    (hq : q = p / (p - 1)) (hK : 0 < K) :
    (∫⁻ t in Ioi (0 : ℝ),
      (∫⁻ x, ENNReal.ofReal
        (‖low (q3RationalAmplitudeScale p K t) x‖ ^ (2 : ℕ))) *
        (ENNReal.ofReal t) ^ (q - 3)) ≤
      ((ENNReal.ofReal (q - 2))⁻¹ * (ENNReal.ofReal K) ^ (q - 2) +
        ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2))) *
        ∫⁻ x, (ENNReal.ofReal ‖f x‖) ^ p := by
  let u : Euclidean d → ℝ := fun x => ‖f x‖
  let cut : ℝ → Euclidean d → ℝ := fun t x =>
    q4PowerCutoffLow p K t u x
  let residual : ℝ → Euclidean d → ENNReal := fun t x =>
    ({x | K < t * (u x) ^ (p - 1)}.indicator
      (fun _ => ENNReal.ofReal
        ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4)) x)
  let w : ℝ → ENNReal := fun t => (ENNReal.ofReal t) ^ (q - 3)
  let lowI : ℝ → ENNReal := fun t =>
    ∫⁻ x, ENNReal.ofReal
      (‖low (q3RationalAmplitudeScale p K t) x‖ ^ (2 : ℕ))
  let cutI : ℝ → ENNReal := fun t =>
    ∫⁻ x, ENNReal.ofReal (‖cut t x‖ ^ (2 : ℕ))
  let residualI : ℝ → ENNReal := fun t => ∫⁻ x, residual t x
  have hpminus : 0 < p - 1 := by linarith
  have hu : Measurable u := by
    simpa only [u] using f.continuous.norm.measurable
  have hunonneg : ∀ x, 0 ≤ u x := by
    intro x
    exact norm_nonneg _
  have hscale_meas : Measurable (q3RationalAmplitudeScale p K) :=
    measurable_q3RationalAmplitudeScale hp1
  have hprofiles := measurable_rational_low_high_profile_lintegrals
    (μ := volume) f low high hlow hhigh
  have hlowI_meas : Measurable lowI := by
    simpa only [lowI, Function.comp_def] using hprofiles.1.comp hscale_meas
  have hcutI_meas : Measurable cutI := by
    simpa only [cutI, cut, u] using
      measurable_lintegral_q4PowerCutoffLow_sq (μ := volume) hp1 K
        (fun x : Euclidean d => ‖f x‖) f.continuous.norm.measurable
  have hcut_fun_meas (t : ℝ) : Measurable (fun x =>
      ENNReal.ofReal (‖cut t x‖ ^ (2 : ℕ))) := by
    have hbase : Measurable (fun x => ENNReal.ofReal ((u x) ^ (2 : ℕ))) :=
      ENNReal.continuous_ofReal.measurable.comp (hu.pow_const 2)
    have hset : MeasurableSet {x | t * (u x) ^ (p - 1) ≤ K} :=
      measurableSet_le (measurable_const.mul
        ((continuous_id.rpow_const (fun _ => Or.inr hpminus.le)).measurable.comp hu))
        measurable_const
    have heq : (fun x => ENNReal.ofReal (‖cut t x‖ ^ (2 : ℕ))) =
        ({x | t * (u x) ^ (p - 1) ≤ K}.indicator
          (fun x => ENNReal.ofReal ((u x) ^ (2 : ℕ))) : Euclidean d → ENNReal) := by
      funext x
      by_cases hx : t * (u x) ^ (p - 1) ≤ K <;>
        simp [cut, q4PowerCutoffLow, hx, Real.norm_eq_abs,
          abs_of_nonneg (hunonneg x)]
    rw [heq]
    exact hbase.indicator hset
  have hw : Measurable w := by
    exact ENNReal.continuous_rpow_const.measurable.comp
      ENNReal.continuous_ofReal.measurable
  have hcut_tail := crossed_low_tail_of_power_cutoff
    (μ := volume) u hu hunonneg hp1 hp2 hq hK cut hcutI_meas (by
      intro t x ht
      dsimp only [cut, u]
      have h := q4PowerCutoffLow_squared_le p K t
        (fun y : Euclidean d => ‖f y‖) x
      simpa [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg (f x))] using h)
  have hresidual_tail := q3_rational_residual_tail
    (μ := volume) u hu hunonneg hp1 hp2 hq hK
  have hpoint (t : ℝ) (ht : 0 < t) (x : Euclidean d) :
      ENNReal.ofReal
          (‖low (q3RationalAmplitudeScale p K t) x‖ ^ (2 : ℕ)) ≤
        ENNReal.ofReal (‖cut t x‖ ^ (2 : ℕ)) + residual t x := by
    by_cases hcut : t * (u x) ^ (p - 1) ≤ K
    · have hbound := rational_low_high_pointwise_tail_bounds f
        (low (q3RationalAmplitudeScale p K t))
        (high (q3RationalAmplitudeScale p K t))
        (q3RationalAmplitudeScale_pos hp1 hK ht)
        (hlow (q3RationalAmplitudeScale p K t))
        (hhigh (q3RationalAmplitudeScale p K t)) x
      have hlow_le :
          ‖low (q3RationalAmplitudeScale p K t) x‖ ^ (2 : ℕ) ≤
            u x ^ (2 : ℕ) := by
        by_cases hscale : q3RationalAmplitudeScale p K t ≤ u x
        · have hsq :
            (q3RationalAmplitudeScale p K t) ^ (2 : ℕ) / 4 ≤
              u x ^ (2 : ℕ) := by
            have hsq' :
                (q3RationalAmplitudeScale p K t) ^ (2 : ℕ) ≤
                  u x ^ (2 : ℕ) := by
              exact pow_le_pow_left₀ (q3RationalAmplitudeScale_pos hp1 hK ht).le
                hscale 2
            nlinarith
          have hb : ‖low (q3RationalAmplitudeScale p K t) x‖ ^ (2 : ℕ) ≤
              (q3RationalAmplitudeScale p K t) ^ (2 : ℕ) / 4 := by
            simpa only [u, if_pos hscale] using hbound.1
          exact hb.trans hsq
        · have hlt : u x < q3RationalAmplitudeScale p K t := lt_of_not_ge hscale
          simpa only [u, if_neg hscale] using hbound.1
      have hcut_eq : cut t x = u x := by
        have hmem : x ∈ {y : Euclidean d | t * ‖u y‖ ^ (p - 1) ≤ K} := by
          simpa only [Set.mem_setOf_eq, Real.norm_eq_abs,
            abs_of_nonneg (hunonneg x)] using hcut
        simp only [cut, q4PowerCutoffLow, Set.indicator_of_mem hmem]
      have hresidual_zero : residual t x = 0 := by
        have hnot : ¬ K < t * (u x) ^ (p - 1) := not_lt_of_ge hcut
        simp [residual, hnot]
      rw [hcut_eq, hresidual_zero]
      simpa [u, Real.norm_eq_abs, abs_of_nonneg (hunonneg x)] using
        ENNReal.ofReal_le_ofReal hlow_le
    · have hlarge : K < t * (u x) ^ (p - 1) := lt_of_not_ge hcut
      have hupos : 0 < u x := by
        by_contra hnot
        have hzero : u x = 0 := le_antisymm (le_of_not_gt hnot) (hunonneg x)
        rw [hzero, Real.zero_rpow hpminus.ne'] at hlarge
        linarith
      have hupow : 0 < (u x) ^ (p - 1) := Real.rpow_pos_of_pos hupos _
      have hscale : q3RationalAmplitudeScale p K t ≤ u x := by
        unfold q3RationalAmplitudeScale
        have hdiv : K / t < (u x) ^ (p - 1) := by
          exact (div_lt_iff₀' ht).mpr hlarge
        have hroot : (K / t) ^ ((p - 1)⁻¹) <
            ((u x) ^ (p - 1)) ^ ((p - 1)⁻¹) :=
          Real.rpow_lt_rpow (le_of_lt (div_pos hK ht)) hdiv (by positivity)
        have hpow : ((u x) ^ (p - 1)) ^ ((p - 1)⁻¹) = u x := by
          rw [← Real.rpow_mul hupos.le,
            show (p - 1) * (p - 1)⁻¹ = 1 from by field_simp,
            Real.rpow_one]
        exact hroot.le.trans_eq hpow
      have hbound := rational_low_high_pointwise_tail_bounds f
        (low (q3RationalAmplitudeScale p K t))
        (high (q3RationalAmplitudeScale p K t))
        (q3RationalAmplitudeScale_pos hp1 hK ht)
        (hlow (q3RationalAmplitudeScale p K t))
        (hhigh (q3RationalAmplitudeScale p K t)) x
      have hlow_le :
          ‖low (q3RationalAmplitudeScale p K t) x‖ ^ (2 : ℕ) ≤
            (q3RationalAmplitudeScale p K t) ^ (2 : ℕ) / 4 := by
        have hsc : q3RationalAmplitudeScale p K t ≤ ‖f x‖ := hscale
        simpa only [if_pos hsc] using hbound.1
      have hcut_zero : cut t x = 0 := by
        have hnotmem : x ∉ {y : Euclidean d | t * ‖u y‖ ^ (p - 1) ≤ K} := by
          simpa only [Set.mem_setOf_eq, Real.norm_eq_abs,
            abs_of_nonneg (hunonneg x)] using hcut
        simp only [cut, q4PowerCutoffLow, Set.indicator_of_notMem hnotmem]
      rw [hcut_zero]
      rw [show residual t x = ENNReal.ofReal
          ((((K / t) ^ ((p - 1)⁻¹)) ^ (2 : ℕ)) / 4) from by
        simp [residual, hlarge]]
      simp only [norm_zero, ENNReal.ofReal_zero, zero_add,
        show (0 : Real) ^ (2 : ℕ) = 0 from by norm_num]
      exact ENNReal.ofReal_le_ofReal (by
        simpa only [q3RationalAmplitudeScale] using hlow_le)
  have hinterior (t : ℝ) (ht : 0 < t) :
      lowI t ≤ cutI t + residualI t := by
    dsimp only [lowI, cutI, residualI]
    calc
      (∫⁻ x, ENNReal.ofReal
          (‖low (q3RationalAmplitudeScale p K t) x‖ ^ (2 : ℕ))) ≤
          ∫⁻ x, ENNReal.ofReal (‖cut t x‖ ^ (2 : ℕ)) + residual t x := by
        apply lintegral_mono
        intro x
        exact hpoint t ht x
      _ = _ := by
        rw [lintegral_add_left (hcut_fun_meas t)]
  have houter :
      (∫⁻ t in Ioi (0 : ℝ), lowI t * w t) ≤
        ∫⁻ t in Ioi (0 : ℝ), (cutI t + residualI t) * w t := by
    apply lintegral_mono_ae
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    exact mul_le_mul' (hinterior t ht) (le_refl (w t))
  have hsplit :
      (∫⁻ t in Ioi (0 : ℝ), (cutI t + residualI t) * w t) =
        (∫⁻ t in Ioi (0 : ℝ), cutI t * w t) +
          ∫⁻ t in Ioi (0 : ℝ), residualI t * w t := by
    calc
      (∫⁻ t in Ioi (0 : ℝ), (cutI t + residualI t) * w t) =
          ∫⁻ t in Ioi (0 : ℝ), cutI t * w t + residualI t * w t := by
        apply lintegral_congr
        intro t
        ring
      _ = _ := lintegral_add_left (hcutI_meas.mul hw) _
  change (∫⁻ t in Ioi (0 : ℝ), lowI t * w t) ≤ _
  calc
    (∫⁻ t in Ioi (0 : ℝ), lowI t * w t) ≤
        ∫⁻ t in Ioi (0 : ℝ), (cutI t + residualI t) * w t := houter
    _ = (∫⁻ t in Ioi (0 : ℝ), cutI t * w t) +
          ∫⁻ t in Ioi (0 : ℝ), residualI t * w t := hsplit
    _ ≤ ((ENNReal.ofReal (q - 2))⁻¹ * (ENNReal.ofReal K) ^ (q - 2)) *
          (∫⁻ x, (ENNReal.ofReal (u x)) ^ p) +
        ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2)) *
          (∫⁻ x, (ENNReal.ofReal (u x)) ^ p) := by
      apply add_le_add
      · simpa only [cutI, w] using hcut_tail
      · simpa only [residualI, w] using hresidual_tail
    _ = _ := by rw [add_mul]

/-- Direct strong crossed interpolation on the Schwartz carrier.  This is
kept private because the public `Q₃` theorem below instantiates every
endpoint from the literal spherical construction rather than exposing an
abstract maximal-operator hypothesis. -/
private theorem q3_rational_schwartz_crossed_moment
    {d : Nat} (T : SchwartzMap (Euclidean d) ℂ → Euclidean d → ℝ)
    (hT_nonneg : ∀ g x, 0 ≤ T g x)
    (hT_subadd : ∀ g h x, T (g + h) x ≤ T g x + T h x)
    (hT_meas : ∀ g, AEMeasurable (T g) volume)
    {A : ℝ} (hA : 0 ≤ A)
    (hLone : ∀ g x, T g x ≤ A * ∫ y, ‖g y‖)
    (Ctwo : ENNReal)
    (hweak_two : ∀ (g : SchwartzMap (Euclidean d) ℂ) {s : ℝ}, 0 < s →
      ENNReal.ofReal (s ^ (2 : ℕ)) * volume {x | s < T g x} ≤
        Ctwo * ∫⁻ x, ENNReal.ofReal (‖g x‖ ^ (2 : ℕ)))
    {p q K I : ℝ} (hp1 : 1 < p) (hp2 : p < 2)
    (hq : q = p / (p - 1)) (hK : 0 < K)
    (f : SchwartzMap (Euclidean d) ℂ)
    (hI : I = ∫ x, ‖f x‖ ^ p) (hbalance : 2 * A * I ≤ K) :
    (∫⁻ x, ENNReal.ofReal ((T f x) ^ q)) ≤
      ENNReal.ofReal q *
        (4 * Ctwo *
          (((ENNReal.ofReal (q - 2))⁻¹ * (ENNReal.ofReal K) ^ (q - 2) +
            ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2))) *
            ∫⁻ x, (ENNReal.ofReal ‖f x‖) ^ p)) := by
  rcases exists_schwartz_rational_low_high_family f with
    ⟨low, high, hlow, hhigh, hsplit⟩
  have hqtwo : 2 < q := by
    rw [hq]
    have hpminus : 0 < p - 1 := by linarith
    apply (lt_div_iff₀ hpminus).mpr
    nlinarith
  have hlow_tail := q3_rational_schwartz_crossed_low_tail
    f low high hlow hhigh hp1 hp2 hq hK
  have hsplit' : ∀ t : ℝ,
      f = low (q3RationalAmplitudeScale p K t) +
        high (q3RationalAmplitudeScale p K t) := by
    intro t
    exact SchwartzMap.ext fun x => hsplit (q3RationalAmplitudeScale p K t) x
  have hhigh_lone : ∀ t : ℝ, 0 < t →
      A * ∫ y, ‖high (q3RationalAmplitudeScale p K t) y‖ ≤ t / 2 := by
    intro t ht
    have hs : 0 < q3RationalAmplitudeScale p K t :=
      q3RationalAmplitudeScale_pos hp1 hK ht
    have hhigh_bound := q4_rational_high_integral_le f
      (low (q3RationalAmplitudeScale p K t))
      (high (q3RationalAmplitudeScale p K t)) hs hp1 hp2
      (hlow (q3RationalAmplitudeScale p K t))
      (hhigh (q3RationalAmplitudeScale p K t))
    have hAI : A * I ≤ K / 2 := by
      nlinarith [hbalance]
    have hAI_div : A * I / K ≤ (1 : ℝ) / 2 := by
      apply (div_le_iff₀ hK).mpr
      calc
        A * I ≤ K / 2 := hAI
        _ = ((1 : ℝ) / 2) * K := by ring
    calc
      A * ∫ y, ‖high (q3RationalAmplitudeScale p K t) y‖ ≤
          A * ((q3RationalAmplitudeScale p K t) ^ (1 - p) *
            ∫ y, ‖f y‖ ^ p) :=
        mul_le_mul_of_nonneg_left hhigh_bound hA
      _ = A * ((q3RationalAmplitudeScale p K t) ^ (1 - p) * I) := by rw [hI]
      _ = A * ((t / K) * I) := by
        rw [q3RationalAmplitudeScale_rpow_one_sub hp1 hK ht]
      _ = t * (A * I / K) := by
        field_simp [hK.ne']
      _ ≤ t * ((1 : ℝ) / 2) := mul_le_mul_of_nonneg_left hAI_div ht.le
      _ = t / 2 := by ring
  have hprofiles := measurable_rational_low_high_profile_lintegrals
    (μ := volume) f low high hlow hhigh
  have hscale_meas : Measurable (q3RationalAmplitudeScale p K) :=
    measurable_q3RationalAmplitudeScale hp1
  apply crossed_marcinkiewicz_strong_of_lone_ltwo_split
    Set.univ (fun (g : SchwartzMap (Euclidean d) ℂ) (x : Euclidean d) => g x)
    T hT_nonneg (fun g h _ _ x => hT_subadd g h x)
    A hA (fun g _ x => hLone g x) Ctwo
    (fun g _ s hs => hweak_two g hs) hqtwo f (hT_meas f)
    (fun t => low (q3RationalAmplitudeScale p K t))
    (fun t => high (q3RationalAmplitudeScale p K t))
    (fun _ => Set.mem_univ _) (fun _ => Set.mem_univ _) hsplit'
    hhigh_lone
    (by
      simpa only [Function.comp_def] using hprofiles.1.comp hscale_meas)
    (((ENNReal.ofReal (q - 2))⁻¹ * (ENNReal.ofReal K) ^ (q - 2) +
      ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2))) *
      ∫⁻ x, (ENNReal.ofReal ‖f x‖) ^ p)
  simpa only [Function.comp_def] using hlow_tail

/-- Chebyshev in the exact square-endpoint form consumed by the rational
crossed calculation.  It is local to this file so the public theorem below
contains only literal spherical hypotheses. -/
private theorem q3_weak_two_of_square_energy
    {d : Nat} (T : SchwartzMap (Euclidean d) ℂ → Euclidean d → ℝ)
    (hT_meas : ∀ g, AEMeasurable (T g) volume)
    {B : ℝ} (hB : 0 ≤ B)
    (hmem : ∀ g, MemLp (T g) 2 volume)
    (henergy : ∀ g,
      (∫ x, (T g x) ^ (2 : ℕ)) ≤ B * ∫ x, ‖g x‖ ^ (2 : ℕ))
    (g : SchwartzMap (Euclidean d) ℂ) {s : ℝ} (hs : 0 < s) :
    ENNReal.ofReal (s ^ (2 : ℕ)) * volume {x | s < T g x} ≤
      ENNReal.ofReal B *
        ∫⁻ x, ENNReal.ofReal (‖g x‖ ^ (2 : ℕ)) := by
  have hTint : Integrable (fun x : Euclidean d => (T g x) ^ (2 : ℕ)) volume :=
    (memLp_two_iff_integrable_sq (hT_meas g).aestronglyMeasurable).1 (hmem g)
  have hCheb :
      ENNReal.ofReal (s ^ (2 : ℕ)) * volume {x | s < T g x} ≤
        ENNReal.ofReal (B * ∫ x, ‖g x‖ ^ (2 : ℕ)) := by
    calc
      ENNReal.ofReal (s ^ (2 : ℕ)) * volume {x | s < T g x} ≤
          ENNReal.ofReal (s ^ (2 : ℕ)) *
            volume {x | ENNReal.ofReal (s ^ (2 : ℕ)) ≤
              ENNReal.ofReal ((T g x) ^ (2 : ℕ))} := by
        apply mul_le_mul_right
        apply measure_mono
        intro x hx
        exact ENNReal.ofReal_le_ofReal (pow_le_pow_left₀ hs.le hx.le 2)
      _ ≤ ∫⁻ x, ENNReal.ofReal ((T g x) ^ (2 : ℕ)) :=
        mul_meas_ge_le_lintegral₀
          ((hT_meas g).pow_const 2).ennreal_ofReal
          (ENNReal.ofReal (s ^ (2 : ℕ)))
      _ = ENNReal.ofReal (∫ x, (T g x) ^ (2 : ℕ)) := by
        symm
        exact ofReal_integral_eq_lintegral_ofReal hTint
          (Filter.Eventually.of_forall fun x => sq_nonneg (T g x))
      _ ≤ ENNReal.ofReal (B * ∫ x, ‖g x‖ ^ (2 : ℕ)) :=
        ENNReal.ofReal_le_ofReal (henergy g)
  have hg_mem : MemLp (g : Euclidean d → ℂ) 2 volume := g.memLp 2 volume
  have hg_int : Integrable (fun x : Euclidean d => ‖g x‖ ^ (2 : ℕ)) volume :=
    (memLp_two_iff_integrable_sq_norm g.continuous.aestronglyMeasurable).1 hg_mem
  have hinput :
      (∫⁻ x, ENNReal.ofReal (‖g x‖ ^ (2 : ℕ))) =
        ENNReal.ofReal (∫ x, ‖g x‖ ^ (2 : ℕ)) := by
    symm
    exact ofReal_integral_eq_lintegral_ofReal hg_int
      (Filter.Eventually.of_forall fun x => sq_nonneg (‖g x‖))
  calc
    ENNReal.ofReal (s ^ (2 : ℕ)) * volume {x | s < T g x} ≤
        ENNReal.ofReal (B * ∫ x, ‖g x‖ ^ (2 : ℕ)) := hCheb
    _ = ENNReal.ofReal B * ENNReal.ofReal (∫ x, ‖g x‖ ^ (2 : ℕ)) := by
      rw [ENNReal.ofReal_mul hB]
    _ = _ := by rw [hinput]

/-- The literal fixed-scale `Q₃` crossed moment estimate in dimensions at
least three.  Unlike an abstract interpolation interface, every analytic
input here is produced internally from the raw physical endpoint and the
Minkowski interval cover.  The free positive balancing parameter `K` is
useful both for the homogeneous zero-input case and for the later choice
`K = 2 A ‖f‖_p^p`. -/
theorem q3_rational_schwartz_crossed_moment_of_physical_lone_ltwo
    {n : Nat} {E : Set Real} {R D B : Real} {j : Nat}
    (hE : E ⊆ Icc (1 : Real) 2) (hR : 0 < R) (hD : 0 < D) (hB : 0 ≤ B)
    (phi : SchwartzMap (Euclidean (n + 1)) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hendpoint : ∀ g : SchwartzMap (Euclidean (n + 1)) Complex,
      ∀ x : Euclidean (n + 1),
      fractalDyadicBandpassMaximal (n + 1) E
        (absoluteDyadicBandpass phi hphiOne hphiZero j) g x ≤
        D * R * ∫ y, ‖(g : Euclidean (n + 1) → Complex) y‖)
    (hl2 : ∀ g : SchwartzMap (Euclidean (n + 1)) Complex,
      MemLp (unnormalizedFractalDyadicBandpassMaximal (n + 1) E
        (absoluteDyadicBandpass phi hphiOne hphiZero j) g) 2 volume ∧
      (∫ x : Euclidean (n + 1),
        ‖unnormalizedFractalDyadicBandpassMaximal (n + 1) E
          (absoluteDyadicBandpass phi hphiOne hphiZero j) g x‖ ^ (2 : Nat)) ≤
        B * ∫ x : Euclidean (n + 1), ‖g x‖ ^ (2 : Nat))
    {p q K I : Real} (hp1 : 1 < p) (hp2 : p < 2)
    (hq : q = p / (p - 1)) (hK : 0 < K)
    (f : SchwartzMap (Euclidean (n + 1)) Complex)
    (hI : I = ∫ x, ‖f x‖ ^ p)
    (hbalance : 2 * (surfaceMass (n + 1) * D * R) * I ≤ K) :
    (∫⁻ x, ENNReal.ofReal
      ((unnormalizedFractalDyadicBandpassMaximal (n + 1) E
        (absoluteDyadicBandpass phi hphiOne hphiZero j) f x) ^ q)) ≤
      ENNReal.ofReal q *
        (4 * ENNReal.ofReal B *
          (((ENNReal.ofReal (q - 2))⁻¹ * (ENNReal.ofReal K) ^ (q - 2) +
            ENNReal.ofReal (((1 : Real) / 4 / q) * K ^ (q - 2))) *
            ∫⁻ x, (ENNReal.ofReal ‖f x‖) ^ p)) := by
  let M : SchwartzMap (Euclidean (n + 1)) Complex → Euclidean (n + 1) → Real :=
    fun g => fractalDyadicBandpassMaximal (n + 1) E
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g
  let U : SchwartzMap (Euclidean (n + 1)) Complex → Euclidean (n + 1) → Real :=
    fun g => unnormalizedFractalDyadicBandpassMaximal (n + 1) E
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g
  let A : Real := surfaceMass (n + 1) * D * R
  have hEpos : E ⊆ Ioi (0 : Real) := by
    intro t ht
    exact lt_of_lt_of_le zero_lt_one (hE ht).1
  have hd0 : 0 < n + 1 := by omega
  have hA : 0 ≤ A := by
    dsimp only [A]
    exact mul_nonneg
      (mul_nonneg (surfaceMass_pos hd0).le hD.le) hR.le
  have hU_nonneg : ∀ g x, 0 ≤ U g x := by
    intro g x
    exact unnormalizedFractalDyadicBandpassMaximal_nonneg E
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g x
  have hU_subadd : ∀ g h x, U (g + h) x ≤ U g x + U h x := by
    intro g h x
    exact unnormalizedFractalDyadicBandpassMaximal_add_le hd0 E hEpos
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g h x
  have hU_meas : ∀ g, AEMeasurable (U g) volume := by
    intro g
    exact (measurable_unnormalizedFractalDyadicBandpassMaximal E
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g).aemeasurable
  have hU_lone : ∀ g x, U g x ≤ A * ∫ y, ‖g y‖ := by
    intro g x
    calc
      U g x = surfaceMass (n + 1) * M g x := by rfl
      _ ≤ surfaceMass (n + 1) *
          (D * R * ∫ y, ‖g y‖) :=
        mul_le_mul_of_nonneg_left (hendpoint g x) (surfaceMass_pos hd0).le
      _ = A * ∫ y, ‖g y‖ := by
        dsimp only [A]
        ring
  have hU_mem : ∀ g, MemLp (U g) 2 volume := by
    intro g
    exact (hl2 g).1
  have hU_energy : ∀ g,
      (∫ x, (U g x) ^ (2 : Nat)) ≤ B * ∫ x, ‖g x‖ ^ (2 : Nat) := by
    intro g
    calc
      (∫ x, (U g x) ^ (2 : Nat)) =
          ∫ x, ‖U g x‖ ^ (2 : Nat) := by
        apply integral_congr_ae
        filter_upwards with x
        rw [Real.norm_of_nonneg (hU_nonneg g x)]
      _ ≤ B * ∫ x, ‖g x‖ ^ (2 : Nat) := (hl2 g).2
  have hU_weak : ∀ (g : SchwartzMap (Euclidean (n + 1)) Complex) {s : Real}, 0 < s →
      ENNReal.ofReal (s ^ (2 : Nat)) * volume {x | s < U g x} ≤
        ENNReal.ofReal B * ∫⁻ x, ENNReal.ofReal (‖g x‖ ^ (2 : Nat)) := by
    intro g s hs
    exact q3_weak_two_of_square_energy U hU_meas hB hU_mem hU_energy g hs
  simpa only [U] using
    q3_rational_schwartz_crossed_moment U hU_nonneg hU_subadd hU_meas hA hU_lone
      (ENNReal.ofReal B) hU_weak hp1 hp2 hq hK f hI (by
        simpa only [A] using hbalance)

/-- The literal fixed-scale `Q₃` crossed moment estimate in dimensions at
least three.  Unlike an abstract interpolation interface, every analytic
input here is produced internally from the raw physical endpoint and the
Minkowski interval cover.  The free positive balancing parameter `K` is
useful both for the homogeneous zero-input case and for the later choice
`K = 2 A ‖f‖_p^p`. -/
theorem q3_literal_minkowski_cover_crossed_moment_of_sharp
    {n : Nat} (hn : 2 ≤ n)
    (C0 C1 : ℝ) (hC0 : 0 < C0) (hC1 : 0 < C1)
    (hdecay : ∀ xi : Euclidean (n + 1), 1 ≤ ‖xi‖ →
      ‖surfaceFourier (n + 1) xi‖ ≤ C0 / ‖xi‖ ^ ((n : ℝ) / 2))
    (hderiv : ∀ xi : Euclidean (n + 1), ∀ s : ℝ, 1 ≤ ‖xi‖ →
      s ∈ Icc (1 : ℝ) 2 →
      ‖deriv (fun t : ℝ => surfaceFourier (n + 1) (t • xi)) s‖ ≤
        C1 / ‖xi‖ ^ ((n : ℝ) / 2 - 1))
    {E : Set ℝ} (hE : E ⊆ Icc (1 : ℝ) 2) (hEne : E.Nonempty)
    {R delta alpha Ccover : ℝ} (hR : 0 < R) (hRone : 1 ≤ R)
    (hdelta : 0 < delta) (hdeltaone : delta < 1) (hdeltaR : delta ≤ R⁻¹)
    (cover : Finset ℝ) (hcover : IsIntervalCover E delta cover)
    (hcard : (cover.card : ℝ) ≤ Ccover * delta ^ (-alpha))
    (phi psi : SchwartzMap (Euclidean (n + 1)) ℂ)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphiNorm : ∀ xi, ‖phi xi‖ ≤ 1)
    (hpsi : ∀ xi : Euclidean (n + 1),
      psi xi = phi (((2 : ℝ) ^ (0 + 1))⁻¹ • xi) -
        phi (((2 : ℝ) ^ 0)⁻¹ • xi))
    {j : Nat} (hj : 1 ≤ j)
    (hRscale : Auto.Spherical.SurfaceCore.dyadicScale j = R)
    {p q K I : ℝ} (hp1 : 1 < p) (hp2 : p < 2)
    (hq : q = p / (p - 1)) (hK : 0 < K)
    (f : SchwartzMap (Euclidean (n + 1)) ℂ)
    (hI : I = ∫ x, ‖f x‖ ^ p)
    (hbalance : 2 *
      (surfaceMass (n + 1) * absoluteDyadicSurfaceL1EndpointConstant n C0 j) * I ≤ K) :
    (∫⁻ x, ENNReal.ofReal
      ((unnormalizedFractalDyadicBandpassMaximal (n + 1) E
        (absoluteDyadicBandpass phi hphiOne hphiZero j) f x) ^ q)) ≤
      ENNReal.ofReal q *
        (4 * ENNReal.ofReal
          ((Ccover * delta ^ (-alpha)) *
            ((8 * C0 ^ 2 + 8 * C1 ^ 2) * R ^ (-(n : ℝ)))) *
          (((ENNReal.ofReal (q - 2))⁻¹ * (ENNReal.ofReal K) ^ (q - 2) +
            ENNReal.ofReal (((1 : ℝ) / 4 / q) * K ^ (q - 2))) *
            ∫⁻ x, (ENNReal.ofReal ‖f x‖) ^ p)) := by
  let M : SchwartzMap (Euclidean (n + 1)) ℂ → Euclidean (n + 1) → ℝ :=
    fun g => fractalDyadicBandpassMaximal (n + 1) E
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g
  let U : SchwartzMap (Euclidean (n + 1)) ℂ → Euclidean (n + 1) → ℝ :=
    fun g => unnormalizedFractalDyadicBandpassMaximal (n + 1) E
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g
  let A : ℝ := surfaceMass (n + 1) * absoluteDyadicSurfaceL1EndpointConstant n C0 j
  let B : ℝ := (Ccover * delta ^ (-alpha)) *
    ((8 * C0 ^ 2 + 8 * C1 ^ 2) * R ^ (-(n : ℝ)))
  have hEpos : E ⊆ Ioi (0 : ℝ) := by
    intro t ht
    exact lt_of_lt_of_le zero_lt_one (hE ht).1
  have hd0 : 0 < n + 1 := by omega
  have hCcover : 0 ≤ Ccover := by
    by_contra hneg
    have hpow : 0 < delta ^ (-alpha) := Real.rpow_pos_of_pos hdelta _
    have hright : Ccover * delta ^ (-alpha) < 0 :=
      mul_neg_of_neg_of_pos (lt_of_not_ge hneg) hpow
    have hleft : 0 ≤ (cover.card : ℝ) := Nat.cast_nonneg _
    linarith [hcard]
  have hA : 0 ≤ A := by
    dsimp only [A]
    exact mul_nonneg (surfaceMass_pos hd0).le
      (absoluteDyadicSurfaceL1EndpointConstant_nonneg n hC0.le j)
  have hB : 0 ≤ B := by
    dsimp only [B]
    positivity
  have hliteral := q3_literal_minkowski_cover_lone_ltwo_of_sharp
    hn C0 C1 hC0 hC1 hdecay hderiv hE hEne hR hRone hdelta hdeltaone hdeltaR
    cover hcover hcard phi psi hphiOne hphiZero hphiNorm hpsi hj hRscale
  have hU_nonneg : ∀ g x, 0 ≤ U g x := by
    intro g x
    exact unnormalizedFractalDyadicBandpassMaximal_nonneg E
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g x
  have hU_subadd : ∀ g h x, U (g + h) x ≤ U g x + U h x := by
    intro g h x
    exact unnormalizedFractalDyadicBandpassMaximal_add_le hd0 E hEpos
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g h x
  have hU_meas : ∀ g, AEMeasurable (U g) volume := by
    intro g
    exact (measurable_unnormalizedFractalDyadicBandpassMaximal E
      (absoluteDyadicBandpass phi hphiOne hphiZero j) g).aemeasurable
  have hU_lone : ∀ g x, U g x ≤ A * ∫ y, ‖g y‖ := by
    intro g x
    calc
      U g x = surfaceMass (n + 1) * M g x := by rfl
      _ ≤ surfaceMass (n + 1) *
          (absoluteDyadicSurfaceL1EndpointConstant n C0 j * ∫ y, ‖g y‖) :=
        mul_le_mul_of_nonneg_left (hliteral.1 g x) (surfaceMass_pos hd0).le
      _ = A * ∫ y, ‖g y‖ := by
        dsimp only [A]
        ring
  have hU_mem : ∀ g, MemLp (U g) 2 volume := by
    intro g
    exact (hliteral.2 g).1
  have hU_energy : ∀ g,
      (∫ x, (U g x) ^ (2 : ℕ)) ≤ B * ∫ x, ‖g x‖ ^ (2 : ℕ) := by
    intro g
    calc
      (∫ x, (U g x) ^ (2 : ℕ)) =
          ∫ x, ‖U g x‖ ^ (2 : ℕ) := by
        apply integral_congr_ae
        filter_upwards with x
        rw [Real.norm_of_nonneg (hU_nonneg g x)]
      _ ≤ B * ∫ x, ‖g x‖ ^ (2 : ℕ) := by
        simpa only [B] using (hliteral.2 g).2
  have hU_weak : ∀ (g : SchwartzMap (Euclidean (n + 1)) ℂ) {s : ℝ}, 0 < s →
      ENNReal.ofReal (s ^ (2 : ℕ)) * volume {x | s < U g x} ≤
        ENNReal.ofReal B * ∫⁻ x, ENNReal.ofReal (‖g x‖ ^ (2 : ℕ)) := by
    intro g s hs
    exact q3_weak_two_of_square_energy U hU_meas hB hU_mem hU_energy g hs
  simpa only [U, B] using
    q3_rational_schwartz_crossed_moment U hU_nonneg hU_subadd hU_meas hA hU_lone
      (ENNReal.ofReal B) hU_weak hp1 hp2 hq hK f hI (by
        simpa only [A] using hbalance)

end

end Auto.Spherical.FractalDilations.MinkowskiQ3RationalInterpolation