
/- This file was machine-generated by Codex -/

import LeanSpherical.Auto.Spherical.FractalDilations.SmoothDyadicIntervalL2
import LeanSpherical.Auto.Spherical.FractalDilations.SmoothDyadicIntervalL1
import LeanSpherical.Auto.Spherical.FractalDilations.MinkowskiDiscretization
import LeanSpherical.Auto.Spherical.InterpolationTail
open Auto.Spherical.FractalDilations.ExponentRegions
open Auto.Spherical.SphericalMaximalL2
open Auto.Spherical.SurfaceCore







/-!
# Frequency-local operators for the Minkowski diagonal

This file contains the operators used in the non-endpoint Minkowski proof.
They are the relative-frequency pieces from the proof of Stein's theorem,
but with the radius supremum restricted to a set `E ⊆ [1,2]`.  Keeping these
definitions in the fractal-dilations directory makes the additional covering
argument independent of the all-radius development.
-/

namespace Auto.Spherical.FractalDilations.MinkowskiSegment

open Filter MeasureTheory FourierTransform Metric Set
open scoped FourierTransform

noncomputable section

/-- The `j`th smooth relative-frequency piece, maximized only over the
specified set of radii.  This is unnormalised; the fixed factor
`(surfaceMass d)⁻¹` is inserted only when it is reassembled into the
normalized spherical average. -/
def fractalRelativeBandpassMaximal (d : ℕ) (E : Set ℝ)
    (φ : SchwartzMap (Euclidean d) ℂ) (j : ℕ)
    (f : SchwartzMap (Euclidean d) ℂ) (x : Euclidean d) : ℝ :=
  (⨆ r : E, ENNReal.ofReal ‖𝓕⁻ (fun ξ : Euclidean d =>
    surfaceFourier d (-r.1 • ξ) *
      (φ (((2 : ℝ) ^ (j + 1))⁻¹ • (r.1 • ξ)) -
        φ (((2 : ℝ) ^ j)⁻¹ • (r.1 • ξ))) *
      𝓕 (f : Euclidean d → ℂ) ξ) x‖).toReal

/-- The finite smooth relative-frequency cutoff, restricted to `E`. -/
def fractalRelativeCutoffMaximal (d : ℕ) (E : Set ℝ)
    (φ : SchwartzMap (Euclidean d) ℂ) (N : ℕ)
    (f : SchwartzMap (Euclidean d) ℂ) (x : Euclidean d) : ℝ :=
  (⨆ r : E, ENNReal.ofReal ‖𝓕⁻ (fun ξ : Euclidean d =>
    surfaceFourier d (-r.1 • ξ) *
      φ (((2 : ℝ) ^ N)⁻¹ • (r.1 • ξ)) *
      𝓕 (f : Euclidean d → ℂ) ξ) x‖).toReal

/-- Restricted relative-frequency lowpass maximal function. -/
def fractalRelativeLowpassMaximal (d : ℕ) (E : Set ℝ)
    (φ : SchwartzMap (Euclidean d) ℂ)
    (f : SchwartzMap (Euclidean d) ℂ) (x : Euclidean d) : ℝ :=
  (⨆ r : E, ENNReal.ofReal ‖𝓕⁻ (fun ξ : Euclidean d =>
    surfaceFourier d (-r.1 • ξ) * φ (r.1 • ξ) *
      𝓕 (f : Euclidean d → ℂ) ξ) x‖).toReal

theorem fractalRelativeBandpassMaximal_nonneg
    {d : ℕ} (E : Set ℝ) (φ : SchwartzMap (Euclidean d) ℂ) (j : ℕ)
    (f : SchwartzMap (Euclidean d) ℂ) (x : Euclidean d) :
    0 ≤ fractalRelativeBandpassMaximal d E φ j f x := by
  exact ENNReal.toReal_nonneg

theorem fractalRelativeCutoffMaximal_nonneg
    {d : ℕ} (E : Set ℝ) (φ : SchwartzMap (Euclidean d) ℂ) (N : ℕ)
    (f : SchwartzMap (Euclidean d) ℂ) (x : Euclidean d) :
    0 ≤ fractalRelativeCutoffMaximal d E φ N f x := by
  exact ENNReal.toReal_nonneg

theorem fractalRelativeLowpassMaximal_nonneg
    {d : ℕ} (E : Set ℝ) (φ : SchwartzMap (Euclidean d) ℂ)
    (f : SchwartzMap (Euclidean d) ℂ) (x : Euclidean d) :
    0 ≤ fractalRelativeLowpassMaximal d E φ f x := by
  exact ENNReal.toReal_nonneg

/-- A finite supremum of nonnegative local pieces has the expected square
function bound.  This is the precise finite-cover step which retains a
square-root, rather than a full cardinality, loss at the `L²` endpoint. -/
theorem memLp_two_of_le_finset_sup_of_local_sq
    {α ι : Type*} [MeasurableSpace α] {μ : Measure α}
    (s : Finset ι) (hs : s.Nonempty) (M : α → ℝ) (u : ι → α → ℝ)
    (hMmeas : Measurable M) (hMnonneg : ∀ x, 0 ≤ M x)
    (hu_nonneg : ∀ i ∈ s, ∀ x, 0 ≤ u i x)
    (hu_meas : ∀ i ∈ s, Measurable (u i))
    (hu_int : ∀ i ∈ s, Integrable (fun x => (u i x) ^ (2 : ℕ)) μ)
    (hle : ∀ x, M x ≤ s.sup' hs (fun i => u i x)) :
    MemLp M 2 μ ∧
      (∫ x, ‖M x‖ ^ (2 : ℕ) ∂μ) ≤
        ∑ i ∈ s, ∫ x, (u i x) ^ (2 : ℕ) ∂μ := by
  have hsup := integrable_sq_finset_sup_radius_blocks s hs u hu_meas hu_int
  have hsup_nonneg (x : α) : 0 ≤ s.sup' hs (fun i => u i x) := by
    rcases s.exists_mem_eq_sup' hs (fun i => u i x) with ⟨i, hi, hsupEq⟩
    rw [hsupEq]
    exact hu_nonneg i hi x
  have hMint : Integrable (fun x => (M x) ^ (2 : ℕ)) μ :=
    Integrable.mono' hsup.1 (hMmeas.pow_const 2).aestronglyMeasurable
      (Filter.Eventually.of_forall fun x => by
        rw [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg _)]
        exact pow_le_pow_left₀ (hMnonneg x) (hle x) 2)
  have hMnormint : Integrable (fun x => ‖M x‖ ^ (2 : ℕ)) μ := by
    convert hMint using 1
    ext x
    rw [Real.norm_of_nonneg (hMnonneg x)]
  refine ⟨(memLp_two_iff_integrable_sq_norm hMmeas.aestronglyMeasurable).2 hMnormint,
    ?_⟩
  calc
    (∫ x, ‖M x‖ ^ (2 : ℕ) ∂μ) = ∫ x, (M x) ^ (2 : ℕ) ∂μ := by
      apply integral_congr_ae
      filter_upwards with x
      rw [Real.norm_of_nonneg (hMnonneg x)]
    _ ≤ ∫ x, (s.sup' hs (fun i => u i x)) ^ (2 : ℕ) ∂μ :=
      integral_mono hMint hsup.1 (fun x =>
        pow_le_pow_left₀ (hMnonneg x) (hle x) 2)
    _ ≤ _ := hsup.2

/-- The corresponding finite-cover `L¹` reduction.  Unlike the square
endpoint, this costs the full sum of the local estimates, as in the usual
Minkowski argument. -/
theorem memLp_one_of_le_finset_sum_of_local_integrable
    {α ι : Type*} [MeasurableSpace α] {μ : Measure α}
    (s : Finset ι) (M : α → ℝ) (u : ι → α → ℝ)
    (hMmeas : Measurable M) (hMnonneg : ∀ x, 0 ≤ M x)
    (hu_nonneg : ∀ i ∈ s, ∀ x, 0 ≤ u i x)
    (hu_int : ∀ i ∈ s, Integrable (u i) μ)
    (hle : ∀ x, M x ≤ ∑ i ∈ s, u i x) :
    MemLp M 1 μ ∧
      (∫ x, ‖M x‖ ∂μ) ≤ ∑ i ∈ s, ∫ x, ‖u i x‖ ∂μ := by
  have hsumInt : Integrable (fun x => ∑ i ∈ s, u i x) μ :=
    integrable_finsetSum s hu_int
  have hsumNonneg (x : α) : 0 ≤ ∑ i ∈ s, u i x := by
    exact Finset.sum_nonneg fun i hi => hu_nonneg i hi x
  have hMint : Integrable M μ :=
    Integrable.mono' hsumInt hMmeas.aestronglyMeasurable
      (Filter.Eventually.of_forall fun x => by
        simpa only [Real.norm_of_nonneg (hMnonneg x)] using hle x)
  refine ⟨(memLp_one_iff_integrable).mpr hMint, ?_⟩
  calc
    (∫ x, ‖M x‖ ∂μ) = ∫ x, M x ∂μ := by
      apply integral_congr_ae
      filter_upwards with x
      rw [Real.norm_of_nonneg (hMnonneg x)]
    _ ≤ ∫ x, ∑ i ∈ s, u i x ∂μ := integral_mono hMint hsumInt hle
    _ = ∑ i ∈ s, ∫ x, u i x ∂μ := integral_finsetSum s hu_int
    _ = ∑ i ∈ s, ∫ x, ‖u i x‖ ∂μ := by
      apply Finset.sum_congr rfl
      intro i hi
      apply integral_congr_ae
      filter_upwards with x
      rw [Real.norm_of_nonneg (hu_nonneg i hi x)]

end

end Auto.Spherical.FractalDilations.MinkowskiSegment