
/- This file was machine-generated by Codex -/

import LeanSpherical.Auto.Spherical.FractalDilations.Q4TriangleGeometry
open Auto.Spherical.FractalDilations.ExponentRegions
open Auto.Spherical.FractalDilations.StrictInteriorGeometry







/-!
# Passing through the `Q4` endpoint

The estimate at `Q4` supplied by Corollary 3.2 of
Anderson--Hughes--Roos--Seeger has an arbitrarily small *loss* at a fixed
dyadic frequency.  Thus a strict point of the `Q1`--`Q3`--`Q4` triangle must
not be treated as a point of the ordinary decaying `Q4` cone.  Instead it is
written as a strict convex interpolation of `Q4` and a point in the open
Minkowski triangle.  The latter has a genuine dyadic gain, which dominates
the chosen small loss.

This file is only the elementary exponent geometry for that argument.  The
formula is useful because it makes the required `Q2` perturbation explicit,
with all three Minkowski barycentric weights positive.
-/

namespace Auto.Spherical.FractalDilations.Q134ToQ123Segment

set_option maxHeartbeats 1000000

noncomputable section

/-- Every strict point of the `Q1`--`Q3`--`Q4` triangle lies strictly on a
segment from `Q4` to a strict point of the Minkowski triangle.

The `Q4` coefficient in the original barycentric description is first
crossed by a sufficiently small amount.  In the affine coordinates based at
`Q1 = 0`, the resulting negative `Q4` coefficient becomes a positive `Q2`
coefficient.  This is precisely the geometric step needed to interpolate
Corollary 3.2 (a small loss at `Q4`) with the strict `Q1Q2Q3` dyadic gain.
-/
theorem exists_strictTriangle123_q4_segment_of_strictTriangle134
    {d : Nat} {beta gamma : Real} {x : ExponentPoint}
    (hd : 3 <= d \/ d = 2 /\ gamma <= 1 / 2)
    (hbeta : 0 < beta) (hbeta_gamma : beta <= gamma) (hgamma_one : gamma <= 1)
    (h : StrictTriangle134Combination d beta gamma x) :
    ∃ z : ExponentPoint, ∃ t : Real,
      0 < t /\ t < 1 /\
        x = (1 - t) • z + t • Q4 d gamma /\
          StrictTriangle123Combination d beta z := by
  rcases h with ⟨a, b, c, ha, hb, hc, habc, hx⟩
  have hd2 : 2 <= d := by
    rcases hd with hd | hd
    · omega
    · omega
  have hbeta_one : beta <= 1 := hbeta_gamma.trans hgamma_one
  have hgamma : 0 < gamma := lt_of_lt_of_le hbeta hbeta_gamma
  let D : Real := d
  let H : Real := D - 1
  let K : Real := H - beta
  let T : Real := D ^ 2 + 2 * gamma - 1
  have hD : (2 : Real) <= D := by
    dsimp only [D]
    exact_mod_cast hd2
  have hH : 0 < H := by
    dsimp only [H]
    linarith
  have hK : 0 < K := by
    dsimp only [K, H]
    exact theoremOne_diagonal_gap_pos hd hbeta_gamma hgamma_one
  have hHbeta : 0 < H + beta := by
    linarith
  have hB3 : 0 < D - beta + 1 := by
    linarith
  have hTalt : (-1 + (d : Real) ^ 2 + gamma * 2) ≠ 0 := by
    have hd2' : (2 : Real) ≤ (d : Real) := by exact_mod_cast hd2
    have hgamma0 : 0 ≤ gamma := hgamma.le
    intro hcontra
    nlinarith
  have hT : 0 < T := by
    dsimp only [T]
    nlinarith [sq_nonneg (D - 2)]
  let u : Real := -(beta * (H + beta)) / (T * K)
  let v : Real := H ^ 2 * (D - beta + 1) / (T * K)
  let r : Real := 1 - u - v
  have hu : u < 0 := by
    dsimp only [u]
    exact div_neg_of_neg_of_pos (by nlinarith : -(beta * (H + beta)) < 0)
      (mul_pos hT hK)
  have hv : 0 < v := by
    dsimp only [v]
    exact div_pos (mul_pos (sq_pos_of_pos hH) hB3) (mul_pos hT hK)
  have hq4 : r • Q1 + u • Q2 d beta + v • Q3 d beta = Q4 d gamma := by
    ext <;> dsimp [r, u, v, D, H, K, T, Q1, Q2, Q3, Q4]
    all_goals field_simp [hHbeta.ne', hB3.ne', hT.ne', hK.ne', hTalt,
      mul_ne_zero hT.ne' hK.ne', mul_ne_zero (mul_ne_zero hT.ne' hK.ne') hHbeta.ne']
    all_goals ring
  have hc_one : c < 1 := by
    nlinarith [ha, hb, habc]
  have hdelta_one : 0 < (1 - c) / 2 := by
    linarith
  have hdelta_two : 0 < b / (2 * v) := by
    exact div_pos hb (mul_pos (by norm_num) hv)
  have habs_one : 0 < |r| + 1 := by
    have : 0 <= |r| := abs_nonneg r
    linarith
  have hdelta_three : 0 < a / (2 * (|r| + 1)) := by
    exact div_pos ha (mul_pos (by norm_num) habs_one)
  let delta : Real := min ((1 - c) / 2) (min (b / (2 * v))
    (a / (2 * (|r| + 1))))
  have hdelta : 0 < delta := by
    dsimp only [delta]
    exact lt_min hdelta_one (lt_min hdelta_two hdelta_three)
  have hdelta_one_le : delta <= (1 - c) / 2 := by
    dsimp only [delta]
    exact min_le_left _ _
  have hdelta_two_le : delta <= b / (2 * v) := by
    dsimp only [delta]
    exact (min_le_right _ _).trans (min_le_left _ _)
  have hdelta_three_le : delta <= a / (2 * (|r| + 1)) := by
    dsimp only [delta]
    exact (min_le_right _ _).trans (min_le_right _ _)
  have hdelta_lt : delta < 1 - c := by
    nlinarith [hdelta_one_le]
  let t : Real := c + delta
  let den : Real := 1 - t
  have ht : 0 < t := by
    dsimp only [t]
    linarith
  have ht_one : t < 1 := by
    dsimp only [t]
    linarith
  have hden : 0 < den := by
    dsimp only [den, t]
    linarith
  have hdelta_v : delta * v <= b / 2 := by
    have htwo_v : 0 < 2 * v := mul_pos (by norm_num) hv
    have hmul : delta * (2 * v) <= b :=
      (le_div_iff₀ htwo_v).mp hdelta_two_le
    nlinarith
  have hwc_num : 0 < b - delta * v := by
    nlinarith [hdelta_v]
  have hdelta_abs_base : delta * (|r| + 1) <= a / 2 := by
    have htwo_abs : 0 < 2 * (|r| + 1) :=
      mul_pos (by norm_num) habs_one
    have hmul : delta * (2 * (|r| + 1)) <= a :=
      (le_div_iff₀ htwo_abs).mp hdelta_three_le
    nlinarith
  have hmul_r_abs : delta * r <= delta * |r| :=
    mul_le_mul_of_nonneg_left (le_abs_self r) hdelta.le
  have habs_le : |r| <= |r| + 1 := by
    have : 0 <= |r| := abs_nonneg r
    linarith
  have hmul_abs : delta * |r| <= delta * (|r| + 1) :=
    mul_le_mul_of_nonneg_left habs_le hdelta.le
  have hwa_num : 0 < a - delta * r := by
    nlinarith [hdelta_abs_base, hmul_r_abs, hmul_abs]
  have hwb_num : 0 < -delta * u := by
    have : delta * u < 0 := mul_neg_of_pos_of_neg hdelta hu
    linarith
  let wa : Real := (a - delta * r) / den
  let wb : Real := (-delta * u) / den
  let wc : Real := (b - delta * v) / den
  have hwa : 0 < wa := div_pos hwa_num hden
  have hwb : 0 < wb := div_pos hwb_num hden
  have hwc : 0 < wc := div_pos hwc_num hden
  have hsum_num :
      (a - delta * r) + (-delta * u) + (b - delta * v) = den := by
    dsimp only [den, t, r]
    calc
      (a - delta * (1 - u - v)) + (-delta * u) + (b - delta * v) =
          a + b - delta := by ring
      _ = 1 - c - delta := by linarith [habc]
      _ = 1 - (c + delta) := by ring
  have hweights : wa + wb + wc = 1 := by
    calc
      wa + wb + wc =
          ((a - delta * r) + (-delta * u) + (b - delta * v)) / den := by
            dsimp only [wa, wb, wc]
            ring
      _ = den / den := by rw [hsum_num]
      _ = 1 := div_self hden.ne'
  let z : ExponentPoint := wa • Q1 + wb • Q2 d beta + wc • Q3 d beta
  have hz : StrictTriangle123Combination d beta z := by
    exact ⟨wa, wb, wc, hwa, hwb, hwc, hweights, rfl⟩
  have hsegment : x = (1 - t) • z + t • Q4 d gamma := by
    rw [← hx]
    simp only [← hq4]
    ext <;> dsimp [z, wa, wb, wc, den, t, r, u, v, D, H, K, T,
      Q1, Q2, Q3, Q4]
    all_goals field_simp [hHbeta.ne', hB3.ne', hT.ne', hK.ne', hden.ne', hTalt]
    all_goals ring
  exact ⟨z, t, ht, ht_one, hsegment, hz⟩

end

end Auto.Spherical.FractalDilations.Q134ToQ123Segment