
/- This file was machine-generated by Codex -/

import LeanSpherical.Auto.Spherical.FractalDilations.Q4LtwoLiteralRate
import LeanSpherical.Auto.Spherical.FractalDilations.Q4TriangleGeometry
open Auto.Spherical.FractalDilations.AbsoluteDyadic
open Auto.Spherical.FractalDilations.AbsoluteReassembly
open Auto.Spherical.FractalDilations.ExponentRegions
open Auto.Spherical.FractalDilations.Q4FiniteProductMaximal
open Auto.Spherical.FractalDilations.Q4LtwoLiteralRate
open Auto.Spherical.FractalDilations.Q4RadialReduction
open Auto.Spherical.FractalDilations.Q4StrictParameters
open Auto.Spherical.FractalDilations.Q4SubpowerParameters
open Auto.Spherical.FractalDilations.Q4TriangleGeometry
open Auto.Spherical.FractalDilations.QuadraticStationaryPhase
open Auto.Spherical.FractalDilations.QuasiAssouadBridge
open Auto.Spherical.SurfaceCore







/-!
# Tunable literal `Q4` loss at a fixed dyadic frequency

Corollary 3.2 in the paper is not a black-box maximal estimate.  Its input
is the finite-shell `TT*` estimate, and its conclusion is that the resulting
frequency ratio can be made smaller than `2^ε` for every `ε > 0`.  This file
packages that calculation while retaining the common radial cutoff explicitly.

The endpoint ratio is intentionally only required to be finite.  It is a
loss estimate, to be mixed later with a strict Minkowski gain; asserting a
ratio below one here would erase the point of the argument.
-/

namespace Auto.Spherical.FractalDilations.Q4LtwoLossRate

open Filter MeasureTheory Set ENNReal

noncomputable section

/-- The `L²` output parameter attached to `theta` has reciprocal parameter
exactly `theta`. -/
theorem two_div_q4LtwoOutputOfTheta
    {theta : Real} (htheta : 0 < theta) :
    2 / q4LtwoOutputOfTheta theta = theta := by
  unfold q4LtwoOutputOfTheta
  field_simp [htheta.ne']

/-- The literal finite-cell `Q4` estimate has a tunable loss at every
non-critical shell parameter in the open Q4 cone.  The cutoff `phi` is an
explicit argument, so this estimate can subsequently be interpolated with a
Minkowski estimate for precisely the same maximal operator.

The inequality `rho < ofReal (2 ^ epsilon)` is the quantitative form needed
later: `epsilon` is selected only after the strict gain and the vertical
geometry have been fixed. -/
theorem q4_active_ltwo_tunable_loss_of_fixed_normRadial_cutoff
    {d : Nat} {E : Set Real} {gamma epsilon theta Ccover : Real}
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ <= 1 -> phi xi = 1)
    (hphiZero : ∀ xi, 2 <= ‖xi‖ -> phi xi = 0)
    (hphiNorm : ∀ xi, ‖phi xi‖ <= 1)
    (hphiRadial : IsNormRadial phi)
    (hd : 3 <= d ∨ d = 2 ∧ gamma < 1 / 2)
    (hE : E ⊆ Icc (1 : Real) 2) (hEne : E.Nonempty)
    (hCcover : 0 <= Ccover) (hgamma : 0 <= gamma)
    (hthetaLower : 1 / (d : Real) < theta)
    (hthetaUpper : theta <
      (((d : Real) - 1) / 2) / ((((d : Real) - 1) / 2) + gamma))
    (hthetaOne : theta < 1) (hepsilon : 0 < epsilon)
    (hcover : HasSubpowerAssouadCoverBound E gamma (epsilon / theta) Ccover) :
    ∃ CT rho : ENNReal, 0 < CT ∧ CT < ⊤ ∧ rho < ⊤ ∧
      rho = ENNReal.ofReal
        ((2 : Real) ^
          (q4FrequencyExponentWithSubpowerLoss d theta (epsilon / theta) / 2)) ∧
      rho < ENNReal.ofReal ((2 : Real) ^ epsilon) ∧
      ∀ j : Nat, 1 <= j -> ∀ f : SchwartzMap (Euclidean d) Complex,
        MemLp (fractalDyadicBandpassMaximal d E
          (absoluteDyadicBandpass phi hphiOne hphiZero j) f)
          (ENNReal.ofReal (q4LtwoOutputOfTheta theta)) volume ∧
        eLpNorm (fractalDyadicBandpassMaximal d E
          (absoluteDyadicBandpass phi hphiOne hphiZero j) f)
          (ENNReal.ofReal (q4LtwoOutputOfTheta theta)) volume <=
          CT * rho ^ j * ENNReal.ofReal
            (Real.sqrt (∫ x, ‖(f : Euclidean d -> Complex) x‖ ^ (2 : Nat))) := by
  have hdpos : 0 < d := by
    rcases hd with hd3 | hd2
    · omega
    · omega
  have hdOne : 1 < d := by
    rcases hd with hd3 | hd2
    · omega
    · omega
  have hdReal : 0 < (d : Real) := by exact_mod_cast hdpos
  have htheta : 0 < theta :=
    lt_trans (one_div_pos.mpr hdReal) hthetaLower
  have heta : 0 <= epsilon / theta :=
    div_nonneg hepsilon.le htheta.le
  have hgap : q4GapExponent d gamma theta < 0 :=
    q4GapExponent_neg_of_lt_balancing_parameter hdOne hgamma hthetaUpper
  have hfrequency :
      q4FrequencyExponentWithSubpowerLoss d theta (epsilon / theta) / 2 <
        epsilon :=
    q4_subpower_half_frequency_exponent_lt hdpos hthetaLower hepsilon
  obtain ⟨hu1, hu2, huoutput⟩ :=
    q4ConjugateInputOfTheta_bounds htheta hthetaOne
  obtain ⟨CT, rho, hCT, hCTtop, hrhotop, hrhoeq, hbound⟩ :=
    q4_active_ltwo_dyadic_rate_of_fixed_normRadial_cutoff
      phi hphiOne hphiZero hphiNorm hphiRadial hd hE hEne hcover hCcover
      hgamma heta hu1 hu2 huoutput hgap
  have hthetaEq : 2 / q4LtwoOutputOfTheta theta = theta :=
    two_div_q4LtwoOutputOfTheta htheta
  have hrhoeq' : rho = ENNReal.ofReal
      ((2 : Real) ^
        (q4FrequencyExponentWithSubpowerLoss d theta (epsilon / theta) / 2)) := by
    calc
      rho = ENNReal.ofReal
          ((2 : Real) ^
            (q4FrequencyExponentWithSubpowerLoss d
              (2 / q4LtwoOutputOfTheta theta) (epsilon / theta) / 2)) := hrhoeq
      _ = ENNReal.ofReal
          ((2 : Real) ^
            (q4FrequencyExponentWithSubpowerLoss d theta (epsilon / theta) / 2)) := by
            rw [hthetaEq]
  refine ⟨CT, rho, hCT, hCTtop, hrhotop, hrhoeq', ?_, ?_⟩
  · rw [hrhoeq']
    exact (ENNReal.ofReal_lt_ofReal_iff_of_nonneg
      (Real.rpow_nonneg (by norm_num) _)).mpr
      (Real.rpow_lt_rpow_of_exponent_lt (by norm_num) hfrequency)
  · intro j hj f
    simpa only using hbound j hj f

/-- The literal zero-gap endpoint has the same arbitrary subpower loss.  This
is the endpoint calculation behind Corollary 3.2: the finite shell gives a
square-root factor, which is absorbed with only a quarter of the requested
loss, while the quasi-Assouad cover uses another quarter.  The base frequency
exponent is allowed to vanish, which is essential for the planar
`d = 2`, `gamma = 1 / 2` case. -/
theorem q4_active_ltwo_zero_gap_tunable_loss_of_fixed_normRadial_cutoff
    {d : Nat} {E : Set Real} {gamma epsilon theta Ccover : Real}
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ <= 1 -> phi xi = 1)
    (hphiZero : ∀ xi, 2 <= ‖xi‖ -> phi xi = 0)
    (hphiNorm : ∀ xi, ‖phi xi‖ <= 1)
    (hphiRadial : IsNormRadial phi)
    (hd : 3 <= d ∨ d = 2 ∧ gamma <= 1 / 2)
    (hE : E ⊆ Icc (1 : Real) 2) (hEne : E.Nonempty)
    (hCcover : 0 <= Ccover) (hgamma : 0 <= gamma)
    (htheta : 0 < theta) (hthetaOne : theta < 1)
    (hfrequency : q4FrequencyExponent d theta <= 0)
    (hgap : q4GapExponent d gamma theta = 0)
    (hepsilon : 0 < epsilon)
    (hcover : HasSubpowerAssouadCoverBound E gamma
      (epsilon / (4 * theta)) Ccover) :
    ∃ CT rho : ENNReal, 0 < CT ∧ CT < ⊤ ∧ rho < ⊤ ∧
      rho = ENNReal.ofReal
        ((2 : Real) ^
          ((q4FrequencyExponentWithSubpowerLoss d theta
            (epsilon / (4 * theta)) + 2 * (epsilon / 4)) / 2)) ∧
      rho < ENNReal.ofReal ((2 : Real) ^ epsilon) ∧
      ∀ j : Nat, 1 <= j -> ∀ f : SchwartzMap (Euclidean d) Complex,
        MemLp (fractalDyadicBandpassMaximal d E
          (absoluteDyadicBandpass phi hphiOne hphiZero j) f)
          (ENNReal.ofReal (q4LtwoOutputOfTheta theta)) volume ∧
        eLpNorm (fractalDyadicBandpassMaximal d E
          (absoluteDyadicBandpass phi hphiOne hphiZero j) f)
          (ENNReal.ofReal (q4LtwoOutputOfTheta theta)) volume <=
          CT * rho ^ j * ENNReal.ofReal
            (Real.sqrt (∫ x, ‖(f : Euclidean d -> Complex) x‖ ^ (2 : Nat))) := by
  have heta : 0 <= epsilon / (4 * theta) := by
    exact div_nonneg hepsilon.le (mul_nonneg (by norm_num) htheta.le)
  obtain ⟨hu1, hu2, huoutput⟩ :=
    q4ConjugateInputOfTheta_bounds htheta hthetaOne
  have hthetaEq : 2 / q4LtwoOutputOfTheta theta = theta :=
    two_div_q4LtwoOutputOfTheta htheta
  have hgap' : q4GapExponent d gamma (2 / q4LtwoOutputOfTheta theta) = 0 := by
    rw [hthetaEq]
    exact hgap
  have hscale : theta * (epsilon / (4 * theta)) = epsilon / 4 := by
    field_simp [htheta.ne']
    ring
  have hsmall :
      (q4FrequencyExponentWithSubpowerLoss d theta
          (epsilon / (4 * theta)) + 2 * (epsilon / 4)) / 2 < epsilon := by
    unfold q4FrequencyExponentWithSubpowerLoss
    rw [hscale]
    nlinarith
  obtain ⟨CT, rho, hCT, hCTtop, hrhotop, hrhoeq, hbound⟩ :=
    q4_active_ltwo_zero_gap_loss_of_fixed_normRadial_cutoff
      phi hphiOne hphiZero hphiNorm hphiRadial hd hE hEne hcover hCcover
      hgamma heta hu1 hu2 huoutput hgap' (by linarith)
  have hrhoeq' : rho = ENNReal.ofReal
      ((2 : Real) ^
        ((q4FrequencyExponentWithSubpowerLoss d theta
          (epsilon / (4 * theta)) + 2 * (epsilon / 4)) / 2)) := by
    calc
      rho = ENNReal.ofReal
          ((2 : Real) ^
            ((q4FrequencyExponentWithSubpowerLoss d
              (2 / q4LtwoOutputOfTheta theta) (epsilon / (4 * theta)) +
              2 * (epsilon / 4)) / 2)) := hrhoeq
      _ = ENNReal.ofReal
          ((2 : Real) ^
            ((q4FrequencyExponentWithSubpowerLoss d theta
              (epsilon / (4 * theta)) + 2 * (epsilon / 4)) / 2)) := by
          rw [hthetaEq]
  refine ⟨CT, rho, hCT, hCTtop, hrhotop, hrhoeq', ?_, ?_⟩
  · rw [hrhoeq']
    exact (ENNReal.ofReal_lt_ofReal_iff_of_nonneg
      (Real.rpow_nonneg (by norm_num) _)).mpr
      (Real.rpow_lt_rpow_of_exponent_lt (by norm_num) hsmall)
  · intro j hj f
    simpa only using hbound j hj f

/-- The Q4 balancing specialization of the literal endpoint-loss estimate.
This includes the planar critical value `d = 2`, `gamma = 1 / 2`; at that
value the unperturbed frequency exponent is zero, but the preceding finite
shell argument still supplies every prescribed subpower loss. -/
theorem q4_active_ltwo_balancing_tunable_loss_of_fixed_normRadial_cutoff
    {d : Nat} {E : Set Real} {gamma epsilon Ccover : Real}
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ <= 1 -> phi xi = 1)
    (hphiZero : ∀ xi, 2 <= ‖xi‖ -> phi xi = 0)
    (hphiNorm : ∀ xi, ‖phi xi‖ <= 1)
    (hphiRadial : IsNormRadial phi)
    (hd : 3 <= d ∨ d = 2 ∧ gamma <= 1 / 2)
    (hE : E ⊆ Icc (1 : Real) 2) (hEne : E.Nonempty)
    (hCcover : 0 <= Ccover) (hgamma : 0 <= gamma)
    (hgammaOne : gamma <= 1) (hgammaPos : 0 < gamma)
    (hepsilon : 0 < epsilon)
    (hcover : HasSubpowerAssouadCoverBound E gamma
      (epsilon / (4 * q4BalancingParameter d gamma)) Ccover) :
    ∃ CT rho : ENNReal, 0 < CT ∧ CT < ⊤ ∧ rho < ⊤ ∧
      rho = ENNReal.ofReal
        ((2 : Real) ^
          ((q4FrequencyExponentWithSubpowerLoss d
            (q4BalancingParameter d gamma)
            (epsilon / (4 * q4BalancingParameter d gamma)) +
            2 * (epsilon / 4)) / 2)) ∧
      rho < ENNReal.ofReal ((2 : Real) ^ epsilon) ∧
      ∀ j : Nat, 1 <= j -> ∀ f : SchwartzMap (Euclidean d) Complex,
        MemLp (fractalDyadicBandpassMaximal d E
          (absoluteDyadicBandpass phi hphiOne hphiZero j) f)
          (ENNReal.ofReal
            (q4LtwoOutputOfTheta (q4BalancingParameter d gamma))) volume ∧
        eLpNorm (fractalDyadicBandpassMaximal d E
          (absoluteDyadicBandpass phi hphiOne hphiZero j) f)
          (ENNReal.ofReal
            (q4LtwoOutputOfTheta (q4BalancingParameter d gamma))) volume <=
          CT * rho ^ j * ENNReal.ofReal
            (Real.sqrt (∫ x, ‖(f : Euclidean d -> Complex) x‖ ^ (2 : Nat))) := by
  have hdOne : 1 < d := by
    rcases hd with hd3 | hd2
    · omega
    · omega
  have htheta : 0 < q4BalancingParameter d gamma :=
    q4BalancingParameter_pos hdOne hgamma
  have hthetaOne : q4BalancingParameter d gamma < 1 :=
    q4BalancingParameter_lt_one hdOne hgammaPos
  have hfrequency :
      q4FrequencyExponent d (q4BalancingParameter d gamma) <= 0 :=
    q4FrequencyExponent_nonpos_balancingParameter hd hgamma hgammaOne
  have hgap : q4GapExponent d gamma (q4BalancingParameter d gamma) = 0 :=
    q4GapExponent_balancingParameter hdOne hgamma
  exact q4_active_ltwo_zero_gap_tunable_loss_of_fixed_normRadial_cutoff
    phi hphiOne hphiZero hphiNorm hphiRadial hd hE hEne hCcover hgamma
    htheta hthetaOne hfrequency hgap hepsilon hcover

end

end Auto.Spherical.FractalDilations.Q4LtwoLossRate