/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.FractalDilations.AllDimensionalDerivativeCoordinateSymbols

/-!
# Cone estimates for differentiated all-dimensional pair kernels

This is the actual higher-dimensional radius-derivative analogue of the
coordinate-wave cone proof.  It works with the literal differentiated
amplitudes and their finite 27-term expansion throughout.
-/

namespace LeanSpherical.HarmonicAnalysis.FractalDilations

open Filter MeasureTheory Metric Set
open scoped BigOperators ContDiff ComplexConjugate

noncomputable section

private theorem contDiff_coordinateWaveRadiusDerivativeMultiplierPairAmplitude
    (d : Nat) (q t : CoordinateWavePart) {R R' : Real} (hR : R ≠ 0) (hR' : R' ≠ 0) :
    ContDiff Real (⊤ : ℕ∞)
      (coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t R R') := by
  unfold coordinateWaveRadiusDerivativeMultiplierPairAmplitude
  apply ((by fun_prop : ContDiff Real (⊤ : ℕ∞)
    (fun _ : Real => (surfaceMass d : Complex)⁻¹)).mul
      (contDiff_coordinateWaveRadiusDerivativeAmplitude d q hR)).mul
  have hbase : ContDiff Real (⊤ : ℕ∞)
      (fun u : Real => (surfaceMass d : Complex)⁻¹ *
        coordinateWaveRadiusDerivativeAmplitude d t R' u) :=
    (by fun_prop).mul (contDiff_coordinateWaveRadiusDerivativeAmplitude d t hR')
  have heq : (fun u : Real => starRingEnd Complex
      ((surfaceMass d : Complex)⁻¹ *
        coordinateWaveRadiusDerivativeAmplitude d t R' u)) =
      (Complex.conjCLE : Complex → Complex) ∘
        (fun u : Real => (surfaceMass d : Complex)⁻¹ *
          coordinateWaveRadiusDerivativeAmplitude d t R' u) := by
    funext u
    simpa only [Function.comp_apply] using
      (Complex.conjCLE_apply
        ((surfaceMass d : Complex)⁻¹ *
          coordinateWaveRadiusDerivativeAmplitude d t R' u)).symm
  rw [heq]
  exact Complex.conjCLE.contDiff.comp hbase

/-- The two literal differentiated multiplier factors retain the expected
`s^(-(d-1))` product stationary size through every finite radial order. -/
private theorem exists_uniform_coordinateWaveRadiusDerivativeMultiplierPairAmplitude_scaled
    {d N : Nat} (hd : 2 ≤ d) (q t : CoordinateWavePart) :
    ∃ C : Real, 0 < C ∧ ∀ k : Nat, k ≤ N → ∀ s r r' u : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) →
      r' ∈ Icc (1 / 2 : Real) (5 / 2) → u ∈ Icc (1 / 2 : Real) 8 →
      ‖iteratedDeriv k
        (coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t (s * r) (s * r')) u‖ ≤
        C / s ^ (d - 1) := by
  obtain ⟨A, hA, hAbound⟩ :=
    exists_uniform_coordinateWaveRadiusDerivativeAmplitude_scaled (d := d) (N := N) hd q
  obtain ⟨B, hB, hBbound⟩ :=
    exists_uniform_coordinateWaveRadiusDerivativeAmplitude_scaled (d := d) (N := N) hd t
  let M : Real := ‖(surfaceMass d : Complex)⁻¹‖
  let D : Real := ∑ l ∈ Finset.range (N + 1),
    tripleWaveLeibnizConstant l (M * A) (M * B)
  have hDnonneg : 0 ≤ D := by
    dsimp [D]
    apply Finset.sum_nonneg
    intro l hl
    exact tripleWaveLeibnizConstant_nonneg l (mul_nonneg (norm_nonneg _) hA.le)
      (mul_nonneg (norm_nonneg _) hB.le)
  refine ⟨D + 1, by linarith, ?_⟩
  intro k hk s r r' u hs hr hr' hu
  have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
  have hR : s * r ≠ 0 := (mul_pos hspos
    (lt_of_lt_of_le (by norm_num) hr.1)).ne'
  have hR' : s * r' ≠ 0 := (mul_pos hspos
    (lt_of_lt_of_le (by norm_num) hr'.1)).ne'
  let Q : Real := (Real.sqrt s) ^ (d - 1)
  have hQpos : 0 < Q := by
    dsimp [Q]
    exact pow_pos (Real.sqrt_pos.2 hspos) _
  have hqbound : ∀ i : Nat, i ≤ k →
      ‖iteratedDeriv i (fun z : Real => (surfaceMass d : Complex)⁻¹ *
        coordinateWaveRadiusDerivativeAmplitude d q (s * r) z) u‖ ≤
        (M * A) / Q := by
    intro i hi
    rw [iteratedDeriv_const_mul_field, norm_mul]
    dsimp [M, Q]
    calc
      ‖(surfaceMass d : Complex)⁻¹‖ *
          ‖iteratedDeriv i (fun z : Real =>
            coordinateWaveRadiusDerivativeAmplitude d q (s * r) z) u‖ ≤
          ‖(surfaceMass d : Complex)⁻¹‖ *
            (A / (Real.sqrt s) ^ (d - 1)) :=
        mul_le_mul_of_nonneg_left
          (hAbound i (hi.trans hk) s r u hs hr hu) (norm_nonneg _)
      _ = (‖(surfaceMass d : Complex)⁻¹‖ * A) /
          (Real.sqrt s) ^ (d - 1) := by ring
  have htbound : ∀ i : Nat, i ≤ k →
      ‖iteratedDeriv i (fun z : Real => starRingEnd Complex
        ((surfaceMass d : Complex)⁻¹ *
          coordinateWaveRadiusDerivativeAmplitude d t (s * r') z)) u‖ ≤
        (M * B) / Q := by
    intro i hi
    rw [norm_iteratedDeriv_starRingEnd
      (fun z : Real => (surfaceMass d : Complex)⁻¹ *
        coordinateWaveRadiusDerivativeAmplitude d t (s * r') z)
      ((by fun_prop : ContDiff Real (⊤ : ℕ∞)
        (fun _ : Real => (surfaceMass d : Complex)⁻¹)).mul
          (contDiff_coordinateWaveRadiusDerivativeAmplitude d t hR')) i u,
      iteratedDeriv_const_mul_field, norm_mul]
    dsimp [M, Q]
    calc
      ‖(surfaceMass d : Complex)⁻¹‖ *
          ‖iteratedDeriv i (fun z : Real =>
            coordinateWaveRadiusDerivativeAmplitude d t (s * r') z) u‖ ≤
          ‖(surfaceMass d : Complex)⁻¹‖ *
            (B / (Real.sqrt s) ^ (d - 1)) :=
        mul_le_mul_of_nonneg_left
          (hBbound i (hi.trans hk) s r' u hs hr' hu) (norm_nonneg _)
      _ = (‖(surfaceMass d : Complex)⁻¹‖ * B) /
          (Real.sqrt s) ^ (d - 1) := by ring
  have hprod := norm_iteratedDeriv_mul_le_tripleWaveLeibnizConstant
    (n := k)
    ((by fun_prop : ContDiff Real (⊤ : ℕ∞)
      (fun _ : Real => (surfaceMass d : Complex)⁻¹)).mul
        (contDiff_coordinateWaveRadiusDerivativeAmplitude d q hR))
    (by
      have hbase : ContDiff Real (⊤ : ℕ∞)
          (fun z : Real => (surfaceMass d : Complex)⁻¹ *
            coordinateWaveRadiusDerivativeAmplitude d t (s * r') z) :=
        (by fun_prop).mul (contDiff_coordinateWaveRadiusDerivativeAmplitude d t hR')
      have heq : (fun z : Real => starRingEnd Complex
          ((surfaceMass d : Complex)⁻¹ *
            coordinateWaveRadiusDerivativeAmplitude d t (s * r') z)) =
          (Complex.conjCLE : Complex → Complex) ∘
            (fun z : Real => (surfaceMass d : Complex)⁻¹ *
              coordinateWaveRadiusDerivativeAmplitude d t (s * r') z) := by
        funext z
        simpa only [Function.comp_apply] using
          (Complex.conjCLE_apply
            ((surfaceMass d : Complex)⁻¹ *
              coordinateWaveRadiusDerivativeAmplitude d t (s * r') z)).symm
      rw [heq]
      exact Complex.conjCLE.contDiff.comp hbase)
    (div_nonneg (mul_nonneg (norm_nonneg _) hA.le) hQpos.le)
    (div_nonneg (mul_nonneg (norm_nonneg _) hB.le) hQpos.le)
    hqbound htbound
  unfold coordinateWaveRadiusDerivativeMultiplierPairAmplitude
  change ‖iteratedDeriv k (fun z : Real =>
      ((surfaceMass d : Complex)⁻¹ *
        coordinateWaveRadiusDerivativeAmplitude d q (s * r) z) *
        starRingEnd Complex
          ((surfaceMass d : Complex)⁻¹ *
            coordinateWaveRadiusDerivativeAmplitude d t (s * r') z)) u‖ ≤ _
  calc
    ‖iteratedDeriv k (fun z : Real =>
        ((surfaceMass d : Complex)⁻¹ *
          coordinateWaveRadiusDerivativeAmplitude d q (s * r) z) *
          starRingEnd Complex
            ((surfaceMass d : Complex)⁻¹ *
              coordinateWaveRadiusDerivativeAmplitude d t (s * r') z)) u‖ ≤
        tripleWaveLeibnizConstant k (M * A / Q) (M * B / Q) := hprod
    _ = tripleWaveLeibnizConstant k (M * A) (M * B) / Q ^ 2 :=
      tripleWaveLeibnizConstant_div_div k (M * A) (M * B) Q hQpos.ne'
    _ ≤ D / Q ^ 2 := by
      apply div_le_div_of_nonneg_right
      · unfold D
        have hmem : k ∈ Finset.range (N + 1) := Finset.mem_range.mpr (by omega)
        exact Finset.single_le_sum
          (fun l hl => tripleWaveLeibnizConstant_nonneg l
            (mul_nonneg (norm_nonneg _) hA.le) (mul_nonneg (norm_nonneg _) hB.le)) hmem
      · exact sq_pos_of_pos hQpos
    _ ≤ (D + 1) / s ^ (d - 1) := by
      dsimp [Q]
      rw [sq_sqrt_stationary_scale (zero_le_one.trans hs) d]
      apply div_le_div_of_nonneg_right
      · linarith
      · positivity

private theorem coordinateRadiusDerivativeTripleWaveCoefficient_eq_fixed_mul_pair
    {d : Nat} (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (R R' : Real) (v x : Euclidean d)
    (p q t : CoordinateWavePart) (u : Real) :
    coordinateRadiusDerivativeTripleWaveCoefficient
      (absoluteDyadicBandpass phi hphiOne hphiZero 0)
      R R' v x p q t u =
      coordinateTripleWaveFixedAmplitude phi v x p u *
        coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t R R' u := by
  have hcutoff := absoluteDyadicBandpass_zero_smul_eq_normalized
    phi hphiOne hphiZero v u
  unfold coordinateRadiusDerivativeTripleWaveCoefficient
    coordinateTripleWaveFixedAmplitude
    coordinateWaveRadiusDerivativeMultiplierPairAmplitude
    normalizedDyadicCutoffSquare
  rw [hcutoff, map_mul]
  ring

/-- Smoothness of the literal differentiated all-dimensional triple
coefficient on a positive radial annulus. -/
theorem contDiff_coordinateRadiusDerivativeTripleWaveCoefficient
    {d : Nat} (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    {R R' : Real} (hR : R ≠ 0) (hR' : R' ≠ 0)
    (v x : Euclidean d) (p q t : CoordinateWavePart) :
    ContDiff Real (⊤ : ℕ∞) (fun u : Real =>
      coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        R R' v x p q t u) := by
  have hfun : (fun u : Real =>
      coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        R R' v x p q t u) =
      fun u : Real => coordinateTripleWaveFixedAmplitude phi v x p u *
        coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t R R' u := by
    funext u
    exact coordinateRadiusDerivativeTripleWaveCoefficient_eq_fixed_mul_pair
      phi hphiOne hphiZero R R' v x p q t u
  rw [hfun]
  exact (contDiff_coordinateTripleWaveFixedAmplitude phi v x p).mul
    (contDiff_coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t hR hR')

/-- The literal differentiated all-dimensional triple coefficient has the
same `s^(-(d-1))` stationary size through every finite radial derivative. -/
private theorem exists_uniform_coordinateRadiusDerivativeTripleWaveCoefficient_scaled
    {d N : Nat} (hd : 2 ≤ d)
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphiRadial : IsNormRadial phi)
    (p q t : CoordinateWavePart) :
    ∃ C : Real, 0 < C ∧ ∀ k : Nat, k ≤ N →
      ∀ s r r' u : Real, 1 ≤ s →
        r ∈ Icc (1 / 2 : Real) (5 / 2) →
        r' ∈ Icc (1 / 2 : Real) (5 / 2) →
        ∀ v x : Euclidean d, ‖v‖ = 1 → u ∈ Icc (1 / 2 : Real) 8 →
          ‖iteratedDeriv k (fun z : Real =>
            coordinateRadiusDerivativeTripleWaveCoefficient
              (absoluteDyadicBandpass phi hphiOne hphiZero 0)
              (s * r) (s * r') v x p q t z) u‖ ≤ C / s ^ (d - 1) := by
  obtain ⟨A, hA, hAbound⟩ :=
    exists_uniform_coordinateTripleWaveFixedAmplitude_bound (N := N) hd phi
      hphiOne hphiZero hphiRadial p
  obtain ⟨B, hB, hBbound⟩ :=
    exists_uniform_coordinateWaveRadiusDerivativeMultiplierPairAmplitude_scaled
      (d := d) (N := N) hd q t
  let C : Real := ∑ l ∈ Finset.range (N + 1), tripleWaveLeibnizConstant l A B
  have hCnonneg : 0 ≤ C := by
    dsimp [C]
    apply Finset.sum_nonneg
    intro l hl
    exact tripleWaveLeibnizConstant_nonneg l hA.le hB.le
  refine ⟨C + 1, by linarith, ?_⟩
  intro k hk s r r' u hs hr hr' v x hv hu
  have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
  have hR : s * r ≠ 0 := (mul_pos hspos
    (lt_of_lt_of_le (by norm_num) hr.1)).ne'
  have hR' : s * r' ≠ 0 := (mul_pos hspos
    (lt_of_lt_of_le (by norm_num) hr'.1)).ne'
  have hfixed : ∀ i : Nat, i ≤ k →
      ‖iteratedDeriv i (coordinateTripleWaveFixedAmplitude phi v x p) u‖ ≤ A := by
    intro i hi
    exact hAbound v x hv i (hi.trans hk) u hu
  have hpair : ∀ i : Nat, i ≤ k →
      ‖iteratedDeriv i
        (coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t (s * r) (s * r')) u‖ ≤
        B / s ^ (d - 1) := by
    intro i hi
    exact hBbound i (hi.trans hk) s r r' u hs hr hr' hu
  have hprod := norm_iteratedDeriv_mul_le_tripleWaveLeibnizConstant
    (n := k) (contDiff_coordinateTripleWaveFixedAmplitude phi v x p)
      (contDiff_coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t hR hR')
      hA.le (div_nonneg hB.le (pow_nonneg (zero_le_one.trans hs) _)) hfixed hpair
  have hfactorfun : (fun z : Real =>
      coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        (s * r) (s * r') v x p q t z) =
      fun z : Real => coordinateTripleWaveFixedAmplitude phi v x p z *
        coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t (s * r) (s * r') z := by
    funext z
    exact coordinateRadiusDerivativeTripleWaveCoefficient_eq_fixed_mul_pair
      phi hphiOne hphiZero (s * r) (s * r') v x p q t z
  rw [hfactorfun]
  have hsdenpos : 0 < s ^ (d - 1) := pow_pos hspos _
  calc
    ‖iteratedDeriv k (fun z : Real =>
        coordinateTripleWaveFixedAmplitude phi v x p z *
          coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t (s * r) (s * r') z) u‖ ≤
        tripleWaveLeibnizConstant k A (B / s ^ (d - 1)) := hprod
    _ = tripleWaveLeibnizConstant k A B / s ^ (d - 1) := by
      rw [tripleWaveLeibnizConstant_right_div k A B
        (s ^ (d - 1)) hsdenpos.ne']
    _ ≤ C / s ^ (d - 1) := by
      apply div_le_div_of_nonneg_right
      · unfold C
        have hmem : k ∈ Finset.range (N + 1) := Finset.mem_range.mpr (by omega)
        exact Finset.single_le_sum
          (fun l hl => tripleWaveLeibnizConstant_nonneg l hA.le hB.le) hmem
      · exact hsdenpos

private theorem coordinateRadiusDerivativeTripleWaveCoefficient_absoluteDyadicBandpass_eq_zero_left
    {d : Nat} (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (r r' : Real) (v x : Euclidean d) (hv : ‖v‖ = 1)
    (p q t : CoordinateWavePart) {u : Real}
    (hu : u ∈ Icc (1 / 2 : Real) 1) :
    coordinateRadiusDerivativeTripleWaveCoefficient
      (absoluteDyadicBandpass phi hphiOne hphiZero 0)
      r r' v x p q t u = 0 := by
  have hpsi := absoluteDyadicBandpass_zero_on_normalized_left
    phi hphiOne hphiZero v hv hu
  unfold coordinateRadiusDerivativeTripleWaveCoefficient
  rw [hpsi]
  simp

private theorem coordinateRadiusDerivativeTripleWaveCoefficient_absoluteDyadicBandpass_eq_zero_right
    {d : Nat} (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (r r' : Real) (v x : Euclidean d) (hv : ‖v‖ = 1)
    (p q t : CoordinateWavePart) {u : Real}
    (hu : u ∈ Icc (4 : Real) 8) :
    coordinateRadiusDerivativeTripleWaveCoefficient
      (absoluteDyadicBandpass phi hphiOne hphiZero 0)
      r r' v x p q t u = 0 := by
  have hpsi := absoluteDyadicBandpass_zero_on_normalized_right
    phi hphiOne hphiZero v hv hu
  unfold coordinateRadiusDerivativeTripleWaveCoefficient
  rw [hpsi]
  simp

private theorem coordinateRadiusDerivativeTripleWaveCoefficient_eventuallyEq_zero_left
    {d : Nat} (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (r r' : Real) (v x : Euclidean d) (hv : ‖v‖ = 1)
    (p q t : CoordinateWavePart) :
    coordinateRadiusDerivativeTripleWaveCoefficient
      (absoluteDyadicBandpass phi hphiOne hphiZero 0)
      r r' v x p q t =ᶠ[𝓝 (1 / 2 : Real)] 0 := by
  filter_upwards [Metric.ball_mem_nhds (1 / 2 : Real)
      (by norm_num : (0 : Real) < 1 / 4)] with u hu
  rw [mem_ball, Real.dist_eq] at hu
  have huabs : |u - 1 / 2| < 1 / 4 := hu
  have hu0 : 1 / 2 ≤ u := by
    have := (abs_lt.mp huabs).1
    linarith
  have huone : u ≤ 1 := by
    have := (abs_lt.mp huabs).2
    linarith
  exact coordinateRadiusDerivativeTripleWaveCoefficient_absoluteDyadicBandpass_eq_zero_left
    phi hphiOne hphiZero r r' v x hv p q t ⟨hu0, huone⟩

private theorem coordinateRadiusDerivativeTripleWaveCoefficient_eventuallyEq_zero_right
    {d : Nat} (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (r r' : Real) (v x : Euclidean d) (hv : ‖v‖ = 1)
    (p q t : CoordinateWavePart) :
    coordinateRadiusDerivativeTripleWaveCoefficient
      (absoluteDyadicBandpass phi hphiOne hphiZero 0)
      r r' v x p q t =ᶠ[𝓝 (8 : Real)] 0 := by
  filter_upwards [Metric.ball_mem_nhds (8 : Real)
      (by norm_num : (0 : Real) < 1)] with u hu
  rw [mem_ball, Real.dist_eq] at hu
  have huabs : |u - 8| < 1 := hu
  have hufour : 4 ≤ u := by
    have := (abs_lt.mp huabs).1
    linarith
  exact coordinateRadiusDerivativeTripleWaveCoefficient_absoluteDyadicBandpass_eq_zero_right
    phi hphiOne hphiZero r r' v x hv p q t ⟨hufour, by linarith⟩

private theorem hasOscillatoryIBPChain_coordinateRadiusDerivativeTripleWaveCoefficient
    {d : Nat} (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    {r r' : Real} (hr : r ≠ 0) (hr' : r' ≠ 0)
    (v x : Euclidean d) (hv : ‖v‖ = 1)
    (p q t : CoordinateWavePart) (N : Nat) :
    HasOscillatoryIBPChain (1 / 2 : Real) 8
      (fun k => iteratedDeriv k
        (coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          r r' v x p q t)) N := by
  apply hasOscillatoryIBPChain_iteratedDeriv_of_contDiff
  · exact contDiff_coordinateRadiusDerivativeTripleWaveCoefficient
      phi hphiOne hphiZero hr hr' v x p q t
  · exact coordinateRadiusDerivativeTripleWaveCoefficient_eventuallyEq_zero_left
      phi hphiOne hphiZero r r' v x hv p q t
  · exact coordinateRadiusDerivativeTripleWaveCoefficient_eventuallyEq_zero_right
      phi hphiOne hphiZero r r' v x hv p q t

private theorem intervalIntegral_coordinateRadiusDerivativeTripleWaveCoefficient_eq_expanded
    {d : Nat} (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    {r r' : Real} (hr : r ≠ 0) (hr' : r' ≠ 0)
    (v x : Euclidean d) (hv : ‖v‖ = 1)
    (p q t : CoordinateWavePart) :
    (∫ u in (1 : Real)..4,
      coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        r r' v x p q t u * oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ r r') u) =
      ∫ u in (1 / 2 : Real)..8,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          r r' v x p q t u * oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ r r') u := by
  apply intervalIntegral_eq_expanded_fixedAnnulus_of_zero
  · exact (contDiff_coordinateRadiusDerivativeTripleWaveCoefficient
      phi hphiOne hphiZero hr hr' v x p q t).continuous.mul (by fun_prop)
  · intro u hu
    rw [coordinateRadiusDerivativeTripleWaveCoefficient_absoluteDyadicBandpass_eq_zero_left
      phi hphiOne hphiZero r r' v x hv p q t hu]
    simp
  · intro u hu
    rw [coordinateRadiusDerivativeTripleWaveCoefficient_absoluteDyadicBandpass_eq_zero_right
      phi hphiOne hphiZero r r' v x hv p q t hu]
    simp

private theorem norm_intervalIntegral_coordinateRadiusDerivativeTripleWaveCoefficient_le_iterated
    {d : Nat} (N : Nat) (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    {r r' : Real} (hr : r ≠ 0) (hr' : r' ≠ 0)
    (v x : Euclidean d) (hv : ‖v‖ = 1)
    (p q t : CoordinateWavePart) (freq M : Real)
    (hfreq : freq ≠ 0) (hM : 0 ≤ M)
    (hbound : ∀ u ∈ Icc (1 / 2 : Real) 8,
      ‖iteratedDeriv N (coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        r r' v x p q t) u‖ ≤ M) :
    ‖∫ u in (1 : Real)..4,
      coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        r r' v x p q t u * oscillatoryExp freq u‖ ≤
      (1 / |freq|) ^ N * ((8 - (1 / 2 : Real)) * M) := by
  rw [intervalIntegral_coordinateRadiusDerivativeTripleWaveCoefficient_eq_expanded
    phi hphiOne hphiZero hr hr' v x hv p q t]
  apply norm_intervalIntegral_mul_oscillatoryExp_le_iterated
    (by norm_num) hfreq
    (hasOscillatoryIBPChain_coordinateRadiusDerivativeTripleWaveCoefficient
      phi hphiOne hphiZero hr hr' v x hv p q t N)
    hM hbound

private theorem exists_inner_endpoint_coordinateRadiusDerivativeTripleWaveIntegral_bound
    {d : Nat} (hd : 3 ≤ d)
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphiRadial : IsNormRadial phi)
    (p q t : CoordinateWavePart)
    (hp : p ≠ .middle) (hq : q ≠ .middle) (ht : t ≠ .middle) :
    ∃ C : Real, 0 < C ∧ ∀ s r r' : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) →
      r' ∈ Icc (1 / 2 : Real) (5 / 2) → r ≠ r' →
      ∀ v x : Euclidean d, ‖v‖ = 1 → ‖x‖ ≤ |r - r'| / 4 →
      ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v (s • x) p q t u *
          oscillatoryExp
            (coordinateTripleWavePhase p q t ‖s • x‖ (s * r) (s * r')) u‖ ≤
        (4 / (s * |r - r'|)) ^ d *
          ((8 - (1 / 2 : Real)) * (C / s ^ (d - 1))) := by
  obtain ⟨C, hC, hCbound⟩ :=
    exists_uniform_coordinateRadiusDerivativeTripleWaveCoefficient_scaled
      (N := d) (by omega) phi hphiOne hphiZero hphiRadial p q t
  refine ⟨C, hC, ?_⟩
  intro s r r' hs hr hr' hrr v x hv hxcone
  let y : Euclidean d := s • x
  let freq : Real := coordinateTripleWavePhase p q t ‖y‖ (s * r) (s * r')
  have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
  have hR : s * r ≠ 0 := (mul_pos hspos
    (lt_of_lt_of_le (by norm_num) hr.1)).ne'
  have hR' : s * r' ≠ 0 := (mul_pos hspos
    (lt_of_lt_of_le (by norm_num) hr'.1)).ne'
  have hgap : 0 < |r - r'| := abs_pos.mpr (sub_ne_zero.mpr hrr)
  have hscalednorm : ‖y‖ = s * ‖x‖ := by
    dsimp [y]
    rw [norm_smul, Real.norm_eq_abs, abs_of_pos hspos]
  have horig : |r - r'| / 4 ≤
      |coordinateTripleWavePhase p q t ‖x‖ r r'| :=
    abs_coordinateTripleWavePhase_ge_quarter_gap_of_endpoints hp hq ht hr hr'
      (norm_nonneg _) hxcone
  have hfreqscale : freq =
      s * coordinateTripleWavePhase p q t ‖x‖ r r' := by
    dsimp [freq]
    rw [hscalednorm]
    exact coordinateTripleWavePhase_scale s ‖x‖ r r' p q t
  have hfreqlower : s * |r - r'| / 4 ≤ |freq| := by
    rw [hfreqscale, abs_mul, abs_of_pos hspos]
    calc
      s * |r - r'| / 4 = s * (|r - r'| / 4) := by ring
      _ ≤ s * |coordinateTripleWavePhase p q t ‖x‖ r r'| :=
        mul_le_mul_of_nonneg_left horig hspos.le
  have hfreqpos : 0 < |freq| := by
    have : 0 < s * |r - r'| / 4 := by positivity
    exact lt_of_lt_of_le this hfreqlower
  have hinv : 1 / |freq| ≤ 4 / (s * |r - r'|) := by
    calc
      1 / |freq| ≤ 1 / (s * |r - r'| / 4) :=
        div_le_div_of_nonneg_left zero_le_one (by positivity) hfreqlower
      _ = 4 / (s * |r - r'|) := by
        field_simp [hspos.ne', hgap.ne']
        ring
  have hM : 0 ≤ C / s ^ (d - 1) :=
    div_nonneg hC.le (pow_nonneg hspos.le _)
  have hbound : ∀ u ∈ Icc (1 / 2 : Real) 8,
      ‖iteratedDeriv d (coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        (s * r) (s * r') v y p q t) u‖ ≤ C / s ^ (d - 1) := by
    intro u hu
    exact hCbound d le_rfl s r r' u hs hr hr' v y hv hu
  have hIBP := norm_intervalIntegral_coordinateRadiusDerivativeTripleWaveCoefficient_le_iterated
    d phi hphiOne hphiZero hR hR' v y hv p q t freq
    (C / s ^ (d - 1)) (ne_of_gt hfreqpos) hM hbound
  change ‖∫ u in (1 : Real)..4,
      coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        (s * r) (s * r') v y p q t u * oscillatoryExp freq u‖ ≤ _
  calc
    ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v y p q t u * oscillatoryExp freq u‖ ≤
        (1 / |freq|) ^ d *
          ((8 - (1 / 2 : Real)) * (C / s ^ (d - 1))) := hIBP
    _ ≤ (4 / (s * |r - r'|)) ^ d *
          ((8 - (1 / 2 : Real)) * (C / s ^ (d - 1))) := by
      apply mul_le_mul_of_nonneg_right
      · exact pow_le_pow_left₀ (by positivity) hinv _
      · positivity

private theorem exists_inner_physicalMiddle_coordinateRadiusDerivativeTripleWaveIntegral_bound
    {d : Nat} (hd : 3 ≤ d)
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphiRadial : IsNormRadial phi)
    (q t : CoordinateWavePart) (hq : q ≠ .middle) (ht : t ≠ .middle) :
    ∃ C : Real, 0 < C ∧ ∀ s r r' : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) →
      r' ∈ Icc (1 / 2 : Real) (5 / 2) → r ≠ r' →
      ∀ v x : Euclidean d, ‖v‖ = 1 → ‖x‖ ≤ |r - r'| / 4 →
      ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v (s • x) .middle q t u *
          oscillatoryExp
            (coordinateTripleWavePhase .middle q t ‖s • x‖ (s * r) (s * r')) u‖ ≤
        (4 / (s * |r - r'|)) ^ d *
          ((8 - (1 / 2 : Real)) * (C / s ^ (d - 1))) := by
  obtain ⟨C, hC, hCbound⟩ :=
    exists_uniform_coordinateRadiusDerivativeTripleWaveCoefficient_scaled
      (N := d) (by omega) phi hphiOne hphiZero hphiRadial .middle q t
  refine ⟨C, hC, ?_⟩
  intro s r r' hs hr hr' hrr v x hv hxcone
  let y : Euclidean d := s • x
  let freq : Real := coordinateTripleWavePhase .middle q t ‖y‖ (s * r) (s * r')
  have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
  have hR : s * r ≠ 0 := (mul_pos hspos
    (lt_of_lt_of_le (by norm_num) hr.1)).ne'
  have hR' : s * r' ≠ 0 := (mul_pos hspos
    (lt_of_lt_of_le (by norm_num) hr'.1)).ne'
  have hgap : 0 < |r - r'| := abs_pos.mpr (sub_ne_zero.mpr hrr)
  have horig : |r - r'| / 4 ≤
      |coordinateTripleWavePhase .middle q t 0 r r'| :=
    abs_coordinateTripleWavePhase_ge_quarter_gap_of_physical_middle hq ht hr hr'
  have hmiddlephase (a b c : Real) :
      coordinateTripleWavePhase .middle q t a b c =
        coordinateTripleWavePhase .middle q t 0 b c := by
    simp [coordinateTripleWavePhase, coordinateWaveRadialPhase]
  have hfreqscale : freq =
      s * coordinateTripleWavePhase .middle q t 0 r r' := by
    dsimp [freq]
    rw [hmiddlephase]
    exact coordinateTripleWavePhase_scale s 0 r r' .middle q t
  have hfreqlower : s * |r - r'| / 4 ≤ |freq| := by
    rw [hfreqscale, abs_mul, abs_of_pos hspos]
    calc
      s * |r - r'| / 4 = s * (|r - r'| / 4) := by ring
      _ ≤ s * |coordinateTripleWavePhase .middle q t 0 r r'| :=
        mul_le_mul_of_nonneg_left horig hspos.le
  have hfreqpos : 0 < |freq| := by
    have : 0 < s * |r - r'| / 4 := by positivity
    exact lt_of_lt_of_le this hfreqlower
  have hinv : 1 / |freq| ≤ 4 / (s * |r - r'|) := by
    calc
      1 / |freq| ≤ 1 / (s * |r - r'| / 4) :=
        div_le_div_of_nonneg_left zero_le_one (by positivity) hfreqlower
      _ = 4 / (s * |r - r'|) := by
        field_simp [hspos.ne', hgap.ne']
        ring
  have hM : 0 ≤ C / s ^ (d - 1) :=
    div_nonneg hC.le (pow_nonneg hspos.le _)
  have hbound : ∀ u ∈ Icc (1 / 2 : Real) 8,
      ‖iteratedDeriv d (coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        (s * r) (s * r') v y .middle q t) u‖ ≤ C / s ^ (d - 1) := by
    intro u hu
    exact hCbound d le_rfl s r r' u hs hr hr' v y hv hu
  have hIBP := norm_intervalIntegral_coordinateRadiusDerivativeTripleWaveCoefficient_le_iterated
    d phi hphiOne hphiZero hR hR' v y hv .middle q t freq
    (C / s ^ (d - 1)) (ne_of_gt hfreqpos) hM hbound
  change ‖∫ u in (1 : Real)..4,
      coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        (s * r) (s * r') v y .middle q t u * oscillatoryExp freq u‖ ≤ _
  calc
    ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v y .middle q t u * oscillatoryExp freq u‖ ≤
        (1 / |freq|) ^ d *
          ((8 - (1 / 2 : Real)) * (C / s ^ (d - 1))) := hIBP
    _ ≤ (4 / (s * |r - r'|)) ^ d *
          ((8 - (1 / 2 : Real)) * (C / s ^ (d - 1))) := by
      apply mul_le_mul_of_nonneg_right
      · exact pow_le_pow_left₀ (by positivity) hinv _
      · positivity

private theorem exists_coordinateWaveRadiusDerivativeAmplitude_middle_scaled_power
    {d : Nat} (L : Nat) :
    ∃ C : Real, 0 < C ∧ ∀ s r u : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) → u ∈ Icc (1 / 2 : Real) 8 →
      ‖coordinateWaveRadiusDerivativeAmplitude d .middle (s * r) u‖ ≤
        C / s ^ L := by
  obtain ⟨C, hC, hbound⟩ :=
    exists_norm_iteratedDeriv_coordinateWaveRadialAmplitude_middle_decay d 1 (L + 1)
  refine ⟨(80 * Real.pi) * C, mul_pos (by positivity) hC, ?_⟩
  intro s r u hs hr hu
  obtain ⟨hfreq, hamp, hscale, hsqrt⟩ :=
    scaled_coordinate_frequency_geometry hs hr hu
  have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
  have hsrhalf : (1 / 2 : Real) ≤ s * r := by
    calc
      (1 / 2 : Real) = 1 * (1 / 2 : Real) := by ring
      _ ≤ s * r := mul_le_mul hs hr.1 (by positivity) (by positivity)
  have hsrpos : 0 < s * r := lt_of_lt_of_le (by norm_num) hsrhalf
  have hsrne : s * r ≠ 0 := hsrpos.ne'
  have huover : ‖((u / (s * r) : Real) : Complex)‖ ≤ 16 := by
    rw [Complex.norm_real, Real.norm_eq_abs,
      abs_of_nonneg (div_nonneg (by linarith [hu.1]) hsrpos.le)]
    apply (div_le_iff₀ hsrpos).2
    nlinarith [hu.2, hsrhalf]
  have hformula :
      coordinateWaveRadiusDerivativeAmplitude d .middle (s * r) u =
        ((u / (s * r) : Real) : Complex) *
          iteratedDeriv 1
            (fun z : Real => coordinateWaveRadialAmplitude d .middle (s * r) z) u := by
    unfold coordinateWaveRadiusDerivativeAmplitude
    rw [deriv_coordinateWaveRadialAmplitude_radius_eq_div_mul_iteratedDeriv
      d .middle hsrne u]
    simp [coordinateWavePhaseSlope]
  have hmiddle :
      ‖iteratedDeriv 1
        (fun z : Real => coordinateWaveRadialAmplitude d .middle (s * r) z) u‖ ≤
        C * |2 * Real.pi * (s * r)| /
          |(2 * Real.pi * (s * r)) * u| ^ (L + 1) := by
    simpa using hbound (s * r) u hfreq
  have hden : s ^ (L + 1) ≤ |(2 * Real.pi * (s * r)) * u| ^ (L + 1) :=
    pow_le_pow_left₀ (zero_le_one.trans hs) hscale _
  have hnum : C * |2 * Real.pi * (s * r)| ≤ C * ((5 * Real.pi) * s) :=
    mul_le_mul_of_nonneg_left hamp hC.le
  have hquot :
      C * |2 * Real.pi * (s * r)| /
          |(2 * Real.pi * (s * r)) * u| ^ (L + 1) ≤
        C * ((5 * Real.pi) * s) / s ^ (L + 1) := by
    calc
      C * |2 * Real.pi * (s * r)| /
          |(2 * Real.pi * (s * r)) * u| ^ (L + 1) ≤
          C * |2 * Real.pi * (s * r)| / s ^ (L + 1) :=
        div_le_div_of_nonneg_left
          (mul_nonneg hC.le (abs_nonneg _)) (pow_pos hspos _) hden
      _ ≤ C * ((5 * Real.pi) * s) / s ^ (L + 1) :=
        div_le_div_of_nonneg_right hnum (pow_pos hspos _)
  rw [hformula, norm_mul]
  calc
    ‖((u / (s * r) : Real) : Complex)‖ *
        ‖iteratedDeriv 1
          (fun z : Real => coordinateWaveRadialAmplitude d .middle (s * r) z) u‖ ≤
        16 * (C * |2 * Real.pi * (s * r)| /
          |(2 * Real.pi * (s * r)) * u| ^ (L + 1)) := by
      exact mul_le_mul huover hmiddle (norm_nonneg _) (by positivity)
    _ ≤ 16 * (C * ((5 * Real.pi) * s) / s ^ (L + 1)) :=
      mul_le_mul_of_nonneg_left hquot (by norm_num)
    _ = ((80 * Real.pi) * C) / s ^ L := by
      rw [show L + 1 = Nat.succ L by omega, pow_succ]
      field_simp [hspos.ne']
      ring

private theorem exists_coordinateWaveRadiusDerivativeMultiplierPairAmplitude_oneMiddle_scaled
    {d : Nat} (hd : 2 ≤ d) (L : Nat) (q t : CoordinateWavePart)
    (hmiddle : q = .middle ∨ t = .middle) :
    ∃ C : Real, 0 < C ∧ ∀ s r r' u : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) →
      r' ∈ Icc (1 / 2 : Real) (5 / 2) → u ∈ Icc (1 / 2 : Real) 8 →
      ‖coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t (s * r) (s * r') u‖ ≤
        C / (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
  rcases hmiddle with hq | ht
  · subst q
    obtain ⟨A, hA, hAbound⟩ :=
      exists_coordinateWaveRadiusDerivativeAmplitude_middle_scaled_power (d := d) L
    obtain ⟨B, hB, hBbound⟩ :=
      exists_uniform_coordinateWaveRadiusDerivativeAmplitude_scaled (d := d) (N := 0) hd t
    let M : Real := ‖(surfaceMass d : Complex)⁻¹‖
    have hM : 0 ≤ M := by
      dsimp [M]
      exact norm_nonneg _
    refine ⟨M ^ 2 * A * B + 1, by positivity, ?_⟩
    intro s r r' u hs hr hr' hu
    have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
    have hqbound := hAbound s r u hs hr hu
    have htbound := hBbound 0 le_rfl s r' u hs hr' hu
    have hQpos : 0 < (Real.sqrt s) ^ (d - 1) :=
      pow_pos (Real.sqrt_pos.2 hspos) _
    unfold coordinateWaveRadiusDerivativeMultiplierPairAmplitude
    simp only [norm_mul, norm_star]
    change M * ‖coordinateWaveRadiusDerivativeAmplitude d .middle (s * r) u‖ *
        (M * ‖coordinateWaveRadiusDerivativeAmplitude d t (s * r') u‖) ≤ _
    calc
      M * ‖coordinateWaveRadiusDerivativeAmplitude d .middle (s * r) u‖ *
          (M * ‖coordinateWaveRadiusDerivativeAmplitude d t (s * r') u‖) ≤
          M * (A / s ^ L) *
            (M * (B / (Real.sqrt s) ^ (d - 1))) := by
        gcongr
      _ = (M ^ 2 * A * B) /
          (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
        field_simp [hspos.ne', hQpos.ne']
        ring
      _ ≤ (M ^ 2 * A * B + 1) /
          (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
        apply div_le_div_of_nonneg_right
        · linarith
        · positivity
  · subst t
    obtain ⟨A, hA, hAbound⟩ :=
      exists_coordinateWaveRadiusDerivativeAmplitude_middle_scaled_power (d := d) L
    obtain ⟨B, hB, hBbound⟩ :=
      exists_uniform_coordinateWaveRadiusDerivativeAmplitude_scaled (d := d) (N := 0) hd q
    let M : Real := ‖(surfaceMass d : Complex)⁻¹‖
    have hM : 0 ≤ M := by
      dsimp [M]
      exact norm_nonneg _
    refine ⟨M ^ 2 * B * A + 1, by positivity, ?_⟩
    intro s r r' u hs hr hr' hu
    have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
    have hqbound := hBbound 0 le_rfl s r u hs hr hu
    have htbound := hAbound s r' u hs hr' hu
    have hQpos : 0 < (Real.sqrt s) ^ (d - 1) :=
      pow_pos (Real.sqrt_pos.2 hspos) _
    unfold coordinateWaveRadiusDerivativeMultiplierPairAmplitude
    simp only [norm_mul, norm_star]
    change M * ‖coordinateWaveRadiusDerivativeAmplitude d q (s * r) u‖ *
        (M * ‖coordinateWaveRadiusDerivativeAmplitude d .middle (s * r') u‖) ≤ _
    calc
      M * ‖coordinateWaveRadiusDerivativeAmplitude d q (s * r) u‖ *
          (M * ‖coordinateWaveRadiusDerivativeAmplitude d .middle (s * r') u‖) ≤
          M * (B / (Real.sqrt s) ^ (d - 1)) * (M * (A / s ^ L)) := by
        gcongr
      _ = (M ^ 2 * B * A) /
          (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
        field_simp [hspos.ne', hQpos.ne']
        ring
      _ ≤ (M ^ 2 * B * A + 1) /
          (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
        apply div_le_div_of_nonneg_right
        · linarith
        · positivity

private theorem exists_oneMiddle_coordinateRadiusDerivativeTripleWaveIntegral_bound
    {d : Nat} (hd : 3 ≤ d) (L : Nat)
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphiRadial : IsNormRadial phi)
    (p q t : CoordinateWavePart) (hmiddle : q = .middle ∨ t = .middle) :
    ∃ C : Real, 0 < C ∧ ∀ s r r' : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) →
      r' ∈ Icc (1 / 2 : Real) (5 / 2) →
      ∀ v x : Euclidean d, ‖v‖ = 1 →
      ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v x p q t u *
          oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        C / (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
  obtain ⟨A, hA, hAbound⟩ :=
    exists_uniform_coordinateTripleWaveFixedAmplitude_bound (N := 0) (by omega) phi
      hphiOne hphiZero hphiRadial p
  obtain ⟨B, hB, hBbound⟩ :=
    exists_coordinateWaveRadiusDerivativeMultiplierPairAmplitude_oneMiddle_scaled
      (by omega) L q t hmiddle
  refine ⟨3 * A * B, mul_pos (mul_pos (by norm_num) hA) hB, ?_⟩
  intro s r r' hs hr hr' v x hv
  have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
  have hdenpos : 0 < s ^ L * (Real.sqrt s) ^ (d - 1) := by positivity
  have hpoint : ∀ u ∈ Icc (1 : Real) 4,
      ‖coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        (s * r) (s * r') v x p q t u *
        oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        (A * B) / (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
    intro u hu
    have huwide : u ∈ Icc (1 / 2 : Real) 8 := by
      constructor <;> linarith [hu.1, hu.2]
    have hfixed := hAbound v x hv 0 le_rfl u huwide
    have hpair := hBbound s r r' u hs hr hr' huwide
    have hfactor := coordinateRadiusDerivativeTripleWaveCoefficient_eq_fixed_mul_pair
      phi hphiOne hphiZero (s * r) (s * r') v x p q t u
    rw [hfactor, norm_mul, norm_oscillatoryExp, mul_one]
    calc
      ‖coordinateTripleWaveFixedAmplitude phi v x p u‖ *
          ‖coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t (s * r) (s * r') u‖ ≤
          A * (B / (s ^ L * (Real.sqrt s) ^ (d - 1))) := by
        exact mul_le_mul hfixed hpair (norm_nonneg _) hA.le
      _ = (A * B) / (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
        field_simp [hdenpos.ne']
        ring
  calc
    ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v x p q t u *
          oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        ((A * B) / (s ^ L * (Real.sqrt s) ^ (d - 1))) * |4 - (1 : Real)| := by
      apply intervalIntegral.norm_integral_le_of_norm_le_const
      intro u hu
      have hu' : u ∈ Icc (1 : Real) 4 := by
        rw [uIoc_of_le (by norm_num : (1 : Real) ≤ 4)] at hu
        exact ⟨hu.1.le, hu.2⟩
      exact hpoint u hu'
    _ = (3 * A * B) / (s ^ L * (Real.sqrt s) ^ (d - 1)) := by
      norm_num
      ring

private theorem exists_coordinateRadiusDerivativeTripleWaveIntegral_crude_bound
    {d : Nat} (hd : 3 ≤ d)
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphiRadial : IsNormRadial phi)
    (p q t : CoordinateWavePart) :
    ∃ C : Real, 0 < C ∧ ∀ s r r' : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) →
      r' ∈ Icc (1 / 2 : Real) (5 / 2) →
      ∀ v x : Euclidean d, ‖v‖ = 1 →
      ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v x p q t u *
          oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        C / s ^ (d - 1) := by
  obtain ⟨A, hA, hAbound⟩ :=
    exists_uniform_coordinateTripleWaveFixedAmplitude_bound (N := 0) (by omega) phi
      hphiOne hphiZero hphiRadial p
  obtain ⟨B, hB, hBbound⟩ :=
    exists_uniform_coordinateWaveRadiusDerivativeMultiplierPairAmplitude_scaled
      (d := d) (N := 0) (by omega) q t
  refine ⟨3 * A * B, mul_pos (mul_pos (by norm_num) hA) hB, ?_⟩
  intro s r r' hs hr hr' v x hv
  have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
  have hpoint : ∀ u ∈ Icc (1 : Real) 4,
      ‖coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        (s * r) (s * r') v x p q t u *
        oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        (A * B) / s ^ (d - 1) := by
    intro u hu
    have huwide : u ∈ Icc (1 / 2 : Real) 8 := by
      constructor <;> linarith [hu.1, hu.2]
    have hfixed := hAbound v x hv 0 le_rfl u huwide
    have hpair := hBbound 0 le_rfl s r r' u hs hr hr' huwide
    have hfactor := coordinateRadiusDerivativeTripleWaveCoefficient_eq_fixed_mul_pair
      phi hphiOne hphiZero (s * r) (s * r') v x p q t u
    rw [hfactor, norm_mul, norm_oscillatoryExp, mul_one]
    calc
      ‖coordinateTripleWaveFixedAmplitude phi v x p u‖ *
          ‖coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t (s * r) (s * r') u‖ ≤
          A * (B / s ^ (d - 1)) := by
        exact mul_le_mul hfixed hpair (norm_nonneg _) hA.le
      _ = (A * B) / s ^ (d - 1) := by
        field_simp [pow_ne_zero _ hspos.ne']
        ring
  calc
    ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v x p q t u *
          oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        ((A * B) / s ^ (d - 1)) * |4 - (1 : Real)| := by
      apply intervalIntegral.norm_integral_le_of_norm_le_const
      intro u hu
      have hu' : u ∈ Icc (1 : Real) 4 := by
        rw [uIoc_of_le (by norm_num : (1 : Real) ≤ 4)] at hu
        exact ⟨hu.1.le, hu.2⟩
      exact hpoint u hu'
    _ = (3 * A * B) / s ^ (d - 1) := by
      norm_num
      ring

private theorem exists_outer_coordinateRadiusDerivativeTripleWaveIntegral_bound
    {d : Nat} (hd : 3 ≤ d)
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphiRadial : IsNormRadial phi)
    (p q t : CoordinateWavePart) :
    ∃ C : Real, 0 < C ∧ ∀ s r r' : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) →
      r' ∈ Icc (1 / 2 : Real) (5 / 2) →
      ∀ v x : Euclidean d, ‖v‖ = 1 → 1 ≤ ‖x‖ →
      ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v x p q t u *
          oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        C / (s ^ (d - 1) * (Real.sqrt ‖x‖) ^ (d - 1)) := by
  let density : Real → Complex := fun u : Real => ((u ^ (d - 1) : Real) : Complex)
  have hdensity : ContDiff Real (⊤ : ℕ∞) density := by
    dsimp [density]
    fun_prop
  obtain ⟨A, hA, hAbound⟩ :=
    exists_uniform_iteratedDeriv_bound_on_fixedAnnulus density hdensity 0
  obtain ⟨D, hD, hDbound⟩ :=
    exists_uniform_normalizedDyadicCutoffSquare_bound_on_unit (N := 0)
      (by omega) phi hphiOne hphiZero hphiRadial
  obtain ⟨P, hP, hPbound⟩ :=
    exists_coordinateWaveRadialAmplitude_physical_decay (by omega) p
  obtain ⟨B, hB, hBbound⟩ :=
    exists_uniform_coordinateWaveRadiusDerivativeMultiplierPairAmplitude_scaled
      (d := d) (N := 0) (by omega) q t
  refine ⟨3 * A * P * D * B,
    mul_pos (mul_pos (mul_pos (mul_pos (by norm_num) hA) hP) hD) hB, ?_⟩
  intro s r r' hs hr hr' v x hv hx
  have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
  have hxpos : 0 < ‖x‖ := lt_of_lt_of_le zero_lt_one hx
  have hsqrtpos : 0 < Real.sqrt ‖x‖ := Real.sqrt_pos.2 hxpos
  have hphysicalden : 0 < (Real.sqrt ‖x‖) ^ (d - 1) := pow_pos hsqrtpos _
  have hsden : 0 < s ^ (d - 1) := pow_pos hspos _
  have hpoint : ∀ u ∈ Icc (1 : Real) 4,
      ‖coordinateRadiusDerivativeTripleWaveCoefficient
        (absoluteDyadicBandpass phi hphiOne hphiZero 0)
        (s * r) (s * r') v x p q t u *
        oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        (A * P * D * B) /
          (s ^ (d - 1) * (Real.sqrt ‖x‖) ^ (d - 1)) := by
    intro u hu
    have huwide : u ∈ Icc (1 / 2 : Real) 8 := by
      constructor <;> linarith [hu.1, hu.2]
    have hden := hAbound 0 le_rfl u huwide
    have hcut := hDbound v hv 0 le_rfl u huwide
    have hphysical := hPbound ‖x‖ u hx huwide
    have hpair := hBbound 0 le_rfl s r r' u hs hr hr' huwide
    have hfactor := coordinateRadiusDerivativeTripleWaveCoefficient_eq_fixed_mul_pair
      phi hphiOne hphiZero (s * r) (s * r') v x p q t u
    rw [hfactor, norm_mul, norm_oscillatoryExp, mul_one]
    unfold coordinateTripleWaveFixedAmplitude
    rw [norm_mul, norm_mul, norm_mul]
    calc
      ‖density u‖ * ‖coordinateWaveRadialAmplitude d p ‖x‖ u‖ *
          ‖normalizedDyadicCutoffSquare phi v u‖ *
            ‖coordinateWaveRadiusDerivativeMultiplierPairAmplitude d q t (s * r) (s * r') u‖ ≤
          A * (P / (Real.sqrt ‖x‖) ^ (d - 1)) * D *
            (B / s ^ (d - 1)) := by
        gcongr
      _ = (A * P * D * B) /
          (s ^ (d - 1) * (Real.sqrt ‖x‖) ^ (d - 1)) := by
        field_simp [pow_ne_zero _ hspos.ne', hphysicalden.ne']
        ring
  calc
    ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v x p q t u *
          oscillatoryExp (coordinateTripleWavePhase p q t ‖x‖ (s * r) (s * r')) u‖ ≤
        ((A * P * D * B) /
          (s ^ (d - 1) * (Real.sqrt ‖x‖) ^ (d - 1))) * |4 - (1 : Real)| := by
      apply intervalIntegral.norm_integral_le_of_norm_le_const
      intro u hu
      have hu' : u ∈ Icc (1 : Real) 4 := by
        rw [uIoc_of_le (by norm_num : (1 : Real) ≤ 4)] at hu
        exact ⟨hu.1.le, hu.2⟩
      exact hpoint u hu'
    _ = (3 * A * P * D * B) /
        (s ^ (d - 1) * (Real.sqrt ‖x‖) ^ (d - 1)) := by
      norm_num
      ring

/-- The literal differentiated coordinate-triple stationary gap estimate in
every dimension at least three. -/
theorem exists_coordinateRadiusDerivativeTripleWaveIntegral_stationaryGap_bound
    {d : Nat} (hd : 3 ≤ d)
    (phi : SchwartzMap (Euclidean d) Complex)
    (hphiOne : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphiZero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphiRadial : IsNormRadial phi)
    (p q t : CoordinateWavePart) :
    ∃ C : Real, 0 < C ∧ ∀ s r r' : Real, 1 ≤ s →
      r ∈ Icc (1 / 2 : Real) (5 / 2) →
      r' ∈ Icc (1 / 2 : Real) (5 / 2) →
      ∀ v x : Euclidean d, ‖v‖ = 1 →
      ‖∫ u in (1 : Real)..4,
        coordinateRadiusDerivativeTripleWaveCoefficient
          (absoluteDyadicBandpass phi hphiOne hphiZero 0)
          (s * r) (s * r') v (s • x) p q t u *
          oscillatoryExp
            (coordinateTripleWavePhase p q t ‖s • x‖ (s * r) (s * r')) u‖ ≤
        C / s ^ (d - 1) *
          (1 + s * |r - r'|) ^ (-q4StationaryExponent d) := by
  obtain ⟨Csmall, hCsmall, hsmall⟩ :=
    exists_coordinateRadiusDerivativeTripleWaveIntegral_crude_bound
      hd phi hphiOne hphiZero hphiRadial p q t
  obtain ⟨Couter, hCouter, houter⟩ :=
    exists_outer_coordinateRadiusDerivativeTripleWaveIntegral_bound
      hd phi hphiOne hphiZero hphiRadial p q t
  by_cases hmiddle : q = .middle ∨ t = .middle
  · obtain ⟨Cmiddle, hCmiddle, hmiddleBound⟩ :=
      exists_oneMiddle_coordinateRadiusDerivativeTripleWaveIntegral_bound hd (2 * d)
        phi hphiOne hphiZero hphiRadial p q t hmiddle
    let C : Real := Csmall * (5 : Real) ^ d + Couter * (8 : Real) ^ d +
      Cmiddle * (3 : Real) ^ d
    refine ⟨C + 1, by dsimp [C]; positivity, ?_⟩
    intro s r r' hs hr hr' v x hv
    let g : Real := |r - r'|
    let T : Real := s * g
    let y : Euclidean d := s • x
    have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
    have hgupper : g ≤ 2 := by
      dsimp [g]
      apply (abs_le).2
      constructor <;> linarith [hr.1, hr.2, hr'.1, hr'.2]
    have hT : 0 ≤ T := by
      dsimp [T]
      positivity
    have hTscale : T ≤ 2 * s := by
      dsimp [T]
      calc
        s * g ≤ s * 2 := mul_le_mul_of_nonneg_left hgupper hs.le
        _ = 2 * s := by ring
    have hyNorm : ‖y‖ = s * ‖x‖ := by
      dsimp [y]
      rw [norm_smul, Real.norm_eq_abs, abs_of_pos hspos]
    by_cases hsmallGap : T ≤ 4
    · have hcrude := hsmall s r r' hs hr hr' v y hv
      have hnum := q4_crude_scale_le_stationaryWeight (d := d)
        (C := Csmall) (by omega) hs hCsmall.le hT hsmallGap
      calc
        ‖∫ u in (1 : Real)..4,
            coordinateRadiusDerivativeTripleWaveCoefficient
              (absoluteDyadicBandpass phi hphiOne hphiZero 0)
              (s * r) (s * r') v y p q t u *
              oscillatoryExp
                (coordinateTripleWavePhase p q t ‖y‖ (s * r) (s * r')) u‖ ≤
            Csmall / s ^ (d - 1) := hcrude
        _ ≤ (Csmall * (5 : Real) ^ d) / s ^ (d - 1) *
            (1 + T) ^ (-q4StationaryExponent d) := hnum
        _ ≤ (C + 1) / s ^ (d - 1) *
            (1 + T) ^ (-q4StationaryExponent d) := by
          apply q4_scaleWeight_mono hs hT
          dsimp [C]
          positivity
    · have hlarge : 4 < T := lt_of_not_ge hsmallGap
      have hTone : 1 ≤ T := by linarith
      by_cases hphysical : g / 4 ≤ ‖x‖
      · have hyOuter : T / 4 ≤ ‖y‖ := by
          rw [hyNorm]
          dsimp [T]
          calc
            s * g / 4 = s * (g / 4) := by ring
            _ ≤ s * ‖x‖ := mul_le_mul_of_nonneg_left hphysical hs.le
        have hyOne : 1 ≤ ‖y‖ := by linarith
        have hphysicalBound := houter s r r' hs hr hr' v y hv hyOne
        have hnum := q4_outer_scale_le_stationaryWeight (d := d)
          (C := Couter) (by omega) hs hCouter.le hTone hyOuter
        calc
          ‖∫ u in (1 : Real)..4,
              coordinateRadiusDerivativeTripleWaveCoefficient
                (absoluteDyadicBandpass phi hphiOne hphiZero 0)
                (s * r) (s * r') v y p q t u *
                oscillatoryExp
                  (coordinateTripleWavePhase p q t ‖y‖ (s * r) (s * r')) u‖ ≤
              Couter / (s ^ (d - 1) * (Real.sqrt ‖y‖) ^ (d - 1)) := hphysicalBound
          _ ≤ (Couter * (8 : Real) ^ d) / s ^ (d - 1) *
              (1 + T) ^ (-q4StationaryExponent d) := hnum
          _ ≤ (C + 1) / s ^ (d - 1) *
              (1 + T) ^ (-q4StationaryExponent d) := by
            apply q4_scaleWeight_mono hs hT
            dsimp [C]
            positivity
      · have hmiddleBound' := hmiddleBound s r r' hs hr hr' v y hv
        have hnum := q4_middle_scale_le_stationaryWeight (d := d)
          (C := Cmiddle) (by omega) hs hCmiddle.le hT hTscale
        calc
          ‖∫ u in (1 : Real)..4,
              coordinateRadiusDerivativeTripleWaveCoefficient
                (absoluteDyadicBandpass phi hphiOne hphiZero 0)
                (s * r) (s * r') v y p q t u *
                oscillatoryExp
                  (coordinateTripleWavePhase p q t ‖y‖ (s * r) (s * r')) u‖ ≤
              Cmiddle / (s ^ (2 * d) * (Real.sqrt s) ^ (d - 1)) := hmiddleBound'
          _ ≤ (Cmiddle * (3 : Real) ^ d) / s ^ (d - 1) *
              (1 + T) ^ (-q4StationaryExponent d) := hnum
          _ ≤ (C + 1) / s ^ (d - 1) *
              (1 + T) ^ (-q4StationaryExponent d) := by
            apply q4_scaleWeight_mono hs hT
            dsimp [C]
            positivity
  · have hq : q ≠ .middle := by
      intro hq
      exact hmiddle (Or.inl hq)
    have ht : t ≠ .middle := by
      intro ht
      exact hmiddle (Or.inr ht)
    obtain ⟨Cinner, hCinner, hinnerBound⟩ :
        ∃ C : Real, 0 < C ∧ ∀ s r r' : Real, 1 ≤ s →
          r ∈ Icc (1 / 2 : Real) (5 / 2) →
          r' ∈ Icc (1 / 2 : Real) (5 / 2) → r ≠ r' →
          ∀ v x : Euclidean d, ‖v‖ = 1 → ‖x‖ ≤ |r - r'| / 4 →
          ‖∫ u in (1 : Real)..4,
            coordinateRadiusDerivativeTripleWaveCoefficient
              (absoluteDyadicBandpass phi hphiOne hphiZero 0)
              (s * r) (s * r') v (s • x) p q t u *
              oscillatoryExp
                (coordinateTripleWavePhase p q t ‖s • x‖ (s * r) (s * r')) u‖ ≤
            (4 / (s * |r - r'|)) ^ d *
              ((8 - (1 / 2 : Real)) * (C / s ^ (d - 1))) := by
      by_cases hp : p = .middle
      · subst p
        exact exists_inner_physicalMiddle_coordinateRadiusDerivativeTripleWaveIntegral_bound
          hd phi hphiOne hphiZero hphiRadial q t hq ht
      · exact exists_inner_endpoint_coordinateRadiusDerivativeTripleWaveIntegral_bound
          hd phi hphiOne hphiZero hphiRadial p q t hp hq ht
    let C : Real := Csmall * (5 : Real) ^ d + Couter * (8 : Real) ^ d +
      ((8 - (1 / 2 : Real)) * Cinner * (8 : Real) ^ d)
    refine ⟨C + 1, by dsimp [C]; positivity, ?_⟩
    intro s r r' hs hr hr' v x hv
    let g : Real := |r - r'|
    let T : Real := s * g
    let y : Euclidean d := s • x
    have hspos : 0 < s := lt_of_lt_of_le zero_lt_one hs
    have hT : 0 ≤ T := by
      dsimp [T]
      positivity
    have hyNorm : ‖y‖ = s * ‖x‖ := by
      dsimp [y]
      rw [norm_smul, Real.norm_eq_abs, abs_of_pos hspos]
    by_cases hsmallGap : T ≤ 4
    · have hcrude := hsmall s r r' hs hr hr' v y hv
      have hnum := q4_crude_scale_le_stationaryWeight (d := d)
        (C := Csmall) (by omega) hs hCsmall.le hT hsmallGap
      calc
        ‖∫ u in (1 : Real)..4,
            coordinateRadiusDerivativeTripleWaveCoefficient
              (absoluteDyadicBandpass phi hphiOne hphiZero 0)
              (s * r) (s * r') v y p q t u *
              oscillatoryExp
                (coordinateTripleWavePhase p q t ‖y‖ (s * r) (s * r')) u‖ ≤
            Csmall / s ^ (d - 1) := hcrude
        _ ≤ (Csmall * (5 : Real) ^ d) / s ^ (d - 1) *
            (1 + T) ^ (-q4StationaryExponent d) := hnum
        _ ≤ (C + 1) / s ^ (d - 1) *
            (1 + T) ^ (-q4StationaryExponent d) := by
          apply q4_scaleWeight_mono hs hT
          dsimp [C]
          positivity
    · have hlarge : 4 < T := lt_of_not_ge hsmallGap
      have hTone : 1 ≤ T := by linarith
      by_cases hphysical : g / 4 ≤ ‖x‖
      · have hyOuter : T / 4 ≤ ‖y‖ := by
          rw [hyNorm]
          dsimp [T]
          calc
            s * g / 4 = s * (g / 4) := by ring
            _ ≤ s * ‖x‖ := mul_le_mul_of_nonneg_left hphysical hs.le
        have hyOne : 1 ≤ ‖y‖ := by linarith
        have hphysicalBound := houter s r r' hs hr hr' v y hv hyOne
        have hnum := q4_outer_scale_le_stationaryWeight (d := d)
          (C := Couter) (by omega) hs hCouter.le hTone hyOuter
        calc
          ‖∫ u in (1 : Real)..4,
              coordinateRadiusDerivativeTripleWaveCoefficient
                (absoluteDyadicBandpass phi hphiOne hphiZero 0)
                (s * r) (s * r') v y p q t u *
                oscillatoryExp
                  (coordinateTripleWavePhase p q t ‖y‖ (s * r) (s * r')) u‖ ≤
              Couter / (s ^ (d - 1) * (Real.sqrt ‖y‖) ^ (d - 1)) := hphysicalBound
          _ ≤ (Couter * (8 : Real) ^ d) / s ^ (d - 1) *
              (1 + T) ^ (-q4StationaryExponent d) := hnum
          _ ≤ (C + 1) / s ^ (d - 1) *
              (1 + T) ^ (-q4StationaryExponent d) := by
            apply q4_scaleWeight_mono hs hT
            dsimp [C]
            positivity
      · have hinner : ‖x‖ ≤ g / 4 := le_of_lt (lt_of_not_ge hphysical)
        have hIBP := hinnerBound s r r' hs hr hr'
          (by
            intro hrr
            have hzero : g = 0 := by
              dsimp [g]
              exact abs_eq_zero.mpr (sub_eq_zero.mpr hrr)
            dsimp [T] at hlarge
            rw [hzero, mul_zero] at hlarge
            linarith)
          v x hv hinner
        have hnum := q4_inner_ibp_scale_le_stationaryWeight (d := d)
          (C := Cinner) (by omega) hs hCinner.le hTone
        calc
          ‖∫ u in (1 : Real)..4,
              coordinateRadiusDerivativeTripleWaveCoefficient
                (absoluteDyadicBandpass phi hphiOne hphiZero 0)
                (s * r) (s * r') v y p q t u *
                oscillatoryExp
                  (coordinateTripleWavePhase p q t ‖y‖ (s * r) (s * r')) u‖ ≤
              (4 / (s * g)) ^ d *
                ((8 - (1 / 2 : Real)) * (Cinner / s ^ (d - 1))) := by
              simpa only [y, T, g] using hIBP
          _ ≤ ((8 - (1 / 2 : Real)) * Cinner * (8 : Real) ^ d) /
              s ^ (d - 1) * (1 + T) ^ (-q4StationaryExponent d) := by
              simpa only [T] using hnum
          _ ≤ (C + 1) / s ^ (d - 1) *
              (1 + T) ^ (-q4StationaryExponent d) := by
            apply q4_scaleWeight_mono hs hT
            dsimp [C]
            positivity

end

end LeanSpherical.HarmonicAnalysis.FractalDilations
