
/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.FractalDilations.AnnulusSharpness
import LeanSpherical.Codex.Spherical.FractalDilations.AnnulusAlgebra
open Codex.Spherical.FractalDilations.AnnulusAlgebra
open Codex.Spherical.FractalDilations.AnnulusLowerBound
open Codex.Spherical.FractalDilations.AnnulusSharpness
open Codex.Spherical.FractalDilations.Definitions
open Codex.Spherical.FractalDilations.ExponentRegions
open Codex.Spherical.FractalDilations.Minkowski







/-!
# The Minkowski annulus sharpness theorem

This module packages the annular small-ball obstruction in the form used by
Theorem 2.  Positive upper Minkowski dimension is reduced to a slightly
smaller packing exponent, while dimension zero uses the one-radius test.
-/

namespace Codex.Spherical.FractalDilations.AnnulusTheorem

noncomputable section

/-- The non-endpoint annular obstruction determined by upper Minkowski
dimension.  The `β = 0` branch is a genuine singleton-radius construction;
for `β > 0`, a strict lower packing exponent is chosen first. -/
theorem minkowski_annulus_test
    {d : ℕ} (hd : 2 ≤ d)
    (E : Set ℝ) (hE : E ⊆ Set.Icc (1 : ℝ) 2) (hEne : E.Nonempty)
    {β p q : ℝ}
    (hβ : 0 ≤ β ∧ β ≤ 1)
    (hMinkowski : upperMinkowskiDimension E = β)
    (hp : 0 < p) (hq : 1 ≤ q)
    (hbad : (1 - β) * q⁻¹ + ((d : ℝ) - 1) < (d : ℝ) * p⁻¹) :
    FractalSphericalUnbounded d E p q := by
  have hd0 : 0 < d := by omega
  have hq0 : 0 < q := lt_of_lt_of_le zero_lt_one hq
  rcases hβ.1.eq_or_lt with hβzero | hβpos
  · have hβeq : β = 0 := hβzero.symm
    have hbadzero : q⁻¹ + ((d : ℝ) - 1) < (d : ℝ) * p⁻¹ := by
      simpa [hβeq] using hbad
    exact fractalSphericalUnbounded_of_single_radius_annulus
      hd0 hE hEne hp hq hbadzero
  · obtain ⟨α, hα0, hαβ, hbadα⟩ :=
      exists_annulus_exponent_lt_minkowski hβpos hq0 hbad
    exact fractalSphericalUnbounded_of_positive_minkowski_annulus
      hd0 hE hMinkowski hα0 hαβ hp hq hbadα

end

end Codex.Spherical.FractalDilations.AnnulusTheorem