/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.FractalDilations.AbsoluteAssembly

/-!
# Off-diagonal absolute-frequency reassembly

The `Q4` part of the fractal-dilation argument is off diagonal.  This file
records the purely formal final step: uniform finite-cutoff moment estimates
at exponents `(p,q)` pass through the absolute-frequency Fatou argument to a
strong `Lᵖ → Lᑫ` estimate.  It is independent of the stationary-phase input
which is needed to produce the dyadic estimates.
-/

namespace LeanSpherical.HarmonicAnalysis.FractalDilations

open Filter MeasureTheory FourierTransform Metric Set
open scoped FourierTransform Topology

noncomputable section

/-- Moment form of an off-diagonal restricted spherical maximal estimate.
The power on the right is exactly the homogeneous `Lᵖ → Lᑫ` normalization. -/
def HasFractalSphericalOffDiagonalMomentStrongType
    (d : ℕ) (E : Set ℝ) (p q : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ f : SchwartzMap (Euclidean d) ℂ,
    MemLp (fractalSphericalMaximalReal d E f) (ENNReal.ofReal q) volume ∧
      (∫ x : Euclidean d,
        ‖fractalSphericalMaximalReal d E f x‖ ^ q) ≤
        C * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p)

/-- The off-diagonal moment formulation implies the strong-type formulation. -/
theorem HasFractalSphericalOffDiagonalMomentStrongType.toStrongType
    {d : ℕ} {E : Set ℝ} {p q : ℝ} (hp : 0 < p) (hq : 0 < q)
    (h : HasFractalSphericalOffDiagonalMomentStrongType d E p q) :
    HasFractalSphericalStrongType d E p q := by
  obtain ⟨C, hC, hbound⟩ := h
  refine ⟨C ^ q⁻¹, Real.rpow_pos_of_pos hC _, fun f => ?_⟩
  obtain ⟨hmem, hmoment⟩ := hbound f
  refine ⟨hmem, ?_⟩
  have hpE0 : ENNReal.ofReal p ≠ 0 := ENNReal.ofReal_ne_zero_iff.mpr hp
  have hpET : ENNReal.ofReal p ≠ ⊤ := ENNReal.ofReal_ne_top
  have hqE0 : ENNReal.ofReal q ≠ 0 := ENNReal.ofReal_ne_zero_iff.mpr hq
  have hqET : ENNReal.ofReal q ≠ ⊤ := ENNReal.ofReal_ne_top
  have hfmem : MemLp (f : Euclidean d → ℂ) (ENNReal.ofReal p) volume :=
    f.memLp (ENNReal.ofReal p) volume
  have hI : 0 ≤ ∫ x : Euclidean d, ‖f x‖ ^ p :=
    integral_nonneg fun x => Real.rpow_nonneg (norm_nonneg _) p
  have hleft : 0 ≤ ∫ x : Euclidean d,
      ‖fractalSphericalMaximalReal d E f x‖ ^ q :=
    integral_nonneg fun x => Real.rpow_nonneg (norm_nonneg _) q
  rw [hmem.eLpNorm_eq_integral_rpow_norm hqE0 hqET,
    hfmem.eLpNorm_eq_integral_rpow_norm hpE0 hpET]
  rw [ENNReal.toReal_ofReal hp.le]
  rw [← ENNReal.ofReal_mul (Real.rpow_nonneg hC.le _)]
  apply ENNReal.ofReal_le_ofReal
  rw [ENNReal.toReal_ofReal hq.le]
  calc
    (∫ x : Euclidean d, ‖fractalSphericalMaximalReal d E f x‖ ^ q) ^ q⁻¹ ≤
        (C * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p)) ^ q⁻¹ :=
      Real.rpow_le_rpow hleft hmoment (inv_nonneg.mpr hq.le)
    _ = C ^ q⁻¹ * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ p⁻¹ := by
      rw [Real.mul_rpow hC.le (Real.rpow_nonneg hI _)]
      rw [← Real.rpow_mul hI]
      congr 1
      field_simp

/-- Uniform off-diagonal moment estimates for finite absolute cutoffs pass to
the restricted maximal operator.  This is the endpoint-free Fatou portion of
the `Q4` assembly; the hypotheses are precisely the finite-cutoff estimates
which the oscillatory `TT*` argument must provide. -/
theorem absolute_reassembly_limit_off_diagonal
    {d : ℕ} {p q : ℝ} (hd0 : 0 < d) (hp : 0 < p) (hq : 0 < q)
    (E : Set ℝ) (hEpos : E ⊆ Ioi (0 : ℝ))
    (φ : SchwartzMap (Euclidean d) ℂ)
    (hφone : ∀ ξ, ‖ξ‖ ≤ 1 → φ ξ = 1)
    (A : ℝ) (hA : 0 < A)
    (hfinite : ∀ (N : ℕ) (f : SchwartzMap (Euclidean d) ℂ),
      MemLp (fractalAbsoluteCutoffMaximal d E φ N f) (ENNReal.ofReal q) volume ∧
      (∫ x : Euclidean d,
        (fractalAbsoluteCutoffMaximal d E φ N f x) ^ q) ≤
        A * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p)) :
    HasFractalSphericalStrongType d E p q := by
  apply HasFractalSphericalOffDiagonalMomentStrongType.toStrongType hp hq
  refine ⟨A, hA, ?_⟩
  intro f
  have hqNN : 0 ≤ q := hq.le
  have hqEN0 : ENNReal.ofReal q ≠ 0 := ENNReal.ofReal_ne_zero_iff.mpr hq
  have hqENT : ENNReal.ofReal q ≠ ⊤ := ENNReal.ofReal_ne_top
  have hUmeas (N : ℕ) :
      AEMeasurable (fun x : Euclidean d =>
        ENNReal.ofReal ((fractalAbsoluteCutoffMaximal d E φ N f x) ^ q)) volume := by
    have hmeas : AEMeasurable (fun x : Euclidean d =>
        (ENNReal.ofReal (fractalAbsoluteCutoffMaximal d E φ N f x)) ^ q) volume :=
      ENNReal.continuous_rpow_const.measurable.comp_aemeasurable
        ((hfinite N f).1.1.aemeasurable.ennreal_ofReal)
    convert hmeas using 1
    funext x
    exact (ENNReal.ofReal_rpow_of_nonneg
      (fractalAbsoluteCutoffMaximal_nonneg E φ N f x) hqNN).symm
  have hUPowInt (N : ℕ) :
      Integrable (fun x : Euclidean d =>
        (fractalAbsoluteCutoffMaximal d E φ N f x) ^ q) volume := by
    have h := (hfinite N f).1.integrable_norm_rpow hqEN0 hqENT
    convert h using 1
    funext x
    rw [Real.norm_eq_abs,
      abs_of_nonneg (fractalAbsoluteCutoffMaximal_nonneg E φ N f x),
      ENNReal.toReal_ofReal hqNN]
  have hUint (N : ℕ) :
      (∫⁻ x : Euclidean d,
        ENNReal.ofReal ((fractalAbsoluteCutoffMaximal d E φ N f x) ^ q)) ≤
        ENNReal.ofReal
          (A * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p)) := by
    calc
      (∫⁻ x : Euclidean d,
        ENNReal.ofReal ((fractalAbsoluteCutoffMaximal d E φ N f x) ^ q)) =
          ENNReal.ofReal (∫ x : Euclidean d,
            (fractalAbsoluteCutoffMaximal d E φ N f x) ^ q) := by
            rw [ofReal_integral_eq_lintegral_ofReal (hUPowInt N)]
            exact Filter.Eventually.of_forall fun x =>
              Real.rpow_nonneg (fractalAbsoluteCutoffMaximal_nonneg E φ N f x) q
      _ ≤ ENNReal.ofReal
          (A * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p)) :=
        ENNReal.ofReal_le_ofReal (hfinite N f).2
  have hFatou :
      (∫⁻ x : Euclidean d,
        ENNReal.ofReal ((fractalSphericalMaximalReal d E f x) ^ q)) ≤
        liminf (fun N : ℕ =>
          ∫⁻ x : Euclidean d,
            ENNReal.ofReal ((fractalAbsoluteCutoffMaximal d E φ N f x) ^ q)) atTop := by
    calc
      (∫⁻ x : Euclidean d,
        ENNReal.ofReal ((fractalSphericalMaximalReal d E f x) ^ q)) ≤
          ∫⁻ x : Euclidean d,
            liminf (fun N : ℕ =>
              ENNReal.ofReal ((fractalAbsoluteCutoffMaximal d E φ N f x) ^ q)) atTop :=
        lintegral_mono (fun x =>
          fractal_spherical_maximal_power_le_liminf_absolute_cutoff
            hd0 hq hqNN E hEpos φ hφone f x)
      _ ≤ liminf (fun N : ℕ =>
          ∫⁻ x : Euclidean d,
            ENNReal.ofReal ((fractalAbsoluteCutoffMaximal d E φ N f x) ^ q)) atTop :=
        lintegral_liminf_le' fun N => hUmeas N
  have hLiminfBound :
      liminf (fun N : ℕ =>
        ∫⁻ x : Euclidean d,
          ENNReal.ofReal ((fractalAbsoluteCutoffMaximal d E φ N f x) ^ q)) atTop ≤
        ENNReal.ofReal
          (A * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p)) :=
    Filter.liminf_le_of_frequently_le'
      (Filter.Frequently.of_forall fun N => hUint N)
  have hlin :
      (∫⁻ x : Euclidean d,
        ENNReal.ofReal ((fractalSphericalMaximalReal d E f x) ^ q)) ≤
        ENNReal.ofReal
          (A * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p)) :=
    hFatou.trans hLiminfBound
  have hmaxmeas : AEStronglyMeasurable (fractalSphericalMaximalReal d E f) volume :=
    (measurable_fractalSphericalMaximalReal E f).aestronglyMeasurable
  have hmaxnonneg : ∀ x, 0 ≤ fractalSphericalMaximalReal d E f x := by
    intro x
    exact ENNReal.toReal_nonneg
  have hright : 0 ≤ A * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p) := by
    apply mul_nonneg hA.le
    exact Real.rpow_nonneg
      (integral_nonneg fun _ => Real.rpow_nonneg (norm_nonneg _) p) _
  rcases memLp_and_integral_of_lintegral_rpow_bound
    (fractalSphericalMaximalReal d E f) hmaxmeas hmaxnonneg hq hlin hright with
      ⟨hmem, hmoment⟩
  refine ⟨hmem, ?_⟩
  calc
    (∫ x : Euclidean d, ‖fractalSphericalMaximalReal d E f x‖ ^ q) =
        ∫ x : Euclidean d, (fractalSphericalMaximalReal d E f x) ^ q := by
          apply integral_congr_ae
          filter_upwards with x
          rw [Real.norm_of_nonneg (hmaxnonneg x)]
    _ ≤ A * (∫ x : Euclidean d, ‖f x‖ ^ p) ^ (q / p) := hmoment

end

end LeanSpherical.HarmonicAnalysis.FractalDilations
