
/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.FractalDilations.Q4PlanarCriticalParameters
open Codex.Spherical.FractalDilations.ExponentRegions
open Codex.Spherical.FractalDilations.Q4PlanarCriticalParameters
open Codex.Spherical.FractalDilations.Q4StrictParameters







/-!
# Parameters after the quasi-Assouad subpower loss

The local cover furnished by quasi-Assouad dimension carries a factor
`delta ^ (-eta)`.  In the Section 3 `TT*` interpolation this contributes
`theta * eta` to the frequency exponent.  This small, but essential, loss
must be chosen before the dyadic pieces are summed.  The lemmas below make
that choice explicitly.

At the planar critical value `gamma = 1 / 2` the gap exponent is positive.
The paper keeps the literal finite range `n <= j + O(1)`; the last lemma
records the corresponding calculation with the subpower loss included.
-/

namespace Codex.Spherical.FractalDilations.Q4SubpowerParameters

noncomputable section

/-- Frequency exponent after the `delta ^ (-eta)` loss in the local
quasi-Assouad cover. -/
def q4FrequencyExponentWithSubpowerLoss (d : Nat) (theta eta : Real) : Real :=
  q4FrequencyExponent d theta + theta * eta

/-- At every frequency parameter strictly above the Q4 threshold, the
quasi-Assouad loss can be chosen so that the *post-`TT*` half exponent is
smaller than any prescribed positive number.  This is the scalar content of
the ``arbitrarily small loss'' in Corollary 3.2.  The choice is explicit and
is deliberately recorded before any interpolation of maximal operators. -/
theorem q4_subpower_half_frequency_exponent_lt
    {d : Nat} {theta epsilon : Real}
    (hd : 0 < d) (htheta : 1 / (d : Real) < theta)
    (hepsilon : 0 < epsilon) :
    q4FrequencyExponentWithSubpowerLoss d theta (epsilon / theta) / 2 <
      epsilon := by
  have hdReal : 0 < (d : Real) := by exact_mod_cast hd
  have hthetaPos : 0 < theta := by
    exact lt_trans (one_div_pos.mpr hdReal) htheta
  have htheta_ne : theta ≠ 0 := hthetaPos.ne'
  unfold q4FrequencyExponentWithSubpowerLoss q4FrequencyExponent
  have hscale : theta * (epsilon / theta) = epsilon := by
    field_simp [htheta_ne]
  rw [hscale]
  have hstrict : 1 < (d : Real) * theta :=
    (div_lt_iff₀ hdReal).mp htheta
  nlinarith

/-- Away from the planar critical line, the two strict Section 3 exponents
remain negative after choosing the quasi-Assouad subpower loss sufficiently
small. -/
theorem exists_q4_strict_negative_exponents_with_subpower_loss
    {d : Nat} {gamma : Real}
    (hd : 3 <= d \/ d = 2 /\ gamma < 1 / 2)
    (hgamma : 0 <= gamma /\ gamma <= 1) :
    exists theta eta : Real, 0 < theta /\ theta < 1 /\ 0 < eta /\
      q4FrequencyExponentWithSubpowerLoss d theta eta < 0 /\
        q4GapExponent d gamma theta < 0 := by
  obtain ⟨theta, htheta0, htheta1, hfrequency, hgap⟩ :=
    exists_q4_strict_negative_exponents hd hgamma
  let eta : Real := -q4FrequencyExponent d theta / (2 * theta)
  have hden : 0 < 2 * theta := mul_pos (by norm_num) htheta0
  have heta : 0 < eta := by
    dsimp only [eta]
    exact div_pos (neg_pos.mpr hfrequency) hden
  have hidentity : theta * eta = -q4FrequencyExponent d theta / 2 := by
    dsimp only [eta]
    field_simp [ne_of_gt htheta0]
    ring
  refine ⟨theta, eta, htheta0, htheta1, heta, ?_, hgap⟩
  unfold q4FrequencyExponentWithSubpowerLoss
  rw [hidentity]
  linarith

/-- A concrete choice of parameters at the planar critical value.  The
combined exponent is negative even after the quasi-Assouad subpower loss. -/
theorem exists_q4_planar_critical_subpower_parameters :
    exists theta eta : Real, 1 / 2 < theta /\ theta < 1 /\ 0 < eta /\
      q4FrequencyExponentWithSubpowerLoss 2 theta eta +
        q4GapExponent 2 (1 / 2) theta < 0 := by
  refine ⟨3 / 4, 1 / 12, by norm_num, by norm_num, by norm_num, ?_⟩
  norm_num [q4FrequencyExponentWithSubpowerLoss, q4FrequencyExponent,
    q4GapExponent]

/-- With the literal finite range of the radius-gap decomposition, the
planar critical shell exponent is controlled by a strictly negative combined
frequency exponent plus a harmless fixed constant. -/
theorem q4_planar_critical_shell_exponent_with_subpower_loss_le
    {theta eta : Real} {j n : Nat}
    (htheta : 1 / 2 < theta) (hn : n <= j + 3) :
    q4FrequencyExponentWithSubpowerLoss 2 theta eta * (j : Real) +
        q4GapExponent 2 (1 / 2) theta * (n : Real) <=
      (q4FrequencyExponentWithSubpowerLoss 2 theta eta +
        q4GapExponent 2 (1 / 2) theta) * (j : Real) +
          3 * (theta - 1 / 2) := by
  have hgap : q4GapExponent 2 (1 / 2) theta = theta - 1 / 2 := by
    norm_num [q4GapExponent]
    ring
  rw [hgap]
  have hnreal : (n : Real) <= (j : Real) + 3 := by
    exact_mod_cast hn
  have hgap_nonneg : 0 <= theta - 1 / 2 := by linarith
  have hmul : (theta - 1 / 2) * (n : Real) <=
      (theta - 1 / 2) * ((j : Real) + 3) :=
    mul_le_mul_of_nonneg_left hnreal hgap_nonneg
  calc
    q4FrequencyExponentWithSubpowerLoss 2 theta eta * (j : Real) +
        (theta - 1 / 2) * (n : Real) <=
      q4FrequencyExponentWithSubpowerLoss 2 theta eta * (j : Real) +
        (theta - 1 / 2) * ((j : Real) + 3) :=
      add_le_add_left hmul _
    _ = (q4FrequencyExponentWithSubpowerLoss 2 theta eta +
        (theta - 1 / 2)) * (j : Real) + 3 * (theta - 1 / 2) := by
      ring

/-- The finite planar critical gap sum with the quasi-Assouad subpower loss
kept in the frequency exponent.  This is the form needed after the literal
`TT*` shell coefficient has been rewritten as a product of a frequency term
and a gap term.  Unlike the ordinary decreasing-gap argument, the gap ratio
is larger than one; the exact range `n < j + 3` is what supplies the final
frequency gain. -/
theorem q4_planar_critical_finite_level_sum_with_subpower_loss_le
    {theta eta : Real} (htheta : 1 / 2 < theta) (j : Nat) :
    (∑ n ∈ Finset.range (j + 3),
      (2 : Real) ^
        (q4FrequencyExponentWithSubpowerLoss 2 theta eta * (j : Real) +
          q4GapExponent 2 (1 / 2) theta * (n : Real))) ≤
      (((2 : Real) ^ (theta - 1 / 2)) ^ 3 /
        ((2 : Real) ^ (theta - 1 / 2) - 1)) *
        ((2 : Real) ^
          (q4FrequencyExponentWithSubpowerLoss 2 theta eta +
            q4GapExponent 2 (1 / 2) theta)) ^ j := by
  let a : Real := q4FrequencyExponentWithSubpowerLoss 2 theta eta
  let b : Real := q4GapExponent 2 (1 / 2) theta
  let r : Real := (2 : Real) ^ (theta - 1 / 2)
  have hb : b = theta - 1 / 2 := by
    dsimp [b, q4GapExponent]
    norm_num
    ring
  have hbpos : 0 < theta - 1 / 2 := by linarith
  have hr : 1 < r := by
    dsimp [r]
    exact Real.one_lt_rpow (by norm_num) hbpos
  have hsum : (∑ n ∈ Finset.range (j + 3), r ^ n) ≤
      r ^ (j + 3) / (r - 1) :=
    q4_finset_sum_pow_le_last_scale_of_one_lt hr (j + 3)
  have hfactor : 0 ≤ (2 : Real) ^ (a * (j : Real)) :=
    Real.rpow_nonneg (by norm_num) _
  calc
    (∑ n ∈ Finset.range (j + 3),
      (2 : Real) ^
        (q4FrequencyExponentWithSubpowerLoss 2 theta eta * (j : Real) +
          q4GapExponent 2 (1 / 2) theta * (n : Real))) =
        (2 : Real) ^ (a * (j : Real)) *
          ∑ n ∈ Finset.range (j + 3), r ^ n := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro n hn
      dsimp [r]
      rw [← Real.rpow_mul_natCast (by norm_num : (0 : Real) ≤ 2)
        (theta - 1 / 2) n]
      rw [← Real.rpow_add (by norm_num : (0 : Real) < 2)]
      rw [show q4FrequencyExponentWithSubpowerLoss 2 theta eta = a by rfl,
        show q4GapExponent 2 (1 / 2) theta = b by rfl, hb]
    _ ≤ (2 : Real) ^ (a * (j : Real)) * (r ^ (j + 3) / (r - 1)) :=
      mul_le_mul_of_nonneg_left hsum hfactor
    _ = (((2 : Real) ^ (theta - 1 / 2)) ^ 3 /
        ((2 : Real) ^ (theta - 1 / 2) - 1)) *
        ((2 : Real) ^
          (q4FrequencyExponentWithSubpowerLoss 2 theta eta +
            q4GapExponent 2 (1 / 2) theta)) ^ j := by
      rw [pow_add]
      dsimp [r]
      rw [← Real.rpow_mul_natCast (by norm_num : (0 : Real) ≤ 2)
        (theta - 1 / 2) j,
        ← Real.rpow_mul_natCast (by norm_num : (0 : Real) ≤ 2)
          (q4FrequencyExponentWithSubpowerLoss 2 theta eta +
            q4GapExponent 2 (1 / 2) theta) j]
      rw [← Real.rpow_add (by norm_num : (0 : Real) < 2)]
      rw [hb]
      congr 2
      ring

/-- The dyadic ratio supplied by the preceding finite planar sum is strictly
smaller than one as soon as the combined subpower-loss exponent is negative.
-/
theorem q4_planar_critical_finite_level_ratio_with_subpower_loss_lt_one
    {theta eta : Real}
    (hneg : q4FrequencyExponentWithSubpowerLoss 2 theta eta +
      q4GapExponent 2 (1 / 2) theta < 0) :
    (2 : Real) ^
      (q4FrequencyExponentWithSubpowerLoss 2 theta eta +
        q4GapExponent 2 (1 / 2) theta) < 1 := by
  exact Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) hneg

end

end Codex.Spherical.FractalDilations.Q4SubpowerParameters