/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.FractalDilations.AssouadSpectrumFacts

/-!
# The quasi-Assouad limit

For the upper Assouad spectrum the scale parameter is monotone.  This gives a
genuine left limit at `1`; the supremal definition in `AssouadSpectrum.lean`
therefore agrees with the requested quasi-Assouad dimension defined as the
limit of the spectrum as `theta` tends to one from below.
-/

namespace LeanSpherical.HarmonicAnalysis.FractalDilations

open Set Filter
open scoped Topology

noncomputable section

private theorem upperAssouadSpectrum_bddAbove_Ioo (E : Set ℝ) :
    BddAbove (upperAssouadSpectrum E '' Ioo (0 : ℝ) 1) := by
  refine ⟨1, ?_⟩
  rintro _ ⟨θ, hθ, rfl⟩
  exact upperAssouadSpectrum_le_one E hθ.2.le

private theorem upperAssouadSpectrum_image_Ioo_nonempty (E : Set ℝ) :
    (upperAssouadSpectrum E '' Ioo (0 : ℝ) 1).Nonempty := by
  refine ⟨upperAssouadSpectrum E (1 / 2), ?_⟩
  exact ⟨1 / 2, by norm_num, rfl⟩

/-- Adding the endpoint `theta = 0` does not alter the supremum of the
monotone upper spectrum on the approach to one. -/
theorem sSup_upperAssouadSpectrum_image_Ioo_eq_quasiAssouadDimension
    (E : Set ℝ) :
    sSup (upperAssouadSpectrum E '' Ioo (0 : ℝ) 1) =
      quasiAssouadDimension E := by
  let A : Set ℝ := upperAssouadSpectrum E '' Ioo (0 : ℝ) 1
  let B : Set ℝ := upperAssouadSpectrum E '' Ico (0 : ℝ) 1
  have hAbdd : BddAbove A := by
    simpa only [A] using upperAssouadSpectrum_bddAbove_Ioo E
  have hAne : A.Nonempty := by
    simpa only [A] using upperAssouadSpectrum_image_Ioo_nonempty E
  have hBbdd : BddAbove B := by
    refine ⟨1, ?_⟩
    rintro _ ⟨θ, hθ, rfl⟩
    exact upperAssouadSpectrum_le_one E hθ.2.le
  have hBne : B.Nonempty := by
    refine ⟨upperAssouadSpectrum E (1 / 2), ?_⟩
    exact ⟨1 / 2, by norm_num, rfl⟩
  have hAsubB : A ⊆ B := by
    rintro _ ⟨θ, hθ, rfl⟩
    exact ⟨θ, ⟨hθ.1.le, hθ.2⟩, rfl⟩
  have hA_le_B : sSup A ≤ sSup B :=
    csSup_le_csSup hBbdd hAne hAsubB
  have hB_le_A : sSup B ≤ sSup A := by
    apply csSup_le hBne
    rintro _ ⟨θ, hθ, rfl⟩
    by_cases hθpos : 0 < θ
    · exact le_csSup hAbdd ⟨θ, ⟨hθpos, hθ.2⟩, rfl⟩
    · have hθzero : θ = 0 := le_antisymm (le_of_not_gt hθpos) hθ.1
      subst θ
      calc
        upperAssouadSpectrum E 0 ≤ upperAssouadSpectrum E (1 / 2) :=
          upperAssouadSpectrum_mono E (by norm_num) (by norm_num)
        _ ≤ sSup A := le_csSup hAbdd ⟨(1 / 2 : ℝ), by norm_num, rfl⟩
  change sSup A = sSup B
  exact le_antisymm hA_le_B hB_le_A

/-- The quasi-Assouad dimension is exactly the left limit of the upper
Assouad spectrum at scale parameter one. -/
theorem hasQuasiAssouadDimension :
    ∀ E : Set ℝ, HasQuasiAssouadDimension E (quasiAssouadDimension E) := by
  intro E
  have hmono : MonotoneOn (upperAssouadSpectrum E) (Ioo (0 : ℝ) 1) :=
    fun _ hθ _ hθ' hθθ' =>
      upperAssouadSpectrum_monotoneOn E ⟨hθ.1.le, hθ.2.le⟩
        ⟨hθ'.1.le, hθ'.2.le⟩ hθθ'
  have hlim := MonotoneOn.tendsto_nhdsWithin_Ioo_left
    (f := upperAssouadSpectrum E) (x := (1 : ℝ)) (y := (0 : ℝ))
    (by exact ⟨1 / 2, by norm_num, by norm_num⟩) hmono
    (upperAssouadSpectrum_bddAbove_Ioo E)
  change Tendsto (upperAssouadSpectrum E) (nhdsWithin 1 (Iio 1))
    (𝓝 (quasiAssouadDimension E))
  rw [← sSup_upperAssouadSpectrum_image_Ioo_eq_quasiAssouadDimension E]
  exact hlim

/-- The filter-limit and supremal formulations of quasi-Assouad dimension
are equivalent for the upper spectrum. -/
theorem hasQuasiAssouadDimension_iff
    {E : Set ℝ} {γ : ℝ} :
    HasQuasiAssouadDimension E γ ↔ quasiAssouadDimension E = γ := by
  constructor
  · intro h
    exact tendsto_nhds_unique (hasQuasiAssouadDimension E) h
  · intro h
    rw [← h]
    exact hasQuasiAssouadDimension E

end

end LeanSpherical.HarmonicAnalysis.FractalDilations
