/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.FractalDilations.SharpnessTests
import Mathlib.Analysis.SpecialFunctions.Pow.Asymptotics

/-!
# Large-ball volume growth for sharpness tests

This file isolates the elementary volume growth used by the translation
obstruction.  Keeping it separate means that the eventual analytic
unboundedness proof only has to supply its Schwartz test functions and the
normalization argument.
-/

namespace LeanSpherical.HarmonicAnalysis.FractalDilations

open MeasureTheory Metric Set Filter

noncomputable section

/-- The real volume of a positive Euclidean ball is its radius to the
dimension times the real volume of the unit ball. -/
theorem volume_ball_toReal (d : ℕ) (r : ℝ) (hr : 0 < r) :
    (volume (ball (0 : Euclidean d) r)).toReal =
      r ^ d * (volume (ball (0 : Euclidean d) 1)).toReal := by
  rw [Measure.addHaar_ball_of_pos volume (0 : Euclidean d) hr]
  simp only [finrank_euclideanSpace_fin, ENNReal.toReal_mul,
    ENNReal.toReal_ofReal (pow_nonneg hr.le _)]

/-- The real volume of the Euclidean unit ball is positive in positive
dimension. -/
theorem volume_unit_ball_toReal_pos {d : ℕ} (hd : 0 < d) :
    0 < (volume (ball (0 : Euclidean d) 1)).toReal := by
  apply ENNReal.toReal_pos
  · exact (Metric.measure_ball_pos volume (0 : Euclidean d) (by norm_num)).ne'
  · exact (measure_ball_lt_top (μ := volume) (x := (0 : Euclidean d))
      (r := (1 : ℝ))).ne

/-- A positive-radius Euclidean ball has a nonzero finite real power of its
volume.  This supplies the nondegeneracy side conditions for normalization. -/
theorem volume_ball_rpow_ne_zero_ne_top
    {d : ℕ} (r e : ℝ) (hr : 0 < r) :
    volume (ball (0 : Euclidean d) r) ^ e ≠ 0 ∧
      volume (ball (0 : Euclidean d) r) ^ e ≠ (⊤ : ENNReal) := by
  have hpos : 0 < volume (ball (0 : Euclidean d) r) :=
    Metric.measure_ball_pos volume (0 : Euclidean d) hr
  have htop : volume (ball (0 : Euclidean d) r) ≠ (⊤ : ENNReal) :=
    (measure_ball_lt_top (μ := volume) (x := (0 : Euclidean d)) (r := r)).ne
  exact ⟨(ENNReal.rpow_pos hpos htop).ne',
    ENNReal.rpow_ne_top_of_ne_zero hpos.ne' htop⟩

/-- A higher real power eventually dominates a lower real power, with any
fixed positive coefficient on the right.  This is the purely ordered-field
part of the large-ball test. -/
theorem exists_rpow_separation {a b B C : ℝ} (hB : 0 < B) (hab : a < b) :
    ∃ T : ℝ, 0 < T ∧ C * T ^ a < T ^ b * B := by
  have hgrow : ∀ᶠ T : ℝ in atTop, C / B < T ^ (b - a) :=
    (tendsto_rpow_atTop (sub_pos.mpr hab)).eventually_gt_atTop (C / B)
  have hpos : ∀ᶠ T : ℝ in atTop, 0 < T := eventually_gt_atTop 0
  obtain ⟨T, hTgrow, hTpos⟩ := (hgrow.and hpos).exists
  refine ⟨T, hTpos, ?_⟩
  have hbase : C < T ^ (b - a) * B := (div_lt_iff₀ hB).mp hTgrow
  have hTa : 0 < T ^ a := Real.rpow_pos_of_pos hTpos _
  have hmul : C * T ^ a < (T ^ (b - a) * B) * T ^ a := by
    calc
      C * T ^ a = C * T ^ a := rfl
      _ < (T ^ (b - a) * B) * T ^ a :=
        mul_lt_mul_of_pos_right hbase hTa
  calc
    C * T ^ a < (T ^ (b - a) * B) * T ^ a := hmul
    _ = (T ^ (b - a) * T ^ a) * B := by ring
    _ = T ^ ((b - a) + a) * B := by rw [← Real.rpow_add hTpos]
    _ = T ^ b * B := by
      have hsum : (b - a) + a = b := by ring
      rw [hsum]

/-- The power separation can be arranged beyond any prescribed threshold. -/
theorem exists_rpow_separation_above {a b B C M : ℝ} (hB : 0 < B) (hab : a < b) :
    ∃ T : ℝ, M < T ∧ 0 < T ∧ C * T ^ a < T ^ b * B := by
  have hgrow : ∀ᶠ T : ℝ in atTop, C / B < T ^ (b - a) :=
    (tendsto_rpow_atTop (sub_pos.mpr hab)).eventually_gt_atTop (C / B)
  have habove : ∀ᶠ T : ℝ in atTop, M < T := eventually_gt_atTop M
  have hpos : ∀ᶠ T : ℝ in atTop, 0 < T := eventually_gt_atTop 0
  obtain ⟨T, hTgrow, hTM, hTpos⟩ := (hgrow.and (habove.and hpos)).exists
  refine ⟨T, hTM, hTpos, ?_⟩
  have hbase : C < T ^ (b - a) * B := (div_lt_iff₀ hB).mp hTgrow
  have hTa : 0 < T ^ a := Real.rpow_pos_of_pos hTpos _
  calc
    C * T ^ a < (T ^ (b - a) * B) * T ^ a :=
      mul_lt_mul_of_pos_right hbase hTa
    _ = (T ^ (b - a) * T ^ a) * B := by ring
    _ = T ^ ((b - a) + a) * B := by rw [← Real.rpow_add hTpos]
    _ = T ^ b * B := by
      have hsum : (b - a) + a = b := by ring
      rw [hsum]

/-- At every pair of positive exponents with `p < q` in reciprocal
coordinates, the volume gained by a large ball beats the input-volume cost.
The radii are `T` and `4T`; this fixed factor is convenient for smooth ball
cutoffs supported in the ball of radius `2R` with `R = 2T`. -/
theorem exists_large_ball_volume_gap
    {d : ℕ} (hd : 0 < d) {p q C : ℝ}
    (hp : 0 < p) (hq : 0 < q) (hbad : p⁻¹ < q⁻¹) :
    ∃ T : ℝ, 0 < T ∧
      C * (volume (ball (0 : Euclidean d) (4 * T))).toReal ^ p⁻¹ <
        (volume (ball (0 : Euclidean d) T)).toReal ^ q⁻¹ := by
  let V : ℝ := (volume (ball (0 : Euclidean d) 1)).toReal
  have hV : 0 < V := volume_unit_ball_toReal_pos hd
  have hd' : 0 < (d : ℝ) := by exact_mod_cast hd
  have hab : (d : ℝ) * p⁻¹ < (d : ℝ) * q⁻¹ :=
    mul_lt_mul_of_pos_left hbad hd'
  have hB : 0 < V ^ q⁻¹ := Real.rpow_pos_of_pos hV _
  obtain ⟨T, hT, hsep⟩ := exists_rpow_separation
    (a := (d : ℝ) * p⁻¹) (b := (d : ℝ) * q⁻¹)
    (B := V ^ q⁻¹) (C := C * 4 ^ ((d : ℝ) * p⁻¹) * V ^ p⁻¹) hB hab
  refine ⟨T, hT, ?_⟩
  rw [volume_ball_toReal d (4 * T) (by positivity), volume_ball_toReal d T hT]
  change C * (((4 * T) ^ d * V) ^ p⁻¹) < (T ^ d * V) ^ q⁻¹
  have hleft : C * (((4 * T) ^ d * V) ^ p⁻¹) =
      (C * 4 ^ ((d : ℝ) * p⁻¹) * V ^ p⁻¹) * T ^ ((d : ℝ) * p⁻¹) := by
    rw [Real.mul_rpow (pow_nonneg (by positivity) _) hV.le]
    rw [← Real.rpow_natCast, ← Real.rpow_mul (by positivity : 0 ≤ 4 * T)]
    rw [Real.mul_rpow (by positivity) hT.le]
    ring
  have hright : (T ^ d * V) ^ q⁻¹ = T ^ ((d : ℝ) * q⁻¹) * V ^ q⁻¹ := by
    rw [Real.mul_rpow (pow_nonneg hT.le _) hV.le]
    rw [← Real.rpow_natCast, ← Real.rpow_mul hT.le]
  rw [hleft, hright]
  exact hsep

/-- The large-ball volume gap can be obtained with radius beyond any fixed
threshold.  This is the form used when the chosen radius must dominate a
member of the dilation set. -/
theorem exists_large_ball_volume_gap_above
    {d : ℕ} (hd : 0 < d) {p q C M : ℝ}
    (hp : 0 < p) (hq : 0 < q) (hbad : p⁻¹ < q⁻¹) :
    ∃ T : ℝ, M < T ∧
      C * (volume (ball (0 : Euclidean d) (4 * T))).toReal ^ p⁻¹ <
        (volume (ball (0 : Euclidean d) T)).toReal ^ q⁻¹ := by
  let V : ℝ := (volume (ball (0 : Euclidean d) 1)).toReal
  have hV : 0 < V := volume_unit_ball_toReal_pos hd
  have hd' : 0 < (d : ℝ) := by exact_mod_cast hd
  have hab : (d : ℝ) * p⁻¹ < (d : ℝ) * q⁻¹ :=
    mul_lt_mul_of_pos_left hbad hd'
  have hB : 0 < V ^ q⁻¹ := Real.rpow_pos_of_pos hV _
  obtain ⟨T, hTM, hT, hsep⟩ := exists_rpow_separation_above
    (a := (d : ℝ) * p⁻¹) (b := (d : ℝ) * q⁻¹)
    (B := V ^ q⁻¹) (C := C * 4 ^ ((d : ℝ) * p⁻¹) * V ^ p⁻¹) (M := M) hB hab
  refine ⟨T, hTM, ?_⟩
  rw [volume_ball_toReal d (4 * T) (by positivity), volume_ball_toReal d T hT]
  change C * (((4 * T) ^ d * V) ^ p⁻¹) < (T ^ d * V) ^ q⁻¹
  have hleft : C * (((4 * T) ^ d * V) ^ p⁻¹) =
      (C * 4 ^ ((d : ℝ) * p⁻¹) * V ^ p⁻¹) * T ^ ((d : ℝ) * p⁻¹) := by
    rw [Real.mul_rpow (pow_nonneg (by positivity) _) hV.le]
    rw [← Real.rpow_natCast, ← Real.rpow_mul (by positivity : 0 ≤ 4 * T)]
    rw [Real.mul_rpow (by positivity) hT.le]
    ring
  have hright : (T ^ d * V) ^ q⁻¹ = T ^ ((d : ℝ) * q⁻¹) * V ^ q⁻¹ := by
    rw [Real.mul_rpow (pow_nonneg hT.le _) hV.le]
    rw [← Real.rpow_natCast, ← Real.rpow_mul hT.le]
  rw [hleft, hright]
  exact hsep

/-- `ENNReal` version of `exists_large_ball_volume_gap_above`, in precisely
the form consumed by the `eLpNorm` estimates. -/
theorem exists_large_ball_volume_gap_above_ennreal
    {d : ℕ} (hd : 0 < d) {p q C M : ℝ}
    (hC : 0 < C) (hp : 0 < p) (hq : 0 < q) (hbad : p⁻¹ < q⁻¹) :
    ∃ T : ℝ, M < T ∧
      ENNReal.ofReal C * volume (ball (0 : Euclidean d) (4 * T)) ^ p⁻¹ <
        volume (ball (0 : Euclidean d) T) ^ q⁻¹ := by
  obtain ⟨T, hTM, hreal⟩ :=
    exists_large_ball_volume_gap_above hd hp hq hbad (C := C) (M := M)
  refine ⟨T, hTM, ?_⟩
  let X : ENNReal := ENNReal.ofReal C * volume (ball (0 : Euclidean d) (4 * T)) ^ p⁻¹
  let Y : ENNReal := volume (ball (0 : Euclidean d) T) ^ q⁻¹
  have hvol4top : volume (ball (0 : Euclidean d) (4 * T)) ≠ (⊤ : ENNReal) :=
    (measure_ball_lt_top (μ := volume) (x := (0 : Euclidean d))
      (r := 4 * T)).ne
  have hvolTtop : volume (ball (0 : Euclidean d) T) ≠ (⊤ : ENNReal) :=
    (measure_ball_lt_top (μ := volume) (x := (0 : Euclidean d)) (r := T)).ne
  have hXtop : X ≠ (⊤ : ENNReal) := by
    dsimp [X]
    exact ENNReal.mul_ne_top ENNReal.ofReal_ne_top
      (ENNReal.rpow_ne_top_of_nonneg (inv_nonneg.mpr hp.le) hvol4top)
  have hYtop : Y ≠ (⊤ : ENNReal) := by
    dsimp [Y]
    exact ENNReal.rpow_ne_top_of_nonneg (inv_nonneg.mpr hq.le) hvolTtop
  apply (ENNReal.toReal_lt_toReal hXtop hYtop).mp
  change X.toReal < Y.toReal
  dsimp [X, Y]
  rw [ENNReal.toReal_mul, ENNReal.toReal_ofReal hC.le,
    ← ENNReal.toReal_rpow, ← ENNReal.toReal_rpow]
  exact hreal

end

end LeanSpherical.HarmonicAnalysis.FractalDilations
