
/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.FractalDilations.ProofSkeleton

open Codex.Spherical.FractalDilations.AssouadSpectrum
open Codex.Spherical.FractalDilations.Definitions
open Codex.Spherical.FractalDilations.ExponentRegions
open Codex.Spherical.FractalDilations.Minkowski
open Codex.Spherical.FractalDilations.ProofSkeleton
open Codex.Spherical.FractalDilations.QuasiAssouadCovers
open Codex.Spherical.FractalDilations.StrongTypeExtension






/-!
# Statements of the fractal-dilation theorems

This is the formal target for the non-endpoint portions of Theorems 1 and 2
of Anderson--Hughes--Roos--Seeger, with the requested quasi-Assouad variant
of the parameter `gamma`.  The operator is first stated on the Schwartz core,
which is the core used by the existing spherical-maximal development.

The named analytic and geometric inputs live in `ProofSkeleton.lean`; this
file exposes the final public theorem names and delegates to those assemblies.
-/

namespace Codex.Spherical.FractalDilations.Theorems

open MeasureTheory Set

noncomputable section

/-- The non-endpoint strong-type assertion of Theorem 1.

The parameter `gamma` is the quasi-Assouad dimension, as requested.  The
proof skeleton is supplied by the dyadic estimates and interpolation modules.
We work in the finite Banach range (`q ≥ 1`); the boundary and
infinite-exponent conventions are outside the scope of this project.
-/
theorem theorem_one
    {d : ℕ} {β γ p q : ℝ}
    (hd : 3 ≤ d ∨ d = 2 ∧ γ ≤ 1 / 2)
    (E : Set ℝ) (hE : E ⊆ Icc (1 : ℝ) 2)
    (hβγ : 0 ≤ β ∧ β ≤ γ ∧ γ ≤ 1)
    (hMinkowski : upperMinkowskiDimension E = β)
    (hquasiAssouad : quasiAssouadDimension E = γ)
    (hp : 0 < p) (hq : 1 ≤ q)
    (hregion : reciprocalExponentPoint p q ∈ R d β γ) :
    HasFractalSphericalStrongType d E p q := by
  exact theorem_one_via_skeleton hd E hE hβγ hMinkowski hquasiAssouad hp hq hregion

/-- The representative-independent `L^p \to L^q` form of Theorem 1.

The pointwise theorem is first proved on Schwartz inputs, where the maximal
operator has a canonical representative.  The nonlinear dense-extension
lemma upgrades it to this `Lp`-class formulation whenever the finite
exponents lie in the usual Banach range. -/
theorem theorem_one_Lp
    {d : ℕ} {β γ p q : ℝ}
    (hd : 3 ≤ d ∨ d = 2 ∧ γ ≤ 1 / 2)
    (E : Set ℝ) (hE : E ⊆ Icc (1 : ℝ) 2)
    (hβγ : 0 ≤ β ∧ β ≤ γ ∧ γ ≤ 1)
    (hMinkowski : upperMinkowskiDimension E = β)
    (hquasiAssouad : quasiAssouadDimension E = γ)
    (hp : 0 < p) (_hq : 0 < q) (hpone : 1 ≤ p) (hqone : 1 ≤ q)
    (hregion : reciprocalExponentPoint p q ∈ R d β γ) :
    letI : Fact (1 ≤ ENNReal.ofReal p) :=
      ⟨by
        rw [← ENNReal.ofReal_one]
        exact ENNReal.ofReal_le_ofReal hpone⟩
    letI : Fact (1 ≤ ENNReal.ofReal q) :=
      ⟨by
        rw [← ENNReal.ofReal_one]
        exact ENNReal.ofReal_le_ofReal hqone⟩
    HasFractalSphericalLpExtension d E p q := by
  letI : Fact (1 ≤ ENNReal.ofReal p) := ⟨by
    rw [← ENNReal.ofReal_one]
    exact ENNReal.ofReal_le_ofReal hpone⟩
  letI : Fact (1 ≤ ENNReal.ofReal q) := ⟨by
    rw [← ENNReal.ofReal_one]
    exact ENNReal.ofReal_le_ofReal hqone⟩
  have hd0 : 0 < d := by
    rcases hd with hd | hd
    · omega
    · omega
  have hEpos : E ⊆ Ioi (0 : ℝ) := by
    intro r hr
    exact lt_of_lt_of_le zero_lt_one (hE hr).1
  exact HasFractalSphericalStrongType.hasLpExtension hd0 hEpos
    (theorem_one hd E hE hβγ hMinkowski hquasiAssouad hp hqone hregion)

/-- The first sharpness assertion of Theorem 2: Minkowski data alone rule
out every exponent outside `Q(β, β)`. -/
theorem theorem_two_i
    {d : ℕ} (hd : 2 ≤ d)
    (E : Set ℝ) (hE : E ⊆ Icc (1 : ℝ) 2) (hEne : E.Nonempty)
    {β p q : ℝ}
    (hβ : 0 ≤ β ∧ β ≤ 1)
    (hMinkowski : upperMinkowskiDimension E = β)
    (hp : 0 < p) (hq : 1 ≤ q)
    (houtside : reciprocalExponentPoint p q ∉ Q d β β) :
    FractalSphericalUnbounded d E p q := by
  exact theorem_two_i_via_skeleton hd E hE hEne hβ hMinkowski hp hq houtside

/-- The Assouad-spectrum sharpness assertion of Theorem 2, formulated with
the requested upper spectrum. -/
theorem theorem_two_ii
    {d : ℕ} (hd : 2 ≤ d)
    (E : Set ℝ) (hE : E ⊆ Icc (1 : ℝ) 2) (hEne : E.Nonempty)
    {β θ p q : ℝ}
    (hβ : 0 ≤ β ∧ β ≤ 1)
    (hMinkowski : upperMinkowskiDimension E = β)
    (hθ : 0 ≤ θ ∧ θ < 1)
    (hspectrum : upperAssouadSpectrum E θ = β / (1 - θ))
    (hp : 0 < p) (hq : 1 ≤ q)
    (houtside : reciprocalExponentPoint p q ∉ Q d β (β / (1 - θ))) :
    FractalSphericalUnbounded d E p q := by
  exact theorem_two_ii_via_skeleton hd E hE hEne hβ hMinkowski hθ hspectrum hp hq houtside

/-- The regular-set sharpness assertion of Theorem 2.  Here the regularity
condition uses quasi-Assouad dimension and the upper Assouad spectrum. -/
theorem theorem_two_iii
    {d : ℕ} (hd : 2 ≤ d)
    (E : Set ℝ) (hE : E ⊆ Icc (1 : ℝ) 2) (hEne : E.Nonempty)
    {β γ p q : ℝ}
    (hβγ : 0 ≤ β ∧ β ≤ γ ∧ γ ≤ 1)
    (hregular : IsQuasiAssouadRegular E β γ)
    (hp : 0 < p) (hq : 1 ≤ q)
    (houtside : reciprocalExponentPoint p q ∉ Q d β γ) :
    FractalSphericalUnbounded d E p q := by
  exact theorem_two_iii_via_skeleton hd E hE hEne hβγ hregular hp hq houtside

end

end Codex.Spherical.FractalDilations.Theorems