
/- This file was machine-generated by Codex -/

import LeanSpherical.Auto.Spherical.PowerWeights.ParameterClosure
import LeanSpherical.Auto.Spherical.PowerWeights.TypeSet

import Mathlib.Topology.Sequences
open Auto.Spherical.PowerWeights.Admissibility
open Auto.Spherical.PowerWeights.Entropy
open Auto.Spherical.PowerWeights.EntropyComparison
open Auto.Spherical.PowerWeights.ParameterClosure
open Auto.Spherical.PowerWeights.TypeSet






/-!
# Topology of the power-weight parameter region

The analytic argument supplies the finite-exponent points.  This file keeps
the elementary coordinate-limit calculations used to pass to their closure
separate from that argument.
-/

namespace Auto.Spherical.PowerWeights.ParameterTopology

open Filter Set Topology

noncomputable section

/-- Taking reciprocal of the first coordinate is continuous along a sequence
whose limit has positive first coordinate. -/
theorem tendsto_fst_inv_of_tendsto_prod
    {q : ℕ → ℝ × ℝ} {z : ℝ × ℝ}
    (hq : Tendsto q atTop (𝓝 z)) (hz : z.1 ≠ 0) :
    Tendsto (fun k => (q k).1⁻¹) atTop (𝓝 z.1⁻¹) := by
  exact ((continuous_fst.tendsto z).comp hq).inv₀ hz

/-- Dividing the second coordinate by the first is continuous along a
sequence whose limiting first coordinate is nonzero. -/
theorem tendsto_snd_div_fst_of_tendsto_prod
    {q : ℕ → ℝ × ℝ} {z : ℝ × ℝ}
    (hq : Tendsto q atTop (𝓝 z)) (hz : z.1 ≠ 0) :
    Tendsto (fun k => (q k).2 / (q k).1) atTop (𝓝 (z.2 / z.1)) := by
  exact ((continuous_snd.tendsto z).comp hq).div
    ((continuous_fst.tendsto z).comp hq) hz

/-- The finite-exponent coordinates determine the exponent and weight once
the first coordinate is positive. -/
theorem exponent_weight_eq_coordinates
    {p α x y : ℝ} (hp : 0 < p) (hx : x = p⁻¹) (hy : y = α / p) :
    p = x⁻¹ ∧ α = y / x := by
  constructor
  · rw [hx, inv_inv]
  · rw [hx, hy]
    field_simp

/-- A finite admissible point obeys the two coordinate bounds that converge
to the closed vertical face. -/
theorem powerWeightAdmissible_coordinate_bounds
    {d : ℕ} {E : Set ℝ} {q : ℝ × ℝ}
    (hE : E.Nonempty) (hEpos : E ⊆ Ioi (0 : ℝ))
    (hq : q ∈ powerWeightAdmissibleRegion d E) :
    -((d : ℝ) - 1) * q.1 ≤ q.2 ∧
      q.2 ≤ ((d : ℝ) - 1) * (1 - q.1) := by
  rcases hq with hvertical | hfinite
  · rcases hvertical with ⟨hq1, hq2⟩
    rw [hq1]
    constructor
    · simpa using hq2.1
    · simpa using hq2.2
  · rcases hfinite with ⟨p, α, hp, hq1, hq2, hcondition⟩
    have hbounds :=
      powerWeightEntropyImplicitCondition_coordinate_bounds hE hEpos hp hcondition
    rw [hq1, hq2]
    exact hbounds

/-- The first coordinate of every admissible point is nonnegative. -/
theorem powerWeightAdmissible_first_nonneg
    {d : ℕ} {E : Set ℝ} {q : ℝ × ℝ}
    (hq : q ∈ powerWeightAdmissibleRegion d E) :
    0 ≤ q.1 := by
  rcases hq with hvertical | hfinite
  · rw [hvertical.1]
  · rcases hfinite with ⟨p, α, hp, hq1, _hq2, _hcondition⟩
    rw [hq1]
    exact inv_nonneg.mpr (zero_le_one.trans hp)

/-- The affine coordinate bounds force a limit on the zero axis into the
vertical face. -/
theorem mem_verticalFace_of_tendsto_of_coordinate_bounds
    {d : ℕ} {q : ℕ → ℝ × ℝ} {z : ℝ × ℝ}
    (hq : Tendsto q atTop (𝓝 z))
    (hbound : ∀ k,
      -((d : ℝ) - 1) * (q k).1 ≤ (q k).2 ∧
        (q k).2 ≤ ((d : ℝ) - 1) * (1 - (q k).1))
    (hz : z.1 = 0) :
    z.1 = 0 ∧ z.2 ∈ Icc (0 : ℝ) ((d : ℝ) - 1) := by
  have hfst : Tendsto (fun k => (q k).1) atTop (𝓝 z.1) :=
    (continuous_fst.tendsto z).comp hq
  have hsnd : Tendsto (fun k => (q k).2) atTop (𝓝 z.2) :=
    (continuous_snd.tendsto z).comp hq
  have hlower : Tendsto (fun k => -((d : ℝ) - 1) * (q k).1)
      atTop (𝓝 (-((d : ℝ) - 1) * z.1)) := by
    simpa only [neg_mul] using (tendsto_const_nhds.mul hfst).neg
  have hupper : Tendsto (fun k => ((d : ℝ) - 1) * (1 - (q k).1))
      atTop (𝓝 (((d : ℝ) - 1) * (1 - z.1))) := by
    exact tendsto_const_nhds.mul (tendsto_const_nhds.sub hfst)
  refine ⟨hz, ?_, ?_⟩
  · have hle : -((d : ℝ) - 1) * z.1 ≤ z.2 :=
      le_of_tendsto_of_tendsto hlower hsnd
        (Filter.Eventually.of_forall fun k => (hbound k).1)
    simpa only [hz, mul_zero, neg_zero] using hle
  · have hle : z.2 ≤ ((d : ℝ) - 1) * (1 - z.1) :=
      le_of_tendsto_of_tendsto hsnd hupper
        (Filter.Eventually.of_forall fun k => (hbound k).2)
    simpa only [hz, sub_zero, mul_one] using hle

/-- Once the implicit condition is finite at one parameter, all its
Legendre--Assouad values have a real representative.  Consequently the two
real inequalities below imply the original extended-real condition. -/
theorem powerWeightEntropyImplicitCondition_of_toReal_components
    {d : ℕ} {E : Set ℝ} {p₀ α₀ p α : ℝ}
    (hE : E.Nonempty) (hEpos : E ⊆ Ioi (0 : ℝ))
    (hbase : powerWeightEntropyImplicitCondition d E p₀ α₀)
    (hleft :
      α + (multiplicativeMinkowskiExponent E).toReal ≤
        ((d : ℝ) - 1) * (p - 1))
    (hright :
      (multiplicativeLegendreAssouadExponent E
        (((d : ℝ) - 1) * (p - 2) - α)).toReal ≤
        ((d : ℝ) - 1) * (p - 1)) :
    powerWeightEntropyImplicitCondition d E p α := by
  let ρ₀ : ℝ := ((d : ℝ) - 1) * (p₀ - 2) - α₀
  let T₀ : ℝ := ((d : ℝ) - 1) * (p₀ - 1)
  let ρ : ℝ := ((d : ℝ) - 1) * (p - 2) - α
  let T : ℝ := ((d : ℝ) - 1) * (p - 1)
  have hν₀ : multiplicativeLegendreAssouadExponent E ρ₀ ≤ (T₀ : EReal) := by
    simpa only [ρ₀, T₀] using powerWeightEntropyImplicitCondition_right hbase
  have hβle :
      multiplicativeMinkowskiExponent E ≤
        multiplicativeLegendreAssouadExponent E ρ₀ :=
    multiplicativeMinkowskiExponent_le_multiplicativeLegendreAssouadExponent E ρ₀
  have hβtop : multiplicativeMinkowskiExponent E ≠ ⊤ :=
    ne_top_of_le_ne_top (EReal.coe_ne_top T₀) (hβle.trans hν₀)
  have hβnonneg : (0 : EReal) ≤ multiplicativeMinkowskiExponent E :=
    multiplicativeMinkowskiExponent_nonneg_of_nonempty_of_subset_Ioi hE hEpos
  have hβbot : multiplicativeMinkowskiExponent E ≠ ⊥ := by
    intro hbot
    rw [hbot] at hβnonneg
    exact (not_le_of_gt (EReal.bot_lt_coe 0)) hβnonneg
  have hνtop (u : ℝ) : multiplicativeLegendreAssouadExponent E u ≠ ⊤ :=
    multiplicativeLegendreAssouadExponent_ne_top_of_le_at hν₀ u
  have hνbot (u : ℝ) : multiplicativeLegendreAssouadExponent E u ≠ ⊥ :=
    multiplicativeLegendreAssouadExponent_ne_bot_of_nonempty_of_subset_Ioi hE hEpos u
  have hleftE :
      (α : EReal) + multiplicativeMinkowskiExponent E ≤ (T : EReal) := by
    have hsumtop : (α : EReal) + multiplicativeMinkowskiExponent E ≠ ⊤ :=
      EReal.add_ne_top (EReal.coe_ne_top _) hβtop
    have hsumbot : (α : EReal) + multiplicativeMinkowskiExponent E ≠ ⊥ :=
      EReal.add_ne_bot_iff.mpr ⟨EReal.coe_ne_bot _, hβbot⟩
    rw [← EReal.coe_toReal hsumtop hsumbot,
      EReal.toReal_add (EReal.coe_ne_top _) (EReal.coe_ne_bot _) hβtop hβbot]
    exact EReal.coe_le_coe (by
      simpa only [EReal.toReal_coe, T] using hleft)
  have hrightE : multiplicativeLegendreAssouadExponent E ρ ≤ (T : EReal) := by
    rw [← EReal.coe_toReal (hνtop ρ) (hνbot ρ)]
    exact EReal.coe_le_coe (by simpa only [ρ, T] using hright)
  exact max_le (by simpa only [T] using hleftE) (by simpa only [ρ, T] using hrightE)

/-- The implicit condition is stable under finite-parameter limits once it
holds at one finite parameter.  The latter hypothesis supplies the
finiteness needed to use the Lipschitz entropy representative. -/
theorem powerWeightEntropyImplicitCondition_of_tendsto
    {d : ℕ} {E : Set ℝ} {p₀ α₀ p α : ℝ}
    (hE : E.Nonempty) (hEpos : E ⊆ Ioi (0 : ℝ))
    (hbase : powerWeightEntropyImplicitCondition d E p₀ α₀)
    {u v : ℕ → ℝ}
    (hu : Tendsto u atTop (𝓝 p)) (hv : Tendsto v atTop (𝓝 α))
    (hcondition : ∀ k, powerWeightEntropyImplicitCondition d E (u k) (v k)) :
    powerWeightEntropyImplicitCondition d E p α := by
  let ρ₀ : ℝ := ((d : ℝ) - 1) * (p₀ - 2) - α₀
  let T₀ : ℝ := ((d : ℝ) - 1) * (p₀ - 1)
  let ρ : ℝ := ((d : ℝ) - 1) * (p - 2) - α
  let T : ℝ := ((d : ℝ) - 1) * (p - 1)
  have hν₀ : multiplicativeLegendreAssouadExponent E ρ₀ ≤ (T₀ : EReal) := by
    simpa only [ρ₀, T₀] using powerWeightEntropyImplicitCondition_right hbase
  have hβle :
      multiplicativeMinkowskiExponent E ≤
        multiplicativeLegendreAssouadExponent E ρ₀ :=
    multiplicativeMinkowskiExponent_le_multiplicativeLegendreAssouadExponent E ρ₀
  have hβtop : multiplicativeMinkowskiExponent E ≠ ⊤ :=
    ne_top_of_le_ne_top (EReal.coe_ne_top T₀) (hβle.trans hν₀)
  have hβnonneg : (0 : EReal) ≤ multiplicativeMinkowskiExponent E :=
    multiplicativeMinkowskiExponent_nonneg_of_nonempty_of_subset_Ioi hE hEpos
  have hβbot : multiplicativeMinkowskiExponent E ≠ ⊥ := by
    intro hbot
    rw [hbot] at hβnonneg
    exact (not_le_of_gt (EReal.bot_lt_coe 0)) hβnonneg
  have hνbot (w : ℝ) : multiplicativeLegendreAssouadExponent E w ≠ ⊥ :=
    multiplicativeLegendreAssouadExponent_ne_bot_of_nonempty_of_subset_Ioi hE hEpos w
  have hLip :
      LipschitzWith 1 (fun w : ℝ =>
        (multiplicativeLegendreAssouadExponent E w).toReal) :=
    multiplicativeLegendreAssouadExponent_toReal_lipschitzWith_one_of_le_at
      hE hEpos hν₀
  have hleft_each (k : ℕ) :
      v k + (multiplicativeMinkowskiExponent E).toReal ≤
        ((d : ℝ) - 1) * (u k - 1) := by
    have hsum :=
      powerWeightEntropyImplicitCondition_left (hcondition k)
    have hsumtop : (v k : EReal) + multiplicativeMinkowskiExponent E ≠ ⊤ :=
      EReal.add_ne_top (EReal.coe_ne_top _) hβtop
    have hsumbot : (v k : EReal) + multiplicativeMinkowskiExponent E ≠ ⊥ :=
      EReal.add_ne_bot_iff.mpr ⟨EReal.coe_ne_bot _, hβbot⟩
    have hreal := EReal.toReal_le_toReal hsum hsumbot (EReal.coe_ne_top _)
    rw [EReal.toReal_add (EReal.coe_ne_top _) (EReal.coe_ne_bot _) hβtop hβbot,
      EReal.toReal_coe] at hreal
    exact hreal
  have hright_each (k : ℕ) :
      (multiplicativeLegendreAssouadExponent E
        (((d : ℝ) - 1) * (u k - 2) - v k)).toReal ≤
        ((d : ℝ) - 1) * (u k - 1) := by
    have hright :=
      powerWeightEntropyImplicitCondition_right (hcondition k)
    have hreal := EReal.toReal_le_toReal hright
      (hνbot (((d : ℝ) - 1) * (u k - 2) - v k)) (EReal.coe_ne_top _)
    exact hreal
  have hT : Tendsto (fun k => ((d : ℝ) - 1) * (u k - 1))
      atTop (𝓝 T) := by
    exact tendsto_const_nhds.mul (hu.sub tendsto_const_nhds)
  have hleft_lim :
      α + (multiplicativeMinkowskiExponent E).toReal ≤ T := by
    apply le_of_tendsto_of_tendsto (hv.add tendsto_const_nhds) hT
    exact Filter.Eventually.of_forall hleft_each
  have hρ : Tendsto (fun k => ((d : ℝ) - 1) * (u k - 2) - v k)
      atTop (𝓝 ρ) := by
    exact (tendsto_const_nhds.mul (hu.sub tendsto_const_nhds)).sub hv
  have hν : Tendsto (fun k =>
      (multiplicativeLegendreAssouadExponent E
        (((d : ℝ) - 1) * (u k - 2) - v k)).toReal)
      atTop (𝓝 (multiplicativeLegendreAssouadExponent E ρ).toReal) :=
    (hLip.continuous.tendsto ρ).comp hρ
  have hright_lim :
      (multiplicativeLegendreAssouadExponent E ρ).toReal ≤ T := by
    apply le_of_tendsto_of_tendsto hν hT
    exact Filter.Eventually.of_forall hright_each
  exact powerWeightEntropyImplicitCondition_of_toReal_components hE hEpos hbase
    (by simpa only [T] using hleft_lim)
    (by simpa only [ρ, T] using hright_lim)

/-- The implicit parameter region, including its limiting vertical face, is
closed.  The proof uses the affine bounds for the zero-axis case and the
Lipschitz entropy representative at positive first coordinate. -/
theorem isClosed_powerWeightAdmissibleRegion
    {d : ℕ} {E : Set ℝ}
    (hE : E.Nonempty) (hEpos : E ⊆ Ioi (0 : ℝ)) :
    IsClosed (powerWeightAdmissibleRegion d E) := by
  apply IsSeqClosed.isClosed
  intro q z hq hqz
  have hfst : Tendsto (fun k => (q k).1) atTop (𝓝 z.1) :=
    (continuous_fst.tendsto z).comp hqz
  have hnonnegSeq : ∀ᶠ k in atTop, (0 : ℝ) ≤ (q k).1 :=
    Filter.Eventually.of_forall fun k =>
      powerWeightAdmissible_first_nonneg (d := d) (E := E) (q := q k) (hq k)
  have hnonneg : 0 ≤ z.1 :=
    ge_of_tendsto hfst hnonnegSeq
  by_cases hzzero : z.1 = 0
  · exact Or.inl <|
      mem_verticalFace_of_tendsto_of_coordinate_bounds hqz
        (fun k => powerWeightAdmissible_coordinate_bounds hE hEpos (hq k)) hzzero
  have hzpos : 0 < z.1 := lt_of_le_of_ne hnonneg (Ne.symm hzzero)
  have hpos_event : ∀ᶠ k in atTop, 0 < (q k).1 :=
    hfst.eventually (eventually_gt_nhds hzpos)
  rcases eventually_atTop.1 hpos_event with ⟨K, hK⟩
  have hKfinite :
      ∃ p α : ℝ, 1 ≤ p ∧ (q K).1 = p⁻¹ ∧ (q K).2 = α / p ∧
        powerWeightEntropyImplicitCondition d E p α := by
    rcases hq K with hvertical | hfinite
    · exfalso
      change (q K).1 = 0 ∧ (q K).2 ∈ Icc (0 : ℝ) ((d : ℝ) - 1) at hvertical
      have hposK := hK K le_rfl
      rw [hvertical.1] at hposK
      exact (lt_irrefl (0 : ℝ)) hposK
    · exact hfinite
  rcases hKfinite with ⟨p₀, α₀, hp₀, hK1, hK2, hbase⟩
  let q' : ℕ → ℝ × ℝ := fun k => q (k + K)
  have hq' : Tendsto q' atTop (𝓝 z) :=
    hqz.comp (tendsto_add_atTop_nat K)
  have hq'pos (k : ℕ) : 0 < (q' k).1 := hK (k + K) (Nat.le_add_left K k)
  have hq'finite (k : ℕ) :
      ∃ p α : ℝ, 1 ≤ p ∧ (q' k).1 = p⁻¹ ∧ (q' k).2 = α / p ∧
        powerWeightEntropyImplicitCondition d E p α := by
    rcases hq (k + K) with hvertical | hfinite
    · exfalso
      change (q (k + K)).1 = 0 ∧
        (q (k + K)).2 ∈ Icc (0 : ℝ) ((d : ℝ) - 1) at hvertical
      have hpos := hq'pos k
      change 0 < (q (k + K)).1 at hpos
      rw [hvertical.1] at hpos
      exact (lt_irrefl (0 : ℝ)) hpos
    · exact hfinite
  let u : ℕ → ℝ := fun k => (q' k).1⁻¹
  let v : ℕ → ℝ := fun k => (q' k).2 / (q' k).1
  have hu : Tendsto u atTop (𝓝 z.1⁻¹) := by
    simpa only [u] using tendsto_fst_inv_of_tendsto_prod hq' hzzero
  have hv : Tendsto v atTop (𝓝 (z.2 / z.1)) := by
    simpa only [v] using tendsto_snd_div_fst_of_tendsto_prod hq' hzzero
  have hu_one (k : ℕ) : 1 ≤ u k := by
    rcases hq'finite k with ⟨pk, ak, hpk, hk1, hk2, hkcondition⟩
    have hpk0 : 0 < pk := lt_of_lt_of_le zero_lt_one hpk
    have hcoord := exponent_weight_eq_coordinates hpk0 hk1 hk2
    simpa only [u, hcoord.1] using hpk
  have hcondition (k : ℕ) :
      powerWeightEntropyImplicitCondition d E (u k) (v k) := by
    rcases hq'finite k with ⟨pk, ak, hpk, hk1, hk2, hkcondition⟩
    have hpk0 : 0 < pk := lt_of_lt_of_le zero_lt_one hpk
    have hcoord := exponent_weight_eq_coordinates hpk0 hk1 hk2
    simpa only [u, v, hcoord.1, hcoord.2] using hkcondition
  have hlimit :
      powerWeightEntropyImplicitCondition d E z.1⁻¹ (z.2 / z.1) :=
    powerWeightEntropyImplicitCondition_of_tendsto hE hEpos hbase hu hv hcondition
  have hp_limit : 1 ≤ z.1⁻¹ :=
    ge_of_tendsto hu (Filter.Eventually.of_forall hu_one)
  refine Or.inr ⟨z.1⁻¹, z.2 / z.1, hp_limit, ?_, ?_, hlimit⟩
  · simp only [inv_inv]
  · field_simp

/-- The analytic necessary condition gives the easy inclusion of the
closure of the strong-type set into the closed admissible region. -/
theorem closure_typeSet_subset_powerWeightAdmissibleRegion_of_necessary
    {d : ℕ} {E : Set ℝ}
    (hE : E.Nonempty) (hEpos : E ⊆ Ioi (0 : ℝ))
    (hnecessary : ∀ ⦃p α : ℝ⦄, 1 ≤ p →
      HasRestrictedNormalizedSphericalMaximalPowerWeightStrongType d E p α →
        powerWeightEntropyImplicitCondition d E p α) :
    closure (restrictedNormalizedSphericalMaximalPowerWeightTypeSet d E) ⊆
      powerWeightAdmissibleRegion d E := by
  apply closure_minimal
  · intro q hq
    rcases hq with ⟨p, α, hp, hq1, hq2, hstrong⟩
    exact Or.inr ⟨p, α, hp, hq1, hq2, hnecessary hp hstrong⟩
  · exact isClosed_powerWeightAdmissibleRegion hE hEpos

end

end Auto.Spherical.PowerWeights.ParameterTopology