
/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.SurfaceCore

import Mathlib.Analysis.SpecialFunctions.PolarCoord
import Mathlib.MeasureTheory.Integral.Prod
import Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls
import Mathlib.Analysis.Complex.Trigonometric
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Inverse
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv
import Mathlib.MeasureTheory.Function.JacobianOneDim
import Mathlib.MeasureTheory.Integral.IntervalIntegral.IntegrationByParts
open Codex.Spherical.SurfaceCore






/-!
# Coordinate and polar-integration prerequisites

This module collects the cylindrical, spherical, polar, radial, and
height-coordinate integration formulas used by surface-measure analysis.
-/

namespace Codex.Spherical.CoordinateIntegration

open MeasureTheory
open scoped ENNReal

noncomputable section

/-- Fubini followed by polar coordinates in the horizontal plane. -/
theorem integral_cylindrical
    (F : ℂ × ℝ → ℂ) (hF : Integrable F ((volume : Measure ℂ).prod volume)) :
    (∫ x : ℂ × ℝ, F x ∂((volume : Measure ℂ).prod volume)) =
      ∫ p in Complex.polarCoord.target,
        p.1 • (∫ z : ℝ, F (Complex.polarCoord.symm p, z) ∂volume) ∂volume := by
  calc
    (∫ x : ℂ × ℝ, F x ∂((volume : Measure ℂ).prod volume)) =
        ∫ w : ℂ, (∫ z : ℝ, F (w, z) ∂volume) ∂volume :=
      integral_prod F hF
    _ = ∫ p in Complex.polarCoord.target,
        p.1 • (∫ z : ℝ, F (Complex.polarCoord.symm p, z) ∂volume) ∂volume := by
      symm
      exact Complex.integral_comp_polarCoord_symm
        (fun w : ℂ => ∫ z : ℝ, F (w, z) ∂volume)

/-- The nonnegative version of `integral_cylindrical`, suitable for computing
volumes of cones by Tonelli's theorem. -/
theorem lintegral_cylindrical
    (F : ℂ × ℝ → ℝ≥0∞) (hF : Measurable F) :
    (∫⁻ x : ℂ × ℝ, F x ∂((volume : Measure ℂ).prod volume)) =
      ∫⁻ p in Complex.polarCoord.target,
        ENNReal.ofReal p.1 *
          (∫⁻ z : ℝ, F (Complex.polarCoord.symm p, z) ∂volume) ∂volume := by
  calc
    (∫⁻ x : ℂ × ℝ, F x ∂((volume : Measure ℂ).prod volume)) =
        ∫⁻ w : ℂ, (∫⁻ z : ℝ, F (w, z) ∂volume) ∂volume :=
      lintegral_prod F hF.aemeasurable
    _ = ∫⁻ p in Complex.polarCoord.target,
        ENNReal.ofReal p.1 *
          (∫⁻ z : ℝ, F (Complex.polarCoord.symm p, z) ∂volume) ∂volume := by
      symm
      exact Complex.lintegral_comp_polarCoord_symm
        (fun w : ℂ => ∫⁻ z : ℝ, F (w, z) ∂volume)

end

end Codex.Spherical.CoordinateIntegration

namespace Codex.Spherical.CoordinateIntegration

open MeasureTheory Set
open scoped ENNReal

noncomputable section

/-- Polar coordinates on the upper half-plane.  The input coordinate order is
`(vertical, horizontal)`, so the horizontal coordinate is `rho * sin phi`. -/
theorem lintegral_meridian_halfPlane
    (F : ℝ × ℝ → ℝ≥0∞) :
    (∫⁻ q in Set.univ ×ˢ Set.Ioi (0 : ℝ), F q) =
      ∫⁻ p in Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi,
        ENNReal.ofReal p.1 * F (polarCoord.symm p) := by
  rw [← lintegral_indicator (MeasurableSet.univ.prod measurableSet_Ioi) F]
  rw [← lintegral_comp_polarCoord_symm
    ((Set.univ ×ˢ Set.Ioi (0 : ℝ)).indicator F)]
  rw [← lintegral_indicator polarCoord.open_target.measurableSet]
  rw [← lintegral_indicator (measurableSet_Ioi.prod measurableSet_Ioo)]
  apply lintegral_congr
  intro p
  by_cases hp : p ∈ polarCoord.target
  · rw [Set.indicator_of_mem hp]
    have hmem : polarCoord.symm p ∈ Set.univ ×ˢ Set.Ioi (0 : ℝ) ↔
        p ∈ Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi := by
      rw [polarCoord_symm_apply]
      simp only [Set.mem_prod, mem_univ, true_and, mem_Ioi, mem_Ioo]
      change 0 < p.1 * Real.sin p.2 ↔ 0 < p.1 ∧ 0 < p.2 ∧ p.2 < Real.pi
      rw [polarCoord_target] at hp
      change 0 < p.1 ∧ -Real.pi < p.2 ∧ p.2 < Real.pi at hp
      constructor
      · intro h
        refine ⟨hp.1, ?_, hp.2.2⟩
        by_contra hphi
        have hsin : Real.sin p.2 ≤ 0 :=
          Real.sin_nonpos_of_nonpos_of_neg_pi_le (le_of_not_gt hphi) hp.2.1.le
        exact (not_lt_of_ge (mul_nonpos_of_nonneg_of_nonpos hp.1.le hsin)) h
      · rintro ⟨_, hphi, _⟩
        exact mul_pos hp.1 (Real.sin_pos_of_pos_of_lt_pi hphi hp.2.2)
    by_cases hp' : p ∈ Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi
    · rw [Set.indicator_of_mem hp' _, Set.indicator_of_mem (hmem.mpr hp') _]
      exact smul_eq_mul _ _
    · rw [Set.indicator_of_notMem hp' _, Set.indicator_of_notMem (mt hmem.mp hp') _]
      simp
  · rw [Set.indicator_of_notMem hp _]
    have hp' : p ∉ Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi := by
      intro h
      exact hp (by
        rw [polarCoord_target]
        change 0 < p.1 ∧ -Real.pi < p.2 ∧ p.2 < Real.pi
        change 0 < p.1 ∧ 0 < p.2 ∧ p.2 < Real.pi at h
        exact ⟨h.1, by linarith [Real.pi_pos], h.2.2⟩)
    rw [Set.indicator_of_notMem hp' _]

/-- Combining the meridian polar Jacobian with the horizontal-radius factor
from cylindrical coordinates gives the spherical density
`rho * (rho * sin phi)`. -/
theorem lintegral_meridian_cylindrical_density
    (G : ℝ × ℝ → ℝ≥0∞) :
    (∫⁻ q in Set.univ ×ˢ Set.Ioi (0 : ℝ),
      ENNReal.ofReal q.2 * G (q.2, q.1)) =
      ∫⁻ p in Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi,
        ENNReal.ofReal p.1 * ENNReal.ofReal (p.1 * Real.sin p.2) *
          G (p.1 * Real.sin p.2, p.1 * Real.cos p.2) := by
  simpa only [polarCoord_symm_apply, mul_assoc] using
    (lintegral_meridian_halfPlane
      (fun q : ℝ × ℝ => ENNReal.ofReal q.2 * G (q.2, q.1)))

/-- The Bochner polar-coordinate transport on the meridian half-plane.  It
is unconditional because the underlying polar change-of-variables theorem is
stated for the Bochner integral itself. -/
theorem integral_meridian_halfPlane
    (F : ℝ × ℝ → ℂ) :
    (∫ q in Set.univ ×ˢ Set.Ioi (0 : ℝ), F q) =
      ∫ p in Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi,
        p.1 • F (polarCoord.symm p) := by
  rw [← integral_indicator (MeasurableSet.univ.prod measurableSet_Ioi)]
  rw [← integral_comp_polarCoord_symm
    ((Set.univ ×ˢ Set.Ioi (0 : ℝ)).indicator F)]
  rw [← integral_indicator polarCoord.open_target.measurableSet]
  rw [← integral_indicator (measurableSet_Ioi.prod measurableSet_Ioo)]
  apply integral_congr_ae
  filter_upwards with p
  by_cases hp : p ∈ polarCoord.target
  · rw [Set.indicator_of_mem hp]
    have hmem : polarCoord.symm p ∈ Set.univ ×ˢ Set.Ioi (0 : ℝ) ↔
        p ∈ Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi := by
      rw [polarCoord_symm_apply]
      simp only [Set.mem_prod, mem_univ, true_and, mem_Ioi, mem_Ioo]
      change 0 < p.1 * Real.sin p.2 ↔ 0 < p.1 ∧ 0 < p.2 ∧ p.2 < Real.pi
      rw [polarCoord_target] at hp
      change 0 < p.1 ∧ -Real.pi < p.2 ∧ p.2 < Real.pi at hp
      constructor
      · intro h
        refine ⟨hp.1, ?_, hp.2.2⟩
        by_contra hphi
        have hsin : Real.sin p.2 ≤ 0 :=
          Real.sin_nonpos_of_nonpos_of_neg_pi_le (le_of_not_gt hphi) hp.2.1.le
        exact (not_lt_of_ge (mul_nonpos_of_nonneg_of_nonpos hp.1.le hsin)) h
      · rintro ⟨_, hphi, _⟩
        exact mul_pos hp.1 (Real.sin_pos_of_pos_of_lt_pi hphi hp.2.2)
    by_cases hp' : p ∈ Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi
    · rw [Set.indicator_of_mem hp' _, Set.indicator_of_mem (hmem.mpr hp') _]
    · rw [Set.indicator_of_notMem hp' _, Set.indicator_of_notMem (mt hmem.mp hp') _]
      simp
  · rw [Set.indicator_of_notMem hp _]
    have hp' : p ∉ Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi := by
      intro h
      exact hp (by
        rw [polarCoord_target]
        change 0 < p.1 ∧ -Real.pi < p.2 ∧ p.2 < Real.pi
        change 0 < p.1 ∧ 0 < p.2 ∧ p.2 < Real.pi at h
        exact ⟨h.1, by linarith [Real.pi_pos], h.2.2⟩)
    rw [Set.indicator_of_notMem hp' _]

/-- Combining the meridian Jacobian with the horizontal cylindrical factor
gives the complex-valued spherical density `ρ * (ρ * sin φ)`. -/
theorem integral_meridian_cylindrical_density
    (G : ℝ × ℝ → ℂ) :
    (∫ q in Set.univ ×ˢ Set.Ioi (0 : ℝ),
      (q.2 : ℂ) * G (q.2, q.1)) =
      ∫ p in Set.Ioi (0 : ℝ) ×ˢ Set.Ioo (0 : ℝ) Real.pi,
        (p.1 : ℂ) * ((p.1 * Real.sin p.2 : ℝ) : ℂ) *
          G (p.1 * Real.sin p.2, p.1 * Real.cos p.2) := by
  simpa only [polarCoord_symm_apply, Complex.real_smul, mul_assoc] using
    (integral_meridian_halfPlane
      (fun q : ℝ × ℝ => (q.2 : ℂ) * G (q.2, q.1)))

end

end Codex.Spherical.CoordinateIntegration

namespace Codex.Spherical.CoordinateIntegration

open MeasureTheory Set
open scoped ENNReal

noncomputable section

/-- Integrating a nonnegative measurable function independent of the
azimuthal variable over the full angular interval contributes a factor
`2π`. -/
theorem lintegral_Ioi_prod_Ioo_angle_factor
    (F : ℝ → ℝ≥0∞) (hF : Measurable F) :
    (∫⁻ p in Ioi (0 : ℝ) ×ˢ Ioo (-Real.pi) Real.pi,
      F p.1 ∂((volume : Measure ℝ).prod volume)) =
      ENNReal.ofReal (2 * Real.pi) * ∫⁻ r in Ioi (0 : ℝ), F r := by
  calc
    (∫⁻ p in Ioi (0 : ℝ) ×ˢ Ioo (-Real.pi) Real.pi,
      F p.1 ∂((volume : Measure ℝ).prod volume)) =
        ∫⁻ r in Ioi (0 : ℝ), ∫⁻ θ in Ioo (-Real.pi) Real.pi,
          F r ∂volume ∂volume := by
      apply setLIntegral_prod
      exact (hF.comp measurable_fst).aemeasurable
    _ = ∫⁻ r in Ioi (0 : ℝ), F r * volume (Ioo (-Real.pi) Real.pi) ∂volume := by
      apply lintegral_congr
      intro r
      simp [lintegral_const]
    _ = (∫⁻ r in Ioi (0 : ℝ), F r ∂volume) * volume (Ioo (-Real.pi) Real.pi) := by
      exact lintegral_mul_const _ hF
    _ = ENNReal.ofReal (2 * Real.pi) * ∫⁻ r in Ioi (0 : ℝ), F r := by
      rw [Real.volume_Ioo]
      have hangle : Real.pi - -Real.pi = 2 * Real.pi := by ring
      rw [hangle, mul_comm]

/-- The Bochner counterpart of the angular factorization.  The radial input
is assumed integrable on `(0, ∞)`, which is exactly what Fubini needs on the
product with the finite angular interval. -/
theorem integral_Ioi_prod_Ioo_angle_factor
    (F : ℝ → ℂ) (hF : IntegrableOn F (Ioi (0 : ℝ)) volume) :
    (∫ p in Ioi (0 : ℝ) ×ˢ Ioo (-Real.pi) Real.pi,
      F p.1 ∂((volume : Measure ℝ).prod volume)) =
      ((2 * Real.pi : ℝ) : ℂ) * ∫ r in Ioi (0 : ℝ), F r := by
  have hprod : IntegrableOn (fun p : ℝ × ℝ => F p.1)
      (Ioi (0 : ℝ) ×ˢ Ioo (-Real.pi) Real.pi) ((volume : Measure ℝ).prod volume) := by
    rw [IntegrableOn, ← Measure.prod_restrict]
    exact hF.comp_fst (volume.restrict (Ioo (-Real.pi) Real.pi))
  have hangle : (volume : Measure ℝ).real (Ioo (-Real.pi) Real.pi) = 2 * Real.pi := by
    rw [Measure.real, Real.volume_Ioo]
    calc
      (ENNReal.ofReal (Real.pi - -Real.pi)).toReal = Real.pi - -Real.pi :=
        ENNReal.toReal_ofReal (by linarith [Real.pi_pos])
      _ = 2 * Real.pi := by ring
  calc
    (∫ p in Ioi (0 : ℝ) ×ˢ Ioo (-Real.pi) Real.pi,
      F p.1 ∂((volume : Measure ℝ).prod volume)) =
        ∫ r in Ioi (0 : ℝ), ∫ θ in Ioo (-Real.pi) Real.pi, F r ∂volume ∂volume := by
      exact setIntegral_prod _ hprod
    _ = ∫ r in Ioi (0 : ℝ), ((2 * Real.pi : ℝ) : ℂ) * F r ∂volume := by
      apply integral_congr_ae
      filter_upwards with r
      rw [setIntegral_const, hangle, Complex.real_smul]
    _ = ((2 * Real.pi : ℝ) : ℂ) * ∫ r in Ioi (0 : ℝ), F r := by
      rw [integral_const_mul]

end

end Codex.Spherical.CoordinateIntegration

namespace Codex.Spherical.CoordinateIntegration

open MeasureTheory Set
open scoped ENNReal

noncomputable section

/-- Lebesgue integration in `ℂ × ℝ`, for functions depending on the horizontal
coordinate only through its radius, is the usual three-dimensional spherical
coordinate integral. -/
theorem lintegral_threeDimensional_spherical
    (G : ℝ × ℝ → ℝ≥0∞) (hG : Measurable G) :
    (∫⁻ y : ℂ × ℝ, G (‖y.1‖, y.2) ∂((volume : Measure ℂ).prod volume)) =
      ENNReal.ofReal (2 * Real.pi) *
        ∫⁻ p in Ioi (0 : ℝ) ×ˢ Ioo (0 : ℝ) Real.pi,
          ENNReal.ofReal p.1 * ENNReal.ofReal (p.1 * Real.sin p.2) *
            G (p.1 * Real.sin p.2, p.1 * Real.cos p.2) := by
  have hF : Measurable (fun y : ℂ × ℝ => G (‖y.1‖, y.2)) :=
    hG.comp ((measurable_norm.comp measurable_fst).prodMk measurable_snd)
  have hRadial : Measurable (fun r : ℝ =>
      ENNReal.ofReal r * ∫⁻ z : ℝ, G (r, z)) :=
    measurable_id.ennreal_ofReal.mul hG.lintegral_prod_right'
  have hMeridian : Measurable (fun q : ℝ × ℝ =>
      ENNReal.ofReal q.2 * G (q.2, q.1)) :=
    (measurable_snd.ennreal_ofReal).mul
      (hG.comp (measurable_snd.prodMk measurable_fst))
  calc
    (∫⁻ y : ℂ × ℝ, G (‖y.1‖, y.2) ∂((volume : Measure ℂ).prod volume)) =
        ∫⁻ p in Complex.polarCoord.target,
          ENNReal.ofReal p.1 *
            (∫⁻ z : ℝ, G (‖Complex.polarCoord.symm p‖, z)) :=
      lintegral_cylindrical _ hF
    _ = ∫⁻ p in Ioi (0 : ℝ) ×ˢ Ioo (-Real.pi) Real.pi,
          ENNReal.ofReal p.1 *
            (∫⁻ z : ℝ, G (‖Complex.polarCoord.symm p‖, z)) := by
      rw [Complex.polarCoord_target]
    _ = ∫⁻ p in Ioi (0 : ℝ) ×ˢ Ioo (-Real.pi) Real.pi,
          ENNReal.ofReal p.1 * (∫⁻ z : ℝ, G (p.1, z)) := by
      apply setLIntegral_congr_fun (measurableSet_Ioi.prod measurableSet_Ioo)
      intro p hp
      have hp0 : 0 < p.1 := hp.1
      simp [abs_of_pos hp0]
    _ = ENNReal.ofReal (2 * Real.pi) *
          ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r * ∫⁻ z : ℝ, G (r, z) :=
      lintegral_Ioi_prod_Ioo_angle_factor _ hRadial
    _ = ENNReal.ofReal (2 * Real.pi) *
          ∫⁻ q in Set.univ ×ˢ Ioi (0 : ℝ),
            ENNReal.ofReal q.2 * G (q.2, q.1) := by
      congr 1
      calc
        (∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r * ∫⁻ z : ℝ, G (r, z)) =
            ∫⁻ r in Ioi (0 : ℝ), ∫⁻ z : ℝ, ENNReal.ofReal r * G (r, z) := by
          apply setLIntegral_congr_fun measurableSet_Ioi
          intro r hr
          change ENNReal.ofReal r * (∫⁻ z : ℝ, G (r, z)) =
            ∫⁻ z : ℝ, ENNReal.ofReal r * G (r, z)
          exact (lintegral_const_mul (μ := volume) (ENNReal.ofReal r)
            (hG.comp (measurable_const.prodMk measurable_id))).symm
        _ = ∫⁻ q in Set.univ ×ˢ Ioi (0 : ℝ),
            ENNReal.ofReal q.2 * G (q.2, q.1) := by
          symm
          change
            (∫⁻ q in Set.univ ×ˢ Ioi (0 : ℝ),
              ENNReal.ofReal q.2 * G (q.2, q.1) ∂((volume : Measure ℝ).prod volume)) =
            ∫⁻ r in Ioi (0 : ℝ), ∫⁻ z : ℝ, ENNReal.ofReal r * G (r, z)
          simpa using
            (setLIntegral_prod_symm (μ := volume) (ν := volume)
              (s := Set.univ) (t := Ioi (0 : ℝ))
              (fun q : ℝ × ℝ => ENNReal.ofReal q.2 * G (q.2, q.1))
              hMeridian.aemeasurable.restrict)
    _ = ENNReal.ofReal (2 * Real.pi) *
          ∫⁻ p in Ioi (0 : ℝ) ×ˢ Ioo (0 : ℝ) Real.pi,
            ENNReal.ofReal p.1 * ENNReal.ofReal (p.1 * Real.sin p.2) *
              G (p.1 * Real.sin p.2, p.1 * Real.cos p.2) := by
      rw [lintegral_meridian_cylindrical_density]

/-- The Euclidean radius of the meridian coordinates `(ρ sin φ, ρ cos φ)` is
`ρ` when `ρ` is nonnegative. -/
theorem sqrt_spherical_meridian_norm_sq (ρ φ : ℝ) (hρ : 0 ≤ ρ) :
    Real.sqrt ((ρ * Real.sin φ) ^ 2 + (ρ * Real.cos φ) ^ 2) = ρ := by
  rw [show (ρ * Real.sin φ) ^ 2 + (ρ * Real.cos φ) ^ 2 = ρ ^ 2 by
    calc
      (ρ * Real.sin φ) ^ 2 + (ρ * Real.cos φ) ^ 2 =
          ρ ^ 2 * (Real.sin φ ^ 2 + Real.cos φ ^ 2) := by ring
      _ = ρ ^ 2 := by rw [Real.sin_sq_add_cos_sq, mul_one]]
  simpa [abs_of_nonneg hρ] using (Real.sqrt_sq_eq_abs ρ)

/-- In meridian spherical coordinates, normalizing the vertical coordinate
returns `cos φ` away from the origin. -/
theorem spherical_normalized_vertical_eq_cos (ρ φ : ℝ) (hρ : 0 < ρ) :
    (ρ * Real.cos φ) /
        Real.sqrt ((ρ * Real.sin φ) ^ 2 + (ρ * Real.cos φ) ^ 2) = Real.cos φ := by
  rw [sqrt_spherical_meridian_norm_sq ρ φ hρ.le]
  field_simp

end

end Codex.Spherical.CoordinateIntegration

namespace Codex.Spherical.CoordinateIntegration

open MeasureTheory Metric Set

noncomputable section

/-- Polar decomposition of Lebesgue integration in positive Euclidean
dimension, using the concrete `unitSurfaceMeasure`.  The radial factor is
`Measure.volumeIoiPow (d - 1)`, i.e. Lebesgue measure on positive radii with
density `r ^ (d - 1)`. -/
theorem integral_polar_unitSurfaceMeasure {d : ℕ} (hd : 0 < d)
    (H : Euclidean d → ℂ) :
    (∫ x : Euclidean d, H x) =
      ∫ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
        H (p.2.1 • (p.1 : Euclidean d)) ∂
          ((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) := by
  let i : Fin d := ⟨0, hd⟩
  letI : Nonempty (Fin d) := ⟨i⟩
  calc
    (∫ x : Euclidean d, H x) =
        ∫ x : ({0}ᶜ : Set (Euclidean d)), H x.1 ∂
          ((volume : Measure (Euclidean d)).comap (↑)) := by
      rw [integral_subtype_comap (measurableSet_singleton _).compl H,
        restrict_compl_singleton]
    _ = ∫ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
        (H ∘ Subtype.val ∘ (homeomorphUnitSphereProd (Euclidean d)).symm) p ∂
          (((volume : Measure (Euclidean d)).toSphere).prod
            (Measure.volumeIoiPow (Module.finrank ℝ (Euclidean d) - 1))) := by
      simpa using
        (volume : Measure (Euclidean d)).measurePreserving_homeomorphUnitSphereProd.integral_comp
          (Homeomorph.measurableEmbedding _)
          (H ∘ Subtype.val ∘ (homeomorphUnitSphereProd (Euclidean d)).symm)
    _ = ∫ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
        H (p.2.1 • (p.1 : Euclidean d)) ∂
          ((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) := by
      simp [unitSurfaceMeasure]

end

end Codex.Spherical.CoordinateIntegration

namespace Codex.Spherical.CoordinateIntegration

open MeasureTheory Metric Set
open scoped ENNReal Pointwise

noncomputable section

/-- The nonnegative polar decomposition associated to the concrete surface
measure. -/
theorem lintegral_polar_unitSurfaceMeasure {d : ℕ} (hd : 0 < d)
    (H : Euclidean d → ℝ≥0∞) :
    (∫⁻ x : Euclidean d, H x) =
      ∫⁻ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
        H (p.2.1 • (p.1 : Euclidean d)) ∂
          ((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) := by
  let i : Fin d := ⟨0, hd⟩
  letI : Nonempty (Fin d) := ⟨i⟩
  calc
    (∫⁻ x : Euclidean d, H x) =
        ∫⁻ x : ({0}ᶜ : Set (Euclidean d)), H x.1 ∂
          ((volume : Measure (Euclidean d)).comap Subtype.val) := by
      rw [lintegral_subtype_comap (measurableSet_singleton _).compl H,
        restrict_compl_singleton]
    _ = ∫⁻ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
        (H ∘ Subtype.val ∘ (homeomorphUnitSphereProd (Euclidean d)).symm) p ∂
          (((volume : Measure (Euclidean d)).toSphere).prod
            (Measure.volumeIoiPow (Module.finrank ℝ (Euclidean d) - 1))) := by
      let hpolar :=
        (volume : Measure (Euclidean d)).measurePreserving_homeomorphUnitSphereProd
      simpa using
        hpolar.lintegral_comp_emb
          (Homeomorph.measurableEmbedding _)
          (H ∘ Subtype.val ∘ (homeomorphUnitSphereProd (Euclidean d)).symm)
    _ = ∫⁻ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
        H (p.2.1 • (p.1 : Euclidean d)) ∂
          ((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) := by
      simp [unitSurfaceMeasure]

/-- The radial power measure is Lebesgue measure on positive radii with its
literal `r ^ n` density. -/
theorem lintegral_volumeIoiPow (n : ℕ) (F : ℝ → ℝ≥0∞) (hF : Measurable F) :
    (∫⁻ r : Ioi (0 : ℝ), F r ∂Measure.volumeIoiPow n) =
      ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r ^ n * F r := by
  have hdensity : Measurable (fun r : Ioi (0 : ℝ) => ENNReal.ofReal (r.1 ^ n)) :=
    (measurable_subtype_coe.pow measurable_const).ennreal_ofReal
  have hsubtype : Measurable (fun r : Ioi (0 : ℝ) => F r.1) :=
    hF.comp measurable_subtype_coe
  calc
    (∫⁻ r : Ioi (0 : ℝ), F r ∂Measure.volumeIoiPow n) =
        ∫⁻ r : Ioi (0 : ℝ),
          ENNReal.ofReal (r.1 ^ n) * F r.1 ∂(Measure.comap Subtype.val volume) := by
      unfold Measure.volumeIoiPow
      rw [lintegral_withDensity_eq_lintegral_mul _ hdensity hsubtype]
      rfl
    _ = ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal (r ^ n) * F r := by
      exact lintegral_subtype_comap (μ := volume) measurableSet_Ioi
        (fun r : ℝ => ENNReal.ofReal (r ^ n) * F r)
    _ = ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r ^ n * F r := by
      apply setLIntegral_congr_fun measurableSet_Ioi
      intro r hr
      change ENNReal.ofReal (r ^ n) * F r = ENNReal.ofReal r ^ n * F r
      rw [ENNReal.ofReal_pow hr.le]

/-- Integrating a nonnegative radial function on Euclidean space factors into
the concrete surface mass and the radial power integral. -/
theorem lintegral_euclidean_radial {d : ℕ} (hd : 0 < d)
    (F : ℝ → ℝ≥0∞) (hF : Measurable F) :
    (∫⁻ x : Euclidean d, F ‖x‖) =
      ENNReal.ofReal (surfaceMass d) *
        ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r ^ (d - 1) * F r := by
  have hproduct : Measurable
      (fun p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ) => F p.2.1) :=
    hF.comp (measurable_subtype_coe.comp measurable_snd)
  have hmass : unitSurfaceMeasure d univ = ENNReal.ofReal (surfaceMass d) := by
    rw [← ENNReal.ofReal_toReal (measure_ne_top (unitSurfaceMeasure d) univ)]
    rfl
  calc
    (∫⁻ x : Euclidean d, F ‖x‖) =
        ∫⁻ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
          F ‖p.2.1 • (p.1 : Euclidean d)‖ ∂
            ((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) :=
      lintegral_polar_unitSurfaceMeasure hd _
    _ = ∫⁻ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
          F p.2.1 ∂((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) := by
      apply lintegral_congr
      rintro ⟨ω, r⟩
      have hω : ‖(ω : Euclidean d)‖ = 1 := by
        simpa only [mem_sphere_zero_iff_norm] using ω.property
      rw [norm_smul, Real.norm_eq_abs, abs_of_pos r.2, hω, mul_one]
    _ = ∫⁻ ω : sphere (0 : Euclidean d) 1,
          (∫⁻ r : Ioi (0 : ℝ), F r.1 ∂Measure.volumeIoiPow (d - 1)) ∂
            unitSurfaceMeasure d :=
      lintegral_prod _ hproduct.aemeasurable
    _ = (∫⁻ r : Ioi (0 : ℝ), F r.1 ∂Measure.volumeIoiPow (d - 1)) *
          unitSurfaceMeasure d univ := by
      rw [lintegral_const]
    _ = ENNReal.ofReal (surfaceMass d) *
        ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r ^ (d - 1) * F r := by
      rw [hmass, lintegral_volumeIoiPow (d - 1) F hF]
      ac_rfl

/-- The cone over a small Euclidean cap of the unit sphere fits in a
comparably sized Euclidean ball.  Polar coordinates therefore turn the cap
measure into a literal ball-volume upper bound. -/
theorem unitSurfaceMeasure_cap_cone_le_volume_ball
    {d : Nat} (hd : 0 < d) (z : Euclidean d) {ε : ℝ}
    (_hε : 0 < ε) (hεhalf : ε ≤ 1 / 2) :
    let S : Set (sphere (0 : Euclidean d) 1) :=
      (fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z ε
    let lo : Ioi (0 : ℝ) :=
      ⟨1 - ε, sub_pos.mpr (lt_of_le_of_lt hεhalf (by norm_num : (1 / 2 : ℝ) < 1))⟩
    let hi : Ioi (0 : ℝ) := ⟨1, by norm_num⟩
    let I : Set (Ioi (0 : ℝ)) := Set.Icc lo hi
    (unitSurfaceMeasure d) S * (Measure.volumeIoiPow (d - 1)) I ≤
      volume (Metric.ball z (2 * ε)) := by
  dsimp
  let S : Set (sphere (0 : Euclidean d) 1) :=
    (fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z ε
  let lo : Ioi (0 : ℝ) :=
    ⟨1 - ε, sub_pos.mpr (lt_of_le_of_lt hεhalf (by norm_num : (1 / 2 : ℝ) < 1))⟩
  let hi : Ioi (0 : ℝ) := ⟨1, by norm_num⟩
  let I : Set (Ioi (0 : ℝ)) := Set.Icc lo hi
  have hS : MeasurableSet S := by
    dsimp [S]
    exact measurableSet_ball.preimage continuous_subtype_val.measurable
  have hI : MeasurableSet I := by
    dsimp [I]
    exact measurableSet_Icc
  have hpairs (p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ))
      (hp : p ∈ S ×ˢ I) : p.2.1 • (p.1 : Euclidean d) ∈ Metric.ball z (2 * ε) := by
    rcases hp with ⟨hpS, hpI⟩
    have hpS' : dist (p.1 : Euclidean d) z < ε := hpS
    have hpIlo : 1 - ε ≤ p.2.1 := hpI.1
    have hpIhi : p.2.1 ≤ 1 := hpI.2
    have hω : ‖(p.1 : Euclidean d)‖ = 1 := by
      simpa only [mem_sphere_zero_iff_norm] using p.1.property
    rw [Metric.mem_ball]
    calc
      dist (p.2.1 • (p.1 : Euclidean d)) z ≤
          dist (p.2.1 • (p.1 : Euclidean d)) (p.1 : Euclidean d) +
            dist (p.1 : Euclidean d) z := dist_triangle _ _ _
      _ = ‖p.2.1 • (p.1 : Euclidean d) - (p.1 : Euclidean d)‖ +
            dist (p.1 : Euclidean d) z := by rw [dist_eq_norm]
      _ = ‖p.2.1 • (p.1 : Euclidean d) - (1 : ℝ) • (p.1 : Euclidean d)‖ +
            dist (p.1 : Euclidean d) z := by simp
      _ = ‖(p.2.1 - 1) • (p.1 : Euclidean d)‖ +
            dist (p.1 : Euclidean d) z := by
        have hsub : (p.2.1 - (1 : ℝ)) • (p.1 : Euclidean d) =
            p.2.1 • (p.1 : Euclidean d) - (1 : ℝ) • (p.1 : Euclidean d) :=
          sub_smul p.2.1 1 (p.1 : Euclidean d)
        rw [hsub]
      _ = |p.2.1 - 1| + dist (p.1 : Euclidean d) z := by
        rw [norm_smul, Real.norm_eq_abs, hω, mul_one]
      _ ≤ ε + dist (p.1 : Euclidean d) z := by
        gcongr
        rw [abs_of_nonpos (sub_nonpos.mpr hpIhi)]
        linarith
      _ < 2 * ε := by linarith
  have hindicator (p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ)) :
      (S ×ˢ I).indicator (fun _ => (1 : ℝ≥0∞)) p ≤
        (Metric.ball z (2 * ε)).indicator (fun _ => (1 : ℝ≥0∞))
          (p.2.1 • (p.1 : Euclidean d)) := by
    by_cases hp : p ∈ S ×ˢ I
    · rw [Set.indicator_of_mem hp, Set.indicator_of_mem (hpairs p hp)]
    · rw [Set.indicator_of_notMem hp]
      exact zero_le
  have hpolar := lintegral_polar_unitSurfaceMeasure hd
    ((Metric.ball z (2 * ε)).indicator (fun _ => (1 : ℝ≥0∞)))
  calc
    (unitSurfaceMeasure d) S * (Measure.volumeIoiPow (d - 1)) I =
        ((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) (S ×ˢ I) :=
      (MeasureTheory.Measure.prod_prod S I).symm
    _ = ∫⁻ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
        (S ×ˢ I).indicator (fun _ => (1 : ℝ≥0∞)) p ∂
          ((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) := by
      rw [lintegral_indicator_const (hS.prod hI)]
      simp
    _ ≤ ∫⁻ p : sphere (0 : Euclidean d) 1 × Ioi (0 : ℝ),
        (Metric.ball z (2 * ε)).indicator (fun _ => (1 : ℝ≥0∞))
          (p.2.1 • (p.1 : Euclidean d)) ∂
          ((unitSurfaceMeasure d).prod (Measure.volumeIoiPow (d - 1))) :=
      lintegral_mono hindicator
    _ = ∫⁻ x : Euclidean d,
        (Metric.ball z (2 * ε)).indicator (fun _ => (1 : ℝ≥0∞)) x := hpolar.symm
    _ = volume (Metric.ball z (2 * ε)) := by
      rw [lintegral_indicator_const measurableSet_ball]
      simp

/-- On the short radial interval used in the cap cone, the polar density is
bounded below by its value at `1 / 2`. -/
theorem volumeIoiPow_unit_interval_lower
    (n : Nat) {ε : ℝ} (hε : 0 < ε) (hεhalf : ε ≤ 1 / 2) :
    let lo : Ioi (0 : ℝ) :=
      ⟨1 - ε, sub_pos.mpr (lt_of_le_of_lt hεhalf (by norm_num : (1 / 2 : ℝ) < 1))⟩
    let hi : Ioi (0 : ℝ) := ⟨1, by norm_num⟩
    let I : Set (Ioi (0 : ℝ)) := Set.Icc lo hi
    ENNReal.ofReal ((1 / 2 : ℝ) ^ n * ε) ≤
      (Measure.volumeIoiPow n) I := by
  dsimp
  let lo : Ioi (0 : ℝ) :=
    ⟨1 - ε, sub_pos.mpr (lt_of_le_of_lt hεhalf (by norm_num : (1 / 2 : ℝ) < 1))⟩
  let hi : Ioi (0 : ℝ) := ⟨1, by norm_num⟩
  let I : Set (Ioi (0 : ℝ)) := Set.Icc lo hi
  let J : Set ℝ := Set.Icc (1 - ε) 1
  have hJ : MeasurableSet J := by
    dsimp [J]
    exact measurableSet_Icc
  have hJpos : J ⊆ Ioi (0 : ℝ) := by
    intro r hr
    have : 1 - ε ≤ r := hr.1
    exact lt_of_lt_of_le
      (sub_pos.mpr (lt_of_le_of_lt hεhalf (by norm_num : (1 / 2 : ℝ) < 1))) this
  have hI : MeasurableSet I := by
    dsimp [I]
    exact measurableSet_Icc
  have hIeq : I = Subtype.val ⁻¹' J := by
    ext r
    change (lo ≤ r ∧ r ≤ hi) ↔ (1 - ε ≤ r.1 ∧ r.1 ≤ 1)
    rfl
  have hpow (r : ℝ) (hr : r ∈ J) : (1 / 2 : ℝ) ^ n ≤ r ^ n := by
    exact pow_le_pow_left₀ (by positivity)
      (by
        have : 1 - ε ≤ r := hr.1
        linarith [hεhalf]) n
  let c : ℝ≥0∞ := ENNReal.ofReal ((1 / 2 : ℝ) ^ n)
  have hpoint (r : ℝ) : J.indicator (fun _ => c) r ≤
      ENNReal.ofReal r ^ n * J.indicator (fun _ => (1 : ℝ≥0∞)) r := by
    by_cases hr : r ∈ J
    · rw [Set.indicator_of_mem hr, Set.indicator_of_mem hr]
      have hrnonneg : 0 ≤ r := by
        have : 1 - ε ≤ r := hr.1
        linarith [hεhalf]
      dsimp [c]
      rw [mul_one, ← ENNReal.ofReal_pow hrnonneg]
      exact ENNReal.ofReal_le_ofReal (hpow r hr)
    · rw [Set.indicator_of_notMem hr, Set.indicator_of_notMem hr]
      simp
  have hvolumeI :
      (Measure.volumeIoiPow n) I =
        ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r ^ n *
          J.indicator (fun _ => (1 : ℝ≥0∞)) r := by
    calc
      (Measure.volumeIoiPow n) I =
          ∫⁻ r : Ioi (0 : ℝ), I.indicator (fun _ => (1 : ℝ≥0∞)) r ∂
            Measure.volumeIoiPow n := by
        rw [lintegral_indicator_const hI]
        simp
      _ = ∫⁻ r : Ioi (0 : ℝ), J.indicator (fun _ => (1 : ℝ≥0∞)) r.1 ∂
            Measure.volumeIoiPow n := by
        apply lintegral_congr
        intro r
        rw [hIeq]
        by_cases hr : r.1 ∈ J
        · have hr' : r ∈ Subtype.val ⁻¹' J := hr
          rw [Set.indicator_of_mem hr']
          rw [Set.indicator_of_mem hr]
        · have hr' : r ∉ Subtype.val ⁻¹' J := hr
          rw [Set.indicator_of_notMem hr']
          rw [Set.indicator_of_notMem hr]
      _ = ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r ^ n *
          J.indicator (fun _ => (1 : ℝ≥0∞)) r :=
        lintegral_volumeIoiPow n (J.indicator (fun _ => (1 : ℝ≥0∞)))
          ((measurable_indicator_const_iff 1).mpr hJ)
  have hlower :
      ∫⁻ r in Ioi (0 : ℝ), J.indicator (fun _ => c) r ≤
        (Measure.volumeIoiPow n) I := by
    rw [hvolumeI]
    exact lintegral_mono (fun r => hpoint r)
  have hleft :
      (∫⁻ r in Ioi (0 : ℝ), J.indicator (fun _ => c) r) =
        ENNReal.ofReal ((1 / 2 : ℝ) ^ n * ε) := by
    rw [lintegral_indicator hJ]
    change ∫⁻ r : ℝ, c ∂(volume.restrict (Ioi (0 : ℝ))).restrict J = _
    rw [Measure.restrict_restrict hJ]
    simp only [Set.inter_eq_left.mpr hJpos]
    rw [setLIntegral_const, Real.volume_Icc]
    dsimp [c]
    rw [← ENNReal.ofReal_mul (by positivity : 0 ≤ (1 / 2 : ℝ) ^ n)]
    congr 1
    ring
  rw [← hleft]
  exact hlower

/-- A small Euclidean cap of the concrete unit-sphere measure is bounded by
the volume of a comparable ball divided by its radial thickness. -/
theorem unitSurfaceMeasure_cap_le_volume_ball_div
    {d : Nat} (hd : 0 < d) (z : Euclidean d) {ε : ℝ}
    (hε : 0 < ε) (hεhalf : ε ≤ 1 / 2) :
    let S : Set (sphere (0 : Euclidean d) 1) :=
      (fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z ε
    (unitSurfaceMeasure d) S ≤
      volume (Metric.ball z (2 * ε)) /
        ENNReal.ofReal ((1 / 2 : ℝ) ^ (d - 1) * ε) := by
  dsimp
  let S : Set (sphere (0 : Euclidean d) 1) :=
    (fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z ε
  let lo : Ioi (0 : ℝ) :=
    ⟨1 - ε, sub_pos.mpr (lt_of_le_of_lt hεhalf (by norm_num : (1 / 2 : ℝ) < 1))⟩
  let hi : Ioi (0 : ℝ) := ⟨1, by norm_num⟩
  let I : Set (Ioi (0 : ℝ)) := Set.Icc lo hi
  let q : ℝ≥0∞ := ENNReal.ofReal ((1 / 2 : ℝ) ^ (d - 1) * ε)
  have hcone : (unitSurfaceMeasure d) S * (Measure.volumeIoiPow (d - 1)) I ≤
      volume (Metric.ball z (2 * ε)) := by
    simpa only [S, lo, hi, I] using
      unitSurfaceMeasure_cap_cone_le_volume_ball hd z hε hεhalf
  have hrad : q ≤ (Measure.volumeIoiPow (d - 1)) I := by
    dsimp only [q]
    simpa only [lo, hi, I] using
      volumeIoiPow_unit_interval_lower (d - 1) hε hεhalf
  have hqpos : 0 < q := by
    dsimp only [q]
    exact ENNReal.ofReal_pos.mpr (mul_pos (pow_pos (by norm_num) _) hε)
  have hmul : (unitSurfaceMeasure d) S * q ≤ volume (Metric.ball z (2 * ε)) := by
    calc
      (unitSurfaceMeasure d) S * q ≤
          (unitSurfaceMeasure d) S * (Measure.volumeIoiPow (d - 1)) I :=
        mul_le_mul_right hrad _
      _ ≤ volume (Metric.ball z (2 * ε)) := hcone
  apply (ENNReal.le_div_iff_mul_le (Or.inl hqpos.ne')
    (Or.inl ENNReal.ofReal_ne_top)).2
  exact hmul

private theorem cap_quotient_coefficient_le
    {d : Nat} (hd : 0 < d) {ε : ℝ} (hε : 0 < ε) :
    ((2 * ε) ^ d) / ((1 / 2 : ℝ) ^ (d - 1) * ε) ≤
      (2 : ℝ) ^ (2 * d) * ε ^ (d - 1) := by
  have hden : 0 < (1 / 2 : ℝ) ^ (d - 1) * ε :=
    mul_pos (pow_pos (by norm_num) _) hε
  apply (div_le_iff₀ hden).2
  rw [mul_pow]
  rw [show ε ^ d = ε ^ (d - 1) * ε by
    rw [← pow_succ]
    congr 1
    omega]
  rw [show (1 / 2 : ℝ) ^ (d - 1) = ((2 : ℝ) ^ (d - 1))⁻¹ by
    rw [show (1 / 2 : ℝ) = (2 : ℝ)⁻¹ by norm_num, inv_pow]]
  have hp : 0 < (2 : ℝ) ^ (d - 1) := pow_pos (by norm_num) _
  apply (le_of_mul_le_mul_right ?_ hp)
  field_simp
  rw [← pow_add]
  gcongr
  · norm_num
  · omega

/-- A Euclidean cap of radius at most `1 / 2` has the expected
codimension-one power bound for the concrete surface measure. -/
theorem unitSurfaceMeasure_cap_le_power
    {d : Nat} (hd : 0 < d) (z : Euclidean d) {ε : ℝ}
    (hε : 0 < ε) (hεhalf : ε ≤ 1 / 2) :
    let S : Set (sphere (0 : Euclidean d) 1) :=
      (fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z ε
    (unitSurfaceMeasure d) S ≤
      (2 : ℝ≥0∞) ^ (2 * d) * volume (Metric.ball (0 : Euclidean d) 1) *
        ENNReal.ofReal (ε ^ (d - 1)) := by
  dsimp
  let S : Set (sphere (0 : Euclidean d) 1) :=
    (fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z ε
  have hbase := unitSurfaceMeasure_cap_le_volume_ball_div hd z hε hεhalf
  have hbase' : (unitSurfaceMeasure d) S ≤
      volume (Metric.ball z (2 * ε)) /
        ENNReal.ofReal ((1 / 2 : ℝ) ^ (d - 1) * ε) := by
    simpa only [S] using hbase
  have hradpos : 0 < (1 / 2 : ℝ) ^ (d - 1) * ε :=
    mul_pos (pow_pos (by norm_num) _) hε
  have hball : volume (Metric.ball z (2 * ε)) =
      ENNReal.ofReal ((2 * ε) ^ d) * volume (Metric.ball (0 : Euclidean d) 1) := by
    rw [Measure.addHaar_ball_of_pos volume z (mul_pos (by norm_num) hε)]
    simp only [finrank_euclideanSpace_fin]
  calc
    (unitSurfaceMeasure d) S ≤
        volume (Metric.ball z (2 * ε)) /
          ENNReal.ofReal ((1 / 2 : ℝ) ^ (d - 1) * ε) := hbase'
    _ = volume (Metric.ball (0 : Euclidean d) 1) *
        ENNReal.ofReal (((2 * ε) ^ d) /
          ((1 / 2 : ℝ) ^ (d - 1) * ε)) := by
      rw [hball]
      rw [ENNReal.ofReal_div_of_pos hradpos]
      simp only [ENNReal.div_eq_inv_mul]
      ac_rfl
    _ ≤ (2 : ℝ≥0∞) ^ (2 * d) * volume (Metric.ball (0 : Euclidean d) 1) *
        ENNReal.ofReal (ε ^ (d - 1)) := by
      have hreal := cap_quotient_coefficient_le hd hε
      have henn : ENNReal.ofReal (((2 * ε) ^ d) /
          ((1 / 2 : ℝ) ^ (d - 1) * ε)) ≤
          (2 : ℝ≥0∞) ^ (2 * d) * ENNReal.ofReal (ε ^ (d - 1)) := by
        calc
          ENNReal.ofReal (((2 * ε) ^ d) /
              ((1 / 2 : ℝ) ^ (d - 1) * ε)) ≤
              ENNReal.ofReal ((2 : ℝ) ^ (2 * d) * ε ^ (d - 1)) :=
            ENNReal.ofReal_le_ofReal hreal
          _ = (2 : ℝ≥0∞) ^ (2 * d) * ENNReal.ofReal (ε ^ (d - 1)) := by
            rw [ENNReal.ofReal_mul (pow_nonneg (by norm_num) _)]
            rw [ENNReal.ofReal_pow (by norm_num : (0 : ℝ) ≤ 2)]
            norm_num
      calc
        volume (Metric.ball (0 : Euclidean d) 1) *
            ENNReal.ofReal (((2 * ε) ^ d) /
              ((1 / 2 : ℝ) ^ (d - 1) * ε)) ≤
            volume (Metric.ball (0 : Euclidean d) 1) *
              ((2 : ℝ≥0∞) ^ (2 * d) * ENNReal.ofReal (ε ^ (d - 1))) :=
          mul_le_mul_right henn _
        _ = (2 : ℝ≥0∞) ^ (2 * d) * volume (Metric.ball (0 : Euclidean d) 1) *
            ENNReal.ofReal (ε ^ (d - 1)) := by ac_rfl

/-- The concrete unit-sphere measure has global codimension-one ball growth.
The constant is finite and depends only on the dimension. -/
theorem exists_unitSurfaceMeasure_cap_le_power
    {d : Nat} (hd : 0 < d) :
    ∃ C : ℝ≥0∞, C ≠ ⊤ ∧ ∀ (z : Euclidean d) (r : ℝ), 0 ≤ r →
      (unitSurfaceMeasure d)
        ((fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z r) ≤
        C * ENNReal.ofReal (r ^ (d - 1)) := by
  let V : ℝ≥0∞ := volume (Metric.ball (0 : Euclidean d) 1)
  let C : ℝ≥0∞ := (2 : ℝ≥0∞) ^ (2 * d) * V +
    ENNReal.ofReal (surfaceMass d) * (2 : ℝ≥0∞) ^ (d - 1)
  refine ⟨C, ?_, ?_⟩
  · dsimp [C, V]
    apply ENNReal.add_ne_top.2
    constructor
    · exact ENNReal.mul_ne_top (ENNReal.pow_ne_top (by norm_num))
        MeasureTheory.measure_ball_ne_top
    · exact ENNReal.mul_ne_top ENNReal.ofReal_ne_top
        (ENNReal.pow_ne_top (by norm_num))
  intro z r hr
  by_cases hrzero : r = 0
  · subst r
    rw [(Metric.ball_eq_empty.2 le_rfl), Set.preimage_empty, measure_empty]
    simp
  have hrpos : 0 < r := lt_of_le_of_ne hr (Ne.symm hrzero)
  by_cases hrsmall : r ≤ 1 / 2
  · have hlocal := unitSurfaceMeasure_cap_le_power hd z hrpos hrsmall
    dsimp [C]
    have hcoefficient : (2 : ℝ≥0∞) ^ (2 * d) * V ≤
        (2 : ℝ≥0∞) ^ (2 * d) * V +
          ENNReal.ofReal (surfaceMass d) * (2 : ℝ≥0∞) ^ (d - 1) :=
      le_add_of_nonneg_right bot_le
    simpa only [V] using hlocal.trans (mul_le_mul_left hcoefficient _)
  have hrlarge : 1 / 2 < r := lt_of_not_ge hrsmall
  have hmeasure : (unitSurfaceMeasure d)
      ((fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z r) ≤
      ENNReal.ofReal (surfaceMass d) := by
    calc
      (unitSurfaceMeasure d)
          ((fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z r) ≤
          (unitSurfaceMeasure d) Set.univ := measure_mono (Set.subset_univ _)
      _ = ENNReal.ofReal (surfaceMass d) := by
        rw [← ENNReal.ofReal_toReal (measure_ne_top _ _)]
        rfl
  have hfactor : 1 ≤ (2 : ℝ≥0∞) ^ (d - 1) * ENNReal.ofReal (r ^ (d - 1)) := by
    have hreal : 1 ≤ (2 * r) ^ (d - 1) := by
      apply one_le_pow₀
      linarith
    calc
      (1 : ℝ≥0∞) = ENNReal.ofReal (1 : ℝ) := by norm_num
      _ ≤ ENNReal.ofReal ((2 * r) ^ (d - 1)) := ENNReal.ofReal_le_ofReal hreal
      _ = (2 : ℝ≥0∞) ^ (d - 1) * ENNReal.ofReal (r ^ (d - 1)) := by
        rw [mul_pow]
        rw [ENNReal.ofReal_mul (pow_nonneg (by norm_num) _)]
        rw [ENNReal.ofReal_pow (by norm_num : (0 : ℝ) ≤ 2)]
        norm_num
  have hmass : ENNReal.ofReal (surfaceMass d) ≤
      (ENNReal.ofReal (surfaceMass d) * (2 : ℝ≥0∞) ^ (d - 1)) *
        ENNReal.ofReal (r ^ (d - 1)) := by
    calc
      ENNReal.ofReal (surfaceMass d) = ENNReal.ofReal (surfaceMass d) * 1 := by ring
      _ ≤ ENNReal.ofReal (surfaceMass d) *
          ((2 : ℝ≥0∞) ^ (d - 1) * ENNReal.ofReal (r ^ (d - 1))) :=
        mul_le_mul_right hfactor _
      _ = (ENNReal.ofReal (surfaceMass d) * (2 : ℝ≥0∞) ^ (d - 1)) *
          ENNReal.ofReal (r ^ (d - 1)) := by ring
  calc
    (unitSurfaceMeasure d)
        ((fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹' Metric.ball z r) ≤
        ENNReal.ofReal (surfaceMass d) := hmeasure
    _ ≤ (ENNReal.ofReal (surfaceMass d) * (2 : ℝ≥0∞) ^ (d - 1)) *
        ENNReal.ofReal (r ^ (d - 1)) := hmass
    _ ≤ C * ENNReal.ofReal (r ^ (d - 1)) := by
      apply mul_le_mul_left
      dsimp [C]
      exact le_add_of_nonneg_left bot_le

/-- Real-valued form of the global unit-sphere cap growth estimate. -/
theorem exists_unitSurfaceMeasure_cap_real_le_power
    {d : Nat} (hd : 0 < d) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (z : Euclidean d) (r : ℝ), 0 ≤ r →
      ((unitSurfaceMeasure d)
        ((fun ω : sphere (0 : Euclidean d) 1 => (ω : Euclidean d)) ⁻¹'
          Metric.ball z r)).toReal ≤
        C * r ^ (d - 1) := by
  obtain ⟨C, hCtop, hcap⟩ := exists_unitSurfaceMeasure_cap_le_power hd
  refine ⟨C.toReal, ENNReal.toReal_nonneg, ?_⟩
  intro z r hr
  have hpow : 0 ≤ r ^ (d - 1) := pow_nonneg hr _
  have hbound := hcap z r hr
  have hright : C * ENNReal.ofReal (r ^ (d - 1)) ≠ ⊤ :=
    ENNReal.mul_ne_top hCtop ENNReal.ofReal_ne_top
  have hrightreal : (C * ENNReal.ofReal (r ^ (d - 1))).toReal =
      C.toReal * r ^ (d - 1) := by
    rw [ENNReal.toReal_mul, ENNReal.toReal_ofReal hpow]
  rw [← hrightreal]
  exact (ENNReal.toReal_le_toReal (measure_ne_top _ _) hright).mpr hbound

end

end Codex.Spherical.CoordinateIntegration

namespace Codex.Spherical.CoordinateIntegration

open MeasureTheory Metric Set
open scoped ENNReal

noncomputable section

/-- A nonnegative function of the final coordinate and the radius in the
first `d` coordinates has the expected height--radial integral formula in
`Euclidean (d + 1)`. -/
theorem lintegral_euclideanSucc_radial_last {d : Nat} (hd : 0 < d)
    (G : ℝ × ℝ → ℝ≥0∞) (hG : Measurable G) :
    (∫⁻ x : Euclidean (d + 1),
      G (‖MeasurableEquiv.toLp 2 (Fin d → ℝ) (fun i => x (Fin.castAdd 1 i))‖,
        x (Fin.last d))) =
      ENNReal.ofReal (surfaceMass d) *
        ∫⁻ z : ℝ, ∫⁻ r in Ioi (0 : ℝ),
          ENNReal.ofReal r ^ (d - 1) * G (r, z) := by
  let C : Euclidean (d + 1) → Euclidean d × ℝ := fun x =>
    (MeasurableEquiv.toLp 2 (Fin d → ℝ) (fun i => x (Fin.castAdd 1 i)),
      x (Fin.last d))
  have hfirst : Measurable (fun x : Euclidean (d + 1) =>
      MeasurableEquiv.toLp 2 (Fin d → ℝ) (fun i => x (Fin.castAdd 1 i))) := by
    apply (MeasurableEquiv.toLp 2 (Fin d → ℝ)).measurable.comp
    apply measurable_pi_lambda
    intro i
    fun_prop
  have hC : Measurable C := by
    exact hfirst.prodMk (by fun_prop)
  have hGC : Measurable (fun q : Euclidean d × ℝ => G (‖q.1‖, q.2)) :=
    hG.comp ((measurable_norm.comp measurable_fst).prodMk measurable_snd)
  have hmeridian : Measurable (fun q : ℝ × ℝ =>
      ENNReal.ofReal q.2 ^ (d - 1) * G (q.2, q.1)) :=
    (measurable_snd.ennreal_ofReal.pow_const (d - 1)).mul
      (hG.comp (measurable_snd.prodMk measurable_fst))
  have hinner : Measurable (fun z : ℝ =>
      ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r ^ (d - 1) * G (r, z)) := by
    change Measurable (fun z : ℝ =>
      ∫⁻ r, (fun q : ℝ × ℝ =>
        ENNReal.ofReal q.2 ^ (d - 1) * G (q.2, q.1)) (z, r) ∂
          volume.restrict (Ioi (0 : ℝ)))
    exact hmeridian.lintegral_prod_right'
  calc
    (∫⁻ x : Euclidean (d + 1),
      G (‖MeasurableEquiv.toLp 2 (Fin d → ℝ) (fun i => x (Fin.castAdd 1 i))‖,
        x (Fin.last d))) =
        ∫⁻ q : Euclidean d × ℝ, G (‖q.1‖, q.2) ∂Measure.map C volume := by
      exact (MeasureTheory.lintegral_map hGC hC).symm
    _ = ∫⁻ q : Euclidean d × ℝ,
        G (‖q.1‖, q.2) ∂((volume : Measure (Euclidean d)).prod volume) := by
      rw [show C = fun x : Euclidean (d + 1) =>
        (MeasurableEquiv.toLp 2 (Fin d → ℝ) (fun i => x (Fin.castAdd 1 i)),
          x (Fin.last d)) by rfl,
        map_euclideanSucc_coordinates_volume]
    _ = ∫⁻ z : ℝ, ∫⁻ y : Euclidean d, G (‖y‖, z) := by
      exact lintegral_prod_symm' _ hGC
    _ = ∫⁻ z : ℝ, ENNReal.ofReal (surfaceMass d) *
          ∫⁻ r in Ioi (0 : ℝ), ENNReal.ofReal r ^ (d - 1) * G (r, z) := by
      apply lintegral_congr
      intro z
      exact lintegral_euclidean_radial hd (fun r => G (r, z))
        (hG.comp (measurable_id.prodMk measurable_const))
    _ = ENNReal.ofReal (surfaceMass d) *
        ∫⁻ z : ℝ, ∫⁻ r in Ioi (0 : ℝ),
          ENNReal.ofReal r ^ (d - 1) * G (r, z) := by
      rw [lintegral_const_mul _ hinner]

end

end Codex.Spherical.CoordinateIntegration

namespace Codex.Spherical.CoordinateIntegration

open MeasureTheory
open scoped ENNReal Interval

noncomputable section

/-- The substitution `u = cos φ` on the meridian. -/
theorem integral_comp_cos_mul_sin (g : ℝ → ℂ) (hg : Continuous g) :
    (∫ φ in (0 : ℝ)..Real.pi, g (Real.cos φ) * (Real.sin φ : ℂ)) =
      ∫ u in (-1 : ℝ)..1, g u := by
  have hsubst := intervalIntegral.integral_deriv_smul_comp
    (a := (0 : ℝ)) (b := Real.pi) (f := Real.cos) (f' := fun φ => -Real.sin φ)
    (g := g) (fun φ _ => Real.hasDerivAt_cos φ) (by fun_prop) hg
  simp only [Function.comp_apply, Real.cos_zero, Real.cos_pi] at hsubst
  calc
    (∫ φ in (0 : ℝ)..Real.pi, g (Real.cos φ) * (Real.sin φ : ℂ)) =
        -∫ φ in (0 : ℝ)..Real.pi, (-Real.sin φ) • g (Real.cos φ) := by
      rw [← intervalIntegral.integral_neg]
      apply intervalIntegral.integral_congr
      intro φ _
      simp only [neg_smul, neg_neg, Complex.real_smul]
      ring
    _ = -∫ u in (1 : ℝ)..(-1 : ℝ), g u := by rw [hsubst]
    _ = ∫ u in (-1 : ℝ)..1, g u := by
      rw [intervalIntegral.integral_symm]
      ring

/-- The measurable change of variables `u = cos φ` on the open meridian. -/
theorem lintegral_comp_cos_mul_sin (u : ℝ → ℝ≥0∞) :
    (∫⁻ φ in Set.Ioo (0 : ℝ) Real.pi,
      ENNReal.ofReal (Real.sin φ) * u (Real.cos φ)) =
      ∫⁻ t in Set.Ioo (-1 : ℝ) 1, u t := by
  let s : Set ℝ := Set.Ioo (0 : ℝ) Real.pi
  have himage : Real.cos '' s = Set.Ioo (-1 : ℝ) 1 := by
    simpa [s] using Real.cosPartialHomeomorph.image_source_eq_target
  rw [← himage]
  simpa [s] using
    (lintegral_image_eq_lintegral_deriv_mul_of_antitoneOn
      (f := Real.cos) (f' := fun φ => -Real.sin φ) (s := s) measurableSet_Ioo
      (fun φ _ => (Real.hasDerivAt_cos φ).hasDerivWithinAt)
      (Real.strictAntiOn_cos.antitoneOn.mono Set.Ioo_subset_Icc_self) u).symm

end

end Codex.Spherical.CoordinateIntegration