import LeanSpherical.Auto.Spherical.RieszThorin
import Mathlib.MeasureTheory.Function.Holder
import Mathlib.MeasureTheory.Function.LpSeminorm.LpNorm

open MeasureTheory ENNReal
open scoped ENNReal

#check eLpNorm_const_smul
#check MemLp.const_smul
#check SimpleFunc.coe_smul
#check SimpleFunc.memLp_iff_finMeasSupp
#check eLpNorm_eq_zero_iff
#check ENNReal.inv_div
#check ENNReal.div_eq_inv_mul
#check ENNReal.div_eq_mul_inv
#check ENNReal.inv_mul_cancel
#check ENNReal.inv_ne_top
#check ENNReal.inv_ne_zero
#check inv_injective
#check inv_inj
#check inv_inv
#check ENNReal.inv_eq_inv
#check eq_inv_of_mul_left
#check eq_inv_of_mul_right
#check inv_eq_iff_eq_inv
#check eq_inv_iff_mul_eq_one
#check eq_inv_iff_mul_eq_one₀
#check inv_eq_iff_eq_inv
#check ENNReal.ofReal_inv_of_pos
#check ENNReal.ofReal_add
#check ENNReal.ofReal_sub
#check ENNReal.toReal_ofReal
#check ENNReal.toReal_inv
#check ENNReal.ext
#check ENNReal.ext_iff
#check ENNReal.inv_inj
#check ENNReal.toReal_rpow
#check ENNReal.ofReal_rpow_of_nonneg
#check ENNReal.ofReal_rpow_of_pos
#check ENNReal.rpow_toReal
#check ENNReal.rpow_toReal_eq
#check ENNReal.toReal_of_ne_top
#check ENNReal.toReal_ofNat
#check ENNReal.rpow_mul
#check ENNReal.rpow_add
#check ENNReal.rpow_lt_top_of_nonneg
#check ENNReal.rpow_ne_top_of_nonneg
#check memLp_of_aestronglyMeasurable_of_eLpNorm_le
#check ENNReal.toReal_mul
#check ENNReal.rpow_ne_top_of_nonneg
#check ENNReal.rpow_lt_top_of_nonneg
#check ENNReal.ofReal_toReal
#check ENNReal.ofReal_mul
#check enorm_eq_nnnorm
#check ENNReal.coe_toNNReal
#check ENNReal.rpow_eq_zero_iff
#check enorm_mul
#check Real.enorm_eq_ofReal
#check ENNReal.toReal_pos
#check ENNReal.toReal_pos_iff
#check ENNReal.toReal_ne_zero
#check Lp.norm_toLp
#check MemLp.eLpNorm_ne_top
#check ENNReal.HolderConjugate.ne_zero
#check ENNReal.HolderConjugate.one_le
#check memLp_top_const
