import LeanSpherical.Codex.Spherical.RieszThorin
import Mathlib.MeasureTheory.Function.Holder
import Mathlib.MeasureTheory.Function.LpSeminorm.LpNorm

open MeasureTheory ENNReal
open scoped ENNReal

#check ContinuousLinearMap.map_smul
#check LinearMap.map_smul
#check eLpNorm_const_smul
#check ofReal_norm
#check ofReal_norm_eq_enorm
#check ENNReal.ofReal_inv_of_pos
#check ENNReal.ofReal_inv
#check Complex.norm_real
#check enorm_eq_nnnorm
#check Complex.nnnorm_real
#check enorm_smul
#check Complex.enorm_real
#check Complex.norm_real
#check Real.norm_of_nonneg
#check ENNReal.ofReal_inv_of_pos
#check ENNReal.inv_mul_cancel
#check ENNReal.mul_inv_cancel
#check ENNReal.mul_le_mul_left
#check ENNReal.mul_le_mul_right
#check mul_le_mul_left'
#check mul_le_mul_right'
#check ENNReal.rpow_ne_top_of_nonneg
#check ENNReal.rpow_lt_top_of_nonneg
#check ENNReal.ofReal_toReal
#check ENNReal.toReal_pos
#check ENNReal.toReal_nonneg
#check ENNReal.toReal_ne_zero
#check ENNReal.zero_lt_iff
#check ENNReal.pos_iff_ne_zero
#check eLpNorm_eq_zero_iff
#check SimpleFunc.ext
#check SimpleFunc.coe_smul
#check eLpNorm_congr_ae
#check eLpNorm_zero
#check bot_unique
#check le_zero_iff
#check ENNReal.mul_eq_zero
#check ENNReal.mul_pos
#check mul_le_mul_of_nonneg_left
#check mul_le_mul_of_nonneg_right
#check mul_le_mul_left
#check mul_le_mul_right
#check mul_le_mul
#check ENNReal.mul_lt_top
