/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.PowerWeights.LacunaryKernel

/-!
# Cancellation for the lacunary high-frequency kernel

The Calderón decomposition for a dyadic lacunary family uses the literal
mean-zero property of the smooth dyadic difference kernel.  This file records
that property directly from Fourier inversion, together with its invariance
under the physical dilations which occur in each selected radius.

There is deliberately no abstract singular-integral interface here: the
kernel is an inverse Fourier transform of the exact Schwartz multiplier used
by `lacunaryRelativeBandpassSphericalMaximal`.
-/

namespace LeanSpherical.HarmonicAnalysis

open MeasureTheory FourierTransform Metric
open scoped FourierTransform

noncomputable section

private theorem integrable_sphere_translate_product
    {d : Nat} (f : Euclidean d → ℂ) (hfcont : Continuous f)
    (hf : Integrable f volume) (r : ℝ) :
    Integrable
      (fun p : Euclidean d × sphere (0 : Euclidean d) 1 =>
        f (p.1 + r • (p.2 : Euclidean d)))
      (volume.prod (unitSurfaceMeasure d)) := by
  have hmeas : AEStronglyMeasurable
      (fun p : Euclidean d × sphere (0 : Euclidean d) 1 =>
        f (p.1 + r • (p.2 : Euclidean d)))
      (volume.prod (unitSurfaceMeasure d)) := by
    apply (hfcont.comp (continuous_fst.add
      ((continuous_const : Continuous fun _ : Euclidean d × sphere (0 : Euclidean d) 1 => r).smul
        (continuous_subtype_val.comp continuous_snd)))).aestronglyMeasurable
  refine (integrable_prod_iff' hmeas).2 ?_
  constructor
  · filter_upwards with omega
    exact hf.comp_add_right (r • (omega : Euclidean d))
  · have h_eq : (fun omega : sphere (0 : Euclidean d) 1 =>
        ∫ x : Euclidean d, ‖f (x + r • (omega : Euclidean d))‖) =
        fun _ => ∫ x : Euclidean d, ‖f x‖ := by
      funext omega
      exact integral_add_right_eq_self (fun x : Euclidean d => ‖f x‖)
        (r • (omega : Euclidean d))
    rw [h_eq]
    exact integrable_const _

/-- A (not necessarily normalized) spherical average preserves total mass up
to the mass of the unit surface measure.  The zero-mean kernel argument uses
this Fubini identity after each physical dilation. -/
theorem integral_sphericalAverage_eq_surfaceMass_mul_integral
    {d : Nat} (f : Euclidean d → ℂ) (hfcont : Continuous f)
    (hf : Integrable f volume) (r : ℝ) :
    (∫ x : Euclidean d, sphericalAverage d f r x) =
      (surfaceMass d : ℂ) * ∫ x : Euclidean d, f x := by
  have hprod := integrable_sphere_translate_product f hfcont hf r
  calc
    (∫ x : Euclidean d, sphericalAverage d f r x) =
        ∫ x : Euclidean d, ∫ omega : sphere (0 : Euclidean d) 1,
          f (x + r • (omega : Euclidean d)) ∂unitSurfaceMeasure d := rfl
    _ = ∫ omega : sphere (0 : Euclidean d) 1,
        ∫ x : Euclidean d, f (x + r • (omega : Euclidean d)) ∂volume
          ∂unitSurfaceMeasure d := integral_integral_swap hprod
    _ = ∫ _ : sphere (0 : Euclidean d) 1, (∫ x : Euclidean d, f x) ∂unitSurfaceMeasure d := by
      apply integral_congr_ae
      filter_upwards with omega
      exact integral_add_right_eq_self f (r • (omega : Euclidean d))
    _ = (surfaceMass d : ℂ) * ∫ x : Euclidean d, f x := by
      simp [surfaceMass]

/-- Fourier inversion evaluated at zero identifies the integral of an inverse
Schwartz Fourier transform with the value of its multiplier at zero. -/
theorem integral_fourierInv_schwartz_eq_zero_frequency
    {d : Nat} (psi : SchwartzMap (Euclidean d) ℂ) :
    (∫ x : Euclidean d, (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) x) = psi 0 := by
  have hfourier :
      𝓕 ((𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) : Euclidean d → ℂ) =
        (psi : Euclidean d → ℂ) := by
    rw [← SchwartzMap.fourier_coe, FourierTransform.fourier_fourierInv_eq]
  have h := congrFun hfourier (0 : Euclidean d)
  rw [Real.fourier_eq] at h
  simpa using h

/-- The inverse kernel of a literal dyadic difference has mean zero. -/
theorem integral_fourierInv_eq_zero_of_dyadic_difference
    {d : Nat} (phi psi : SchwartzMap (Euclidean d) ℂ)
    (hpsi : ∀ xi : Euclidean d, psi xi = phi ((2 : ℝ)⁻¹ • xi) - phi xi) :
    (∫ x : Euclidean d, (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) x) = 0 := by
  rw [integral_fourierInv_schwartz_eq_zero_frequency]
  simpa using hpsi 0

/-- Mean zero of the dyadic difference kernel is unchanged by the normalized
physical dilation at any positive scale. -/
theorem integral_scaled_fourierInv_eq_zero_of_dyadic_difference
    {d : Nat} (phi psi : SchwartzMap (Euclidean d) ℂ)
    (hpsi : ∀ xi : Euclidean d, psi xi = phi ((2 : ℝ)⁻¹ • xi) - phi xi)
    {s : ℝ} (hs : 0 < s) :
    (∫ x : Euclidean d,
      ((s ^ d : ℝ) : ℂ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • x)) = 0 := by
  rw [integral_smul]
  rw [Measure.integral_comp_smul_of_nonneg volume
    (fun x : Euclidean d => (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) x) s (hR := hs.le)]
  simp only [finrank_euclideanSpace_fin]
  rw [integral_fourierInv_eq_zero_of_dyadic_difference phi psi hpsi]
  simp

/-- The normalized physical dilation of an inverse Schwartz kernel remains
integrable.  This is the kernel class used by every member of a lacunary
family. -/
theorem integrable_scaled_fourierInv
    {d : Nat} (psi : SchwartzMap (Euclidean d) ℂ)
    {s : ℝ} (hs : 0 < s) :
    Integrable (fun x : Euclidean d =>
      ((s ^ d : ℝ) : ℂ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • x)) volume := by
  change Integrable (fun x : Euclidean d =>
    ((s ^ d : ℝ) : ℂ) * (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • x)) volume
  exact ((𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ).integrable.comp_smul hs.ne').const_mul _

/-- Normalized physical dilation preserves the `L¹` mass of the inverse
Schwartz kernel. -/
theorem integral_norm_scaled_fourierInv_eq
    {d : Nat} (psi : SchwartzMap (Euclidean d) ℂ)
    {s : ℝ} (hs : 0 < s) :
    (∫ x : Euclidean d,
      ‖((s ^ d : ℝ) : ℂ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • x)‖) =
        ∫ x : Euclidean d, ‖(𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) x‖ := by
  calc
    (∫ x : Euclidean d,
      ‖((s ^ d : ℝ) : ℂ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • x)‖) =
        ∫ x : Euclidean d,
          ‖(s ^ d : ℝ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • x)‖ := by
      congr with x
    _ = _ := integral_norm_dilate_eq d
      ((𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) : Euclidean d → ℂ) hs

private theorem integrable_sphere_translate_of_continuous
    {d : Nat} (f : Euclidean d → ℂ) (hf : Continuous f)
    (r : ℝ) (x : Euclidean d) :
    Integrable (fun omega : sphere (0 : Euclidean d) 1 =>
      f (x + r • (omega : Euclidean d))) (unitSurfaceMeasure d) := by
  apply Continuous.integrable_of_hasCompactSupport
  · exact hf.comp
      ((continuous_const : Continuous fun _ : sphere (0 : Euclidean d) 1 => x).add
        ((continuous_const : Continuous fun _ : sphere (0 : Euclidean d) 1 => r).smul
          continuous_subtype_val))
  · exact HasCompactSupport.of_compactSpace _

/-- Spherical averaging respects subtraction on continuous functions.  This
small algebraic fact keeps the later translation estimate tied to the literal
surface kernel, rather than to an abstract convolution wrapper. -/
theorem sphericalAverage_sub_of_continuous
    {d : Nat} (f g : Euclidean d → ℂ) (hf : Continuous f) (hg : Continuous g)
    (r : ℝ) (x : Euclidean d) :
    sphericalAverage d (f - g) r x =
      sphericalAverage d f r x - sphericalAverage d g r x := by
  unfold sphericalAverage
  change (∫ omega : sphere (0 : Euclidean d) 1,
    (f (x + r • (omega : Euclidean d)) - g (x + r • (omega : Euclidean d)))
      ∂unitSurfaceMeasure d) = _
  rw [integral_sub
    (integrable_sphere_translate_of_continuous f hf r x)
    (integrable_sphere_translate_of_continuous g hg r x)]

/-- A spatial translation commutes with spherical averaging.  Written in
difference form, this turns the spatial smoothness of the underlying kernel
into the Hörmander difference required by the lacunary bad-ball argument. -/
theorem sphericalAverage_sub_translate
    {d : Nat} (f : Euclidean d → ℂ) (hf : Continuous f)
    (r : ℝ) (h x : Euclidean d) :
    sphericalAverage d f r (x + h) - sphericalAverage d f r x =
      sphericalAverage d (fun y : Euclidean d => f (y + h) - f y) r x := by
  let g : Euclidean d → ℂ := fun y => f (h + y)
  have hg : Continuous g :=
    hf.comp ((continuous_const : Continuous fun _ : Euclidean d => h).add continuous_id)
  calc
    sphericalAverage d f r (x + h) - sphericalAverage d f r x =
        sphericalAverage d g r x - sphericalAverage d f r x := by
      simpa only [g, add_comm] using congrArg
        (fun z : ℂ => z - sphericalAverage d f r x)
        (sphericalAverage_translate d f r h x).symm
    _ = sphericalAverage d (g - f) r x :=
      (sphericalAverage_sub_of_continuous g f hg hf r x).symm
    _ = sphericalAverage d (fun y : Euclidean d => f (y + h) - f y) r x := by
      have hgf : g = fun y : Euclidean d => f (y + h) := by
        funext y
        simp only [g]
        rw [add_comm]
      rw [hgf]
      apply congrArg (fun q : Euclidean d → ℂ => sphericalAverage d q r x)
      funext y
      rfl

/-- The `L¹` translation difference of every spherical average is bounded by
the corresponding translation difference of its kernel, uniformly in the
spherical radius. -/
theorem integral_norm_sphericalAverage_sub_translate_le
    {d : Nat} (f : Euclidean d → ℂ) (hfcont : Continuous f)
    (hf : Integrable f volume) (r : ℝ) (h : Euclidean d) :
    (∫ x : Euclidean d,
      ‖sphericalAverage d f r (x + h) - sphericalAverage d f r x‖) ≤
      surfaceMass d * ∫ y : Euclidean d, ‖f (y + h) - f y‖ := by
  let g : Euclidean d → ℂ := fun y => f (y + h) - f y
  have hgcont : Continuous g :=
    (hfcont.comp (continuous_id.add continuous_const)).sub hfcont
  have hgint : Integrable g volume := (hf.comp_add_right h).sub hf
  calc
    (∫ x : Euclidean d,
      ‖sphericalAverage d f r (x + h) - sphericalAverage d f r x‖) =
        ∫ x : Euclidean d, ‖sphericalAverage d g r x‖ := by
      congr with x
      simpa only [g] using congrArg norm
        (sphericalAverage_sub_translate f hfcont r h x)
    _ ≤ surfaceMass d * ∫ y : Euclidean d, ‖g y‖ :=
      integral_norm_sphericalAverage_le_surfaceMass_mul g hgcont hgint r
    _ = surfaceMass d * ∫ y : Euclidean d, ‖f (y + h) - f y‖ := by rfl

/-- Spherical translation does not increase the `L¹` mass of a normalized
inverse-Schwartz kernel by more than the surface mass.  The bound is uniform
in both the physical dilation and the selected spherical radius. -/
theorem integral_norm_sphericalAverage_scaled_fourierInv_le
    {d : Nat} (psi : SchwartzMap (Euclidean d) ℂ)
    {s : ℝ} (hs : 0 < s) (r : ℝ) :
    (∫ x : Euclidean d,
      ‖sphericalAverage d
        (fun y : Euclidean d =>
          ((s ^ d : ℝ) : ℂ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • y)) r x‖) ≤
      surfaceMass d * ∫ x : Euclidean d,
        ‖(𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) x‖ := by
  let K : Euclidean d → ℂ := fun y =>
    ((s ^ d : ℝ) : ℂ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • y)
  have hKcont : Continuous K := by
    change Continuous (fun y : Euclidean d =>
      ((s ^ d : ℝ) : ℂ) * (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • y))
    exact continuous_const.mul
      ((𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ).continuous.comp
        ((continuous_const : Continuous fun _ : Euclidean d => s).smul continuous_id))
  have hKint : Integrable K volume := by
    simpa only [K] using integrable_scaled_fourierInv psi hs
  calc
    (∫ x : Euclidean d, ‖sphericalAverage d K r x‖) ≤
        surfaceMass d * ∫ x : Euclidean d, ‖K x‖ :=
      integral_norm_sphericalAverage_le_surfaceMass_mul K hKcont hKint r
    _ = surfaceMass d * ∫ x : Euclidean d,
        ‖(𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) x‖ := by
      rw [show (∫ x : Euclidean d, ‖K x‖) =
          ∫ x : Euclidean d, ‖(𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) x‖ by
        simpa only [K] using integral_norm_scaled_fourierInv_eq psi hs]

/-- The mean-zero high-frequency kernel remains mean zero after the spherical
translation appearing in one selected radius. -/
theorem integral_sphericalAverage_scaled_fourierInv_eq_zero_of_dyadic_difference
    {d : Nat} (phi psi : SchwartzMap (Euclidean d) ℂ)
    (hpsi : ∀ xi : Euclidean d, psi xi = phi ((2 : ℝ)⁻¹ • xi) - phi xi)
    {s : ℝ} (hs : 0 < s) (r : ℝ) :
    (∫ x : Euclidean d,
      sphericalAverage d
        (fun y : Euclidean d =>
          ((s ^ d : ℝ) : ℂ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • y)) r x) = 0 := by
  let K : Euclidean d → ℂ := fun y =>
    ((s ^ d : ℝ) : ℂ) • (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • y)
  have hKcont : Continuous K := by
    change Continuous (fun y : Euclidean d =>
      ((s ^ d : ℝ) : ℂ) * (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • y))
    exact continuous_const.mul
      ((𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ).continuous.comp
        ((continuous_const : Continuous fun _ : Euclidean d => s).smul continuous_id))
  have hKint : Integrable K volume := by
    change Integrable (fun y : Euclidean d =>
      ((s ^ d : ℝ) : ℂ) * (𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ) (s • y)) volume
    exact ((𝓕⁻ psi : SchwartzMap (Euclidean d) ℂ).integrable.comp_smul hs.ne').const_mul _
  calc
    (∫ x : Euclidean d, sphericalAverage d K r x) =
        (surfaceMass d : ℂ) * ∫ y : Euclidean d, K y :=
      integral_sphericalAverage_eq_surfaceMass_mul_integral K hKcont hKint r
    _ = 0 := by
      rw [show (∫ y : Euclidean d, K y) = 0 by
        simpa only [K] using
          integral_scaled_fourierInv_eq_zero_of_dyadic_difference phi psi hpsi hs]
      ring

end

end LeanSpherical.HarmonicAnalysis
