/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.PowerWeights.MeasureRegularity
import LeanSpherical.Codex.Spherical.PowerWeights.Dilation

/-!
# Dilation formulae for power-weighted moments

The local-to-global argument uses actual scale invariance, rather than an
abstract rescaling wrapper.  This file records the change of variables for a
power-weighted moment; the scalar is the usual `R^(-d-α)`.
-/

namespace LeanSpherical.HarmonicAnalysis

open MeasureTheory

noncomputable section

/-- A power-weighted nonnegative moment transforms under a positive Euclidean
dilation by the factor `R⁻ᵈ R⁻ᵅ`. -/
theorem integral_norm_rpow_mul_radialPowerWeight_toReal_comp_smul
    {d : ℕ} (f : Euclidean d → ℂ) (p α : ℝ) {R : ℝ} (hR : 0 < R) :
    (∫ x : Euclidean d, ‖f (R • x)‖ ^ p *
      (radialPowerWeight d α x).toReal) =
      (R ^ d)⁻¹ * R ^ (-α) *
        ∫ y : Euclidean d, ‖f y‖ ^ p *
          (radialPowerWeight d α y).toReal := by
  have hR0 : 0 ≤ R := hR.le
  have hpoint (x : Euclidean d) :
      ‖f (R • x)‖ ^ p * (radialPowerWeight d α x).toReal =
        R ^ (-α) *
          (‖f (R • x)‖ ^ p *
            (radialPowerWeight d α (R • x)).toReal) := by
    have hnorm : ‖R • x‖ = R * ‖x‖ := by
      rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg hR0]
    have hrewrite : ‖x‖ ^ α = R ^ (-α) * (R * ‖x‖) ^ α := by
      calc
        ‖x‖ ^ α = 1 * ‖x‖ ^ α := (one_mul _).symm
        _ = (R ^ (-α) * R ^ α) * ‖x‖ ^ α := by
          rw [← Real.rpow_add hR]
          norm_num
        _ = R ^ (-α) * (R * ‖x‖) ^ α := by
          rw [Real.mul_rpow hR0 (norm_nonneg x)]
          ring
    calc
      ‖f (R • x)‖ ^ p * (radialPowerWeight d α x).toReal =
          ‖f (R • x)‖ ^ p * ‖x‖ ^ α := by
            rw [radialPowerWeight_toReal]
      _ = ‖f (R • x)‖ ^ p * (R ^ (-α) * (R * ‖x‖) ^ α) := by
            rw [hrewrite]
      _ = R ^ (-α) * (‖f (R • x)‖ ^ p * (R * ‖x‖) ^ α) := by
            ring
      _ = R ^ (-α) *
          (‖f (R • x)‖ ^ p * (radialPowerWeight d α (R • x)).toReal) := by
            rw [radialPowerWeight_toReal, hnorm]
  calc
    (∫ x : Euclidean d, ‖f (R • x)‖ ^ p *
        (radialPowerWeight d α x).toReal) =
        ∫ x : Euclidean d, R ^ (-α) *
          (‖f (R • x)‖ ^ p *
            (radialPowerWeight d α (R • x)).toReal) := by
          apply integral_congr_ae
          filter_upwards with x
          exact hpoint x
    _ = R ^ (-α) * ∫ x : Euclidean d,
        ‖f (R • x)‖ ^ p * (radialPowerWeight d α (R • x)).toReal := by
          rw [integral_const_mul]
    _ = R ^ (-α) * ((R ^ d)⁻¹ *
        ∫ y : Euclidean d, ‖f y‖ ^ p *
          (radialPowerWeight d α y).toReal) := by
          rw [Measure.integral_comp_smul_of_nonneg volume
            (fun y : Euclidean d => ‖f y‖ ^ p *
              (radialPowerWeight d α y).toReal) R (hR := hR0)]
          simp only [finrank_euclideanSpace_fin, smul_eq_mul]
    _ = (R ^ d)⁻¹ * R ^ (-α) *
        ∫ y : Euclidean d, ‖f y‖ ^ p *
          (radialPowerWeight d α y).toReal := by
          ring

end

end LeanSpherical.HarmonicAnalysis
