
/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.PowerWeights.ThinRadialTailSummation
import LeanSpherical.Codex.Spherical.PowerWeights.ThinRadialTailRawEnvelope
import LeanSpherical.Codex.Spherical.PowerWeights.ThinRadialTailVolume
import LeanSpherical.Codex.Spherical.PowerWeights.ThinRadialStrictCap
import LeanSpherical.Codex.Spherical.PowerWeights.ThinRadialSpatialReassembly
import LeanSpherical.Codex.Spherical.PowerWeights.PhysicalCentralAnnulus
open Codex.Spherical.PowerWeights.AnnularWeight
open Codex.Spherical.PowerWeights.Entropy
open Codex.Spherical.PowerWeights.PowerMeasure
open Codex.Spherical.PowerWeights.ThinRadialPartition
open Codex.Spherical.PowerWeights.ThinRadialTailGaps
open Codex.Spherical.PowerWeights.ThinRadialTailNumerics
open Codex.Spherical.SurfaceCore







/-!
# Raw strict-negative relative-band bounds

This file is the focused production layer between the literal thin-radial
cap/tail estimates and the final summable-band assembly.  It keeps the
central cap and off-window tail coefficients explicit, rather than hiding
them behind a new operator abstraction.
-/

namespace Codex.Spherical.PowerWeights.StrictNegativeRawBands

open MeasureTheory Metric Set
open scoped BigOperators ENNReal NNReal

noncomputable section

/-- The nonconstant part of one off-window distance-block moment after the
annular volume factor has been extracted.  Here `n + 1` is the ambient
dimension, `k` is the spatial shell, and `q` is the distance-block index. -/
def thinRadialTailRawCoefficient
    (n j k q : Nat) (C : Real) (p alpha : Real) : ENNReal :=
  ((((j + 1 : Nat) : ENNReal) * ENNReal.ofReal (C * (2 : Real) ^ j) *
      (ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3))) ^
        (j - k - 1 + q - 6)) ^ p) *
    ((2 ^ (q + 1) : Nat) : ENNReal) ^ p *
      (ENNReal.ofReal (((2 : Real) ^ k)⁻¹)) ^ ((n : Real) + alpha + p)

private theorem thinRadialTail_half_nat_rpow_rpow
    (x : ENNReal) (m : Nat) (p : Real) :
    (x ^ m) ^ p = x ^ (p * (m : Real)) := by
  rw [← ENNReal.rpow_natCast]
  rw [← ENNReal.rpow_mul]
  congr 1
  ring

/-- The clipped six-index loss in the tail cutoff is a fixed factor. -/
private theorem thinRadialTail_half_index_loss
    (N m q : Nat) :
    ((ENNReal.ofReal (1 / 2 : Real)) ^ N) ^ (m + q - 6) ≤
      (ENNReal.ofReal (1 / 2 : Real)) ^ (-6 * (N : Real)) *
        (ENNReal.ofReal (1 / 2 : Real)) ^ ((N : Real) * (m : Real)) *
          (ENNReal.ofReal (1 / 2 : Real)) ^ ((N : Real) * (q : Real)) := by
  let x : ENNReal := ENNReal.ofReal (1 / 2 : Real)
  have hx0 : x ≠ 0 := by
    dsimp only [x]
    exact (ENNReal.ofReal_pos.mpr (by norm_num)).ne'
  have hxtop : x ≠ ∞ := by
    dsimp only [x]
    exact ENNReal.ofReal_ne_top
  have hxle : x ≤ 1 := by
    dsimp only [x]
    norm_num
  have hcombine (a b : Real) : x ^ a * x ^ b = x ^ (a + b) := by
    rw [ENNReal.rpow_add a b hx0 hxtop]
  have hright :
      x ^ (-6 * (N : Real)) * x ^ ((N : Real) * (m : Real)) *
        x ^ ((N : Real) * (q : Real)) =
      x ^ (-6 * (N : Real) + (N : Real) * (m : Real) +
        (N : Real) * (q : Real)) := by
    rw [hcombine, hcombine]
  have hleft :
      (x ^ N) ^ (m + q - 6) =
        x ^ ((N : Real) * ((m + q - 6 : Nat) : Real)) := by
    rw [← pow_mul]
    rw [← ENNReal.rpow_natCast]
    congr 1
    push_cast
    ring
  have hexp :
      -6 * (N : Real) + (N : Real) * (m : Real) + (N : Real) * (q : Real) ≤
        (N : Real) * ((m + q - 6 : Nat) : Real) := by
    have hN : 0 ≤ (N : Real) := by positivity
    by_cases hmq : 6 ≤ m + q
    · rw [Nat.cast_sub hmq]
      push_cast
      ring_nf
      exact le_rfl
    · have hsmall : m + q ≤ 5 := by omega
      have hzero : m + q - 6 = 0 := by omega
      rw [hzero]
      norm_num
      have hmqreal : (m : Real) + (q : Real) ≤ 6 := by
        exact_mod_cast (show m + q ≤ 6 by omega)
      nlinarith
  change (x ^ N) ^ (m + q - 6) ≤
    x ^ (-6 * (N : Real)) * x ^ ((N : Real) * (m : Real)) *
      x ^ ((N : Real) * (q : Real))
  rw [hleft, hright]
  exact ENNReal.rpow_le_rpow_of_exponent_ge hxle hexp

/-- The literal tail coefficient in `ThinRadialTailMoment` is bounded by
the separated raw coefficient above once the weighted annular prefactor is
put at its homogeneous scale.  This applies unchanged to the lower and
upper distance blocks, whose displayed tail coefficients are identical. -/
theorem thinRadialTail_moment_rhs_le_rawCoefficient
    {n j k q : Nat} (hjk : k + 1 ≤ j) (hq : q ≤ k + 4)
    (C : Real) {p alpha s : Real} (hp : 1 ≤ p)
    (hs : 0 < s) (hscale : s = ((2 : Real) ^ k)⁻¹)
    (V I : ENNReal)
    (hvolume :
      powerWeightedVolume (n + 1) alpha
          (euclideanAnnulus (n + 1) (s / 4) (s / 2)) *
        ((ENNReal.ofReal (surfaceMass (n + 1)) *
            (ENNReal.ofReal (8 : Real)) ^ n * ENNReal.ofReal (3 / 2 : Real) *
              ENNReal.ofReal s) ^ (p - 1)) ≤
        V * (ENNReal.ofReal s) ^ ((n : Real) + alpha + p)) :
    powerWeightedVolume (n + 1) alpha
        (euclideanAnnulus (n + 1) (s / 4) (s / 2)) *
      (((j : ENNReal) *
            (ENNReal.ofReal (C * (2 : Real) ^ j) *
              (ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3))) ^
                thinRadialDistanceCutoff j k q) +
          ENNReal.ofReal (C * (2 : Real) ^ j) *
            (ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3))) ^ (j - 3)) ^ p *
        ((2 ^ (q + 1) : Nat) : ENNReal) ^ p *
        ((ENNReal.ofReal (surfaceMass (n + 1)) *
            (ENNReal.ofReal (8 : Real)) ^ n * ENNReal.ofReal (3 / 2 : Real) *
              ENNReal.ofReal s) ^ (p - 1)) *
          ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
            ((ENNReal.ofReal 2) ^ p * 2) * I) ≤
      (V * ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
        ((ENNReal.ofReal 2) ^ p * 2)) *
          thinRadialTailRawCoefficient n j k q C p alpha * I := by
  let b : ENNReal := ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3))
  let A : ENNReal := ENNReal.ofReal (C * (2 : Real) ^ j)
  let Q : ENNReal :=
    (j : ENNReal) * (A * b ^ thinRadialDistanceCutoff j k q) +
      A * b ^ (j - 3)
  let Qbound : ENNReal :=
    ((j + 1 : Nat) : ENNReal) * A * b ^ (j - k - 1 + q - 6)
  have hp0 : 0 ≤ p := by linarith
  have hQ : Q ≤ Qbound := by
    simpa only [Q, Qbound, A, b, mul_assoc] using
      thinRadialTail_distance_coefficient_le (n := n) hjk hq A
  have hQpow : Q ^ p ≤ Qbound ^ p := ENNReal.rpow_le_rpow hQ hp0
  have hfactor := mul_le_mul_right hvolume
    (Qbound ^ p * ((2 ^ (q + 1) : Nat) : ENNReal) ^ p *
      ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
        ((ENNReal.ofReal 2) ^ p * 2) * I)
  change
    powerWeightedVolume (n + 1) alpha
        (euclideanAnnulus (n + 1) (s / 4) (s / 2)) *
      (Q ^ p * ((2 ^ (q + 1) : Nat) : ENNReal) ^ p *
        ((ENNReal.ofReal (surfaceMass (n + 1)) *
            (ENNReal.ofReal (8 : Real)) ^ n * ENNReal.ofReal (3 / 2 : Real) *
              ENNReal.ofReal s) ^ (p - 1)) *
          ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
            ((ENNReal.ofReal 2) ^ p * 2) * I) ≤ _
  calc
    powerWeightedVolume (n + 1) alpha
        (euclideanAnnulus (n + 1) (s / 4) (s / 2)) *
      (Q ^ p * ((2 ^ (q + 1) : Nat) : ENNReal) ^ p *
        ((ENNReal.ofReal (surfaceMass (n + 1)) *
            (ENNReal.ofReal (8 : Real)) ^ n * ENNReal.ofReal (3 / 2 : Real) *
              ENNReal.ofReal s) ^ (p - 1)) *
          ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
            ((ENNReal.ofReal 2) ^ p * 2) * I) ≤
        powerWeightedVolume (n + 1) alpha
          (euclideanAnnulus (n + 1) (s / 4) (s / 2)) *
        (Qbound ^ p * ((2 ^ (q + 1) : Nat) : ENNReal) ^ p *
          ((ENNReal.ofReal (surfaceMass (n + 1)) *
              (ENNReal.ofReal (8 : Real)) ^ n * ENNReal.ofReal (3 / 2 : Real) *
                ENNReal.ofReal s) ^ (p - 1)) *
            ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
              ((ENNReal.ofReal 2) ^ p * 2) * I) := by
          gcongr
    _ =
        (powerWeightedVolume (n + 1) alpha
            (euclideanAnnulus (n + 1) (s / 4) (s / 2)) *
          ((ENNReal.ofReal (surfaceMass (n + 1)) *
              (ENNReal.ofReal (8 : Real)) ^ n * ENNReal.ofReal (3 / 2 : Real) *
                ENNReal.ofReal s) ^ (p - 1))) *
          (Qbound ^ p * ((2 ^ (q + 1) : Nat) : ENNReal) ^ p *
            ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
              ((ENNReal.ofReal 2) ^ p * 2) * I) := by ring
    _ ≤
        (V * (ENNReal.ofReal s) ^ ((n : Real) + alpha + p)) *
          (Qbound ^ p * ((2 ^ (q + 1) : Nat) : ENNReal) ^ p *
            ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
              ((ENNReal.ofReal 2) ^ p * 2) * I) := by
          gcongr
    _ =
        (V * ((ENNReal.ofReal (8 : Real)) ^ alpha)⁻¹ *
          ((ENNReal.ofReal 2) ^ p * 2)) *
            thinRadialTailRawCoefficient n j k q C p alpha * I := by
          dsimp only [thinRadialTailRawCoefficient, Qbound, A, b]
          rw [hscale]
          ring

/-- The raw tail coefficient has one dyadic gain in the frequency index
and two geometric gains, in the reverse shell distance and distance-block
indices.  The fixed six-index clipping loss is included in the constant. -/
theorem thinRadialTailRawCoefficient_le_geometric
    {n j k q : Nat} (hjk : k + 1 ≤ j) (C : Real) {p alpha : Real}
    (hC : 0 ≤ C) (hp : 0 ≤ p) :
    thinRadialTailRawCoefficient n j k q C p alpha ≤
      (ENNReal.ofReal C) ^ p *
        (ENNReal.ofReal (1 / 2 : Real)) ^
          (-(p * (6 * (n : Real) + 26) + (n : Real) + alpha)) *
        ((j + 1 : Nat) : ENNReal) ^ p *
        (dyadicMultiplicativeScale j : ENNReal) ^ ((n : Real) + alpha) *
        ((ENNReal.ofReal (1 / 2 : Real)) ^
          (p * ((n : Real) + 3) - ((n : Real) + alpha))) ^ (j - k - 1) *
        ((ENNReal.ofReal (1 / 2 : Real)) ^
          (p * ((n : Real) + 3))) ^ q := by
  let x : ENNReal := ENNReal.ofReal (1 / 2 : Real)
  have hA : ENNReal.ofReal (C * (2 : Real) ^ j) =
      ENNReal.ofReal C * x ^ (-(j : Real)) := by
    rw [ENNReal.ofReal_mul hC]
    change ENNReal.ofReal C * ENNReal.ofReal ((2 : Real) ^ j) = _
    rw [show ENNReal.ofReal ((2 : Real) ^ j) = x ^ (-(j : Real)) by
      dsimp only [x]
      rw [ENNReal.ofReal_pow (by norm_num : (0 : Real) ≤ 2)]
      rw [← ENNReal.rpow_natCast]
      rw [show ENNReal.ofReal (1 / 2 : Real) =
          (ENNReal.ofReal (2 : Real))⁻¹ by
        rw [← ENNReal.ofReal_inv_of_pos (by norm_num : (0 : Real) < 2)]
        norm_num]
      rw [ENNReal.inv_rpow]
      rw [← ENNReal.rpow_neg]
      congr 1
      ring]
  have hb : ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3)) =
      x ^ (n + 1 + 3) := by
    dsimp only [x]
    rw [show (2 : Real)⁻¹ = 1 / 2 by norm_num]
    rw [ENNReal.ofReal_pow (by norm_num : (0 : Real) ≤ 1 / 2)]
  have hscale (k : Nat) (D : Real) :
      (ENNReal.ofReal (((2 : Real) ^ k)⁻¹)) ^ D = x ^ ((k : Real) * D) := by
    dsimp only [x]
    rw [show ENNReal.ofReal (((2 : Real) ^ k)⁻¹) =
        (ENNReal.ofReal (1 / 2 : Real)) ^ k by
      rw [show ((2 : Real) ^ k)⁻¹ = ((1 / 2 : Real) ^ k) by
        rw [← inv_pow]
        norm_num]
      rw [ENNReal.ofReal_pow (by norm_num : (0 : Real) ≤ 1 / 2)]]
    simpa only [mul_comm] using thinRadialTail_half_nat_rpow_rpow _ _ _
  have hq (q : Nat) :
      ((2 ^ (q + 1) : Nat) : ENNReal) ^ p = x ^ (-p * ((q + 1 : Nat) : Real)) := by
    dsimp only [x]
    rw [Nat.cast_pow]
    have htwo : ((↑(2 : Nat) : ENNReal)) = ENNReal.ofReal (2 : Real) := by norm_num
    rw [htwo]
    rw [show ENNReal.ofReal (2 : Real) =
        (ENNReal.ofReal (1 / 2 : Real))⁻¹ by
      symm
      rw [← ENNReal.ofReal_inv_of_pos (by norm_num : (0 : Real) < 1 / 2)]
      norm_num]
    rw [← ENNReal.rpow_natCast]
    rw [ENNReal.inv_rpow]
    rw [← ENNReal.rpow_neg]
    rw [← ENNReal.rpow_mul]
    congr 1
    ring
  have hdelta (j : Nat) : (dyadicMultiplicativeScale j : ENNReal) = x ^ j := by
    dsimp only [dyadicMultiplicativeScale]
    simp only [ENNReal.coe_pow]
    congr 1
    rw [ENNReal.coe_inv (by norm_num : (2 : NNReal) ≠ 0)]
    have htwo : (↑(2 : NNReal) : ENNReal) = ENNReal.ofReal (2 : Real) := by
      norm_num
    rw [htwo]
    rw [← ENNReal.ofReal_inv_of_pos (by norm_num : (0 : Real) < 2)]
    norm_num
    rfl
  have hx0 : x ≠ 0 := by
    dsimp only [x]
    exact (ENNReal.ofReal_pos.mpr (by norm_num)).ne'
  have hxtop : x ≠ ∞ := by
    dsimp only [x]
    exact ENNReal.ofReal_ne_top
  have hcombine (a b : Real) : x ^ a * x ^ b = x ^ (a + b) := by
    rw [ENNReal.rpow_add a b hx0 hxtop]
  have hfour (a b c d : Real) :
      x ^ a * x ^ b * x ^ c * x ^ d = x ^ (a + b + c + d) := by
    rw [hcombine, hcombine, hcombine]
  have hsix (a b c d e f : Real) :
      x ^ a * x ^ b * x ^ c * x ^ d * x ^ e * x ^ f =
        x ^ (a + b + c + d + e + f) := by
    rw [hcombine, hcombine, hcombine, hcombine, hcombine]
  have htail :
      (x ^ (n + 1 + 3)) ^ (j - k - 1 + q - 6) ≤
        x ^ (-6 * ((n + 1 + 3 : Nat) : Real)) *
          x ^ (((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real)) *
            x ^ (((n + 1 + 3 : Nat) : Real) * (q : Real)) := by
    simpa only [x] using
      thinRadialTail_half_index_loss (n + 1 + 3) (j - k - 1) q
  have htailp := ENNReal.rpow_le_rpow htail hp
  rw [hdelta]
  rw [thinRadialTail_half_nat_rpow_rpow]
  rw [← ENNReal.rpow_natCast]
  rw [← ENNReal.rpow_mul]
  rw [← ENNReal.rpow_natCast]
  rw [← ENNReal.rpow_mul]
  change thinRadialTailRawCoefficient n j k q C p alpha ≤
    (ENNReal.ofReal C) ^ p * x ^
        (-(p * (6 * (n : Real) + 26) + (n : Real) + alpha)) *
      ((j + 1 : Nat) : ENNReal) ^ p *
        x ^ (((n : Real) + alpha) * (j : Real)) *
        x ^ ((p * ((n : Real) + 3) - ((n : Real) + alpha)) *
          ((j - k - 1 : Nat) : Real)) *
          x ^ (p * ((n : Real) + 3) * (q : Real))
  have hrawEq :
      thinRadialTailRawCoefficient n j k q C p alpha =
        ((j + 1 : Nat) : ENNReal) ^ p *
          ((ENNReal.ofReal C) ^ p * (x ^ (-(j : Real))) ^ p) *
            ((x ^ (n + 1 + 3)) ^ (j - k - 1 + q - 6)) ^ p *
              x ^ (-p * ((q + 1 : Nat) : Real)) *
                x ^ ((k : Real) * ((n : Real) + alpha + p)) := by
    unfold thinRadialTailRawCoefficient
    rw [hA, hb, hq, hscale]
    rw [ENNReal.mul_rpow_of_nonneg _ _ hp]
    rw [ENNReal.mul_rpow_of_nonneg _ _ hp]
    rw [ENNReal.mul_rpow_of_nonneg _ _ hp]
  have hApow : (x ^ (-(j : Real))) ^ p = x ^ (-(j : Real) * p) := by
    rw [← ENNReal.rpow_mul]
  have hEnvEq :
      (x ^ (-6 * ((n + 1 + 3 : Nat) : Real)) *
        x ^ (((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real)) *
          x ^ (((n + 1 + 3 : Nat) : Real) * (q : Real))) ^ p =
        x ^ ((-6 * ((n + 1 + 3 : Nat) : Real)) * p) *
          x ^ ((((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real)) * p) *
            x ^ ((((n + 1 + 3 : Nat) : Real) * (q : Real)) * p) := by
    rw [ENNReal.mul_rpow_of_nonneg _ _ hp]
    rw [ENNReal.mul_rpow_of_nonneg _ _ hp]
    rw [← ENNReal.rpow_mul]
    rw [← ENNReal.rpow_mul]
    rw [← ENNReal.rpow_mul]
  have hmiddle :
      thinRadialTailRawCoefficient n j k q C p alpha ≤
        ((j + 1 : Nat) : ENNReal) ^ p *
          ((ENNReal.ofReal C) ^ p * x ^ (-(j : Real) * p)) *
            (x ^ ((-6 * ((n + 1 + 3 : Nat) : Real)) * p) *
              x ^ ((((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real)) * p) *
                x ^ ((((n + 1 + 3 : Nat) : Real) * (q : Real)) * p)) *
              x ^ (-p * ((q + 1 : Nat) : Real)) *
                x ^ ((k : Real) * ((n : Real) + alpha + p)) := by
    rw [hrawEq]
    calc
      _ ≤ ((j + 1 : Nat) : ENNReal) ^ p *
          ((ENNReal.ofReal C) ^ p * (x ^ (-(j : Real))) ^ p) *
            (x ^ (-6 * ((n + 1 + 3 : Nat) : Real)) *
              x ^ (((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real)) *
                x ^ (((n + 1 + 3 : Nat) : Real) * (q : Real))) ^ p *
              x ^ (-p * ((q + 1 : Nat) : Real)) *
                x ^ ((k : Real) * ((n : Real) + alpha + p)) := by
          gcongr
      _ = _ := by rw [hApow, hEnvEq]
  have hExp :
      (-(j : Real) * p) +
          (-6 * ((n + 1 + 3 : Nat) : Real) * p) +
          (((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real) * p) +
          (((n + 1 + 3 : Nat) : Real) * (q : Real) * p) +
          (-p * ((q + 1 : Nat) : Real)) +
          ((k : Real) * ((n : Real) + alpha + p)) =
        (-(p * (6 * (n : Real) + 26) + (n : Real) + alpha)) +
          ((n : Real) + alpha) * (j : Real) +
          (p * ((n : Real) + 3) - ((n : Real) + alpha)) *
            ((j - k - 1 : Nat) : Real) +
          p * ((n : Real) + 3) * (q : Real) := by
    have hk : k ≤ j := by omega
    have hlast : 1 ≤ j - k := by omega
    have hmcast : ((j - k - 1 : Nat) : Real) =
        (j : Real) - (k : Real) - 1 := by
      calc
        ((j - k - 1 : Nat) : Real) = ((j - k : Nat) : Real) - 1 := by
          rw [Nat.cast_sub hlast]
          norm_num
        _ = (j : Real) - (k : Real) - 1 := by rw [Nat.cast_sub hk]
    rw [hmcast]
    push_cast
    ring
  have hmiddleEq :
      ((j + 1 : Nat) : ENNReal) ^ p *
          ((ENNReal.ofReal C) ^ p * x ^ (-(j : Real) * p)) *
            (x ^ ((-6 * ((n + 1 + 3 : Nat) : Real)) * p) *
              x ^ ((((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real)) * p) *
                x ^ ((((n + 1 + 3 : Nat) : Real) * (q : Real)) * p)) *
              x ^ (-p * ((q + 1 : Nat) : Real)) *
                x ^ ((k : Real) * ((n : Real) + alpha + p)) =
        (ENNReal.ofReal C) ^ p * x ^
            (-(p * (6 * (n : Real) + 26) + (n : Real) + alpha)) *
          ((j + 1 : Nat) : ENNReal) ^ p *
            x ^ (((n : Real) + alpha) * (j : Real)) *
              x ^ ((p * ((n : Real) + 3) - ((n : Real) + alpha)) *
                ((j - k - 1 : Nat) : Real)) *
                x ^ (p * ((n : Real) + 3) * (q : Real)) := by
    calc
      _ = (ENNReal.ofReal C) ^ p * ((j + 1 : Nat) : ENNReal) ^ p *
          x ^ (-(j : Real) * p) *
          x ^ (-6 * ((n + 1 + 3 : Nat) : Real) * p) *
          x ^ (((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real) * p) *
          x ^ (((n + 1 + 3 : Nat) : Real) * (q : Real) * p) *
          x ^ (-p * ((q + 1 : Nat) : Real)) *
          x ^ ((k : Real) * ((n : Real) + alpha + p)) := by
            ring
      _ = (ENNReal.ofReal C) ^ p * ((j + 1 : Nat) : ENNReal) ^ p *
          (x ^ (-(j : Real) * p) *
            x ^ (-6 * ((n + 1 + 3 : Nat) : Real) * p) *
            x ^ (((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real) * p) *
            x ^ (((n + 1 + 3 : Nat) : Real) * (q : Real) * p) *
              x ^ (-p * ((q + 1 : Nat) : Real)) *
              x ^ ((k : Real) * ((n : Real) + alpha + p))) := by
              ac_rfl
      _ = (ENNReal.ofReal C) ^ p * ((j + 1 : Nat) : ENNReal) ^ p *
          x ^ ((-(j : Real) * p) +
            (-6 * ((n + 1 + 3 : Nat) : Real) * p) +
            (((n + 1 + 3 : Nat) : Real) * ((j - k - 1 : Nat) : Real) * p) +
            (((n + 1 + 3 : Nat) : Real) * (q : Real) * p) +
            (-p * ((q + 1 : Nat) : Real)) +
            ((k : Real) * ((n : Real) + alpha + p))) := by
              rw [hsix]
      _ = (ENNReal.ofReal C) ^ p * ((j + 1 : Nat) : ENNReal) ^ p *
          x ^ ((-(p * (6 * (n : Real) + 26) + (n : Real) + alpha)) +
            ((n : Real) + alpha) * (j : Real) +
            (p * ((n : Real) + 3) - ((n : Real) + alpha)) *
              ((j - k - 1 : Nat) : Real) +
            p * ((n : Real) + 3) * (q : Real)) := by rw [hExp]
      _ = (ENNReal.ofReal C) ^ p * ((j + 1 : Nat) : ENNReal) ^ p *
          (x ^ (-(p * (6 * (n : Real) + 26) + (n : Real) + alpha)) *
            x ^ (((n : Real) + alpha) * (j : Real)) *
              x ^ ((p * ((n : Real) + 3) - ((n : Real) + alpha)) *
                ((j - k - 1 : Nat) : Real)) *
                  x ^ (p * ((n : Real) + 3) * (q : Real))) := by
            rw [hfour]
      _ = _ := by ring
  exact hmiddle.trans_eq hmiddleEq

end

end Codex.Spherical.PowerWeights.StrictNegativeRawBands