
/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.PowerWeights.ThinRadialGeometry
import LeanSpherical.Codex.Spherical.PowerWeights.EntropyDilation
open Codex.Spherical.PowerWeights.Definitions
open Codex.Spherical.PowerWeights.Entropy
open Codex.Spherical.PowerWeights.EntropyAsymptotics
open Codex.Spherical.PowerWeights.EntropyBounds
open Codex.Spherical.PowerWeights.EntropyDilation
open Codex.Spherical.PowerWeights.FiniteFrequency
open Codex.Spherical.PowerWeights.LocalBlocks
open Codex.Spherical.PowerWeights.StrictImplicitEntropyBounds
open Codex.Spherical.PowerWeights.ThinRadialGeometry







/-!
# Uniform normalized thin-window entropy

The strict local entropy estimate is unchanged after passing to a normalized
radius block.  This small lemma keeps the cutoff scale uniform in the block
radius, which is the form needed by the finite relative-cutoff argument.
-/

namespace Codex.Spherical.PowerWeights.ThinRadialUniformEntropy

open Filter Set
open scoped ENNReal NNReal Topology

noncomputable section

/-- At sufficiently fine relative-frequency scales, every nonempty thin
window in every normalized radius block has the same strict local entropy
power bound. -/
theorem exists_tail_small_scale_normalized_thinRadiusWindow_entropy_nat_bound_of_strict_implicit
    {d : Nat} (hd : 2 ≤ d) {E : Set Real} {p alpha : Real}
    (hp : 1 < p)
    (hstrict :
      max ((alpha : EReal) + multiplicativeMinkowskiExponent E)
          (multiplicativeLegendreAssouadExponent E
            (((d : Real) - 1) * (p - 2) - alpha)) <
        ((((d : Real) - 1) * (p - 1) : Real) : EReal)) :
    ∃ epsilon : Real, 0 < epsilon ∧
      epsilon < ((d : Real) - 1) * (p - 1) ∧
      ∃ j0 : Nat, ∀ j ≥ j0, ∀ (R : Real), 0 < R → ∀ (s : Real) (mu : Int),
        0 < s → s ≤ 1 / 16 →
        (dyadicMultiplicativeScale j : Real) ≤ 16 * s →
        ((normalizedRadiusBlock E R) ∩ thinRadiusWindow s mu).Nonempty →
        ∃ N : Nat,
          multiplicativeEntropy ((normalizedRadiusBlock E R) ∩ thinRadiusWindow s mu)
              (dyadicMultiplicativeScale j) ≤ N ∧
          (N : ENNReal) ≤
            (ENNReal.ofReal (16 * s)) ^
              (((d : Real) - 1) * (p - 2) - alpha) *
            ((dyadicMultiplicativeScale j : ENNReal)⁻¹) ^
              (((d : Real) - 1) * (p - 1) - epsilon) := by
  obtain ⟨epsilon, hepsilon, hepsilonlt, _hMinkowski, hLegendre, _hlocal⟩ :=
    exists_eventually_localMultiplicativeEntropy_power_bound_of_strict_implicit
      hd hp hstrict
  have hprofile : ∀ᶠ delta : NNReal in 𝓝[>] (0 : NNReal),
      multiplicativeLegendreAssouadProfile E
          (((d : Real) - 1) * (p - 2) - alpha) delta ≤
        ((delta : ENNReal)⁻¹) ^
          (((d : Real) - 1) * (p - 1) - epsilon) :=
    eventually_multiplicativeLegendreAssouadProfile_le_inv_rpow_of_exponent_lt
      hLegendre
  have htail : ∀ᶠ j : Nat in atTop,
      ∀ (R : Real), 0 < R → ∀ (s : Real) (mu : Int),
        0 < s → s ≤ 1 / 16 →
        (dyadicMultiplicativeScale j : Real) ≤ 16 * s →
        ((normalizedRadiusBlock E R) ∩ thinRadiusWindow s mu).Nonempty →
        ∃ N : Nat,
          multiplicativeEntropy ((normalizedRadiusBlock E R) ∩ thinRadiusWindow s mu)
              (dyadicMultiplicativeScale j) ≤ N ∧
          (N : ENNReal) ≤
            (ENNReal.ofReal (16 * s)) ^
              (((d : Real) - 1) * (p - 2) - alpha) *
            ((dyadicMultiplicativeScale j : ENNReal)⁻¹) ^
              (((d : Real) - 1) * (p - 1) - epsilon) := by
    have hseq := tendsto_dyadicMultiplicativeScale_atTop_nhdsWithin_zero.eventually hprofile
    filter_upwards [hseq] with j hprofilej
    intro R hR s mu hs hssmall hdeltaD hne
    have hbase : 13 / 16 ≤ s * ((mu : Real) - 1) :=
      thinRadiusWindow_base_lower_thirteen_sixteenths_of_inter_nonempty
        hssmall (normalizedRadiusBlock_subset_Icc_one_two hR) hne
    have hDone : 16 * s ≤ 1 := by nlinarith
    let D : NNReal := ⟨16 * s, by positivity⟩
    have hdeltaDnn : dyadicMultiplicativeScale j ≤ D := by
      exact_mod_cast hdeltaD
    have hDoneNN : D ≤ 1 := by
      exact_mod_cast hDone
    let diam : Icc (dyadicMultiplicativeScale j) 1 := ⟨D, hdeltaDnn, hDoneNN⟩
    let c : PositiveRadius :=
      ⟨s * ((mu : Real) - 1), lt_of_lt_of_le (by norm_num) hbase⟩
    have hwindow : thinRadiusWindow s mu ⊆ multiplicativeInterval c D := by
      simpa only [c, D] using
        (thinRadiusWindow_subset_multiplicativeInterval_small_scale hs hbase)
    have hlocal :
        localMultiplicativeEntropy (normalizedRadiusBlock E R) c D
            (dyadicMultiplicativeScale j) ≤
          ((D : ENNReal) ^ (((d : Real) - 1) * (p - 2) - alpha) *
            ((dyadicMultiplicativeScale j : ENNReal)⁻¹) ^
              (((d : Real) - 1) * (p - 1) - epsilon)) := by
      calc
        localMultiplicativeEntropy (normalizedRadiusBlock E R) c D
            (dyadicMultiplicativeScale j) ≤
            ((D : ENNReal) ^ (((d : Real) - 1) * (p - 2) - alpha) *
              multiplicativeLegendreAssouadProfile (normalizedRadiusBlock E R)
                (((d : Real) - 1) * (p - 2) - alpha)
                (dyadicMultiplicativeScale j)) :=
          localMultiplicativeEntropy_le_diam_rpow_mul_of_profile_le
            (dyadicMultiplicativeScale_pos j) (le_refl _)
              c diam
        _ ≤ ((D : ENNReal) ^ (((d : Real) - 1) * (p - 2) - alpha) *
              ((dyadicMultiplicativeScale j : ENNReal)⁻¹) ^
                (((d : Real) - 1) * (p - 1) - epsilon)) := by
          gcongr
          exact (multiplicativeLegendreAssouadProfile_normalizedRadiusBlock_le
            E hR (((d : Real) - 1) * (p - 2) - alpha)
            (dyadicMultiplicativeScale j)).trans hprofilej
    obtain ⟨N, hN, hNbound⟩ :=
      exists_local_entropy_nat_witness_of_power_bound
        (A := 1) (p := 1) (rho := ((d : Real) - 1) * (p - 2) - alpha)
        (s := ((d : Real) - 1) * (p - 1) - epsilon)
        (dyadicMultiplicativeScale_pos j) c diam (by simpa using hlocal)
    refine ⟨N, ?_, ?_⟩
    · calc
        multiplicativeEntropy ((normalizedRadiusBlock E R) ∩ thinRadiusWindow s mu)
            (dyadicMultiplicativeScale j) ≤
            multiplicativeEntropy
              ((normalizedRadiusBlock E R) ∩ multiplicativeInterval c D)
                (dyadicMultiplicativeScale j) :=
          multiplicativeEntropy_mono (by
            intro r hr
            exact ⟨hr.1, hwindow hr.2⟩) _
        _ = localMultiplicativeEntropy (normalizedRadiusBlock E R) c D
              (dyadicMultiplicativeScale j) := rfl
        _ = localMultiplicativeEntropy (normalizedRadiusBlock E R) c diam.1
              (dyadicMultiplicativeScale j) := by simp [diam]
        _ ≤ N := hN
    · have hDcoe : (D : ENNReal) = ENNReal.ofReal (16 * s) := by
        rw [ENNReal.coe_nnreal_eq]
        change ENNReal.ofReal (16 * s) = ENNReal.ofReal (16 * s)
        rfl
      have hNbound' : (N : ENNReal) ≤
          ((diam.1 : NNReal) : ENNReal) ^
              (((d : Real) - 1) * (p - 2) - alpha) *
            ((dyadicMultiplicativeScale j : ENNReal)⁻¹) ^
              (((d : Real) - 1) * (p - 1) - epsilon) := by
        simpa using hNbound
      simpa only [diam, hDcoe] using hNbound'
  rcases eventually_atTop.1 htail with ⟨j0, hj0⟩
  exact ⟨epsilon, hepsilon, hepsilonlt, j0, hj0⟩

end

end Codex.Spherical.PowerWeights.ThinRadialUniformEntropy
