/- This file was machine-generated by Codex -/

import LeanSpherical.Codex.Spherical.PowerWeights.ThinRadialCapShell
import LeanSpherical.Codex.Spherical.PowerWeights.ThinRadialStrictProduct

/-!
# Strict-negative cap shell

This file turns the literal cap shell estimate for a thin radial partition
piece into the uniform coefficient estimate required at the strict negative
endpoint.
-/

namespace LeanSpherical.HarmonicAnalysis

open MeasureTheory Metric Set
open scoped BigOperators ENNReal NNReal

noncomputable section

private theorem thinRadial_capTail_ratio_lt_one (n : Nat) :
    2 * ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3)) < (1 : ENNReal) := by
  have hpow : ((2 : Real)⁻¹) ^ (n + 1 + 3) ≤ ((2 : Real)⁻¹) ^ 2 := by
    apply pow_le_pow_of_le_one
    · positivity
    · norm_num
    · omega
  calc
    2 * ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3)) =
        ENNReal.ofReal (2 * (((2 : Real)⁻¹) ^ (n + 1 + 3))) := by
          rw [ENNReal.ofReal_mul (by norm_num : (0 : Real) ≤ 2)]
          norm_num
    _ ≤ ENNReal.ofReal (2 * ((2 : Real)⁻¹) ^ 2) :=
      ENNReal.ofReal_le_ofReal (mul_le_mul_of_nonneg_left hpow (by norm_num))
    _ < 1 := by norm_num

/-- The explicit transverse cap-tail envelope is finite. -/
theorem relativeMovingBandCapTailEnvelope_ne_top (n : Nat) (C : Real) :
    relativeMovingBandCapTailEnvelope n C ≠ ∞ := by
  let q : ENNReal := ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3))
  have hratio : 2 * q < 1 := by
    simpa only [q] using thinRadial_capTail_ratio_lt_one n
  have hone_sub0 : 1 - 2 * q ≠ 0 := (tsub_pos_of_lt hratio).ne'
  have hinvtop : (1 - 2 * q)⁻¹ ≠ ∞ := ENNReal.inv_ne_top.mpr hone_sub0
  unfold relativeMovingBandCapTailEnvelope
  change
    ENNReal.ofReal (24 * C) * volume (ball (0 : Euclidean n) 1) *
        (1 - 2 * q)⁻¹ +
      ENNReal.ofReal (4 * C) * volume (ball (0 : Euclidean (n + 1)) 1) ≠ ∞
  refine ENNReal.add_ne_top.mpr ⟨?_, ?_⟩
  · exact ENNReal.mul_ne_top
      (ENNReal.mul_ne_top ENNReal.ofReal_ne_top
        (measure_ball_lt_top (μ := volume) (x := (0 : Euclidean n)) (r := (1 : Real))).ne)
      hinvtop
  · exact ENNReal.mul_ne_top ENNReal.ofReal_ne_top
      (measure_ball_lt_top (μ := volume) (x := (0 : Euclidean (n + 1)))
        (r := (1 : Real))).ne

private theorem strictNegativeCapInterpolation_envelope
    {n : Nat} {p alpha epsilon rho sigma : Real}
    (hp1 : 1 < p) (hp2 : p < 2) (halpha : alpha < 0)
    (hrho : rho + (n : Real) * (2 - p) = -alpha)
    (hsigma : (n : Real) * (p - 1) - sigma = epsilon)
    {kappa1 kappa2 K Kraw T W N delta : ENNReal}
    {s b bUpper : Real}
    (hW : W = (ENNReal.ofReal (s / 4)) ^ alpha *
      ((ENNReal.ofReal b) ^ alpha)⁻¹)
    (hW0 : W ≠ 0) (hWtop : W ≠ ∞)
    (hN0 : N ≠ 0) (hNtop : N ≠ ∞)
    (hs : 0 < s) (hsone : s ≤ 1) (hbpos : 0 < b) (hb : b ≤ bUpper)
    (hdelta0 : delta ≠ 0) (hdeltatop : delta ≠ ∞)
    (hTtop : T ≠ ∞) (hKrawtop : Kraw ≠ ∞)
    (hNbound : N ≤ K * (ENNReal.ofReal s) ^ rho * (delta⁻¹) ^ sigma) :
    ∃ tau : Real, 0 < tau ∧ ∀ {c1 c2 A1 A2 I : ENNReal},
      c1 ≤ W * T * N * (ENNReal.ofReal s) ^ n →
      c2 ≤ W * Kraw * N * delta ^ n →
      A1 ≤ kappa1 * I → A2 ≤ kappa2 * I →
      ENNReal.ofReal p *
          (4 * c2 * ((ENNReal.ofReal tau) ^ (2 - p) * A2) +
            2 * c1 * ((ENNReal.ofReal tau) ^ (1 - p) * A1)) ≤
        ENNReal.ofReal p * (4 * kappa2 + 2 * kappa1) *
          ((1 + T) ^ (2 - p) * (1 + Kraw) ^ (p - 1) * K) *
            ((ENNReal.ofReal (4 * bUpper)) ^ (-alpha) * delta ^ epsilon) * I := by
  let d1 : ENNReal := (1 + T) * W * N * (ENNReal.ofReal s) ^ n
  let d2 : ENNReal := (1 + Kraw) * W * N * delta ^ n
  have hsp : 0 < ENNReal.ofReal s := ENNReal.ofReal_pos.mpr hs
  have hsdivp : 0 < ENNReal.ofReal (s / 4) :=
    ENNReal.ofReal_pos.mpr (by positivity)
  have hbpos : 0 < ENNReal.ofReal b := by
    apply ENNReal.ofReal_pos.mpr
    exact hbpos
  have hWpos : 0 < W := by
    rw [hW]
    apply ENNReal.mul_pos
    · exact (ENNReal.rpow_pos hsdivp ENNReal.ofReal_ne_top).ne'
    · apply ENNReal.inv_ne_zero.mpr
      exact ENNReal.rpow_ne_top_of_ne_zero hbpos.ne' ENNReal.ofReal_ne_top
  have hd1top : d1 ≠ ∞ := by
    dsimp only [d1]
    apply ENNReal.mul_ne_top
    · apply ENNReal.mul_ne_top
      · apply ENNReal.mul_ne_top
        · exact ENNReal.add_ne_top.mpr ⟨by norm_num, hTtop⟩
        · exact hWtop
      · exact hNtop
    · exact ENNReal.pow_ne_top ENNReal.ofReal_ne_top
  have hd2top : d2 ≠ ∞ := by
    dsimp only [d2]
    apply ENNReal.mul_ne_top
    · apply ENNReal.mul_ne_top
      · apply ENNReal.mul_ne_top
        · exact ENNReal.add_ne_top.mpr ⟨by norm_num, hKrawtop⟩
        · exact hWtop
      · exact hNtop
    · exact ENNReal.pow_ne_top hdeltatop
  have hNpos : 0 < N := pos_iff_ne_zero.mpr hN0
  have hAenvpos : 0 < 1 + T := by positivity
  have hBenvpos : 0 < 1 + Kraw := by positivity
  have hAenvWpos : 0 < (1 + T) * W :=
    ENNReal.mul_pos hAenvpos.ne' hWpos.ne'
  have hAenvWNpos : 0 < (1 + T) * W * N :=
    ENNReal.mul_pos hAenvWpos.ne' hNpos.ne'
  have hBenvWpos : 0 < (1 + Kraw) * W :=
    ENNReal.mul_pos hBenvpos.ne' hWpos.ne'
  have hBenvWNpos : 0 < (1 + Kraw) * W * N :=
    ENNReal.mul_pos hBenvWpos.ne' hNpos.ne'
  have hd10 : d1 ≠ 0 := by
    dsimp only [d1]
    exact (ENNReal.mul_pos hAenvWNpos.ne' (pow_ne_zero n hsp.ne')).ne'
  have hd20 : d2 ≠ 0 := by
    dsimp only [d2]
    exact (ENNReal.mul_pos hBenvWNpos.ne' (pow_ne_zero n hdelta0)).ne'
  have hproduct :
      d1 ^ (2 - p) * d2 ^ (p - 1) ≤
        ((1 + T) ^ (2 - p) * (1 + Kraw) ^ (p - 1) * K) *
          ((ENNReal.ofReal (4 * bUpper)) ^ (-alpha) * delta ^ epsilon) := by
    simpa only [mul_assoc] using
      (strict_negative_cap_product_envelope_uniform_of_upper_bound
        (c1 := d1) (c2 := d2) (A := 1 + T) (B := 1 + Kraw)
        hp1 hp2 halpha hrho hsigma hW hW0 hWtop hN0 hNtop hs hsone hb
        hdelta0 hdeltatop hNbound (by rfl) (by rfl))
  let tau : Real := (d1 / d2).toReal
  have htau := positive_toReal_div_of_ennreal hd10 hd1top hd20 hd2top
  refine ⟨tau, htau.1, ?_⟩
  intro c1 c2 A1 A2 I hc1 hc2 hA1 hA2
  have hc1' : c1 ≤ d1 := by
    calc
      c1 ≤ W * T * N * (ENNReal.ofReal s) ^ n := hc1
      _ = T * W * N * (ENNReal.ofReal s) ^ n := by ring
      _ ≤ (1 + T) * W * N * (ENNReal.ofReal s) ^ n := by
        gcongr
        exact le_add_of_nonneg_left bot_le
      _ = d1 := by rfl
  have hc2' : c2 ≤ d2 := by
    calc
      c2 ≤ W * Kraw * N * delta ^ n := hc2
      _ = Kraw * W * N * delta ^ n := by ring
      _ ≤ (1 + Kraw) * W * N * delta ^ n := by
        gcongr
        exact le_add_of_nonneg_left bot_le
      _ = d2 := by rfl
  calc
    ENNReal.ofReal p *
        (4 * c2 * ((ENNReal.ofReal tau) ^ (2 - p) * A2) +
          2 * c1 * ((ENNReal.ofReal tau) ^ (1 - p) * A1)) ≤
        ENNReal.ofReal p *
          (4 * d2 * ((ENNReal.ofReal tau) ^ (2 - p) * A2) +
            2 * d1 * ((ENNReal.ofReal tau) ^ (1 - p) * A1)) := by
          gcongr
    _ ≤ ENNReal.ofReal p * (4 * kappa2 + 2 * kappa1) *
          ((1 + T) ^ (2 - p) * (1 + Kraw) ^ (p - 1) * K) *
            ((ENNReal.ofReal (4 * bUpper)) ^ (-alpha) * delta ^ epsilon) * I := by
          simpa only [mul_assoc] using
            (balanced_cap_interpolation_moment_le_of_product
              hp1 hp2 hd10 hd1top hd20 hd2top htau.2 hA1 hA2 hproduct)

/-- A thin radial cap shell has the strict-negative interpolation bound once
its local entropy witness and square coefficient have the indicated power
envelopes.  The selected interpolation scale is made before invoking the cap
estimate, so the finite interval cover may still depend on that scale. -/
theorem exists_thinRadialPartition_strictNegativeCap_shell_lintegral_rpow_le
    {n : Nat} (hn : 2 ≤ n) (C0 C1 : Real) (hC0 : 0 < C0) (hC1 : 0 < C1)
    (hdecay : ∀ xi : Euclidean (n + 1), 1 ≤ ‖xi‖ →
      ‖surfaceFourier (n + 1) xi‖ ≤ C0 / ‖xi‖ ^ ((n : Real) / 2))
    (hderiv : ∀ xi : Euclidean (n + 1), ∀ u : Real, 1 ≤ ‖xi‖ →
      u ∈ Icc (1 : Real) 2 →
      ‖deriv (fun z : Real => surfaceFourier (n + 1) (z • xi)) u‖ ≤
        C1 / ‖xi‖ ^ ((n : Real) / 2 - 1))
    (phi : SchwartzMap (Euclidean (n + 1)) Complex)
    (hphi_one : ∀ xi, ‖xi‖ ≤ 1 → phi xi = 1)
    (hphi_zero : ∀ xi, 2 ≤ ‖xi‖ → phi xi = 0)
    (hphi_norm : ∀ xi, ‖phi xi‖ ≤ 1) :
    ∃ C : Real, 0 < C ∧ ∀ (j : Nat)
      (f : SchwartzMap (Euclidean (n + 1)) Complex) (E : Set Real)
      (delta : NNReal) (N : Nat) {s alpha p : Real} (m : Nat) (mu : Int)
      {epsilon rho sigma : Real} {K Kraw : ENNReal} {bUpper : Real},
      4 ≤ j → (E ∩ thinRadiusWindow s mu).Nonempty → E ⊆ Icc (1 : Real) 2 →
      multiplicativeEntropy (E ∩ thinRadiusWindow s mu) delta ≤ N →
      0 < delta → Real.log 2 * (delta : Real) ≤ 1 →
      8 * Real.log 2 * (delta : Real) ≤ ((2 : Real) ^ j)⁻¹ →
      (hs : 0 < s) → 4 * s ≤ 1 → alpha < 0 →
      0 < s * ((m : Real) - 1 / 4) →
      s < s * ((m : Real) - 1 / 4) → 1 < p → p < 2 →
      0 < epsilon → rho + (n : Real) * (2 - p) = -alpha →
      (n : Real) * (p - 1) - sigma = epsilon →
      s * ((m : Real) + 5 / 4) ≤ bUpper → Kraw ≠ ∞ →
      ENNReal.ofReal
          (2 * ((4 * C0) / (dyadicScale j) ^ ((n : Real) / 2)) ^ (2 : Nat) +
            2 * (8 * Real.log 2 * (delta : Real)) ^ (2 : Nat) *
              (2 * ((4 * C1) / (dyadicScale j) ^ ((n : Real) / 2 - 1) +
                (12 * C0 *
                  ‖((SchwartzMap.fderivCLM Complex (Euclidean (n + 1)) Complex) phi).toBoundedContinuousFunction‖) /
                  (dyadicScale j) ^ ((n : Real) / 2))) ^ (2 : Nat)) ≤
            Kraw * (delta : ENNReal) ^ n →
      (N : ENNReal) ≤ K * (ENNReal.ofReal s) ^ rho *
        ((delta : ENNReal)⁻¹) ^ sigma →
      let b : Real := s * ((m : Real) + 5 / 4)
      let g : SchwartzMap (Euclidean (n + 1)) Complex :=
        SchwartzMap.pairing (ContinuousLinearMap.mul Complex Complex) f
          (thinRadialPartition (n + 1) s hs m)
      let I : ENNReal :=
        ∫⁻ x, (ENNReal.ofReal ‖g x‖) ^ p ∂powerWeightedVolume (n + 1) alpha
      let kappa2 : ENNReal :=
        ENNReal.ofReal ((1 : Real) / 4) * (ENNReal.ofReal p)⁻¹ +
          (ENNReal.ofReal (2 - p))⁻¹
      let kappa1 : ENNReal :=
        (ENNReal.ofReal (p - 1))⁻¹ + (ENNReal.ofReal (3 - p))⁻¹
      let T : ENNReal :=
        (2 + (ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3)))⁻¹) *
          relativeMovingBandCapTailEnvelope n C
      (∫⁻ x in euclideanAnnulus (n + 1) (s / 4) (s / 2),
        ENNReal.ofReal
          ((restrictedRelativeBandpassSphericalMaximal (n + 1)
            (E ∩ thinRadiusWindow s mu) phi j g x).toReal ^ p)
          ∂powerWeightedVolume (n + 1) alpha) ≤
        ENNReal.ofReal p * (4 * kappa2 + 2 * kappa1) *
          ((1 + T) ^ (2 - p) * (1 + Kraw) ^ (p - 1) * K) *
            ((ENNReal.ofReal (4 * bUpper)) ^ (-alpha) *
              (delta : ENNReal) ^ epsilon) * I := by
  obtain ⟨C, hC, hcap⟩ :=
    exists_thinRadialPartition_entropyCap_shell_global_lintegral_rpow_le
      hn C0 C1 hC0 hC1 hdecay hderiv phi hphi_one hphi_zero hphi_norm
  refine ⟨C, hC, ?_⟩
  intro j f E delta N s alpha p m mu epsilon rho sigma K Kraw bUpper hj hEne hE hN
    hdelta0 hdelta hshort hs hsquarter halpha hmpos hsep hp1 hp2 hepsilon
    hrho hsigma hb hKrawtop hLbound hNbound
  let b : Real := s * ((m : Real) + 5 / 4)
  let g : SchwartzMap (Euclidean (n + 1)) Complex :=
    SchwartzMap.pairing (ContinuousLinearMap.mul Complex Complex) f
      (thinRadialPartition (n + 1) s hs m)
  let I : ENNReal :=
    ∫⁻ x, (ENNReal.ofReal ‖g x‖) ^ p ∂powerWeightedVolume (n + 1) alpha
  let kappa2 : ENNReal :=
    ENNReal.ofReal ((1 : Real) / 4) * (ENNReal.ofReal p)⁻¹ +
      (ENNReal.ofReal (2 - p))⁻¹
  let kappa1 : ENNReal :=
    (ENNReal.ofReal (p - 1))⁻¹ + (ENNReal.ofReal (3 - p))⁻¹
  let T : ENNReal :=
    (2 + (ENNReal.ofReal (((2 : Real)⁻¹) ^ (n + 1 + 3)))⁻¹) *
      relativeMovingBandCapTailEnvelope n C
  have hsone : s ≤ 1 := by linarith
  have hbpos : 0 < b := by
    dsimp only [b]
    positivity
  obtain ⟨R0, hR0card, hR0ordered, hR0ends, hR0length, hR0cover, hR0bound⟩ :=
    hcap j f E delta N (s := s) (alpha := alpha) (p := p) (tau := 1) m mu
      hj hEne hE hN hdelta hshort hs hsquarter halpha.le hmpos hsep hp1 hp2
        (by norm_num)
  have hNnat0 : N ≠ 0 := by
    intro hNzero
    have hR0cardzero : R0.card = 0 := by omega
    have hR0empty : R0 = ∅ := Finset.card_eq_zero.mp hR0cardzero
    rcases hEne with ⟨r, hr⟩
    have hrcover := hR0cover hr
    simpa [hR0empty] using hrcover
  have hN0 : (N : ENNReal) ≠ 0 := by exact_mod_cast hNnat0
  have hNtop : (N : ENNReal) ≠ ∞ := ENNReal.coe_ne_top
  let W : ENNReal := (ENNReal.ofReal (s / 4)) ^ alpha *
    ((ENNReal.ofReal b) ^ alpha)⁻¹
  have hW : W = (ENNReal.ofReal (s / 4)) ^ alpha *
      ((ENNReal.ofReal b) ^ alpha)⁻¹ := rfl
  have hsdivpos : 0 < ENNReal.ofReal (s / 4) :=
    ENNReal.ofReal_pos.mpr (by positivity)
  have hbennpos : 0 < ENNReal.ofReal b := ENNReal.ofReal_pos.mpr hbpos
  have hW0 : W ≠ 0 := by
    dsimp only [W]
    exact (ENNReal.mul_pos
      (ENNReal.rpow_pos hsdivpos ENNReal.ofReal_ne_top).ne'
      (ENNReal.inv_ne_zero.mpr
        (ENNReal.rpow_ne_top_of_ne_zero hbennpos.ne' ENNReal.ofReal_ne_top))).ne'
  have hWtop : W ≠ ∞ := by
    dsimp only [W]
    apply ENNReal.mul_ne_top
    · exact ENNReal.rpow_ne_top_of_ne_zero hsdivpos.ne' ENNReal.ofReal_ne_top
    · apply ENNReal.inv_ne_top.mpr
      exact (ENNReal.rpow_pos hbennpos ENNReal.ofReal_ne_top).ne'
  obtain ⟨tau, htau, htaubound⟩ :=
    strictNegativeCapInterpolation_envelope hp1 hp2 halpha hrho hsigma
      (kappa1 := kappa1) (kappa2 := kappa2) (K := K) (W := W) (T := T)
      (Kraw := Kraw) (bUpper := bUpper) hW hW0 hWtop hN0 hNtop hs hsone
      hbpos hb (ENNReal.coe_ne_zero.mpr hdelta0.ne') ENNReal.coe_ne_top
      (by
        dsimp only [T]
        apply ENNReal.mul_ne_top
        · apply ENNReal.add_ne_top.mpr
          constructor
          · norm_num
          · apply ENNReal.inv_ne_top.mpr
            exact (ENNReal.ofReal_pos.mpr (by positivity)).ne'
        · exact relativeMovingBandCapTailEnvelope_ne_top n C)
      hKrawtop hNbound
  obtain ⟨R, hRcard, hRordered, hRends, hRlength, hRcover, hcapbound⟩ :=
    hcap j f E delta N (s := s) (alpha := alpha) (p := p) (tau := tau) m mu
      hj hEne hE hN hdelta hshort hs hsquarter halpha.le hmpos hsep hp1 hp2 htau
  let raw : ENNReal := ENNReal.ofReal
    (2 * ((4 * C0) / (dyadicScale j) ^ ((n : Real) / 2)) ^ (2 : Nat) +
      2 * (8 * Real.log 2 * (delta : Real)) ^ (2 : Nat) *
        (2 * ((4 * C1) / (dyadicScale j) ^ ((n : Real) / 2 - 1) +
          (12 * C0 *
            ‖((SchwartzMap.fderivCLM Complex (Euclidean (n + 1)) Complex) phi).toBoundedContinuousFunction‖) /
            (dyadicScale j) ^ ((n : Real) / 2))) ^ (2 : Nat))
  have hraw : raw ≤ Kraw * (delta : ENNReal) ^ n := by
    simpa only [raw] using hLbound
  let L : ENNReal := (N : ENNReal) * raw
  let c1 : ENNReal := (ENNReal.ofReal (s / 4)) ^ alpha *
    (∑ q ∈ R, relativeIntervalBandCapTail n j C q.1 q.2 s) *
      ((ENNReal.ofReal b) ^ alpha)⁻¹
  let c2 : ENNReal := (ENNReal.ofReal (s / 4)) ^ alpha * L *
    ((ENNReal.ofReal b) ^ alpha)⁻¹
  let a2 : ENNReal := kappa2 * I
  let a1 : ENNReal := kappa1 * I
  have hc1 : c1 ≤ W * T * (N : ENNReal) * (ENNReal.ofReal s) ^ n := by
    have htail := relativeIntervalBandCapCoefficient_le_envelope n j C s b alpha R N
      hC hj hs hsone hRcard (fun q hq => (hRends q hq).2.2) hRlength
    dsimp only [c1, W, T]
    simpa only [mul_assoc, mul_left_comm, mul_comm] using htail
  have hc2 : c2 ≤ W * Kraw * (N : ENNReal) * (delta : ENNReal) ^ n := by
    dsimp only [c2, L]
    calc
      (ENNReal.ofReal (s / 4)) ^ alpha * ((N : ENNReal) * raw) *
          ((ENNReal.ofReal b) ^ alpha)⁻¹ = W * (N : ENNReal) * raw := by
              rw [hW]
              ring
      _ ≤ W * (N : ENNReal) * (Kraw * (delta : ENNReal) ^ n) := by gcongr
      _ = W * Kraw * (N : ENNReal) * (delta : ENNReal) ^ n := by ring
  have hbalanced := htaubound hc1 hc2 (le_refl a1) (le_refl a2)
  change
    (∫⁻ x in euclideanAnnulus (n + 1) (s / 4) (s / 2),
      ENNReal.ofReal
        ((restrictedRelativeBandpassSphericalMaximal (n + 1)
          (E ∩ thinRadiusWindow s mu) phi j g x).toReal ^ p)
        ∂powerWeightedVolume (n + 1) alpha) ≤ _
  calc
    _ ≤ ENNReal.ofReal p *
        (4 * c2 * ((ENNReal.ofReal tau) ^ (2 - p) * a2) +
          2 * c1 * ((ENNReal.ofReal tau) ^ (1 - p) * a1)) := by
            simpa only [b, g, raw, L, c1, c2, a1, a2, kappa1, kappa2, I] using hcapbound
    _ ≤ _ := by
      simpa only [a1, a2, kappa1, kappa2, I, T, mul_assoc] using hbalanced

end

end LeanSpherical.HarmonicAnalysis
